### ISSUE TITLE
Tizen TV Simulator Check certificate error

### ISSUE THREAD

**Issue by yusufusta** [flexn-io/renative#1017]
**Describe the bug**
I'm running `rnv run -p tizen -t T-samsung-7.0-x86` this command but it's not working.

**Error Log:**
```
✔ Executing: /Users/yusufusta/tizen-studio/tools/ide/bin/tizen package -- /Users/yusufusta/Projects/netiptv/platformBuilds/app_tizen/build -s RNVanillaCert -t wgt -o /Users/yusufusta/Projects/netiptv/platformBuilds/app_tizen/output
✔ Executing: /Users/yusufusta/tizen-studio/tools/ide/bin/tizen uninstall -p NkVRhWHJST.RNVanillaTV -t T-samsung-7.0-x86
✖ FAILED: /Users/yusufusta/tizen-studio/tools/ide/bin/tizen install -- /Users/yusufusta/Projects/netiptv/platformBuilds/app_tizen/output -n RNVanillaTV.wgt -t T-samsung-7.0-x86
[ error ] [run] COMMAND: 

/Users/yusufusta/tizen-studio/tools/ide/bin/tizen install -- /Users/yusufusta/Projects/netiptv/platformBuilds/app_tizen/output -n RNVanillaTV.wgt -t T-samsung-7.0-x86 

FAILED with ERROR: 

app_id[NkVRhWHJST.RNVanillaTV] install failed[118, -12], reason: Check certificate error : 
spend time for wascmd is [389]ms
Failed to install Tizen application.
Total time: 00:00:01.097

Command failed with exit code 1: /Users/yusufusta/tizen-studio/tools/ide/bin/tizen install -- /Users/yusufusta/Projects/netiptv/platformBuilds/app_tizen/output -n RNVanillaTV.wgt -t T-samsung-7.0-x86
Transferring the package...
Transferred the package: /Users/yusufusta/Projects/netiptv/platformBuilds/app_tizen/output/RNVanillaTV.wgt -> /home/owner/share/tmp/sdk_tools/tmp
Installing the package...
--------------------
Platform log view
--------------------
install NkVRhWHJST.RNVanillaTV
package_path /home/owner/share/tmp/sdk_tools/tmp/RNVanillaTV.wgt
app_id[NkVRhWHJST.RNVanillaTV] install start
app_id[NkVRhWHJST.RNVanillaTV] installing[10]
app_id[NkVRhWHJST.RNVanillaTV] installing[13]
app_id[NkVRhWHJST.RNVanillaTV] installing[15]
app_id[NkVRhWHJST.RNVanillaTV] installing[18]
app_id[NkVRhWHJST.RNVanillaTV] installing[21]
app_id[NkVRhWHJST.RNVanillaTV] installing[23]
app_id[NkVRhWHJST.RNVanillaTV] install failed[118, -12], reason: Check certificate error : 
spend time for wascmd is [389]ms
Failed to install Tizen application.
Total time: 00:00:01.097

Error: Command failed with exit code 1: /Users/yusufusta/tizen-studio/tools/ide/bin/tizen install -- /Users/yusufusta/Projects/netiptv/platformBuilds/app_tizen/output -n RNVanillaTV.wgt -t T-samsung-7.0-x86
Transferring the package...
Transferred the package: /Users/yusufusta/Projects/netiptv/platformBuilds/app_tizen/output/RNVanillaTV.wgt -> /home/owner/share/tmp/sdk_tools/tmp
Installing the package...
--------------------
Platform log view
--------------------
install NkVRhWHJST.RNVanillaTV
package_path /home/owner/share/tmp/sdk_tools/tmp/RNVanillaTV.wgt
app_id[NkVRhWHJST.RNVanillaTV] install start
app_id[NkVRhWHJST.RNVanillaTV] installing[10]
app_id[NkVRhWHJST.RNVanillaTV] installing[13]
app_id[NkVRhWHJST.RNVanillaTV] installing[15]
app_id[NkVRhWHJST.RNVanillaTV] installing[18]
app_id[NkVRhWHJST.RNVanillaTV] installing[21]
app_id[NkVRhWHJST.RNVanillaTV] installing[23]
app_id[NkVRhWHJST.RNVanillaTV] install failed[118, -12], reason: Check certificate error : 
spend time for wascmd is [389]ms
Failed to install Tizen application.
Total time: 00:00:01.097
    at makeError (/Users/yusufusta/Projects/netiptv/node_modules/rnv/node_modules/execa/lib/error.js:60:11)
    at handlePromise (/Users/yusufusta/Projects/netiptv/node_modules/rnv/node_modules/execa/index.js:118:26)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)


[ warn ] [run] There is no emulator or device connected! Let's try to launch it. "rnv target launch -p tizen -t T-samsung-7.0-x86"
[ task ] [run] launchTizenSimulator:T-samsung-7.0-x86[2]
✖ FAILED: /Users/yusufusta/tizen-studio/tools/emulator/bin/em-cli launch --name T-samsung-7.0-x86
[ error ] [run] COMMAND: 

/Users/yusufusta/tizen-studio/tools/emulator/bin/em-cli launch --name T-samsung-7.0-x86 

FAILED with ERROR: 

Error: Failed to start this VM.
[T-samsung-7.0-x86] is running now...

Command failed with exit code 2: /Users/yusufusta/tizen-studio/tools/emulator/bin/em-cli launch --name T-samsung-7.0-x86
Error: Failed to start this VM.
[T-samsung-7.0-x86] is running now...

Error: Command failed with exit code 2: /Users/yusufusta/tizen-studio/tools/emulator/bin/em-cli launch --name T-samsung-7.0-x86
Error: Failed to start this VM.
[T-samsung-7.0-x86] is running now...
    at makeError (/Users/yusufusta/Projects/netiptv/node_modules/rnv/node_modules/execa/lib/error.js:60:11)
    at handlePromise (/Users/yusufusta/Projects/netiptv/node_modules/rnv/node_modules/execa/index.js:118:26)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)```

**Desktop:**

-   OS: MacOS Ventura 13.0.1
-   Node Version: v18.16.0
-   RNV Version: 0.36.1

**Comment by yusufusta** [comment]
Also I can't generate new cert.

<img width="768" alt="image" src="https://github.com/flexn-io/renative/assets/46392667/003c842f-27e7-48fa-bc5f-56a06a266441">

That's weird

**Comment by pauliusguzas** [comment]
@yusufusta thanks for reporting this, are you still unable togenerate new cert? Because that doesn't look like rnv issue in that case. It is important though that in `renative.json` under appConfigs you provide correct certificate name like below
```
        "tizen": {
            "target": "es6",
            "package": "samsungdev",
            "id": "samsungdev.flexntemplate",
            "appName": "TestHarness",
            "entryFile": "index",
            "certificateProfile": "RNVanillaCert",
            "buildSchemes": {
                "debug": {
                    "bundleAssets": false
                },
                "test": {},
                "canary": {},
                "production": {
                    "bundleAssets": true,
                    "bundleIsDev": false
                }
            }
        },
```
By default rnv generjates certificate by the name RNVanillaCert and uses it, but if your certificate can't be generated then there is nothing for rnv to use

**Comment by GabrieleKaceviciute** [comment]
Closing as answer has been provided, feel free to reopen if needed
