### ISSUE TITLE
[Regression] 0.37.0-rc.7 template-starter issues

### ISSUE THREAD

**Issue by pauliusguzas** [flexn-io/renative#1055]
Can't run renative/template starter

AndroidTV:
```
✖ FAILED: ./gradlew assembleDebug -x bundleReleaseJsAndAssets
┌──────────────────────────────────────────────────────────────────────────────┐
│  🚀  SUMMARY | 6/28/2023, 2:31:18 PM                                         │
│  $ rnv run -p androidtv                                                      │
├──────────────────────────────────────────────────────────────────────────────┤
│  ReNative Version: 0.37.0-rc.7                                               │
│  Project Name ($package.name): @rnv/template-starter                         │
│  Project Version ($package.version): 0.37.0-rc.7                             │
│  Workspace ($.workspaceID): rnv                                              │
│  Platform (-p): androidtv                                                    │
│  Engine ($.platforms.androidtv.engine): engine-rn-tvos                       │
│  App Config (-c): template                                                   │
│  Build Scheme (-s): debug                                                    │
│  Target (-t): Android_TV_720p_API_22                                         │
│  Supported Platforms: androidtv                                              │
│  Env Info: darwin | x64 | node v16.14.2                                      │
│  Executed Time: 0h:0m:18s:99ms                                               │
│                                                                              │
│ [ warn ] [configure] Your app is missing assets at ./appConfigs/base,./appConfigs/base,./appConfigs/template.
│ [ error ] [run] COMMAND:

./gradlew assembleDebug -x bundleReleaseJsAndAssets

FAILED with ERROR:

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:processDebugResources'.
> A failure occurred while executing com.android.build.gradle.internal.res.LinkApplicationAndroidResourcesTask$TaskAction
   > Android resource linking failed
     ERROR:/Users/pauliusguzas/Desktop/renative/packages/template-starter/platformBuilds/template_androidtv/app/build/intermediates/packaged_manifests/debug/AndroidManifest.xml:24: AAPT: error: resource mipmap/ic_launcher (aka renative.helloworld.debug:mipmap/ic_launcher) not found.

     ERROR:/Users/pauliusguzas/Desktop/renative/packages/template-starter/platformBuilds/template_androidtv/app/build/intermediates/packaged_manifests/debug/AndroidManifest.xml:34: AAPT: error: resource drawable/ic_logo (aka renative.helloworld.debug:drawable/ic_logo) not found.

     ERROR:/Users/pauliusguzas/Desktop/renative/packages/template-starter/platformBuilds/template_androidtv/app/build/intermediates/packaged_manifests/debug/AndroidManifest.xml:49: AAPT: error: resource drawable/ic_logo (aka renative.helloworld.debug:drawable/ic_logo) not found.


* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 6s
24 actionable tasks: 1 executed, 23 up-to-date

Command failed with exit code 1: ./gradlew assembleDebug -x bundleReleaseJsAndAssets

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:processDebugResources'.
> A failure occurred while executing com.android.build.gradle.internal.res.LinkApplicationAndroidResourcesTask$TaskAction
   > Android resource linking failed
     ERROR:/Users/pauliusguzas/Desktop/renative/packages/template-starter/platformBuilds/template_androidtv/app/build/intermediates/packaged_manifests/debug/AndroidManifest.xml:24: AAPT: error: resource mipmap/ic_launcher (aka renative.helloworld.debug:mipmap/ic_launcher) not found.

     ERROR:/Users/pauliusguzas/Desktop/renative/packages/template-starter/platformBuilds/template_androidtv/app/build/intermediates/packaged_manifests/debug/AndroidManifest.xml:34: AAPT: error: resource drawable/ic_logo (aka renative.helloworld.debug:drawable/ic_logo) not found.

     ERROR:/Users/pauliusguzas/Desktop/renative/packages/template-starter/platformBuilds/template_androidtv/app/build/intermediates/packaged_manifests/debug/AndroidManifest.xml:49: AAPT: error: resource drawable/ic_logo (aka renative.helloworld.debug:drawable/ic_logo) not found.


* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 6s
Configuration on demand is an incubating feature.

> Configure project :app
WARNING:: The option 'android.useDeprecatedNdk' is deprecated.
The current default is 'false'.
It has been removed from the current version of the Android Gradle plugin.
NdkCompile is no longer supported
Warning: The 'kotlin-android-extensions' Gradle plugin is deprecated. Please use this migration guide (https://goo.gle/kotlin-android-extensions-deprecation) to start working with View Binding (https://developer.android.com/topic/libraries/view-binding) and the 'kotlin-parcelize' plugin.
WARNING:: The specified Android SDK Build Tools version (30.0.0) is ignored, as it is below the minimum supported version (30.0.2) for Android Gradle Plugin 4.2.2.
Android SDK Build Tools 30.0.2 will be used.
To suppress this warning, remove "buildToolsVersion '30.0.0'" from your build.gradle file, as each version of the Android Gradle Plugin now has a default version of the build tools.

> Task :app:preBuild UP-TO-DATE
> Task :app:preDebugBuild UP-TO-DATE
> Task :app:compileDebugAidl NO-SOURCE
> Task :app:compileDebugRenderscript NO-SOURCE
> Task :app:generateDebugBuildConfig UP-TO-DATE
> Task :app:checkDebugAarMetadata UP-TO-DATE
> Task :app:bundleDebugJsAndAssets SKIPPED
> Task :app:mergeDebugShaders UP-TO-DATE
> Task :app:compileDebugShaders NO-SOURCE
> Task :app:generateDebugAssets UP-TO-DATE
> Task :app:mergeDebugAssets UP-TO-DATE
> Task :app:copyDebugBundledJs SKIPPED
> Task :app:generateDebugResValues UP-TO-DATE
> Task :app:generateDebugResources UP-TO-DATE
> Task :app:mergeDebugResources UP-TO-DATE
> Task :app:createDebugCompatibleScreenManifests UP-TO-DATE
> Task :app:extractDeepLinksDebug UP-TO-DATE
> Task :app:processDebugMainManifest UP-TO-DATE
> Task :app:processDebugManifest UP-TO-DATE
> Task :app:processDebugManifestForPackage UP-TO-DATE
> Task :app:javaPreCompileDebug UP-TO-DATE
> Task :app:mergeDebugNativeDebugMetadata NO-SOURCE
> Task :app:compressDebugAssets UP-TO-DATE
> Task :app:processDebugJavaRes NO-SOURCE
> Task :app:checkDebugDuplicateClasses UP-TO-DATE
> Task :app:desugarDebugFileDependencies UP-TO-DATE
> Task :app:mergeExtDexDebug UP-TO-DATE
> Task :app:mergeLibDexDebug UP-TO-DATE
> Task :app:mergeDebugJniLibFolders UP-TO-DATE
> Task :app:mergeDebugNativeLibs UP-TO-DATE
> Task :app:stripDebugDebugSymbols UP-TO-DATE
> Task :app:validateSigningDebug UP-TO-DATE
> Task :app:writeDebugAppMetadata UP-TO-DATE
> Task :app:writeDebugSigningConfigVersions UP-TO-DATE
> Task :app:processDebugResources FAILED
24 actionable tasks: 1 executed, 23 up-to-date


FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:processDebugResources'.
> A failure occurred while executing com.android.build.gradle.internal.res.LinkApplicationAndroidResourcesTask$TaskAction
   > Android resource linking failed
     ERROR:/Users/pauliusguzas/Desktop/renative/packages/template-starter/platformBuilds/template_androidtv/app/build/intermediates/packaged_manifests/debug/AndroidManifest.xml:24: AAPT: error: resource mipmap/ic_launcher (aka renative.helloworld.debug:mipmap/ic_launcher) not found.

     ERROR:/Users/pauliusguzas/Desktop/renative/packages/template-starter/platformBuilds/template_androidtv/app/build/intermediates/packaged_manifests/debug/AndroidManifest.xml:34: AAPT: error: resource drawable/ic_logo (aka renative.helloworld.debug:drawable/ic_logo) not found.

     ERROR:/Users/pauliusguzas/Desktop/renative/packages/template-starter/platformBuilds/template_androidtv/app/build/intermediates/packaged_manifests/debug/AndroidManifest.xml:49: AAPT: error: resource drawable/ic_logo (aka renative.helloworld.debug:drawable/ic_logo) not found.


* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 6s

Error: Command failed with exit code 1: ./gradlew assembleDebug -x bundleReleaseJsAndAssets

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:processDebugResources'.
> A failure occurred while executing com.android.build.gradle.internal.res.LinkApplicationAndroidResourcesTask$TaskAction
   > Android resource linking failed
     ERROR:/Users/pauliusguzas/Desktop/renative/packages/template-starter/platformBuilds/template_androidtv/app/build/intermediates/packaged_manifests/debug/AndroidManifest.xml:24: AAPT: error: resource mipmap/ic_launcher (aka renative.helloworld.debug:mipmap/ic_launcher) not found.

     ERROR:/Users/pauliusguzas/Desktop/renative/packages/template-starter/platformBuilds/template_androidtv/app/build/intermediates/packaged_manifests/debug/AndroidManifest.xml:34: AAPT: error: resource drawable/ic_logo (aka renative.helloworld.debug:drawable/ic_logo) not found.

     ERROR:/Users/pauliusguzas/Desktop/renative/packages/template-starter/platformBuilds/template_androidtv/app/build/intermediates/packaged_manifests/debug/AndroidManifest.xml:49: AAPT: error: resource drawable/ic_logo (aka renative.helloworld.debug:drawable/ic_logo) not found.


* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 6s
Configuration on demand is an incubating feature.

> Configure project :app
WARNING:: The option 'android.useDeprecatedNdk' is deprecated.
The current default is 'false'.
It has been removed from the current version of the Android Gradle plugin.
NdkCompile is no longer supported
Warning: The 'kotlin-android-extensions' Gradle plugin is deprecated. Please use this migration guide (https://goo.gle/kotlin-android-extensions-deprecation) to start working with View Binding (https://developer.android.com/topic/libraries/view-binding) and the 'kotlin-parcelize' plugin.
WARNING:: The specified Android SDK Build Tools version (30.0.0) is ignored, as it is below the minimum supported version (30.0.2) for Android Gradle Plugin 4.2.2.
Android SDK Build Tools 30.0.2 will be used.
To suppress this warning, remove "buildToolsVersion '30.0.0'" from your build.gradle file, as each version of the Android Gradle Plugin now has a default version of the build tools.

> Task :app:preBuild UP-TO-DATE
> Task :app:preDebugBuild UP-TO-DATE
> Task :app:compileDebugAidl NO-SOURCE
> Task :app:compileDebugRenderscript NO-SOURCE
> Task :app:generateDebugBuildConfig UP-TO-DATE
> Task :app:checkDebugAarMetadata UP-TO-DATE
> Task :app:bundleDebugJsAndAssets SKIPPED
> Task :app:mergeDebugShaders UP-TO-DATE
> Task :app:compileDebugShaders NO-SOURCE
> Task :app:generateDebugAssets UP-TO-DATE
> Task :app:mergeDebugAssets UP-TO-DATE
> Task :app:copyDebugBundledJs SKIPPED
> Task :app:generateDebugResValues UP-TO-DATE
> Task :app:generateDebugResources UP-TO-DATE
> Task :app:mergeDebugResources UP-TO-DATE
> Task :app:createDebugCompatibleScreenManifests UP-TO-DATE
> Task :app:extractDeepLinksDebug UP-TO-DATE
> Task :app:processDebugMainManifest UP-TO-DATE
> Task :app:processDebugManifest UP-TO-DATE
> Task :app:processDebugManifestForPackage UP-TO-DATE
> Task :app:javaPreCompileDebug UP-TO-DATE
> Task :app:mergeDebugNativeDebugMetadata NO-SOURCE
> Task :app:compressDebugAssets UP-TO-DATE
> Task :app:processDebugJavaRes NO-SOURCE
> Task :app:checkDebugDuplicateClasses UP-TO-DATE
> Task :app:desugarDebugFileDependencies UP-TO-DATE
> Task :app:mergeExtDexDebug UP-TO-DATE
> Task :app:mergeLibDexDebug UP-TO-DATE
> Task :app:mergeDebugJniLibFolders UP-TO-DATE
> Task :app:mergeDebugNativeLibs UP-TO-DATE
> Task :app:stripDebugDebugSymbols UP-TO-DATE
> Task :app:validateSigningDebug UP-TO-DATE
> Task :app:writeDebugAppMetadata UP-TO-DATE
> Task :app:writeDebugSigningConfigVersions UP-TO-DATE
> Task :app:processDebugResources FAILED
24 actionable tasks: 1 executed, 23 up-to-date
    at makeError (/Users/pauliusguzas/Desktop/renative/node_modules/execa/lib/error.js:60:11)
    at handlePromise (/Users/pauliusguzas/Desktop/renative/node_modules/execa/index.js:118:26)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)


│                                                                              │
│  Project location:                                                           │
│  ./platformBuilds/template_androidtv                                         │
└──────────────────────────────────────────────────────────────────────────────┘
pauliusguzas@Pauliuss-MacBook-Pro template-starter %
```
iOS, tvOS:
```
✖ FAILED: node /Users/pauliusguzas/Desktop/renative/node_modules/react-native/local-cli/cli.js run-ios --project-path platformBuilds/template_ios --scheme RNVApp --configuration Debug --simulator iPhone\ 14 --allowProvisioningUpdates
┌──────────────────────────────────────────────────────────────────────────────┐
│  🚀  SUMMARY | 6/28/2023, 2:32:31 PM                                         │
│  $ rnv run -p ios                                                            │
├──────────────────────────────────────────────────────────────────────────────┤
│  ReNative Version: 0.37.0-rc.7                                               │
│  Project Name ($package.name): @rnv/template-starter                         │
│  Project Version ($package.version): 0.37.0-rc.7                             │
│  Workspace ($.workspaceID): rnv                                              │
│  Platform (-p): ios                                                          │
│  Engine ($.platforms.ios.engine): engine-rn                                  │
│  App Config (-c): template                                                   │
│  Build Scheme (-s): debug                                                    │
│  Target (-t): iPhone 14                                                      │
│  Supported Platforms: ios                                                    │
│  Env Info: darwin | x64 | node v16.14.2                                      │
│  Executed Time: 0h:0m:15s:673ms                                              │
│                                                                              │
│ [ error ] [run] COMMAND:

node /Users/pauliusguzas/Desktop/renative/node_modules/react-native/local-cli/cli.js run-ios --project-path platformBuilds/template_ios --scheme RNVApp --configuration Debug --simulator iPhone\ 14 --allowProvisioningUpdates

FAILED with ERROR:

error: unknown option `--allowProvisioningUpdates'

Command failed with exit code 1: node /Users/pauliusguzas/Desktop/renative/node_modules/react-native/local-cli/cli.js run-ios --project-path platformBuilds/template_ios --scheme RNVApp --configuration Debug --simulator iPhone 14 --allowProvisioningUpdates
error: unknown option `--allowProvisioningUpdates'

error: unknown option `--allowProvisioningUpdates'

Error: Command failed with exit code 1: node /Users/pauliusguzas/Desktop/renative/node_modules/react-native/local-cli/cli.js run-ios --project-path platformBuilds/template_ios --scheme RNVApp --configuration Debug --simulator iPhone 14 --allowProvisioningUpdates
error: unknown option `--allowProvisioningUpdates'
    at makeError (/Users/pauliusguzas/Desktop/renative/node_modules/execa/lib/error.js:60:11)
    at handlePromise (/Users/pauliusguzas/Desktop/renative/node_modules/execa/index.js:118:26)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)


│                                                                              │
│  Project location:                                                           │
│  ./platformBuilds/template_ios/RNVApp.xcworkspace                            │
└──────────────────────────────────────────────────────
```
macos:
```
┌──────────────────────────────────────────────────────────────────────────────┐
│  🚀  SUMMARY | 6/28/2023, 2:33:13 PM                                         │
│  $ rnv run -p macos                                                          │
├──────────────────────────────────────────────────────────────────────────────┤
│  ReNative Version: 0.37.0-rc.7                                               │
│  Project Name ($package.name): @rnv/template-starter                         │
│  Project Version ($package.version): 0.37.0-rc.7                             │
│  Workspace ($.workspaceID): rnv                                              │
│  Platform (-p): macos                                                        │
│  Engine ($.platforms.macos.engine): engine-rn-electron                       │
│  App Config (-c): template                                                   │
│  Build Scheme (-s): debug                                                    │
│  Supported Platforms: macos                                                  │
│  Env Info: darwin | x64 | node v16.14.2                                      │
│  Executed Time: 0h:0m:0s:420ms                                               │
│                                                                              │
│ [ warn ] [configure] Your app is missing assets at ./appConfigs/base,./appConfigs/base,./appConfigs/template.
│ [ error ] [configure] Cannot read properties of undefined (reading '@electron/remote')
TypeError: Cannot read properties of undefined (reading '@electron/remote')
    at /Users/pauliusguzas/Desktop/renative/packages/engine-rn-electron/src/sdks/sdk-electron/index.js:107:67
    at new Promise (<anonymous>)
    at configureProject (/Users/pauliusguzas/Desktop/renative/packages/engine-rn-electron/src/sdks/sdk-electron/index.js:67:5)
    at /Users/pauliusguzas/Desktop/renative/packages/engine-rn-electron/src/sdks/sdk-electron/index.js:61:11
    at step (/Users/pauliusguzas/Desktop/renative/node_modules/tslib/tslib.js:193:27)
    at Object.next (/Users/pauliusguzas/Desktop/renative/node_modules/tslib/tslib.js:174:57)
    at fulfilled (/Users/pauliusguzas/Desktop/renative/node_modules/tslib/tslib.js:164:62)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
│                                                                              │
│  Project location:                                                           │
│  ./platformBuilds/template_macos                                             │
└──────────────────────────────────────────────────────────────────────────────┘
pauliusguzas@Pauliuss-MacBook-Pro template-starter %
```

**Comment by pauliusguzas** [comment]
Can't test tvos due to temporary env issue, if fixed will update

**Comment by GabrieleKaceviciute** [comment]
version 0.37.0-rc.8
Doesn't work on android tv and android:

[android.webm](https://github.com/flexn-io/renative/assets/106537292/737ac3e1-a7ee-4934-8892-d201569f6346)

**Comment by GabrieleKaceviciute** [comment]
works on v 0.37.0-rc.9
