### ISSUE TITLE
[Regression] rnv/template-starter@0.37.0-rc.9 issues running

### ISSUE THREAD

**Issue by pauliusguzas** [flexn-io/renative#1057]
Reproduce:
1. Install rnv@0.37.0-rc.9 with yarn globally
2. create new project with rnv new
3. run template as in commands below

1. rnv run (this error only occurs when this is the first command ran after doing rnv new)
```
┌──────────────────────────────────────────────────────────────────────────────┐
│  🚀  SUMMARY | 6/30/2023, 9:56:02 AM                                         │
│  $ rnv run                                                                   │
├──────────────────────────────────────────────────────────────────────────────┤
│  ReNative Version: 0.37.0-rc.9                                               │
│  Project Name ($package.name): rnv9                                          │
│  Project Version ($package.version): 0.1.0                                   │
│  Workspace ($.workspaceID): rnv                                              │
│  Build Scheme (-s): debug                                                    │
│  Env Info: darwin | x64 | node v16.14.2                                      │
│  Executed Time: 0h:1m:53s:546ms                                              │
│                                                                              │
│ [ error ] Cannot find module 'metro-cache'
Require stack:
- /Users/pauliusguzas/Desktop/rnv9/node_modules/@rnv/engine-rn-tvos/dist/adapter.js
- /Users/pauliusguzas/Desktop/rnv9/node_modules/@rnv/engine-rn-tvos/dist/index.js
- /Users/pauliusguzas/.config/yarn/global/node_modules/rnv/dist/core/engineManager/index.js
- /Users/pauliusguzas/.config/yarn/global/node_modules/rnv/dist/core/runtimeManager/index.js
- /Users/pauliusguzas/.config/yarn/global/node_modules/rnv/dist/cli/index.js
- /Users/pauliusguzas/.config/yarn/global/node_modules/rnv/dist/index.js
- /Users/pauliusguzas/.config/yarn/global/node_modules/rnv/bin/index.js
Error: Cannot find module 'metro-cache'
Require stack:
- /Users/pauliusguzas/Desktop/rnv9/node_modules/@rnv/engine-rn-tvos/dist/adapter.js
- /Users/pauliusguzas/Desktop/rnv9/node_modules/@rnv/engine-rn-tvos/dist/index.js
- /Users/pauliusguzas/.config/yarn/global/node_modules/rnv/dist/core/engineManager/index.js
- /Users/pauliusguzas/.config/yarn/global/node_modules/rnv/dist/core/runtimeManager/index.js
- /Users/pauliusguzas/.config/yarn/global/node_modules/rnv/dist/cli/index.js
- /Users/pauliusguzas/.config/yarn/global/node_modules/rnv/dist/index.js
- /Users/pauliusguzas/.config/yarn/global/node_modules/rnv/bin/index.js
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:933:15)
    at Function.Module._load (node:internal/modules/cjs/loader:778:27)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at Object.<anonymous> (/Users/pauliusguzas/Desktop/rnv9/node_modules/@rnv/engine-rn-tvos/src/adapter.js:5:19)
    at Module._compile (node:internal/modules/cjs/loader:1103:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1157:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
│                                                                              │
└──────────────────────────────────────────────────────────────────────────────┘
pauliusguzas@Pauliuss-MacBook-Pro rnv9 %
```
2. rnv run -p web
```
┌──────────────────────────────────────────────────────────────────────────────┐
│  🚀  SUMMARY | 6/30/2023, 10:53:34 AM                                        │
│  $ rnv run -p web                                                            │
├──────────────────────────────────────────────────────────────────────────────┤
│  ReNative Version: 0.37.0-rc.9                                               │
│  Project Name ($package.name): rnv9                                          │
│  Project Version ($package.version): 0.1.0                                   │
│  Workspace ($.workspaceID): rnv                                              │
│  Platform (-p): web                                                          │
│  Engine ($.platforms.web.engine): engine-rn-next                             │
│  Template: @rnv/template-starter@0.37.0-rc.9                                 │
│  App Config (-c): app                                                        │
│  Build Scheme (-s): debug                                                    │
│  Supported Platforms: web                                                    │
│  Env Info: darwin | x64 | node v16.14.2                                      │
│  Executed Time: 0h:0m:4s:171ms                                               │
│                                                                              │
│ [ warn ] [configure] Your app is missing assets at ./appConfigs/base,./appConfigs/app.
│ [ error ] [run] COMMAND:

npx next dev --port 8080

FAILED with ERROR:

Command failed with exit code 1: npx next dev --port 8080

Error: Command failed with exit code 1: npx next dev --port 8080
    at makeError (/Users/pauliusguzas/Desktop/rnv9/node_modules/execa/lib/error.js:60:11)
    at handlePromise (/Users/pauliusguzas/Desktop/rnv9/node_modules/execa/index.js:118:26)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)


│                                                                              │
│  Project location:                                                           │
│  ./platformBuilds/app_web                                                    │
└──────────────────────────────────────────────────────────────────────────────┘
pauliusguzas@Pauliuss-MacBook-Pro rnv9 %
```
3. rnv run -p android
[android.txt](https://github.com/flexn-io/renative/files/11914894/android.txt)
4. rnv run -p ios
[ios.txt](https://github.com/flexn-io/renative/files/11914895/ios.txt)
5. rnv run -p androidtv
[androidtv.txt](https://github.com/flexn-io/renative/files/11914902/androidtv.txt)
6. rnv run -p fir
[firetv.txt](https://github.com/flexn-io/renative/files/11914906/firetv.txt)
etv
7. rnv run -p tvos
```
✔ Executing: node /Users/pauliusguzas/Desktop/rnv9/node_modules/react-native-tvos/local-cli/cli.js run-ios --project-path platformBuilds/app_tvos --scheme RNVAppTVOS --configuration Debug --simulator Apple\ TV --allowProvisioningUpdates
┌──────────────────────────────────────────────────────────────────────────────┐
│  🚀  BUNDLER STARTED | 6/30/2023, 11:48:43 AM                                │
│  $ rnv run -p tvos                                                           │
├──────────────────────────────────────────────────────────────────────────────┤
│  ReNative Version: 0.37.0-rc.9                                               │
│  Project Name ($package.name): rnv9                                          │
│  Project Version ($package.version): 0.1.0                                   │
│  Workspace ($.workspaceID): rnv                                              │
│  Platform (-p): tvos                                                         │
│  Engine ($.platforms.tvos.engine): engine-rn-tvos                            │
│  Template: @rnv/template-starter@0.37.0-rc.9                                 │
│  App Config (-c): app                                                        │
│  Build Scheme (-s): debug                                                    │
│  Target (-t): Apple TV                                                       │
│  Supported Platforms: tvos                                                   │
│  Env Info: darwin | x64 | node v16.14.2                                      │
│  Executed Time: 0h:8m:43s:747ms                                              │
│                                                                              │
│ [ warn ] [configure] Your app is missing assets at ./appConfigs/base,./appConfigs/app.
│                                                                              │
│  Project location:                                                           │
│  ./platformBuilds/app_tvos/RNVAppTVOS.xcworkspace                            │
└──────────────────────────────────────────────────────────────────────────────┘
```

**Comment by pauliusguzas** [comment]
NOTE: if after creating project first thing user runs is tvos, and then macos, this is what he gets
tvos:
```
┌──────────────────────────────────────────────────────────────────────────────┐
│  🚀  SUMMARY | 7/4/2023, 11:04:43 AM                                         │
│  $ rnv run -p tvos                                                           │
├──────────────────────────────────────────────────────────────────────────────┤
│  ReNative Version: 0.37.0-rc.9                                               │
│  Project Name ($package.name): gab4                                          │
│  Project Version ($package.version): 0.1.0                                   │
│  Workspace ($.workspaceID): rnv                                              │
│  Platform (-p): tvos                                                         │
│  Build Scheme (-s): debug                                                    │
│  Env Info: darwin | x64 | node v16.14.2                                      │
│  Executed Time: 0h:2m:9s:926ms                                               │
│                                                                              │
│ [ error ] Cannot find module 'metro-cache'
Require stack:
- /Users/pauliusguzas/Desktop/gab4/node_modules/@rnv/engine-rn-tvos/dist/adapter.js
- /Users/pauliusguzas/Desktop/gab4/node_modules/@rnv/engine-rn-tvos/dist/index.js
- /Users/pauliusguzas/.nvm/versions/node/v16.14.2/lib/node_modules/rnv/dist/core/engineManager/index.js
- /Users/pauliusguzas/.nvm/versions/node/v16.14.2/lib/node_modules/rnv/dist/core/runtimeManager/index.js
- /Users/pauliusguzas/.nvm/versions/node/v16.14.2/lib/node_modules/rnv/dist/cli/index.js
- /Users/pauliusguzas/.nvm/versions/node/v16.14.2/lib/node_modules/rnv/dist/index.js
- /Users/pauliusguzas/.nvm/versions/node/v16.14.2/lib/node_modules/rnv/bin/index.js
Error: Cannot find module 'metro-cache'
Require stack:
- /Users/pauliusguzas/Desktop/gab4/node_modules/@rnv/engine-rn-tvos/dist/adapter.js
- /Users/pauliusguzas/Desktop/gab4/node_modules/@rnv/engine-rn-tvos/dist/index.js
- /Users/pauliusguzas/.nvm/versions/node/v16.14.2/lib/node_modules/rnv/dist/core/engineManager/index.js
- /Users/pauliusguzas/.nvm/versions/node/v16.14.2/lib/node_modules/rnv/dist/core/runtimeManager/index.js
- /Users/pauliusguzas/.nvm/versions/node/v16.14.2/lib/node_modules/rnv/dist/cli/index.js
- /Users/pauliusguzas/.nvm/versions/node/v16.14.2/lib/node_modules/rnv/dist/index.js
- /Users/pauliusguzas/.nvm/versions/node/v16.14.2/lib/node_modules/rnv/bin/index.js
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:933:15)
    at Function.Module._load (node:internal/modules/cjs/loader:778:27)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at Object.<anonymous> (/Users/pauliusguzas/Desktop/gab4/node_modules/@rnv/engine-rn-tvos/src/adapter.js:5:19)
    at Module._compile (node:internal/modules/cjs/loader:1103:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1157:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
│                                                                              │
└──────────────────────────────────────────────────────────────────────────────┘
pauliusguzas@Pauliuss-MacBook-Pro gab4 %
```
macos:
```
┌──────────────────────────────────────────────────────────────────────────────┐
│  🚀  SUMMARY | 7/4/2023, 11:06:44 AM                                         │
│  $ rnv run -p macos                                                          │
├──────────────────────────────────────────────────────────────────────────────┤
│  ReNative Version: 0.37.0-rc.9                                               │
│  Project Name ($package.name): gab4                                          │
│  Project Version ($package.version): 0.1.0                                   │
│  Workspace ($.workspaceID): rnv                                              │
│  Platform (-p): macos                                                        │
│  Engine ($.platforms.macos.engine): engine-rn-electron                       │
│  Template: @rnv/template-starter@0.37.0-rc.9                                 │
│  App Config (-c): app                                                        │
│  Build Scheme (-s): debug                                                    │
│  Supported Platforms: macos                                                  │
│  Env Info: darwin | x64 | node v16.14.2                                      │
│  Executed Time: 0h:0m:49s:711ms                                              │
│                                                                              │
│ [ success ] [install] /next/dist/lib/find-pages-dir.js requires override by: /@flexn/plugins/pluginTemplates/next/overrides.json. FIXING...DONE
│ [ warn ] [configure] Your app is missing assets at ./appConfigs/base,./appConfigs/app.
│ [ error ] [run] Cannot find module '/Users/pauliusguzas/Desktop/gab4/node_modules/semver/index.js'. Please verify that the package.json has a valid "main" entry
Error: Cannot find module '/Users/pauliusguzas/Desktop/gab4/node_modules/semver/index.js'. Please verify that the package.json has a valid "main" entry
    at tryPackage (node:internal/modules/cjs/loader:353:19)
    at Function.Module._findPath (node:internal/modules/cjs/loader:566:18)
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:919:27)
    at Function.Module._load (node:internal/modules/cjs/loader:778:27)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at Object.<anonymous> (/Users/pauliusguzas/Desktop/gab4/node_modules/babel-plugin-polyfill-corejs2/lib/helpers.js:6:38)
    at Module._compile (node:internal/modules/cjs/loader:1103:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1157:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
│                                                                              │
│  Project location:                                                           │
│  ./platformBuilds/app_macos                                                  │
└──────────────────────────────────────────────────────────────────────────────┘
pauliusguzas@Pauliuss-MacBook-Pro gab4 %
```

**Comment by pauliusguzas** [comment]
Updates on rc.10:
Metro cash issue is now also when doing `rnv crypto decrypt` or `rnv crypto encrypt`

**Comment by pauliusguzas** [comment]
Updates on rc.12:
metro-cache issues fixed

**Comment by pauliusguzas** [comment]
Updates on rc.13:
androidtv/firetv issue remains, everything else is fixed

**Comment by pauliusguzas** [comment]
Updates on rc.14:
All issues solved
