### ISSUE TITLE
Hooks don't work if that is the first command after rnv new

### ISSUE THREAD

**Issue by pauliusguzas** [flexn-io/renative#1061]
**Describe the bug**
Hooks don't work if that is the first command after rnv new, if user previously tried running, or encrypting, then hooks work

**To Reproduce**
1. Create rnv project with` rnv new`
2. Do `rnv hooks run`

```
┌──────────────────────────────────────────────────────────────────────────────┐
│  🚀  SUMMARY | 7/3/2023, 3:14:00 PM                                          │
│  $ rnv hooks run                                                             │
├──────────────────────────────────────────────────────────────────────────────┤
│  ReNative Version: 0.37.0-rc.9                                               │
│  Project Name ($package.name): naujas                                        │
│  Project Version ($package.version): 0.1.0                                   │
│  Workspace ($.workspaceID): rnv                                              │
│  Engine: engine-core                                                         │
│  Template: @rnv/template-starter@0.37.0-rc.9                                 │
│  App Config (-c): app                                                        │
│  Build Scheme (-s): debug                                                    │
│  Env Info: darwin | x64 | node v16.14.2                                      │
│  Executed Time: 0h:1m:16s:965ms                                              │
│                                                                              │
│ [ error ] [hooks run] Build hooks have not been compiled properly!
│                                                                              │
└──────────────────────────────────────────────────────────────────────────────┘
pauliusguzas@Pauliuss-MacBook-Pro naujas %
```

**Expected behavior**
Hooks exit successfully

**Desktop (please complete the following information):**

-   OS: macOS 13.2
-   Node Version v16.14.2
-   RNV Version 0.37.0-rc.9

**Comment by pauliusguzas** [comment]
0.38.0-canary.1

Hooks don't work the firsst time they are ran, no matter if that is the first command after rnv new. There is no hook to choose from and after clicking enter error appears
And the error is different:
```
[ task ] <= [hooks run] <= project configure
? Pick an available hook: (Use arrow keys)

/Users/pauliusguzas/.config/yarn/global/node_modules/rnv/node_modules/inquirer/lib/prompts/list.js:153
    return this.opt.choices.getChoice(this.selected).value;
                                                    ^
TypeError: Cannot read properties of undefined (reading 'value')
    at ListPrompt.getCurrentValue (/Users/pauliusguzas/.config/yarn/global/node_modules/rnv/node_modules/inquirer/lib/prompts/list.js:153:53)
    at /Users/pauliusguzas/.config/yarn/global/node_modules/rnv/node_modules/rxjs/src/internal/operators/map.ts:58:33
    at OperatorSubscriber._this._next (/Users/pauliusguzas/.config/yarn/global/node_modules/rnv/node_modules/rxjs/src/internal/operators/OperatorSubscriber.ts:70:13)
    at OperatorSubscriber.Subscriber.next (/Users/pauliusguzas/.config/yarn/global/node_modules/rnv/node_modules/rxjs/src/internal/Subscriber.ts:75:12)
    at /Users/pauliusguzas/.config/yarn/global/node_modules/rnv/node_modules/rxjs/src/internal/operators/take.ts:60:26
    at OperatorSubscriber._this._next (/Users/pauliusguzas/.config/yarn/global/node_modules/rnv/node_modules/rxjs/src/internal/operators/OperatorSubscriber.ts:70:13)
    at OperatorSubscriber.Subscriber.next (/Users/pauliusguzas/.config/yarn/global/node_modules/rnv/node_modules/rxjs/src/internal/Subscriber.ts:75:12)
    at Interface.handler (/Users/pauliusguzas/.config/yarn/global/node_modules/rnv/node_modules/rxjs/src/internal/observable/fromEvent.ts:292:52)
    at Interface.emit (node:events:538:35)
    at Interface._onLine (node:readline:487:10)

pauliusguzas@Pauliuss-MacBook-Pro ketvi4 %
```

**Comment by pauliusguzas** [comment]
1.0.0-canary.8
```
pauliusguzas@MBP-de-Flexn Desktop % npx rnv hooks run

┌──────────────────────────────────────────────────────────────────────────────┐
│                                                                              │
│        ██████╗ ███████╗███╗   ██╗ █████╗ ████████╗██╗██╗   ██╗███████╗       │
│        ██╔══██╗██╔════╝████╗  ██║██╔══██╗╚══██╔══╝██║██║   ██║██╔════╝       │
│        ██████╔╝█████╗  ██╔██╗ ██║███████║   ██║   ██║██║   ██║█████╗         │
│        ██╔══██╗██╔══╝  ██║╚██╗██║██╔══██║   ██║   ██║╚██╗ ██╔╝██╔══╝         │
│        ██║  ██║███████╗██║ ╚████║██║  ██║   ██║   ██║ ╚████╔╝ ███████╗       │
│        ╚═╝  ╚═╝╚══════╝╚═╝  ╚═══╝╚═╝  ╚═╝   ╚═╝   ╚═╝  ╚═══╝  ╚══════╝       │
│                                                                              │
│        Version: 1.0.0-canary.8                                               │
│        https://renative.org                                                  │
│        🚀 Firing up!...                                                      │
│        $ rnv hooks run                                                       │
│        Start Time: 11/21/2023, 4:22:08 PM                                    │
│                                                                              │
└──────────────────────────────────────────────────────────────────────────────┘

[ task ] registerEngine:engine-core[1]
[ task ] configureRuntimeDefaults[1] appId:undefined
[ task ] checkAndMigrateProject[1]
[ task ] loadPluginTemplates[1]
[ task ] parseRenativeConfigs[1]
[ task ] getWorkspaceDirPath[1]
[ task ] checkAndBootstrapIfRequired[1]
[ task ] loadIntegrations[1]
[ task ] loadEngines[1]
[ task ] findSuitableTask[1]
[ info ] Current Engine: engine-core path: undefined
[ task ] registerMissingPlatformEngines[1]
[ task ] initializeTask[1] hooks run
[ task ] => [hooks run]
[ task ] [hooks run] taskRnvHooksRun[1]
[ info ] [hooks run] Your are running your buildHook outside of renative project
? Build hooks not configured in this project. Configure? Yes
[ hook ] [hooks run] buildHooks Build hooks not complied. BUILDING...
Error: Cannot find module '@rnv/core'
Require stack:
- /Users/pauliusguzas/Desktop/buildHooks/dist/index.js
- /Users/pauliusguzas/Desktop/renative/renative/packages/core/lib/buildHooks/index.js
- /Users/pauliusguzas/Desktop/renative/renative/packages/core/lib/tasks/index.js
- /Users/pauliusguzas/Desktop/renative/renative/packages/core/lib/integrations/index.js
- /Users/pauliusguzas/Desktop/renative/renative/packages/core/lib/runner.js
- /Users/pauliusguzas/Desktop/renative/renative/packages/core/lib/index.js
- /Users/pauliusguzas/Desktop/renative/renative/packages/cli/lib/index.js
- /Users/pauliusguzas/Desktop/renative/renative/packages/rnv/bin/index.js
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:1075:15)
    at Function.Module._load (node:internal/modules/cjs/loader:920:27)
    at Module.require (node:internal/modules/cjs/loader:1141:19)
    at require (node:internal/modules/cjs/helpers:110:18)
    at Object.<anonymous> (/Users/pauliusguzas/Desktop/buildHooks/dist/index.js:30:30)
    at Module._compile (node:internal/modules/cjs/loader:1254:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1308:10)
    at Module.load (node:internal/modules/cjs/loader:1117:32)
    at Function.Module._load (node:internal/modules/cjs/loader:958:12)
    at Module.require (node:internal/modules/cjs/loader:1141:19) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/Users/pauliusguzas/Desktop/buildHooks/dist/index.js',
    '/Users/pauliusguzas/Desktop/renative/renative/packages/core/lib/buildHooks/index.js',
    '/Users/pauliusguzas/Desktop/renative/renative/packages/core/lib/tasks/index.js',
    '/Users/pauliusguzas/Desktop/renative/renative/packages/core/lib/integrations/index.js',
    '/Users/pauliusguzas/Desktop/renative/renative/packages/core/lib/runner.js',
    '/Users/pauliusguzas/Desktop/renative/renative/packages/core/lib/index.js',
    '/Users/pauliusguzas/Desktop/renative/renative/packages/cli/lib/index.js',
    '/Users/pauliusguzas/Desktop/renative/renative/packages/rnv/bin/index.js'
  ]
}

 $ rnv hooks run - Done! 🚀
┌──────────────────────────────────────────────────────────────────────────────┐
│  🚀  SUMMARY | 11/21/2023, 4:22:14 PM                                        │
│  $ rnv hooks run                                                             │
├──────────────────────────────────────────────────────────────────────────────┤
│  ReNative Version: 1.0.0-canary.8                                            │
│  Engine: engine-core                                                         │
│  Build Scheme (-s): debug                                                    │
│  Env Info: darwin | x64 | node v18.16.0                                      │
│  Executed Time: 0h:0m:5s:399ms                                               │
│                                                                              │
│  All good as 🦄                                                              │
│                                                                              │
└──────────────────────────────────────────────────────────────────────────────┘
```
