### ISSUE TITLE
[Web] can't run web application using rnv run -p web [RNV] version 0.36.1

### ISSUE THREAD

**Issue by iMokhles** [flexn-io/renative#1070]
**Describe the bug**
i face those errors when i run
`rnv run -p web`
and
`rnv run -p web -r`

ERROR 1:

```
Found custom dir:/Users/imokhles/Documents/MokhlesProjects/RN/Fantasy/src/pages
info  - Disabled SWC as replacement for Babel because of custom Babel configuration "babel.config.js" https://nextjs.org/docs/messages/swc-disabled
info  - automatically enabled Fast Refresh for 1 custom loader
info  - Using external babel configuration from /Users/imokhles/Documents/MokhlesProjects/RN/Fantasy/babel.config.js
wait  - compiling...
error - ./node_modules/react-native-vector-icons/lib/create-icon-set.js
Error: You gave us a visitor for the node type ClassAccessorProperty but it's not a valid type
info  - automatically enabled Fast Refresh for 1 custom loader
info  - automatically enabled Fast Refresh for 1 custom loader
info  - automatically enabled Fast Refresh for 1 custom loader
info  - automatically enabled Fast Refresh for 1 custom loader
info  - automatically enabled Fast Refresh for 1 custom loader
info  - automatically enabled Fast Refresh for 1 custom loader
info  - automatically enabled Fast Refresh for 1 custom loader
info  - automatically enabled Fast Refresh for 1 custom loader
wait  - compiling /_error (client and server)...
wait  - compiling...
(node:56118) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 client/_error listeners added to [EventEmitter]. Use emitter.setMaxListeners() to increase limit
(Use `node --trace-warnings ...` to show where the warning was created)
(node:56118) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 server/_error listeners added to [EventEmitter]. Use emitter.setMaxListeners() to increase limit
error - ./node_modules/react-native-vector-icons/lib/create-icon-set.js
Error: You gave us a visitor for the node type ClassAccessorProperty but it's not a valid type


```
ERROR 2:

```
Error: Cannot find module '/Users/imokhles/Documents/MokhlesProjects/RN/Fantasy/platformBuilds/app_web/.next/fallback-build-manifest.json'
Require stack:
- /Users/imokhles/Documents/MokhlesProjects/RN/Fantasy/node_modules/next/dist/server/load-components.js
- /Users/imokhles/Documents/MokhlesProjects/RN/Fantasy/node_modules/next/dist/server/next-server.js
- /Users/imokhles/Documents/MokhlesProjects/RN/Fantasy/node_modules/next/dist/server/next.js
- /Users/imokhles/Documents/MokhlesProjects/RN/Fantasy/node_modules/next/dist/server/lib/start-server.js
- /Users/imokhles/Documents/MokhlesProjects/RN/Fantasy/node_modules/next/dist/cli/next-dev.js
- /Users/imokhles/Documents/MokhlesProjects/RN/Fantasy/node_modules/next/dist/bin/next
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:933:15)
    at Function.call [as _resolveFilename] (/Users/imokhles/Documents/MokhlesProjects/RN/Fantasy/node_modules/next/build/webpack/require-hook.ts:142:26)
    at Function.Module._load (node:internal/modules/cjs/loader:778:27)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at Object.require [as loadDefaultErrorComponents] (/Users/imokhles/Documents/MokhlesProjects/RN/Fantasy/node_modules/next/server/load-components.ts:57:20)
    at DevServer.getFallbackErrorComponents (/Users/imokhles/Documents/MokhlesProjects/RN/Fantasy/node_modules/next/server/dev/next-dev-server.ts:977:44)
    at DevServer.renderErrorToResponse (/Users/imokhles/Documents/MokhlesProjects/RN/Fantasy/node_modules/next/server/base-server.ts:1889:34)
    at pipe.req.req (/Users/imokhles/Documents/MokhlesProjects/RN/Fantasy/node_modules/next/server/base-server.ts:1812:26)
    at DevServer.pipe (/Users/imokhles/Documents/MokhlesProjects/RN/Fantasy/node_modules/next/server/base-server.ts:1020:21) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/Users/imokhles/Documents/MokhlesProjects/RN/Fantasy/node_modules/next/dist/server/load-components.js',
    '/Users/imokhles/Documents/MokhlesProjects/RN/Fantasy/node_modules/next/dist/server/next-server.js',
    '/Users/imokhles/Documents/MokhlesProjects/RN/Fantasy/node_modules/next/dist/server/next.js',
    '/Users/imokhles/Documents/MokhlesProjects/RN/Fantasy/node_modules/next/dist/server/lib/start-server.js',
    '/Users/imokhles/Documents/MokhlesProjects/RN/Fantasy/node_modules/next/dist/cli/next-dev.js',
    '/Users/imokhles/Documents/MokhlesProjects/RN/Fantasy/node_modules/next/dist/bin/next'
  ]
}

```

**Expected behavior**
App should run on browser ( web platform )

**Desktop (please complete the following information):**

-   OS: macOS
-   Node Version v16.16.0
-   RNV Version 0.36.1

**Comment by pauliusguzas** [comment]
@iMokhles Hello, thanks for reporting this issue, could you please try [0.37.1](https://www.npmjs.com/package/rnv/v/0.37.1) version?

**Comment by pauliusguzas** [comment]
@iMokhles closing as issue has been resolved, please feel free to reopen
