### ISSUE TITLE
[Regression] [web, macos] Web doesn't run on @rnv/template-starter@0.38.0-canary.1

### ISSUE THREAD

**Issue by pauliusguzas** [flexn-io/renative#1100]
**Describe the bug**
Web doesn't run on @rnv/template-starter@0.38.0-canary.1

**To Reproduce**
1. Create new project with `rnv run` and choose `@rnv/template-starter` template with `0.38.0-canary.1` version
2. Run `rnv run -p web` or `rnv run -p macos`

**Expected behavior**
app runs

**Screenshots or copy&paste**
```
│  🚀  SUMMARY | 9/7/2023, 11:09:49 AM                                         │
│  $ rnv run -p web                                                            │
├──────────────────────────────────────────────────────────────────────────────┤
│  ReNative Version: 0.38.0-canary.1                                           │
│  Project Name ($package.name): ketvi4                                        │
│  Project Version ($package.version): 0.1.0                                   │
│  Workspace ($.workspaceID): rnv                                              │
│  Platform (-p): web                                                          │
│  Engine ($.platforms.web.engine): engine-rn-next                             │
│  Template: @rnv/template-starter@0.38.0-canary.1                             │
│  App Config (-c): app                                                        │
│  Build Scheme (-s): debug                                                    │
│  Supported Platforms: web                                                    │
│  Env Info: darwin | x64 | node v16.14.2                                      │
│  Executed Time: 0h:0m:3s:932ms                                               │
│                                                                              │
│ [ error ] [configure] The "path" argument must be of type string. Received undefined
TypeError: The "path" argument must be of type string. Received undefined
    at new NodeError (node:internal/errors:371:5)
    at validateString (node:internal/validators:120:11)
    at Object.join (node:path:1172:7)
    at /Users/pauliusguzas/Desktop/ketvi4/node_modules/rnv/src/core/projectManager/index.ts:464:27
    at step (/Users/pauliusguzas/Desktop/ketvi4/node_modules/rnv/node_modules/tslib/tslib.js:143:27)
    at Object.next (/Users/pauliusguzas/Desktop/ketvi4/node_modules/rnv/node_modules/tslib/tslib.js:124:57)
    at /Users/pauliusguzas/Desktop/ketvi4/node_modules/rnv/node_modules/tslib/tslib.js:117:75
    at new Promise (<anonymous>)
    at Object.__awaiter (/Users/pauliusguzas/Desktop/ketvi4/node_modules/rnv/node_modules/tslib/tslib.js:113:16)
    at copyAssetsFolder (/Users/pauliusguzas/Desktop/ketvi4/node_modules/rnv/src/core/projectManager/index.ts:436:57)
│                                                                              │
│  Project location:                                                           │
│  ./platformBuilds/app_web                                                    │
└──────────────────────────────────────────────────────────────────────────────┘
pauliusguzas@Pauliuss-MacBook-Pro ketvi4 %
```

**Desktop (please complete the following information):**
- OS: macOS Ventura 13.2
- Node Version: 16.14.2
- RNV Version: 0.38.0-canary.1
- @rnv/template-starter: 0.38.0-canary.1

**Comment by mihaiblaga89** [comment]
@pauliusguzas should be fixed in latest canary, feel free to close if so
