### ISSUE TITLE
[webos, tizen, tizenwatch, tizenmobile, macos] TypeError: Cannot read properties of undefined (reading 'logInfo')

### ISSUE THREAD

**Issue by pauliusguzas** [flexn-io/renative#1123]
**Describe the bug**
Can't build/export all web based platforms beside actual web

**To Reproduce**
1. go to template-starter package
2. run `rnv export -p webos`

```
TypeError: Cannot read properties of undefined (reading 'logInfo')
    at Object.<anonymous> (/Users/pauliusguzas/Desktop/renative/renative/packages/sdk-webpack/src/scripts/build.js:20:61)
    at Module._compile (node:internal/modules/cjs/loader:1254:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1308:10)
    at Module.load (node:internal/modules/cjs/loader:1117:32)
    at Function.Module._load (node:internal/modules/cjs/loader:958:12)
    at Module.require (node:internal/modules/cjs/loader:1141:19)
    at require (node:internal/modules/cjs/helpers:110:18)
    at /Users/pauliusguzas/Desktop/renative/renative/packages/sdk-webpack/src/index.ts:216:19
    at step (/Users/pauliusguzas/Desktop/renative/renative/node_modules/tslib/tslib.js:195:27)
    at Object.next (/Users/pauliusguzas/Desktop/renative/renative/node_modules/tslib/tslib.js:176:57)

 $ rnv build -p webos - Done! 🚀
┌──────────────────────────────────────────────────────────────────────────────┐
│  🚀  SUMMARY | 10/5/2023, 10:38:35 AM                                        │
│  $ rnv build -p webos                                                        │
├──────────────────────────────────────────────────────────────────────────────┤
│  ReNative Version: 1.0.0-canary.0                                            │
│  Project Name ($package.name): @rnv/template-starter                         │
│  Project Version ($package.version): 1.0.0-canary.0                          │
│  Workspace ($.workspaceID): rnv                                              │
│  Platform (-p): webos                                                        │
│  Engine ($.platforms.webos.engine): engine-rn-web                            │
│  App Config (-c): template                                                   │
│  Build Scheme (-s): debug                                                    │
│  Target (-t): emulator                                                       │
│  Supported Platforms: webos                                                  │
│  Env Info: darwin | x64 | node v18.16.0                                      │
│  Executed Time: 0h:0m:0s:469ms                                               │
│                                                                              │
│ [ warn ] [project configure] Version mismatch of devDependency react-native-gesture-handler between package.json: v(2.13.1) and plugins.json: v(2.12.1). This is template. NO ACTION
│                                                                              │
│  Project location:                                                           │
│  ./platformBuilds/template_webos                                             │
└──────────────────────────────────────────────────────────────────────────────┘
pauliusguzas@MBP-de-Flexn template-starter %
```

**Expected behavior**
Template app should start in Android simulator

**Desktop (please complete the following information):**

-   OS: Ventura 13.5.2
-   Node Version 18.16.0
-   RNV Version 1.0.0-canary.1
-   rnv/template-starter Version 1.0.0-canary.1

**Comment by kasinskas** [comment]
https://github.com/flexn-io/renative/pull/1124
