### ISSUE TITLE
[web] build/export error

### ISSUE THREAD

**Issue by pauliusguzas** [flexn-io/renative#1125]
**Describe the bug**
Can't build/export web without errors

**To Reproduce**
1. go to template-starter package
2. run `rnv export -p web`

```
> Export encountered errors on following paths:
	/
	/404
	/_error: /500
   Creating an optimized production build...
 ✓ Compiled successfully
   Linting and checking validity of types...
   Collecting page data...
   Generating static pages (0/3)...
 ✓ Generating static pages (3/3)
    at makeError (/Users/pauliusguzas/Desktop/renative/renative/node_modules/execa/lib/error.js:60:11)
    at handlePromise (/Users/pauliusguzas/Desktop/renative/renative/node_modules/execa/index.js:118:26)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)



 $ rnv build -p web - Done! 🚀
┌──────────────────────────────────────────────────────────────────────────────┐
│  🚀  SUMMARY | 10/5/2023, 12:43:53 PM                                        │
│  $ rnv build -p web                                                          │
├──────────────────────────────────────────────────────────────────────────────┤
│  ReNative Version: 1.0.0-canary.1                                            │
│  Project Name ($package.name): @rnv/template-starter                         │
│  Project Version ($package.version): 1.0.0-canary.1                          │
│  Workspace ($.workspaceID): rnv                                              │
│  Platform (-p): web                                                          │
│  Engine ($.platforms.web.engine): engine-rn-next                             │
│  App Config (-c): template                                                   │
│  Build Scheme (-s): debug                                                    │
│  Supported Platforms: web                                                    │
│  Env Info: darwin | x64 | node v18.16.0                                      │
│  Executed Time: 0h:0m:18s:721ms                                              │
│                                                                              │
│ [ warn ] [project configure] Version mismatch of devDependency react-native-gesture-handler between package.json: v(2.13.1) and plugins.json: v(2.12.1). This is template. NO ACTION
│                                                                              │
│  Project location:                                                           │
│  ./platformBuilds/template_web                                               │
└──────────────────────────────────────────────────────────────────────────────┘
pauliusguzas@MBP-de-Flexn template-starter %
```

**Desktop (please complete the following information):**

-   OS: Ventura 13.5.2
-   Node Version 18.16.0
-   RNV Version 1.0.0-canary.1
-   rnv/template-starter Version 1.0.0-canary.1

**Comment by pauliusguzas** [comment]
Works on sanity_1.0.0-2
