### ISSUE TITLE
[Regression] [Android, Androidwear, AndroidTV, FireTV] rnv/template-starter@1.0.0-canary.1 cannot run (RNV new project)

### ISSUE THREAD

**Issue by GabrieleKaceviciute** [flexn-io/renative#1131]
**Describe the bug**
Can't run/build/export all android platforms

**Steps to reproduce the behavior:**

1. Install rnv@1.0.0-canary.1 with npm globally
2. create new project with `rnv new` and choose rnv/template-starter with same version
3. do `npx rnv run -p android` / `androidwear`  / `androidtv ` / `firetv` / `android -d`

```
[ error ] [configure] Cannot write file. source path doesn't exists: /Users/gabriele/Desktop/tests/bimbam/node_modules/@rnv/sdk-android/templates/gradleProject/gradle/wrapper/gradle-wrapper.properties
[ error ] [configure] Cannot write file. source path doesn't exists: /Users/gabriele/Desktop/tests/bimbam/node_modules/@rnv/engine-rn/templates/platforms/android/app/src/main/java/rnv/SplashActivity.kt
[ task ] [configure] parseAndroidManifestSync[1]
[ task ] [configure] parsePlugins[5]
[ task ] [configure] _checkSigningCerts[1]
[ task ] [configure] copyBuildsFolder[1]
[ task ] [configure] copyTemplatePluginsSync[1] (./platformBuilds/app_android)
[ task ] [configure] parsePlugins[6]
[ task ] [configure] jetifyIfRequired[1]
⠋ Executing: npx jetifyError: ENOENT: no such file or directory, chmod '/Users/gabriele/Desktop/tests/bimbam/platformBuilds/app_android/gradlew'
    at Object.chmodSync (node:fs:1991:3)
    at fsChmodSync (/Users/gabriele/Desktop/tests/bimbam/node_modules/@rnv/core/src/system/fs.ts:36:81)
    at /Users/gabriele/Desktop/tests/bimbam/node_modules/@rnv/sdk-android/src/gradleWrapperParser.ts:24:16
    at step (/Users/gabriele/Desktop/tests/bimbam/node_modules/tslib/tslib.js:195:27)
    at Object.next (/Users/gabriele/Desktop/tests/bimbam/node_modules/tslib/tslib.js:176:57)
    at /Users/gabriele/Desktop/tests/bimbam/node_modules/tslib/tslib.js:169:75
    at new Promise (<anonymous>)
    at Object.__awaiter (/Users/gabriele/Desktop/tests/bimbam/node_modules/tslib/tslib.js:165:16)
    at copyGradleProjectTemplate (/Users/gabriele/Desktop/tests/bimbam/node_modules/@rnv/sdk-android/src/gradleWrapperParser.ts:16:52)
    at parseGradleWrapperSync (/Users/gabriele/Desktop/tests/bimbam/node_modules/@rnv/sdk-android/src/gradleWrapperParser.ts:30:5)
➜  ~/Desktop/tests/bimbam 
```

**Expected behavior**
Template app should start in Android simulator or device

**Desktop (please complete the following information):**

-   OS: macOS Ventura 13.5.2
-   Node Version 18.18.0
-   RNV Version 1.0.0-canary.1

**Comment by mihaiblaga89** [comment]
should already be fixed by https://github.com/flexn-io/renative/pull/1178

**Comment by GabrieleKaceviciute** [comment]
1.0.0-feat-bonanza.4
Android, androidTV, fireTV - works
Androidwear run ->
```
✔ Executing: npx react-native run-android --mode=Debug --no-packager --deviceId=emulator-5554

info Building the app...
> Task :app:processDebugMainManifest FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:processDebugMainManifest'.
> com.android.manifmerger.ManifestMerger2$MergeFailureException: Error parsing /Users/gabriele/Desktop/tests/qwer/platformBuilds/app_androidwear/app/src/main/AndroidManifest.xml

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.

* Get more help at https://help.gradle.org

Deprecated Gradle features were used in this build, making it incompatible with Gradle 9.0.

You can use '--warning-mode all' to show the individual deprecation warnings and determine if they come from your own scripts or plugins.

See https://docs.gradle.org/8.0.1/userguide/command_line_interface.html#sec:command_line_warnings

BUILD FAILED in 5s
23 actionable tasks: 6 executed, 17 up-to-date

info 💡 Tip: Make sure that you have set up your development environment correctly, by running react-native doctor. To read more about doctor command visit: https://github.com/react-native-community/cli/blob/main/packages/cli-doctor/README.md#doctor

error Failed to build the app.
Error: Command failed with exit code 1: ./gradlew app:installDebug -x lint -PreactNativeDevServerPort=8089
    at makeError (/Users/gabriele/Desktop/tests/qwer/node_modules/execa/lib/error.js:60:11)
    at Function.module.exports.sync (/Users/gabriele/Desktop/tests/qwer/node_modules/execa/index.js:194:17)
    at build (/Users/gabriele/Desktop/tests/qwer/node_modules/@react-native-community/cli-platform-android/build/commands/buildAndroid/index.js:95:22)
    at runOnSpecificDevice (/Users/gabriele/Desktop/tests/qwer/node_modules/@react-native-community/cli-platform-android/build/commands/runAndroid/index.js:205:33)
    at buildAndRun (/Users/gabriele/Desktop/tests/qwer/node_modules/@react-native-community/cli-platform-android/build/commands/runAndroid/index.js:167:12)
    at Object.runAndroid [as func] (/Users/gabriele/Desktop/tests/qwer/node_modules/@react-native-community/cli-platform-android/build/commands/runAndroid/index.js:100:10)
    at Command.handleAction (/Users/gabriele/Desktop/tests/qwer/node_modules/react-native/node_modules/@react-native-community/cli/build/index.js:111:9)
COMMAND:

npx react-native run-android --mode=Debug --no-packager --deviceId=emulator-5554

FAILED with ERROR:

Command failed with exit code 1: npx react-native run-android --mode=Debug --no-packager --deviceId=emulator-5554

Error: Command failed with exit code 1: npx react-native run-android --mode=Debug --no-packager --deviceId=emulator-5554
    at makeError (/Users/gabriele/Desktop/tests/qwer/node_modules/execa/lib/error.js:60:11)
    at handlePromise (/Users/gabriele/Desktop/tests/qwer/node_modules/execa/index.js:118:26)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)



 $ npx rnv run -p androidwear - Done! 🚀
┌──────────────────────────────────────────────────────────────────────────────┐
│  🚀  SUMMARY | 11/6/2023, 3:36:00 PM                                         │
│  $ npx rnv run -p androidwear                                                │
├──────────────────────────────────────────────────────────────────────────────┤
│  ReNative Version: 1.0.0-feat-bonanza.4                                      │
│  Project Name ($package.name): qwer                                          │
│  Project Version ($package.version): 0.1.0                                   │
│  Workspace ($.workspaceID): rnv                                              │
│  Platform (-p): androidwear                                                  │
│  Engine ($.platforms.androidwear.engine): engine-rn                          │
│  Template: @rnv/template-starter@1.0.0-feat-bonanza.4                        │
│  App Config (-c): app                                                        │
│  Build Scheme (-s): debug                                                    │
│  Target (-t): Wear_OS_Square_API_30                                          │
│  Supported Platforms: androidwear                                            │
│  Master Template: @rnv/template-starter                                      │
│  Env Info: darwin | x64 | node v18.14.2                                      │
│  Executed Time: 0h:0m:42s:789ms                                              │
│                                                                              │
│  All good as 🦄                                                              │
│                                                                              │
│  Project location:                                                           │
│  ./platformBuilds/app_androidwear                                            │
└──────────────────────────────────────────────────────────────────────────────┘
➜  ~/Desktop/tests/qwer
```
androidwear export/build ->
```
✖ FAILED: npx react-native build-android --mode=Debug --no-packager --tasks assembleDebug
COMMAND:

npx react-native build-android --mode=Debug --no-packager --tasks assembleDebug

FAILED with ERROR:

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:processDebugMainManifest'.
> com.android.manifmerger.ManifestMerger2$MergeFailureException: Error parsing /Users/gabriele/Desktop/tests/qwer/platformBuilds/app_androidwear/app/src/main/AndroidManifest.xml

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.

* Get more help at https://help.gradle.org

Deprecated Gradle features were used in this build, making it incompatible with Gradle 9.0.

You can use '--warning-mode all' to show the individual deprecation warnings and determine if they come from your own scripts or plugins.

See https://docs.gradle.org/8.0.1/userguide/command_line_interface.html#sec:command_line_warnings

BUILD FAILED in 5s
23 actionable tasks: 3 executed, 20 up-to-date

info 💡 Tip: Make sure that you have set up your development environment correctly, by running react-native doctor. To read more about doctor command visit: https://github.com/react-native-community/cli/blob/main/packages/cli-doctor/README.md#doctor

error Failed to build the app.
Error: Command failed with exit code 1: ./gradlew app:assembleDebug
    at makeError (/Users/gabriele/Desktop/tests/qwer/node_modules/execa/lib/error.js:60:11)
    at Function.module.exports.sync (/Users/gabriele/Desktop/tests/qwer/node_modules/execa/index.js:194:17)
    at build (/Users/gabriele/Desktop/tests/qwer/node_modules/@react-native-community/cli-platform-android/build/commands/buildAndroid/index.js:95:22)
    at Object.buildAndroid [as func] (/Users/gabriele/Desktop/tests/qwer/node_modules/@react-native-community/cli-platform-android/build/commands/buildAndroid/index.js:87:10)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at Command.handleAction (/Users/gabriele/Desktop/tests/qwer/node_modules/react-native/node_modules/@react-native-community/cli/build/index.js:111:9)

Command failed with exit code 1: npx react-native build-android --mode=Debug --no-packager --tasks assembleDebug
warn Both "tasks" and "mode" parameters were passed to "build" command. Using "tasks" for building the app.

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:processDebugMainManifest'.
> com.android.manifmerger.ManifestMerger2$MergeFailureException: Error parsing /Users/gabriele/Desktop/tests/qwer/platformBuilds/app_androidwear/app/src/main/AndroidManifest.xml

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 5s
error Failed to build the app.
info Building the app...
> Task :gradle-plugin:compileKotlin UP-TO-DATE
> Task :gradle-plugin:compileJava NO-SOURCE
> Task :gradle-plugin:pluginDescriptors UP-TO-DATE
> Task :gradle-plugin:processResources UP-TO-DATE
> Task :gradle-plugin:classes UP-TO-DATE
> Task :gradle-plugin:jar UP-TO-DATE
> Task :gradle-plugin:inspectClassesForKotlinIC UP-TO-DATE
> Task :app:buildCodegenCLI SKIPPED
> Task :app:generateCodegenSchemaFromJavaScript SKIPPED
> Task :app:generateCodegenArtifactsFromSchema SKIPPED
> Task :app:generateNewArchitectureFiles
> Task :app:generatePackageList
> Task :app:preBuild
> Task :app:preDebugBuild
> Task :app:mergeDebugNativeDebugMetadata NO-SOURCE
> Task :react-native-gesture-handler:buildCodegenCLI SKIPPED
> Task :react-native-gesture-handler:generateCodegenSchemaFromJavaScript UP-TO-DATE
> Task :react-native-gesture-handler:generateCodegenArtifactsFromSchema UP-TO-DATE
> Task :react-native-gesture-handler:preBuild UP-TO-DATE
> Task :react-native-gesture-handler:preDebugBuild UP-TO-DATE
> Task :react-native-gesture-handler:compileDebugAidl NO-SOURCE
> Task :app:compileDebugAidl NO-SOURCE
> Task :react-native-gesture-handler:packageDebugRenderscript NO-SOURCE
> Task :app:compileDebugRenderscript NO-SOURCE
> Task :app:generateDebugBuildConfig UP-TO-DATE
> Task :app:javaPreCompileDebug UP-TO-DATE
> Task :react-native-gesture-handler:writeDebugAarMetadata UP-TO-DATE
> Task :app:checkDebugAarMetadata UP-TO-DATE
> Task :app:generateDebugResValues UP-TO-DATE
> Task :react-native-gesture-handler:compileDebugRenderscript NO-SOURCE
> Task :react-native-gesture-handler:generateDebugResValues UP-TO-DATE
> Task :react-native-gesture-handler:generateDebugResources UP-TO-DATE
> Task :react-native-gesture-handler:packageDebugResources UP-TO-DATE
> Task :app:mapDebugSourceSetPaths UP-TO-DATE
> Task :app:generateDebugResources UP-TO-DATE
> Task :app:mergeDebugResources UP-TO-DATE
> Task :app:createDebugCompatibleScreenManifests UP-TO-DATE
> Task :app:extractDeepLinksDebug UP-TO-DATE
> Task :react-native-gesture-handler:extractDeepLinksDebug UP-TO-DATE
> Task :react-native-gesture-handler:processDebugManifest UP-TO-DATE
> Task :app:processDebugMainManifest FAILED

Deprecated Gradle features were used in this build, making it incompatible with Gradle 9.0.

You can use '--warning-mode all' to show the individual deprecation warnings and determine if they come from your own scripts or plugins.

See https://docs.gradle.org/8.0.1/userguide/command_line_interface.html#sec:command_line_warnings
23 actionable tasks: 3 executed, 20 up-to-date

info 💡 Tip: Make sure that you have set up your development environment correctly, by running react-native doctor. To read more about doctor command visit: https://github.com/react-native-community/cli/blob/main/packages/cli-doctor/README.md#doctor

Error: Command failed with exit code 1: ./gradlew app:assembleDebug
    at makeError (/Users/gabriele/Desktop/tests/qwer/node_modules/execa/lib/error.js:60:11)
    at Function.module.exports.sync (/Users/gabriele/Desktop/tests/qwer/node_modules/execa/index.js:194:17)
    at build (/Users/gabriele/Desktop/tests/qwer/node_modules/@react-native-community/cli-platform-android/build/commands/buildAndroid/index.js:95:22)
    at Object.buildAndroid [as func] (/Users/gabriele/Desktop/tests/qwer/node_modules/@react-native-community/cli-platform-android/build/commands/buildAndroid/index.js:87:10)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at Command.handleAction (/Users/gabriele/Desktop/tests/qwer/node_modules/react-native/node_modules/@react-native-community/cli/build/index.js:111:9)

warn Both "tasks" and "mode" parameters were passed to "build" command. Using "tasks" for building the app.

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:processDebugMainManifest'.
> com.android.manifmerger.ManifestMerger2$MergeFailureException: Error parsing /Users/gabriele/Desktop/tests/qwer/platformBuilds/app_androidwear/app/src/main/AndroidManifest.xml

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 5s
error Failed to build the app.

Error: Command failed with exit code 1: npx react-native build-android --mode=Debug --no-packager --tasks assembleDebug
warn Both "tasks" and "mode" parameters were passed to "build" command. Using "tasks" for building the app.

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:processDebugMainManifest'.
> com.android.manifmerger.ManifestMerger2$MergeFailureException: Error parsing /Users/gabriele/Desktop/tests/qwer/platformBuilds/app_androidwear/app/src/main/AndroidManifest.xml

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 5s
error Failed to build the app.
info Building the app...
> Task :gradle-plugin:compileKotlin UP-TO-DATE
> Task :gradle-plugin:compileJava NO-SOURCE
> Task :gradle-plugin:pluginDescriptors UP-TO-DATE
> Task :gradle-plugin:processResources UP-TO-DATE
> Task :gradle-plugin:classes UP-TO-DATE
> Task :gradle-plugin:jar UP-TO-DATE
> Task :gradle-plugin:inspectClassesForKotlinIC UP-TO-DATE
> Task :app:buildCodegenCLI SKIPPED
> Task :app:generateCodegenSchemaFromJavaScript SKIPPED
> Task :app:generateCodegenArtifactsFromSchema SKIPPED
> Task :app:generateNewArchitectureFiles
> Task :app:generatePackageList
> Task :app:preBuild
> Task :app:preDebugBuild
> Task :app:mergeDebugNativeDebugMetadata NO-SOURCE
> Task :react-native-gesture-handler:buildCodegenCLI SKIPPED
> Task :react-native-gesture-handler:generateCodegenSchemaFromJavaScript UP-TO-DATE
> Task :react-native-gesture-handler:generateCodegenArtifactsFromSchema UP-TO-DATE
> Task :react-native-gesture-handler:preBuild UP-TO-DATE
> Task :react-native-gesture-handler:preDebugBuild UP-TO-DATE
> Task :react-native-gesture-handler:compileDebugAidl NO-SOURCE
> Task :app:compileDebugAidl NO-SOURCE
> Task :react-native-gesture-handler:packageDebugRenderscript NO-SOURCE
> Task :app:compileDebugRenderscript NO-SOURCE
> Task :app:generateDebugBuildConfig UP-TO-DATE
> Task :app:javaPreCompileDebug UP-TO-DATE
> Task :react-native-gesture-handler:writeDebugAarMetadata UP-TO-DATE
> Task :app:checkDebugAarMetadata UP-TO-DATE
> Task :app:generateDebugResValues UP-TO-DATE
> Task :react-native-gesture-handler:compileDebugRenderscript NO-SOURCE
> Task :react-native-gesture-handler:generateDebugResValues UP-TO-DATE
> Task :react-native-gesture-handler:generateDebugResources UP-TO-DATE
> Task :react-native-gesture-handler:packageDebugResources UP-TO-DATE
> Task :app:mapDebugSourceSetPaths UP-TO-DATE
> Task :app:generateDebugResources UP-TO-DATE
> Task :app:mergeDebugResources UP-TO-DATE
> Task :app:createDebugCompatibleScreenManifests UP-TO-DATE
> Task :app:extractDeepLinksDebug UP-TO-DATE
> Task :react-native-gesture-handler:extractDeepLinksDebug UP-TO-DATE
> Task :react-native-gesture-handler:processDebugManifest UP-TO-DATE
> Task :app:processDebugMainManifest FAILED

Deprecated Gradle features were used in this build, making it incompatible with Gradle 9.0.

You can use '--warning-mode all' to show the individual deprecation warnings and determine if they come from your own scripts or plugins.

See https://docs.gradle.org/8.0.1/userguide/command_line_interface.html#sec:command_line_warnings
23 actionable tasks: 3 executed, 20 up-to-date

info 💡 Tip: Make sure that you have set up your development environment correctly, by running react-native doctor. To read more about doctor command visit: https://github.com/react-native-community/cli/blob/main/packages/cli-doctor/README.md#doctor

Error: Command failed with exit code 1: ./gradlew app:assembleDebug
    at makeError (/Users/gabriele/Desktop/tests/qwer/node_modules/execa/lib/error.js:60:11)
    at Function.module.exports.sync (/Users/gabriele/Desktop/tests/qwer/node_modules/execa/index.js:194:17)
    at build (/Users/gabriele/Desktop/tests/qwer/node_modules/@react-native-community/cli-platform-android/build/commands/buildAndroid/index.js:95:22)
    at Object.buildAndroid [as func] (/Users/gabriele/Desktop/tests/qwer/node_modules/@react-native-community/cli-platform-android/build/commands/buildAndroid/index.js:87:10)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at Command.handleAction (/Users/gabriele/Desktop/tests/qwer/node_modules/react-native/node_modules/@react-native-community/cli/build/index.js:111:9)
    at makeError (/Users/gabriele/Desktop/tests/qwer/node_modules/execa/lib/error.js:60:11)
    at handlePromise (/Users/gabriele/Desktop/tests/qwer/node_modules/execa/index.js:118:26)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)



 $ npx rnv export -p androidwear - Done! 🚀
┌──────────────────────────────────────────────────────────────────────────────┐
│  🚀  SUMMARY | 11/6/2023, 3:33:25 PM                                         │
│  $ npx rnv export -p androidwear                                             │
├──────────────────────────────────────────────────────────────────────────────┤
│  ReNative Version: 1.0.0-feat-bonanza.4                                      │
│  Project Name ($package.name): qwer                                          │
│  Project Version ($package.version): 0.1.0                                   │
│  Workspace ($.workspaceID): rnv                                              │
│  Platform (-p): androidwear                                                  │
│  Engine ($.platforms.androidwear.engine): engine-rn                          │
│  Template: @rnv/template-starter@1.0.0-feat-bonanza.4                        │
│  App Config (-c): app                                                        │
│  Build Scheme (-s): debug                                                    │
│  Target (-t): Wear_OS_Square_API_30                                          │
│  Supported Platforms: androidwear                                            │
│  Master Template: @rnv/template-starter                                      │
│  Env Info: darwin | x64 | node v18.14.2                                      │
│  Executed Time: 0h:0m:7s:362ms                                               │
│                                                                              │
│  All good as 🦄                                                              │
│                                                                              │
│  Project location:                                                           │
│  ./platformBuilds/app_androidwear                                            │
└──────────────────────────────────────────────────────────────────────────────┘
➜  ~/Desktop/tests/qwer
```

**Comment by pauliusguzas** [comment]
run/build on android, atv, androidwear, firetv fixed, export is tracked here https://github.com/flexn-io/renative/issues/1229
