### ISSUE TITLE
[Regression] [iOS, tvOS] rnv/template-starter@1.0.0-canary.1 cannot run (RNV new project)

### ISSUE THREAD

**Issue by GabrieleKaceviciute** [flexn-io/renative#1132]
**Describe the bug**
Can't run/build/export template on ios simulators and devices

**To Reproduce**
1. Install rnv@1.0.0-canary.1 with npm globally
2. create new project with `rnv new` and choose rnv/template-starter with same version
3. do `npx rnv run -p ios` / `ios -d ` / `npx rnv build -p ios`

**Screenshots or copy&paste**
```
$ rnv run -p ios - Done! 🚀
┌──────────────────────────────────────────────────────────────────────────────┐
│  🚀  SUMMARY | 10/5/2023, 2:50:54 PM                                         │
│  $ rnv run -p ios                                                            │
├──────────────────────────────────────────────────────────────────────────────┤
│  ReNative Version: 1.0.0-canary.1                                            │
│  Project Name ($package.name): bimbam                                        │
│  Project Version ($package.version): 0.1.0                                   │
│  Workspace ($.workspaceID): rnv                                              │
│  Platform (-p): ios                                                          │
│  Engine ($.platforms.ios.engine): engine-rn                                  │
│  Template: @rnv/template-starter@1.0.0-canary.1                              │
│  App Config (-c): app                                                        │
│  Build Scheme (-s): debug                                                    │
│  Target (-t): iPhone 14                                                      │
│  Supported Platforms: ios                                                    │
│  Env Info: darwin | x64 | node v18.18.0                                      │
│  Executed Time: 0h:0m:4s:138ms                                               │
│                                                                              │
│ [ warn ] [configure] pod install is not enough! Let's try pod update! Error:
 COMMAND:

bundle install

FAILED with ERROR:

Command failed with exit code 10: bundle install
Could not locate Gemfile

Could not locate Gemfile

Error: Command failed with exit code 10: bundle install
Could not locate Gemfile
    at makeError (./node_modules/execa/lib/error.js:60:11)
    at handlePromise (./node_modules/execa/index.js:118:26)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)


│                                                                              │
│  Project location:                                                           │
│  ./platformBuilds/app_ios/RNVApp.xcworkspace                                 │
└──────────────────────────────────────────────────────────────────────────────┘
```

**Desktop (please complete the following information):**

-   OS: macOS Ventura 13.5.2
-   Node Version 18.18.0
-   RNV Version 1.0.0-canary.1

**Comment by GabrieleKaceviciute** [comment]
Closing as duplicate of https://github.com/flexn-io/renative/issues/1213
