### ISSUE TITLE
[macos] export fails

### ISSUE THREAD

**Issue by pauliusguzas** [flexn-io/renative#1134]
**Describe the bug**
Can't export template on macos (sanity_1.0.0-1 tag)

**To Reproduce**
1. go to template-starter package
2. run `rnv export -p macos`

```
FAILED with ERROR:

Command failed with exit code 1: /Users/pauliusguzas/Desktop/renative/renative/node_modules/.bin/electron-builder --config /Users/pauliusguzas/Desktop/renative/renative/packages/template-starter/platformBuilds/template_macos/electronConfig.json --macos
  • electron-builder  version=24.6.4 os=22.6.0
  • loaded configuration  file=/Users/pauliusguzas/Desktop/renative/renative/packages/template-starter/platformBuilds/template_macos/electronConfig.json
  ⨯ Cannot compute electron version from installed node modules - none of the possible electron modules are installed.
See https://github.com/electron-userland/electron-builder/issues/3984#issuecomment-504968246

Error: Command failed with exit code 1: /Users/pauliusguzas/Desktop/renative/renative/node_modules/.bin/electron-builder --config /Users/pauliusguzas/Desktop/renative/renative/packages/template-starter/platformBuilds/template_macos/electronConfig.json --macos
  • electron-builder  version=24.6.4 os=22.6.0
  • loaded configuration  file=/Users/pauliusguzas/Desktop/renative/renative/packages/template-starter/platformBuilds/template_macos/electronConfig.json
  ⨯ Cannot compute electron version from installed node modules - none of the possible electron modules are installed.
See https://github.com/electron-userland/electron-builder/issues/3984#issuecomment-504968246
    at makeError (/Users/pauliusguzas/Desktop/renative/renative/node_modules/execa/lib/error.js:60:11)
    at handlePromise (/Users/pauliusguzas/Desktop/renative/renative/node_modules/execa/index.js:118:26)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)



 $ rnv export -p macos - Done! 🚀
┌──────────────────────────────────────────────────────────────────────────────┐
│  🚀  SUMMARY | 10/6/2023, 2:05:40 PM                                         │
│  $ rnv export -p macos                                                       │
├──────────────────────────────────────────────────────────────────────────────┤
│  ReNative Version: 1.0.0-canary.1                                            │
│  Project Name ($package.name): @rnv/template-starter                         │
│  Project Version ($package.version): 1.0.0-canary.1                          │
│  Workspace ($.workspaceID): rnv                                              │
│  Platform (-p): macos                                                        │
│  Engine ($.platforms.macos.engine): engine-rn-electron                       │
│  App Config (-c): template                                                   │
│  Build Scheme (-s): debug                                                    │
│  Supported Platforms: macos                                                  │
│  Env Info: darwin | x64 | node v18.16.0                                      │
│  Executed Time: 0h:0m:11s:835ms                                              │
│                                                                              │
│ [ success ] [build] Compiled successfully.

│                                                                              │
│  Project location:                                                           │
│  ./platformBuilds/template_macos                                             │
└──────────────────────────────────────────────────────────────────────────────┘
pauliusguzas@MacBook-Pro-de-Flexn template-starter %
```

**Desktop (please complete the following information):**

-   OS: Ventura 13.5.2
-   Node Version 18.16.0
-   RNV Version 1.0.0-canary.1
-   rnv/template-starter Version 1.0.0-canary.1

**Comment by GabrieleKaceviciute** [comment]
not reproduced on 1.0.0-canary.8
