### ISSUE TITLE
[Androidwear, firetv] Can't run app on simulator

### ISSUE THREAD

**Issue by pauliusguzas** [flexn-io/renative#1142]
**Describe the bug**
Can't run app on simulator (sanity_1.0.0-1 tag). Haven't checked device as don't have any

**To Reproduce**
1. go to template-starter package
2. run `rnv run -p androidwear`

```
[ success ] [run] Found active emulator! emulator-5558. Will use it
[ task ] [run] _runGradleApp[1]
✔ Executing: npx react-native run-android --mode=Debug --no-packager --deviceId=emulator-5558

⠹ INFO    | Setting display: 0 configuration to: 320x640, dpi: 160x160error Command failed with exit code 1: ./gradlew tasks

FAILURE: Build failed with an exception.

* Where:
Build file '/Users/pauliusguzas/Desktop/renative/renative/packages/template-starter/platformBuilds/template_androidwear/app/build.gradle' line: 22

* What went wrong:
A problem occurred evaluating project ':app'.
> Could not read script '/Users/pauliusguzas/Desktop/renative/renative/node_modules/react-native/react.gradle' as it does not exist.

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 7s
Starting a Gradle Daemon, 1 incompatible Daemon could not be reused, use --status for details
Configuration on demand is an incubating feature.

> Configure project :app
WARNING:: The option 'android.useDeprecatedNdk' is deprecated.
The current default is 'false'.
It has been removed from the current version of the Android Gradle plugin.
NdkCompile is no longer supported
Warning: The 'kotlin-android-extensions' Gradle plugin is deprecated. Please use this migration guide (https://goo.gle/kotlin-android-extensions-deprecation) to start working with View Binding (https://developer.android.com/topic/libraries/view-binding) and the 'kotlin-parcelize' plugin.
Error: Command failed with exit code 1: ./gradlew tasks

FAILURE: Build failed with an exception.

* Where:
Build file '/Users/pauliusguzas/Desktop/renative/renative/packages/template-starter/platformBuilds/template_androidwear/app/build.gradle' line: 22

* What went wrong:
A problem occurred evaluating project ':app'.
> Could not read script '/Users/pauliusguzas/Desktop/renative/renative/node_modules/react-native/react.gradle' as it does not exist.

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 7s
Starting a Gradle Daemon, 1 incompatible Daemon could not be reused, use --status for details
Configuration on demand is an incubating feature.

> Configure project :app
WARNING:: The option 'android.useDeprecatedNdk' is deprecated.
The current default is 'false'.
It has been removed from the current version of the Android Gradle plugin.
NdkCompile is no longer supported
Warning: The 'kotlin-android-extensions' Gradle plugin is deprecated. Please use this migration guide (https://goo.gle/kotlin-android-extensions-deprecation) to start working with View Binding (https://developer.android.com/topic/libraries/view-binding) and the 'kotlin-parcelize' plugin.
    at makeError (/Users/pauliusguzas/Desktop/renative/renative/node_modules/execa/lib/error.js:60:11)
    at module.exports.sync (/Users/pauliusguzas/Desktop/renative/renative/node_modules/execa/index.js:194:17)
    at getGradleTasks (/Users/pauliusguzas/Desktop/renative/renative/node_modules/@react-native-community/cli-platform-android/build/commands/runAndroid/listAndroidTasks.js:53:32)
    at getTaskNames (/Users/pauliusguzas/Desktop/renative/renative/node_modules/@react-native-community/cli-platform-android/build/commands/runAndroid/getTaskNames.js:21:73)
    at runOnSpecificDevice (/Users/pauliusguzas/Desktop/renative/renative/node_modules/@react-native-community/cli-platform-android/build/commands/runAndroid/index.js:184:55)
    at buildAndRun (/Users/pauliusguzas/Desktop/renative/renative/node_modules/@react-native-community/cli-platform-android/build/commands/runAndroid/index.js:167:12)
    at Object.runAndroid [as func] (/Users/pauliusguzas/Desktop/renative/renative/node_modules/@react-native-community/cli-platform-android/build/commands/runAndroid/index.js:100:10)
    at async Command.handleAction (/Users/pauliusguzas/Desktop/renative/renative/node_modules/@react-native-community/cli/build/index.js:111:9)
COMMAND:

npx react-native run-android --mode=Debug --no-packager --deviceId=emulator-5558

FAILED with ERROR:

Command failed with exit code 1: npx react-native run-android --mode=Debug --no-packager --deviceId=emulator-5558

Error: Command failed with exit code 1: npx react-native run-android --mode=Debug --no-packager --deviceId=emulator-5558
    at makeError (/Users/pauliusguzas/Desktop/renative/renative/node_modules/execa/lib/error.js:60:11)
    at handlePromise (/Users/pauliusguzas/Desktop/renative/renative/node_modules/execa/index.js:118:26)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)



 $ rnv run -p androidwatch - Done! 🚀
┌──────────────────────────────────────────────────────────────────────────────┐
│  🚀  SUMMARY | 10/9/2023, 10:46:07 AM                                        │
│  $ rnv run -p androidwatch                                                   │
├──────────────────────────────────────────────────────────────────────────────┤
│  ReNative Version: 1.0.0-canary.1                                            │
│  Project Name ($package.name): @rnv/template-starter                         │
│  Project Version ($package.version): 1.0.0-canary.1                          │
│  Workspace ($.workspaceID): rnv                                              │
│  Platform (-p): androidwear                                                  │
│  Engine ($.platforms.androidwear.engine): engine-rn                          │
│  App Config (-c): template                                                   │
│  Build Scheme (-s): debug                                                    │
│  Target (-t): Android_Wear_Round_API_28                                      │
│  Supported Platforms: ios, android, androidtv, firetv,                       │
│  androidwear, web, webtv, tizen, tvos, webos, macos, windows,                │
│  tizenwatch, tizenmobile, kaios, firefoxos, firefoxtv, chromecast            │
│  Env Info: darwin | x64 | node v18.16.0                                      │
│  Executed Time: 0h:1m:15s:599ms                                              │
│                                                                              │
│ [ warn ] Could not find suitable engine for platform androidwatch
Maybe you forgot to define platforms.androidwatch.engine in your renative.json?
│ [ error ] [configure] Cannot write file. source path doesn't exists: /Users/pauliusguzas/Desktop/renative/renative/packages/engine-rn/templates/platforms/androidwear/app/src/main/java/rnv_template/MainActivity.java.tpl
│ [ error ] [configure] Cannot write file. source path doesn't exists: /Users/pauliusguzas/Desktop/renative/renative/packages/engine-rn/templates/platforms/androidwear/app/src/main/java/rnv_template/MainApplication.java.tpl
│ [ error ] [configure] Cannot write file. source path doesn't exists: /Users/pauliusguzas/Desktop/renative/renative/packages/engine-rn/templates/platforms/androidwear/app/src/debug/java/rnv_template/ReactNativeFlipper.java.tpl
│ [ error ] [configure] Cannot write file. source path doesn't exists: /Users/pauliusguzas/Desktop/renative/renative/packages/engine-rn/templates/platforms/androidwear/app/src/release/java/rnv_template/ReactNativeFlipper.java.tpl
│ [ success ] [run] Found active emulator! emulator-5558. Will use it
│                                                                              │
│  Project location:                                                           │
│  ./platformBuilds/template_androidwear                                       │
└──────────────────────────────────────────────────────────────────────────────┘
pauliusguzas@MBP-de-Flexn template-starter %
```

**Expected behavior**
Template app should start in Androidwear simulator

**Desktop (please complete the following information):**

-   OS: Ventura 13.5.2
-   Node Version 18.16.0
-   RNV Version 1.0.0-canary.1
-   rnv/template-starter Version 1.0.0-canary.1

**Comment by pauliusguzas** [comment]
Closing as not relevant
