### ISSUE TITLE
hooks fail to run

### ISSUE THREAD

**Issue by pauliusguzas** [flexn-io/renative#1153]
**Describe the bug**
hooks fail to run (sanity_1.0.0-1 tag checkout)

**To Reproduce**
1. go to template-starter package
2. run `rnv hooks run`

**Expected behavior**
rnv asks to choose hook and it runs successfully

**Screenshots or copy&paste**
x64:
```
pauliusguzas@MacBook-Pro-de-Flexn template-starter % rnv hooks run

┌──────────────────────────────────────────────────────────────────────────────┐
│                                                                              │
│        ██████╗ ███████╗███╗   ██╗ █████╗ ████████╗██╗██╗   ██╗███████╗       │
│        ██╔══██╗██╔════╝████╗  ██║██╔══██╗╚══██╔══╝██║██║   ██║██╔════╝       │
│        ██████╔╝█████╗  ██╔██╗ ██║███████║   ██║   ██║██║   ██║█████╗         │
│        ██╔══██╗██╔══╝  ██║╚██╗██║██╔══██║   ██║   ██║╚██╗ ██╔╝██╔══╝         │
│        ██║  ██║███████╗██║ ╚████║██║  ██║   ██║   ██║ ╚████╔╝ ███████╗       │
│        ╚═╝  ╚═╝╚══════╝╚═╝  ╚═══╝╚═╝  ╚═╝   ╚═╝   ╚═╝  ╚═══╝  ╚══════╝       │
│                                                                              │
│        Version: 1.0.0-canary.1                                               │
│        https://renative.org                                                  │
│        🚀 Firing up!...                                                      │
│        $ rnv hooks run                                                       │
│        Start Time: 10/10/2023, 12:00:32 PM                                   │
│                                                                              │
└──────────────────────────────────────────────────────────────────────────────┘

[ task ] registerEngine:engine-core[1]
[ task ] configureRuntimeDefaults[1] appId:null
[ task ] checkAndMigrateProject[1]
[ task ] loadPluginTemplates[1]
[ task ] _parsePluginTemplateDependencies[1] scope:root
[ task ] parseRenativeConfigs[1]
[ task ] getWorkspaceDirPath[1]
[ task ] _generatePlatformTemplatePaths[1]
[ task ] checkAndBootstrapIfRequired[1]
[ task ] loadIntegrations[1]
[ task ] loadEngines[1]
[ task ] loadEnginePluginDeps[1]
[ task ] loadEnginePackageDeps[1]
[ task ] findSuitableTask[1]
[ info ] Current Engine: engine-core path: undefined
[ task ] registerMissingPlatformEngines[1]
[ task ] initializeTask[1] hooks run
[ task ] => [hooks run]
[ task ] [hooks run] taskRnvHooksRun[1]
[ task ] => [hooks run] => [project configure]
[ hook ] [project configure] executePipe ('project:configure:before')
[ hook ] [project configure] buildHooks Build hooks not complied. BUILDING...
 > ../../../../jsconfig.json:1:0: error: Unexpected end of file
    1 │
      ╵ ^

BUILD_HOOK Failed with error: Error: Build failed with 1 error:
../../../../jsconfig.json:1:0: error: Unexpected end of file

 $ rnv hooks run - Done! 🚀
┌──────────────────────────────────────────────────────────────────────────────┐
│  🚀  SUMMARY | 10/10/2023, 12:00:33 PM                                       │
│  $ rnv hooks run                                                             │
├──────────────────────────────────────────────────────────────────────────────┤
│  ReNative Version: 1.0.0-canary.1                                            │
│  Project Name ($package.name): @rnv/template-starter                         │
│  Project Version ($package.version): 1.0.0-canary.1                          │
│  Workspace ($.workspaceID): rnv                                              │
│  Engine: engine-core                                                         │
│  App Config (-c): template                                                   │
│  Build Scheme (-s): debug                                                    │
│  Env Info: darwin | x64 | node v18.16.0                                      │
│  Executed Time: 0h:0m:0s:96ms                                                │
│                                                                              │
│  All good as 🦄                                                              │
│                                                                              │
└──────────────────────────────────────────────────────────────────────────────┘
pauliusguzas@MacBook-Pro-de-Flexn template-starter %
```
ARM:
```
? Pick an available hook: hello
TypeError: Cannot read properties of undefined (reading 'logHook')
    at Object.hello (/Users/buildminion3/Desktop/renative/packages/template-starter/buildHooks/dist/index.js:33:23)
    at /Users/buildminion3/Desktop/renative/packages/engine-core/src/tasks/task.rnv.hooks.run.ts:49:33
    at step (/Users/buildminion3/Desktop/renative/node_modules/tslib/tslib.js:195:27)
    at Object.next (/Users/buildminion3/Desktop/renative/node_modules/tslib/tslib.js:176:57)
    at fulfilled (/Users/buildminion3/Desktop/renative/node_modules/tslib/tslib.js:166:62)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)

 $ rnv hooks run - Done! 🚀
┌──────────────────────────────────────────────────────────────────────────────┐
│  🚀  SUMMARY | 10/11/2023, 11:51:02 AM                                       │
│  $ rnv hooks run                                                             │
├──────────────────────────────────────────────────────────────────────────────┤
│  ReNative Version: 1.0.0-canary.1                                            │
│  Project Name ($package.name): @rnv/template-starter                         │
│  Project Version ($package.version): 1.0.0-canary.1                          │
│  Workspace ($.workspaceID): rnv                                              │
│  Engine: engine-core                                                         │
│  App Config (-c): template                                                   │
│  Build Scheme (-s): debug                                                    │
│  Env Info: darwin | x64 | node v18.14.2                                      │
│  Executed Time: 0h:0m:0s:904ms                                               │
│                                                                              │
│  All good as 🦄                                                              │
│                                                                              │
└──────────────────────────────────────────────────────────────────────────────┘
buildminion3@Builds-Mac-mini template-starter %
```

**Desktop (please complete the following information):**

-   OS: Ventura 13.5.2
-   Node Version 18.16.0
-   RNV Version 1.0.0-canary.1
-   rnv/template-starter Version 1.0.0-canary.1

**Comment by pauliusguzas** [comment]
Fails on macOS on sanity_1.0.0-2 tag

**Comment by pauliusguzas** [comment]
failed due to local machine setup issues

**Comment by GabrieleKaceviciute** [comment]
not reproduced on 1.0.0-canary.8
