### ISSUE TITLE
Unable to run @rnv/template-starter@0.37.3

### ISSUE THREAD

**Issue by budgustin** [flexn-io/renative#1165]
Noob here.  Following the getting started documentation.  Taking prompt defaults whenever possible. When running `rnv run`, `npm i` fails with dependency conflicts.  React version dependency seems to be overwritten with each `rnv run`.  Below console log.  What do I need to do to resolve this and run the template?

Desktop (please complete the following information):

OS: Sonoma 14.0
Node Version 20.8.0
RNV Version 0.37.3
rnv/template-starter Version 0.37.3

```
[~/src/learn]$ rnv new

┌──────────────────────────────────────────────────────────────────────────────┐
│                                                                              │
│        ██████╗ ███████╗███╗   ██╗ █████╗ ████████╗██╗██╗   ██╗███████╗       │
│        ██╔══██╗██╔════╝████╗  ██║██╔══██╗╚══██╔══╝██║██║   ██║██╔════╝       │
│        ██████╔╝█████╗  ██╔██╗ ██║███████║   ██║   ██║██║   ██║█████╗         │
│        ██╔══██╗██╔══╝  ██║╚██╗██║██╔══██║   ██║   ██║╚██╗ ██╔╝██╔══╝         │
│        ██║  ██║███████╗██║ ╚████║██║  ██║   ██║   ██║ ╚████╔╝ ███████╗       │
│        ╚═╝  ╚═╝╚══════╝╚═╝  ╚═══╝╚═╝  ╚═╝   ╚═╝   ╚═╝  ╚═══╝  ╚══════╝       │
│                                                                              │
│        Version: 0.37.3                                                       │
│        https://renative.org                                                  │
│        🚀 Firing up!...                                                      │
│        $ rnv new                                                             │
│        Start Time: 10/12/2023, 8:48:32 AM                                    │
│                                                                              │
└──────────────────────────────────────────────────────────────────────────────┘

[ task ] registerEngine:engine-core[1]
[ task ] configureRuntimeDefaults[1] appId:null
[ task ] checkAndMigrateProject[1]
[ task ] loadPluginTemplates[1]
[ task ] _parsePluginTemplateDependencies[1] scope:root
[ task ] parseRenativeConfigs[1]
[ task ] getWorkspaceDirPath[1]
[ task ] checkAndBootstrapIfRequired[1]
[ task ] loadIntegrations[1]
[ task ] loadEngines[1]
[ task ] findSuitableTask[1]
[ info ] Current Engine: engine-core path: undefined
[ task ] registerMissingPlatformEngines[1]
[ task ] initializeTask[1] new
[ task ] => [new]
[ task ] [new] taskRnvNew[1]
? What's your project Name? (no spaces, folder based on ID will be created in this
 directory) rnv-starter
? What's your project Title? Renative Starter
? What's your App ID? com.mycompany.rnv-starter
? What's your Version? 0.1.0
? What workspace to use? rnv
[ task ] [new] loadPluginTemplates[2]
[ task ] [new] _parsePluginTemplateDependencies[2] scope:root
[ task ] [new] parseRenativeConfigs[2]
[ task ] [new] getWorkspaceDirPath[2]
? What template to use? @rnv/template-starter - Multiplatform 'hello world' templa
te
✔ Executing: npm view @rnv/template-starter versions
✔ Executing: npm dist-tag ls @rnv/template-starter
? What @rnv/template-starter version to use? 0.37.3 (HEAD: latest)
✔ Executing: npm add @rnv/template-starter@0.37.3
? What platforms would you like to use? ios, android, androidtv, firetv, androidwe
ar, web, webtv, tizen, tvos, webos, macos, windows, tizenwatch, tizenmobile, kaios
, firefoxos, firefoxtv, chromecast
asnwer {}
? Do you want to set-up git in your new project? Yes
? 
┌──────────────────────────────────────────────────────────────────────────────┐
│  🚀  ReNative Project Generator                                              │
│                                                                              │
├──────────────────────────────────────────────────────────────────────────────┤
│                                                                              │
│  Project Name (folder): rnv-starter                                          │
│  Workspace: rnv                                                              │
│  Project Title: Renative Starter                                             │
│  Project Version: 0.1.0                                                      │
│  App ID: com.mycompany.rnv-starter                                           │
│  Project Template: @rnv/template-starter@0.37.3                              │
│  Git Enabled: true                                                           │
│                                                                              │
│  Project Platforms:                                                          │
│  ios, android, androidtv, firetv, androidwear, web, webtv, tizen,            │
│  tvos, webos, macos, windows, tizenwatch, tizenmobile, kaios,                │
? 
┌──────────────────────────────────────────────────────────────────────────────┐
│  🚀  ReNative Project Generator                                              │
│                                                                              │
├──────────────────────────────────────────────────────────────────────────────┤
│                                                                              │
│  Project Name (folder): rnv-starter                                          │
│  Workspace: rnv                                                              │
│  Project Title: Renative Starter                                             │
│  Project Version: 0.1.0                                                      │
│  App ID: com.mycompany.rnv-starter                                           │
│  Project Template: @rnv/template-starter@0.37.3                              │
│  Git Enabled: true                                                           │
│                                                                              │
│  Project Platforms:                                                          │
│  ios, android, androidtv, firetv, androidwear, web, webtv, tizen,            │
│  tvos, webos, macos, windows, tizenwatch, tizenmobile, kaios,                │
│  firefoxos, firefoxtv, chromecast                                            │
│                                                                              │
│  Project Structure:                                                          │
│                                                                              │
│  rnv-starter                                                                 │
│   ├── appConfigs            # Application flavour configuration files/assets │
│   │   └── [APP_ID]          # Example application flavour                    │
│   │       ├── assets        # Platform assets injected to ./platformAssets   │
│   │       ├── builds        # Platform files injected to ./platformBuilds    │
│   │       ├── fonts             # Folder for all custom fonts                │
│   │       ├── plugins           # Multi-platform plugins injections          │
│   │       └── renative.json # Application flavour config                     │
│   ├── platformAssets        # Generated cross-platform assets                │
│   ├── platformBuilds        # Generated platform app projects                │
│   ├── src                   # Source code files                              │
│   ├── index.*.js            # Entry files                                    │
│   └── renative.json         # ReNative project configuration                 │
│                                                                              │
└──────────────────────────────────────────────────────────────────────────────┘

Is all this correct? Yes
[ task ] [new] _generateProject:@rnv/template-starter:0.37.3[1]
[ task ] [new] checkAndCreateGitignore[1]
[ info ] [new] Your .gitignore is missing. CREATING...DONE
[ task ] [new] configureGit:.[1]
[ info ] [new] Your project does not have a git repo. Creating one...DONE
✔ Executing: git init
✔ Executing: git add -A
✔ Executing: git commit -m "Initial"
[ success ] [new] Your project is ready! navigate to project cd rnv-starter and run rnv run to see magic happen!
[ task ] <= new

 $ rnv new - Done! 🚀
┌──────────────────────────────────────────────────────────────────────────────┐
│  🚀  SUMMARY | 10/12/2023, 8:49:18 AM                                        │
│  $ rnv new                                                                   │
├──────────────────────────────────────────────────────────────────────────────┤
│  ReNative Version: 0.37.3                                                    │
│  Engine: engine-core                                                         │
│  Build Scheme (-s): debug                                                    │
│  Env Info: darwin | arm64 | node v20.8.0                                     │
│  Executed Time: 0h:0m:46s:406ms                                              │
│                                                                              │
│ [ success ] [new] Your project is ready! navigate to project cd rnv-starter and run rnv run to see magic happen!
│                                                                              │
└──────────────────────────────────────────────────────────────────────────────┘
[~/src/learn]$ cd rnv-starter
[main][~/src/learn/rnv-starter]$ rnv run

┌──────────────────────────────────────────────────────────────────────────────┐
│                                                                              │
│        ██████╗ ███████╗███╗   ██╗ █████╗ ████████╗██╗██╗   ██╗███████╗       │
│        ██╔══██╗██╔════╝████╗  ██║██╔══██╗╚══██╔══╝██║██║   ██║██╔════╝       │
│        ██████╔╝█████╗  ██╔██╗ ██║███████║   ██║   ██║██║   ██║█████╗         │
│        ██╔══██╗██╔══╝  ██║╚██╗██║██╔══██║   ██║   ██║╚██╗ ██╔╝██╔══╝         │
│        ██║  ██║███████╗██║ ╚████║██║  ██║   ██║   ██║ ╚████╔╝ ███████╗       │
│        ╚═╝  ╚═╝╚══════╝╚═╝  ╚═══╝╚═╝  ╚═╝   ╚═╝   ╚═╝  ╚═══╝  ╚══════╝       │
│                                                                              │
│        Version: 0.37.3                                                       │
│        https://renative.org                                                  │
│        🚀 Firing up!...                                                      │
│        $ rnv run                                                             │
│        Start Time: 10/12/2023, 8:49:31 AM                                    │
│                                                                              │
└──────────────────────────────────────────────────────────────────────────────┘

[ task ] registerEngine:engine-core[1]
[ task ] configureRuntimeDefaults[1] appId:null
[ task ] checkAndMigrateProject[1]
[ task ] loadPluginTemplates[1]
[ task ] _parsePluginTemplateDependencies[1] scope:root
[ task ] parseRenativeConfigs[1]
[ task ] getWorkspaceDirPath[1]
[ task ] _generatePlatformTemplatePaths[1]
[ task ] checkAndBootstrapIfRequired[1]
[ task ] loadIntegrations[1]
[ task ] loadEngines[1]
[ info ] Some engines not installed in your project:
> @rnv/engine-rn@0.37.3
> @rnv/engine-rn-tvos@0.37.3
> @rnv/engine-rn-next@0.37.3
> @rnv/engine-rn-web@0.37.3
> @rnv/engine-rn-electron@0.37.3
 ADDING TO PACKAGE.JSON...DONE
[ task ] checkAndCreateProjectPackage[1]
[ info ] Your ./package.json is missing. CREATING...DONE
[ task ] installPackageDependencies[1] packageManager:(npm install)
✔ Executing: npm install
[ task ] loadEngines[2]
[ task ] loadEnginePluginDeps[1]
[ info ] Engines: @react-native-community/cli-platform-ios,@react-native-community/cli,react-native-tvos,react-native-web,next require plugins @react-native-community/cli-platform-ios,@react-native-community/cli,react-native-tvos,react-native-web,next to be added to ./renative.json
? Continue?.
If you don't want to use this dependency make sure you remove platform which requires this engine from supportedPlatfo
rms Yes
[ info ] Adding @react-native-community/cli-platform-ios,@react-native-community/cli,react-native-tvos,react-native-web,next. ...DONE
[ task ] loadEnginePackageDeps[1]
[ info ] Engine @rnv/engine-rn requires npm devDependency xcode for platform ios. ADDING...DONE
[ info ] Engine @rnv/engine-rn requires npm devDependency jetifier for platform android. ADDING...DONE
[ info ] Engine @rnv/engine-rn-web requires npm dependency raf for platform tizen. ADDING...DONE
[ task ] configurePlugins[1]
[ info ] Missing dependency @rnv/renative v(0.37.3) in package.json. package.json will be overriden
[ info ] Missing dependency react v(18.2.0) in package.json. package.json will be overriden
[ info ] Missing dependency react-art v(18.2.0) in package.json. package.json will be overriden
[ info ] Missing dependency react-dom v(18.2.0) in package.json. package.json will be overriden
[ info ] Missing dependency react-native v(0.67.2) in package.json. package.json will be overriden
[ info ] Missing dependency react-native-gesture-handler v(2.9.0) in package.json. package.json will be overriden
[ task ] installPackageDependencies[2] packageManager:(npm install)
✖ FAILED: npm install
[ warn ] COMMAND: 

npm install 

FAILED with ERROR: 

Command failed with exit code 1: npm install
npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR! 
npm ERR! While resolving: rnv-starter@0.1.0
npm ERR! Found: react@18.2.0
npm ERR! node_modules/react
npm ERR!   react@"18.2.0" from the root project
npm ERR! 
npm ERR! Could not resolve dependency:
npm ERR! peer react@"17.0.2" from react-native@0.67.2
npm ERR! node_modules/react-native
npm ERR!   react-native@"0.67.2" from the root project
npm ERR! 
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
npm ERR! 
npm ERR! 
npm ERR! For a full report see:
npm ERR! /Users/user/.npm/_logs/2023-10-12T13_50_44_138Z-eresolve-report.txt

npm ERR! A complete log of this run can be found in: /Users/user/.npm/_logs/2023-10-12T13_50_44_138Z-debug-0.log

npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR! 
npm ERR! While resolving: rnv-starter@0.1.0
npm ERR! Found: react@18.2.0
npm ERR! node_modules/react
npm ERR!   react@"18.2.0" from the root project
npm ERR! 
npm ERR! Could not resolve dependency:
npm ERR! peer react@"17.0.2" from react-native@0.67.2
npm ERR! node_modules/react-native
npm ERR!   react-native@"0.67.2" from the root project
npm ERR! 
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
npm ERR! 
npm ERR! 
npm ERR! For a full report see:
npm ERR! /Users/user/.npm/_logs/2023-10-12T13_50_44_138Z-eresolve-report.txt

npm ERR! A complete log of this run can be found in: /Users/user/.npm/_logs/2023-10-12T13_50_44_138Z-debug-0.log

Error: Command failed with exit code 1: npm install
npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR! 
npm ERR! While resolving: rnv-starter@0.1.0
npm ERR! Found: react@18.2.0
npm ERR! node_modules/react
npm ERR!   react@"18.2.0" from the root project
npm ERR! 
npm ERR! Could not resolve dependency:
npm ERR! peer react@"17.0.2" from react-native@0.67.2
npm ERR! node_modules/react-native
npm ERR!   react-native@"0.67.2" from the root project
npm ERR! 
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
npm ERR! 
npm ERR! 
npm ERR! For a full report see:
npm ERR! /Users/user/.npm/_logs/2023-10-12T13_50_44_138Z-eresolve-report.txt

npm ERR! A complete log of this run can be found in: /Users/user/.npm/_logs/2023-10-12T13_50_44_138Z-debug-0.log
    at makeError (/Users/user/.nvm/versions/node/v20.8.0/lib/node_modules/rnv/node_modules/execa/lib/error.js:60:11)
    at handlePromise (/Users/user/.nvm/versions/node/v20.8.0/lib/node_modules/rnv/node_modules/execa/index.js:118:26)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)


 Seems like your node_modules is corrupted by other libs. ReNative will try to fix it for you
[ task ] cleanNodeModules[1]
[ task ] installPackageDependencies[3] packageManager:(npm install)
✖ FAILED: npm install
[ error ] COMMAND: 

npm install 

FAILED with ERROR: 

Command failed with exit code 1: npm install
npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR! 
npm ERR! While resolving: rnv-starter@0.1.0
npm ERR! Found: react@18.2.0
npm ERR! node_modules/react
npm ERR!   react@"18.2.0" from the root project
npm ERR! 
npm ERR! Could not resolve dependency:
npm ERR! peer react@"17.0.2" from react-native@0.67.2
npm ERR! node_modules/react-native
npm ERR!   react-native@"0.67.2" from the root project
npm ERR! 
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
npm ERR! 
npm ERR! 
npm ERR! For a full report see:
npm ERR! /Users/user/.npm/_logs/2023-10-12T13_50_46_576Z-eresolve-report.txt

npm ERR! A complete log of this run can be found in: /Users/user/.npm/_logs/2023-10-12T13_50_46_576Z-debug-0.log

npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR! 
npm ERR! While resolving: rnv-starter@0.1.0
npm ERR! Found: react@18.2.0
npm ERR! node_modules/react
npm ERR!   react@"18.2.0" from the root project
npm ERR! 
npm ERR! Could not resolve dependency:
npm ERR! peer react@"17.0.2" from react-native@0.67.2
npm ERR! node_modules/react-native
npm ERR!   react-native@"0.67.2" from the root project
npm ERR! 
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
npm ERR! 
npm ERR! 
npm ERR! For a full report see:
npm ERR! /Users/user/.npm/_logs/2023-10-12T13_50_46_576Z-eresolve-report.txt

npm ERR! A complete log of this run can be found in: /Users/user/.npm/_logs/2023-10-12T13_50_46_576Z-debug-0.log

Error: Command failed with exit code 1: npm install
npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR! 
npm ERR! While resolving: rnv-starter@0.1.0
npm ERR! Found: react@18.2.0
npm ERR! node_modules/react
npm ERR!   react@"18.2.0" from the root project
npm ERR! 
npm ERR! Could not resolve dependency:
npm ERR! peer react@"17.0.2" from react-native@0.67.2
npm ERR! node_modules/react-native
npm ERR!   react-native@"0.67.2" from the root project
npm ERR! 
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
npm ERR! 
npm ERR! 
npm ERR! For a full report see:
npm ERR! /Users/user/.npm/_logs/2023-10-12T13_50_46_576Z-eresolve-report.txt

npm ERR! A complete log of this run can be found in: /Users/user/.npm/_logs/2023-10-12T13_50_46_576Z-debug-0.log
    at makeError (/Users/user/.nvm/versions/node/v20.8.0/lib/node_modules/rnv/node_modules/execa/lib/error.js:60:11)
    at handlePromise (/Users/user/.nvm/versions/node/v20.8.0/lib/node_modules/rnv/node_modules/execa/index.js:118:26)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)


[ error ] COMMAND: 

npm install 

FAILED with ERROR: 

Command failed with exit code 1: npm install
npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR! 
npm ERR! While resolving: rnv-starter@0.1.0
npm ERR! Found: react@18.2.0
npm ERR! node_modules/react
npm ERR!   react@"18.2.0" from the root project
npm ERR! 
npm ERR! Could not resolve dependency:
npm ERR! peer react@"17.0.2" from react-native@0.67.2
npm ERR! node_modules/react-native
npm ERR!   react-native@"0.67.2" from the root project
npm ERR! 
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
npm ERR! 
npm ERR! 
npm ERR! For a full report see:
npm ERR! /Users/user/.npm/_logs/2023-10-12T13_50_46_576Z-eresolve-report.txt

npm ERR! A complete log of this run can be found in: /Users/user/.npm/_logs/2023-10-12T13_50_46_576Z-debug-0.log

npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR! 
npm ERR! While resolving: rnv-starter@0.1.0
npm ERR! Found: react@18.2.0
npm ERR! node_modules/react
npm ERR!   react@"18.2.0" from the root project
npm ERR! 
npm ERR! Could not resolve dependency:
npm ERR! peer react@"17.0.2" from react-native@0.67.2
npm ERR! node_modules/react-native
npm ERR!   react-native@"0.67.2" from the root project
npm ERR! 
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
npm ERR! 
npm ERR! 
npm ERR! For a full report see:
npm ERR! /Users/user/.npm/_logs/2023-10-12T13_50_46_576Z-eresolve-report.txt

npm ERR! A complete log of this run can be found in: /Users/user/.npm/_logs/2023-10-12T13_50_46_576Z-debug-0.log

Error: Command failed with exit code 1: npm install
npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR! 
npm ERR! While resolving: rnv-starter@0.1.0
npm ERR! Found: react@18.2.0
npm ERR! node_modules/react
npm ERR!   react@"18.2.0" from the root project
npm ERR! 
npm ERR! Could not resolve dependency:
npm ERR! peer react@"17.0.2" from react-native@0.67.2
npm ERR! node_modules/react-native
npm ERR!   react-native@"0.67.2" from the root project
npm ERR! 
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
npm ERR! 
npm ERR! 
npm ERR! For a full report see:
npm ERR! /Users/user/.npm/_logs/2023-10-12T13_50_46_576Z-eresolve-report.txt

npm ERR! A complete log of this run can be found in: /Users/user/.npm/_logs/2023-10-12T13_50_46_576Z-debug-0.log
    at makeError (/Users/user/.nvm/versions/node/v20.8.0/lib/node_modules/rnv/node_modules/execa/lib/error.js:60:11)
    at handlePromise (/Users/user/.nvm/versions/node/v20.8.0/lib/node_modules/rnv/node_modules/execa/index.js:118:26)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)


┌──────────────────────────────────────────────────────────────────────────────┐
│  🚀  SUMMARY | 10/12/2023, 8:50:48 AM                                        │
│  $ rnv run                                                                   │
├──────────────────────────────────────────────────────────────────────────────┤
│  ReNative Version: 0.37.3                                                    │
│  Project Name ($package.name): rnv-starter                                   │
│  Project Version ($package.version): 0.1.0                                   │
│  Workspace ($.workspaceID): rnv                                              │
│  Build Scheme (-s): debug                                                    │
│  Env Info: darwin | arm64 | node v20.8.0                                     │
│  Executed Time: 0h:1m:17s:239ms                                              │
│                                                                              │
│ [ warn ] COMMAND: 

npm install 

FAILED with ERROR: 

Command failed with exit code 1: npm install
npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR! 
npm ERR! While resolving: rnv-starter@0.1.0
npm ERR! Found: react@18.2.0
npm ERR! node_modules/react
npm ERR!   react@"18.2.0" from the root project
npm ERR! 
npm ERR! Could not resolve dependency:
npm ERR! peer react@"17.0.2" from react-native@0.67.2
npm ERR! node_modules/react-native
npm ERR!   react-native@"0.67.2" from the root project
npm ERR! 
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
npm ERR! 
npm ERR! 
npm ERR! For a full report see:
npm ERR! /Users/user/.npm/_logs/2023-10-12T13_50_44_138Z-eresolve-report.txt

npm ERR! A complete log of this run can be found in: /Users/user/.npm/_logs/2023-10-12T13_50_44_138Z-debug-0.log

npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR! 
npm ERR! While resolving: rnv-starter@0.1.0
npm ERR! Found: react@18.2.0
npm ERR! node_modules/react
npm ERR!   react@"18.2.0" from the root project
npm ERR! 
npm ERR! Could not resolve dependency:
npm ERR! peer react@"17.0.2" from react-native@0.67.2
npm ERR! node_modules/react-native
npm ERR!   react-native@"0.67.2" from the root project
npm ERR! 
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
npm ERR! 
npm ERR! 
npm ERR! For a full report see:
npm ERR! /Users/user/.npm/_logs/2023-10-12T13_50_44_138Z-eresolve-report.txt

npm ERR! A complete log of this run can be found in: /Users/user/.npm/_logs/2023-10-12T13_50_44_138Z-debug-0.log

Error: Command failed with exit code 1: npm install
npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR! 
npm ERR! While resolving: rnv-starter@0.1.0
npm ERR! Found: react@18.2.0
npm ERR! node_modules/react
npm ERR!   react@"18.2.0" from the root project
npm ERR! 
npm ERR! Could not resolve dependency:
npm ERR! peer react@"17.0.2" from react-native@0.67.2
npm ERR! node_modules/react-native
npm ERR!   react-native@"0.67.2" from the root project
npm ERR! 
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
npm ERR! 
npm ERR! 
npm ERR! For a full report see:
npm ERR! /Users/user/.npm/_logs/2023-10-12T13_50_44_138Z-eresolve-report.txt

npm ERR! A complete log of this run can be found in: /Users/user/.npm/_logs/2023-10-12T13_50_44_138Z-debug-0.log
    at makeError (/Users/user/.nvm/versions/node/v20.8.0/lib/node_modules/rnv/node_modules/execa/lib/error.js:60:11)
    at handlePromise (/Users/user/.nvm/versions/node/v20.8.0/lib/node_modules/rnv/node_modules/execa/index.js:118:26)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)


 Seems like your node_modules is corrupted by other libs. ReNative will try to fix it for you
│ [ error ] COMMAND: 

npm install 

FAILED with ERROR: 

Command failed with exit code 1: npm install
npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR! 
npm ERR! While resolving: rnv-starter@0.1.0
npm ERR! Found: react@18.2.0
npm ERR! node_modules/react
npm ERR!   react@"18.2.0" from the root project
npm ERR! 
npm ERR! Could not resolve dependency:
npm ERR! peer react@"17.0.2" from react-native@0.67.2
npm ERR! node_modules/react-native
npm ERR!   react-native@"0.67.2" from the root project
npm ERR! 
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
npm ERR! 
npm ERR! 
npm ERR! For a full report see:
npm ERR! /Users/user/.npm/_logs/2023-10-12T13_50_46_576Z-eresolve-report.txt

npm ERR! A complete log of this run can be found in: /Users/user/.npm/_logs/2023-10-12T13_50_46_576Z-debug-0.log

npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR! 
npm ERR! While resolving: rnv-starter@0.1.0
npm ERR! Found: react@18.2.0
npm ERR! node_modules/react
npm ERR!   react@"18.2.0" from the root project
npm ERR! 
npm ERR! Could not resolve dependency:
npm ERR! peer react@"17.0.2" from react-native@0.67.2
npm ERR! node_modules/react-native
npm ERR!   react-native@"0.67.2" from the root project
npm ERR! 
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
npm ERR! 
npm ERR! 
npm ERR! For a full report see:
npm ERR! /Users/user/.npm/_logs/2023-10-12T13_50_46_576Z-eresolve-report.txt

npm ERR! A complete log of this run can be found in: /Users/user/.npm/_logs/2023-10-12T13_50_46_576Z-debug-0.log

Error: Command failed with exit code 1: npm install
npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR! 
npm ERR! While resolving: rnv-starter@0.1.0
npm ERR! Found: react@18.2.0
npm ERR! node_modules/react
npm ERR!   react@"18.2.0" from the root project
npm ERR! 
npm ERR! Could not resolve dependency:
npm ERR! peer react@"17.0.2" from react-native@0.67.2
npm ERR! node_modules/react-native
npm ERR!   react-native@"0.67.2" from the root project
npm ERR! 
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
npm ERR! 
npm ERR! 
npm ERR! For a full report see:
npm ERR! /Users/user/.npm/_logs/2023-10-12T13_50_46_576Z-eresolve-report.txt

npm ERR! A complete log of this run can be found in: /Users/user/.npm/_logs/2023-10-12T13_50_46_576Z-debug-0.log
    at makeError (/Users/user/.nvm/versions/node/v20.8.0/lib/node_modules/rnv/node_modules/execa/lib/error.js:60:11)
    at handlePromise (/Users/user/.nvm/versions/node/v20.8.0/lib/node_modules/rnv/node_modules/execa/index.js:118:26)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
```

**Comment by budgustin** [comment]
Rolled back node version to 16.x and it worked.  Thanks!
