### ISSUE TITLE
[tvos] build error

### ISSUE THREAD

**Issue by GabrieleKaceviciute** [flexn-io/renative#1170]
**Describe the bug**
Can't build tvos without errors (sanity_1.0.0-2 tag)

**To Reproduce**
1. go to template-starter package
2. do `rnv build -p tvos`

**Screenshots or copy&paste**
```
✖ FAILED: xcodebuild
COMMAND:

xcodebuild

FAILED with ERROR:

2023-10-13 10:50:00.132 xcodebuild[16857:106471] Writing error result bundle to /var/folders/lk/l5d9tgs51q3fhgtjd8jlk2tc0000gn/T/ResultBundle_2023-13-10_10-50-0000.xcresult
xcodebuild: error: Unable to find a destination matching the provided destination specifier:
 { platform:tvOS Simulator, name:Apple TV }
	Available destinations for the "RNVApp" scheme:
 { platform:iOS, id:dvtdevice-DVTiPhonePlaceholder-iphoneos:placeholder, name:Any iOS Device }
 { platform:iOS Simulator, id:dvtdevice-DVTiOSDeviceSimulatorPlaceholder-iphonesimulator:placeholder, name:Any iOS Simulator Device }
 { platform:iOS Simulator, id:6447F792-0449-4CFF-AFDD-262170AF67E0, OS:16.2, name:iPad (10th generation) }

Command failed with exit code 70: xcodebuild -workspace /Users/gabriele/Desktop/renative/packages/template-starter/platformBuilds/template_tvos/RNVApp.xcworkspace -scheme RNVApp -configuration Debug -derivedDataPath /Users/gabriele/Desktop/renative/packages/template-starter/platformBuilds/template_tvos/build/RNVApp -destination platform=tvOS Simulator,name=Apple TV build -allowProvisioningUpdates
2023-10-13 10:50:00.132 xcodebuild[16857:106471] Writing error result bundle to /var/folders/lk/l5d9tgs51q3fhgtjd8jlk2tc0000gn/T/ResultBundle_2023-13-10_10-50-0000.xcresult
xcodebuild: error: Unable to find a destination matching the provided destination specifier:
		{ platform:tvOS Simulator, name:Apple TV }

	Available destinations for the "RNVApp" scheme:
		{ platform:iOS, id:dvtdevice-DVTiPhonePlaceholder-iphoneos:placeholder, name:Any iOS Device }
		{ platform:iOS Simulator, id:dvtdevice-DVTiOSDeviceSimulatorPlaceholder-iphonesimulator:placeholder, name:Any iOS Simulator Device }
		{ platform:iOS Simulator, id:6447F792-0449-4CFF-AFDD-262170AF67E0, OS:16.2, name:iPad (10th generation) }
		{ platform:iOS Simulator, id:1C106D3E-8BEF-4970-9B3E-6B69289CC1F3, OS:16.2, name:iPad Air (5th generation) }
		{ platform:iOS Simulator, id:E1780AA4-34BF-456B-9381-A9B6A1BD1A0B, OS:16.2, name:iPad Pro (11-inch) (4th generation) }
		{ platform:iOS Simulator, id:0DC9495D-3EA4-4489-8EF1-A748B4AE0BCC, OS:16.2, name:iPad Pro (12.9-inch) (6th generation) }
		{ platform:iOS Simulator, id:464CB9A5-A962-403C-9E38-6899A8ECF800, OS:16.2, name:iPad mini (6th generation) }
		{ platform:iOS Simulator, id:FCE20CBD-4131-46CD-992F-B4C11DD4C6C3, OS:16.2, name:iPhone 14 }
		{ platform:iOS Simulator, id:3FA262DD-649E-4B52-BDB4-E7199100F868, OS:16.2, name:iPhone 14 Plus }
		{ platform:iOS Simulator, id:170C20C6-609B-47B6-AA11-E3A5E8BE29B5, OS:16.2, name:iPhone 14 Pro }
		{ platform:iOS Simulator, id:33D70015-4AF8-4997-81BB-6A13C9ED4E61, OS:16.2, name:iPhone 14 Pro Max }
		{ platform:iOS Simulator, id:6830E150-3B0E-4A6F-A8E6-E604DAADD576, OS:16.2, name:iPhone SE (3rd generation) }
Command line invocation:
    /Applications/Xcode.app/Contents/Developer/usr/bin/xcodebuild -workspace /Users/gabriele/Desktop/renative/packages/template-starter/platformBuilds/template_tvos/RNVApp.xcworkspace -scheme RNVApp -configuration Debug -derivedDataPath /Users/gabriele/Desktop/renative/packages/template-starter/platformBuilds/template_tvos/build/RNVApp -destination "platform=tvOS Simulator,name=Apple TV" build -allowProvisioningUpdates

User defaults from command line:
    IDEDerivedDataPathOverride = /Users/gabriele/Desktop/renative/packages/template-starter/platformBuilds/template_tvos/build/RNVApp
    IDEPackageSupportUseBuiltinSCM = YES


2023-10-13 10:50:00.132 xcodebuild[16857:106471] Writing error result bundle to /var/folders/lk/l5d9tgs51q3fhgtjd8jlk2tc0000gn/T/ResultBundle_2023-13-10_10-50-0000.xcresult
xcodebuild: error: Unable to find a destination matching the provided destination specifier:
		{ platform:tvOS Simulator, name:Apple TV }

	Available destinations for the "RNVApp" scheme:
		{ platform:iOS, id:dvtdevice-DVTiPhonePlaceholder-iphoneos:placeholder, name:Any iOS Device }
		{ platform:iOS Simulator, id:dvtdevice-DVTiOSDeviceSimulatorPlaceholder-iphonesimulator:placeholder, name:Any iOS Simulator Device }
		{ platform:iOS Simulator, id:6447F792-0449-4CFF-AFDD-262170AF67E0, OS:16.2, name:iPad (10th generation) }
		{ platform:iOS Simulator, id:1C106D3E-8BEF-4970-9B3E-6B69289CC1F3, OS:16.2, name:iPad Air (5th generation) }
		{ platform:iOS Simulator, id:E1780AA4-34BF-456B-9381-A9B6A1BD1A0B, OS:16.2, name:iPad Pro (11-inch) (4th generation) }
		{ platform:iOS Simulator, id:0DC9495D-3EA4-4489-8EF1-A748B4AE0BCC, OS:16.2, name:iPad Pro (12.9-inch) (6th generation) }
		{ platform:iOS Simulator, id:464CB9A5-A962-403C-9E38-6899A8ECF800, OS:16.2, name:iPad mini (6th generation) }
		{ platform:iOS Simulator, id:FCE20CBD-4131-46CD-992F-B4C11DD4C6C3, OS:16.2, name:iPhone 14 }
		{ platform:iOS Simulator, id:3FA262DD-649E-4B52-BDB4-E7199100F868, OS:16.2, name:iPhone 14 Plus }
		{ platform:iOS Simulator, id:170C20C6-609B-47B6-AA11-E3A5E8BE29B5, OS:16.2, name:iPhone 14 Pro }
		{ platform:iOS Simulator, id:33D70015-4AF8-4997-81BB-6A13C9ED4E61, OS:16.2, name:iPhone 14 Pro Max }
		{ platform:iOS Simulator, id:6830E150-3B0E-4A6F-A8E6-E604DAADD576, OS:16.2, name:iPhone SE (3rd generation) }

Error: Command failed with exit code 70: xcodebuild -workspace /Users/gabriele/Desktop/renative/packages/template-starter/platformBuilds/template_tvos/RNVApp.xcworkspace -scheme RNVApp -configuration Debug -derivedDataPath /Users/gabriele/Desktop/renative/packages/template-starter/platformBuilds/template_tvos/build/RNVApp -destination platform=tvOS Simulator,name=Apple TV build -allowProvisioningUpdates
2023-10-13 10:50:00.132 xcodebuild[16857:106471] Writing error result bundle to /var/folders/lk/l5d9tgs51q3fhgtjd8jlk2tc0000gn/T/ResultBundle_2023-13-10_10-50-0000.xcresult
xcodebuild: error: Unable to find a destination matching the provided destination specifier:
		{ platform:tvOS Simulator, name:Apple TV }

	Available destinations for the "RNVApp" scheme:
		{ platform:iOS, id:dvtdevice-DVTiPhonePlaceholder-iphoneos:placeholder, name:Any iOS Device }
		{ platform:iOS Simulator, id:dvtdevice-DVTiOSDeviceSimulatorPlaceholder-iphonesimulator:placeholder, name:Any iOS Simulator Device }
		{ platform:iOS Simulator, id:6447F792-0449-4CFF-AFDD-262170AF67E0, OS:16.2, name:iPad (10th generation) }
		{ platform:iOS Simulator, id:1C106D3E-8BEF-4970-9B3E-6B69289CC1F3, OS:16.2, name:iPad Air (5th generation) }
		{ platform:iOS Simulator, id:E1780AA4-34BF-456B-9381-A9B6A1BD1A0B, OS:16.2, name:iPad Pro (11-inch) (4th generation) }
		{ platform:iOS Simulator, id:0DC9495D-3EA4-4489-8EF1-A748B4AE0BCC, OS:16.2, name:iPad Pro (12.9-inch) (6th generation) }
		{ platform:iOS Simulator, id:464CB9A5-A962-403C-9E38-6899A8ECF800, OS:16.2, name:iPad mini (6th generation) }
		{ platform:iOS Simulator, id:FCE20CBD-4131-46CD-992F-B4C11DD4C6C3, OS:16.2, name:iPhone 14 }
		{ platform:iOS Simulator, id:3FA262DD-649E-4B52-BDB4-E7199100F868, OS:16.2, name:iPhone 14 Plus }
		{ platform:iOS Simulator, id:170C20C6-609B-47B6-AA11-E3A5E8BE29B5, OS:16.2, name:iPhone 14 Pro }
		{ platform:iOS Simulator, id:33D70015-4AF8-4997-81BB-6A13C9ED4E61, OS:16.2, name:iPhone 14 Pro Max }
		{ platform:iOS Simulator, id:6830E150-3B0E-4A6F-A8E6-E604DAADD576, OS:16.2, name:iPhone SE (3rd generation) }
Command line invocation:
    /Applications/Xcode.app/Contents/Developer/usr/bin/xcodebuild -workspace /Users/gabriele/Desktop/renative/packages/template-starter/platformBuilds/template_tvos/RNVApp.xcworkspace -scheme RNVApp -configuration Debug -derivedDataPath /Users/gabriele/Desktop/renative/packages/template-starter/platformBuilds/template_tvos/build/RNVApp -destination "platform=tvOS Simulator,name=Apple TV" build -allowProvisioningUpdates

User defaults from command line:
    IDEDerivedDataPathOverride = /Users/gabriele/Desktop/renative/packages/template-starter/platformBuilds/template_tvos/build/RNVApp
    IDEPackageSupportUseBuiltinSCM = YES

    at makeError (/Users/gabriele/Desktop/renative/node_modules/execa/lib/error.js:60:11)
    at handlePromise (/Users/gabriele/Desktop/renative/node_modules/execa/index.js:118:26)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)



 $ rnv build -p tvos - Done! 🚀
┌──────────────────────────────────────────────────────────────────────────────┐
│  🚀  SUMMARY | 10/13/2023, 10:50:01 AM                                       │
│  $ rnv build -p tvos                                                         │
├──────────────────────────────────────────────────────────────────────────────┤
│  ReNative Version: 1.0.0-canary.4                                            │
│  Project Name ($package.name): @rnv/template-starter                         │
│  Project Version ($package.version): 1.0.0-canary.4                          │
│  Workspace ($.workspaceID): rnv                                              │
│  Platform (-p): tvos                                                         │
│  Engine ($.platforms.tvos.engine): engine-rn-tvos                            │
│  App Config (-c): template                                                   │
│  Build Scheme (-s): debug                                                    │
│  Target (-t): Apple TV                                                       │
│  Supported Platforms: tvos                                                   │
│  Env Info: darwin | x64 | node v18.14.2                                      │
│  Executed Time: 0h:0m:4s:673ms                                               │
│                                                                              │
│  All good as 🦄                                                              │
│                                                                              │
│  Project location:                                                           │
│  ./platformBuilds/template_tvos/RNVApp.xcworkspace                           │
└──────────────────────────────────────────────────────────────────────────────┘
➜  ~/Desktop/renative/packages/template-starter git:(68ac31540)
```

**Desktop (please complete the following information):**

-   OS: macOS Ventura 13.5.2
-   Node Version 18.14.2
-   RNV Version 1.0.0-canary.7
-   rnv/template-starter Version 1.0.0-canary.7

**Comment by GabrieleKaceviciute** [comment]
not reproduced on 1.0.0-feat-pin-cli.2
