### ISSUE TITLE
rnv run -p android can't find gradle

### ISSUE THREAD

**Issue by mihaiblaga89** [flexn-io/renative#1176]
**Describe the bug**

assets seem to not have been copied properly from the template

```
[ task ] <= [configure] <= platform configure
[ task ] [configure] configureEntryPoint[1]
[ task ] [configure] configureGradleProject[1]
[ task ] [configure] copyAssetsFolder[1]
[ info ] [configure] Found custom assetSources at ./node_modules/@flexn/assets-renative-outline/assets/android. Will be used to generate assets.
[ task ] [configure] configureAndroidProperties[1]
[ task ] [configure] configureProject[1]
[ task ] [configure] parsePlugins[3]
[ task ] [configure] parseFonts[2]
[ task ] [configure] parsePlugins[4]
[ task ] [configure] parseAppBuildGradleSync[1]
[ task ] [configure] parseGradleWrapperSync[1]
[ task ] [configure] copyGradleProjectTemplate[1]
[ error ] [configure] Cannot write file. source path doesn't exists: /Users/lego/temp/testrnv1-6/node_modules/@rnv/sdk-android/templates/gradleProject/gradle/wrapper/gradle-wrapper.properties
[ error ] [configure] Cannot write file. source path doesn't exists: /Users/lego/temp/testrnv1-6/node_modules/@rnv/engine-rn/templates/platforms/android/app/src/main/java/rnv/SplashActivity.kt
[ task ] [configure] parseAndroidManifestSync[1]
[ task ] [configure] parsePlugins[5]
[ task ] [configure] _checkSigningCerts[1]
[ task ] [configure] copyBuildsFolder[1]
[ task ] [configure] copyTemplatePluginsSync[1] (./platformBuilds/app_android)
[ task ] [configure] parsePlugins[6]
[ task ] [configure] jetifyIfRequired[1]
⠋ Executing: npx jetifyError: ENOENT: no such file or directory, chmod '/Users/lego/temp/testrnv1-6/platformBuilds/app_android/gradlew'
    at Object.chmodSync (node:fs:1991:3)
    at fsChmodSync (/Users/lego/temp/testrnv1-6/node_modules/@rnv/core/src/system/fs.ts:36:81)
    at /Users/lego/temp/testrnv1-6/node_modules/@rnv/sdk-android/src/gradleWrapperParser.ts:24:16
    at step (/Users/lego/temp/testrnv1-6/node_modules/tslib/tslib.js:195:27)
    at Object.next (/Users/lego/temp/testrnv1-6/node_modules/tslib/tslib.js:176:57)
    at /Users/lego/temp/testrnv1-6/node_modules/tslib/tslib.js:169:75
    at new Promise (<anonymous>)
    at Object.__awaiter (/Users/lego/temp/testrnv1-6/node_modules/tslib/tslib.js:165:16)
    at copyGradleProjectTemplate (/Users/lego/temp/testrnv1-6/node_modules/@rnv/sdk-android/src/gradleWrapperParser.ts:16:52)
    at parseGradleWrapperSync (/Users/lego/temp/testrnv1-6/node_modules/@rnv/sdk-android/src/gradleWrapperParser.ts:30:5)

```

**Comment by pauliusguzas** [comment]
@mihaiblaga89 any reproducibility steps?

**Comment by mihaiblaga89** [comment]
@pauliusguzas rnv new, run `npx rnv run -p android`
