### ISSUE TITLE
error when try to do `yarn bootstrap` on windows

### ISSUE THREAD

**Issue by GabrieleKaceviciute** [flexn-io/renative#1183]
**Describe the bug**
Can't do `yarn bootstrap` without error

**To Reproduce**
1. go to renative local repo
2. do `yarn bootstrap`

**Screenshots or copy&paste**
```
PS C:\Users\dev\Desktop\renative> yarn bootstrap
yarn run v1.22.19
$ yarn run link:rnv && npx lerna bootstrap && yarn build
$ npm r rnv -g && cd packages/rnv && npm link

removed 1 package in 171ms

added 1 package, and audited 4 packages in 498ms

found 0 vulnerabilities
lerna notice cli v6.6.2
lerna info versioning independent
lerna info bootstrap root only
[1/5] Validating package.json...
[2/5] Resolving packages...
[3/5] Fetching packages...
error ttab@0.7.3: The platform "win32" is incompatible with this module.
error Found incompatible module.
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
lerna ERR! yarn install --mutex network:42424 --non-interactive --no-package-lock --unsafe-perm=true --no-optional exited 1 in '@flexn/renative-monorepo'
lerna ERR! yarn install --mutex network:42424 --non-interactive --no-package-lock --unsafe-perm=true --no-optional exited 1 in '@flexn/renative-monorepo'
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
PS C:\Users\dev\Desktop\renative>
```

**Desktop (please complete the following information):**

-   OS: windows 10 Pro
-   Node Version 18.14.2
-   RNV Version 1.0.0-canary.4

**Comment by mihaiblaga89** [comment]
pushed the fix to main

**Comment by GabrieleKaceviciute** [comment]
@mihaiblaga89 now this occurs

```
PS C:\Users\dev\Desktop\renative> yarn bootstrap
yarn run v1.22.19
$ yarn run link:rnv && npx lerna bootstrap && yarn build
$ npm r rnv -g && cd packages/rnv && npm link

removed 1 package in 316ms

added 1 package, and audited 4 packages in 731ms

found 0 vulnerabilities
lerna notice cli v6.6.2
lerna info versioning independent
lerna info bootstrap root only
[1/5] Validating package.json...
[2/5] Resolving packages...
[3/5] Fetching packages...
[4/5] Linking dependencies...
warning " > @babel/eslint-parser@7.17.0" has unmet peer dependency "@babel/core@>=7.11.0".
warning " > @flexn/typescript-config@1.0.0" has unmet peer dependency "tslib@>=2.3.1".
warning " > babel-jest@29.2.1" has unmet peer dependency "@babel/core@^7.8.0".
warning "babel-jest > babel-preset-jest@29.6.3" has unmet peer dependency "@babel/core@^7.0.0".
warning "babel-jest > babel-preset-jest > babel-preset-current-node-syntax@1.0.1" has unmet peer dependency "@babel/core@^7.0.0".
warning "babel-jest > babel-preset-jest > babel-preset-current-node-syntax > @babel/plugin-syntax-async-generators@7.8.4" has unmet peer dependency "@babel/core@^7.0.0-0".
warning "babel-jest > babel-preset-jest > babel-preset-current-node-syntax > @babel/plugin-syntax-bigint@7.8.3" has unmet peer dependency "@babel/core@^7.0.0-0".
warning "babel-jest > babel-preset-jest > babel-preset-current-node-syntax > @babel/plugin-syntax-class-properties@7.12.13" has unmet peer dependency "@babel/core@^7.0.0-0".
warning "babel-jest > babel-preset-jest > babel-preset-current-node-syntax > @babel/plugin-syntax-import-meta@7.10.4" has unmet peer dependency "@babel/core@^7.0.0-0".
warning "babel-jest > babel-preset-jest > babel-preset-current-node-syntax > @babel/plugin-syntax-json-strings@7.8.3" has unmet peer dependency "@babel/core@^7.0.0-0".
warning "babel-jest > babel-preset-jest > babel-preset-current-node-syntax > @babel/plugin-syntax-logical-assignment-operators@7.10.4" has unmet peer dependency "@babel/core@^7.0.0-0".
warning "babel-jest > babel-preset-jest > babel-preset-current-node-syntax > @babel/plugin-syntax-nullish-coalescing-operator@7.8.3" has unmet peer dependency "@babel/core@^7.0.0-0".
warning "babel-jest > babel-preset-jest > babel-preset-current-node-syntax > @babel/plugin-syntax-numeric-separator@7.10.4" has unmet peer dependency "@babel/core@^7.0.0-0".
warning "babel-jest > babel-preset-jest > babel-preset-current-node-syntax > @babel/plugin-syntax-object-rest-spread@7.8.3" has unmet peer dependency "@babel/core@^7.0.0-0".
warning "babel-jest > babel-preset-jest > babel-preset-current-node-syntax > @babel/plugin-syntax-optional-catch-binding@7.8.3" has unmet peer dependency "@babel/core@^7.0.0-0".
warning "babel-jest > babel-preset-jest > babel-preset-current-node-syntax > @babel/plugin-syntax-optional-chaining@7.8.3" has unmet peer dependency "@babel/core@^7.0.0-0".
warning "babel-jest > babel-preset-jest > babel-preset-current-node-syntax > @babel/plugin-syntax-top-level-await@7.14.5" has unmet peer dependency "@babel/core@^7.0.0-0".
warning " > ts-jest@27.1.5" has incorrect peer dependency "jest@^27.0.0".
warning " > ts-jest@27.1.5" has incorrect peer dependency "typescript@>=3.8 <5.0".
warning " > @rnv/engine-rn-tvos@1.0.0-canary.7" has unmet peer dependency "metro-cache@^0.78.1".
warning " > @rnv/engine-rn-windows@1.0.0-canary.7" has unmet peer dependency "@react-native-community/cli@*".
warning " > @rnv/engine-rn-windows@1.0.0-canary.7" has unmet peer dependency "react-native@*".
warning " > @rnv/engine-rn@1.0.0-canary.7" has unmet peer dependency "@react-native/metro-config@^0.73.1".
warning "workspace-aggregator-d934dcb7-fd05-41f0-8aa0-ba22b50fcbbc > @rnv/engine-rn-next > @expo/next-adapter@5.0.2" has unmet peer dependency "expo@^46".
warning "workspace-aggregator-d934dcb7-fd05-41f0-8aa0-ba22b50fcbbc > @rnv/engine-rn-next > @expo/next-adapter@5.0.2" has unmet peer dependency "next@^13".
warning "workspace-aggregator-d934dcb7-fd05-41f0-8aa0-ba22b50fcbbc > @rnv/engine-rn-next > @expo/next-adapter@5.0.2" has unmet peer dependency "react@^18".
warning "workspace-aggregator-d934dcb7-fd05-41f0-8aa0-ba22b50fcbbc > @rnv/engine-rn-next > @expo/next-adapter@5.0.2" has unmet peer dependency "react-native-web@~0.18.0".
warning "workspace-aggregator-d934dcb7-fd05-41f0-8aa0-ba22b50fcbbc > @rnv/engine-rn-next > @expo/next-adapter@5.0.2" has unmet peer dependency "webpack@^4.46.0 || ^5.74.0".
warning "workspace-aggregator-d934dcb7-fd05-41f0-8aa0-ba22b50fcbbc > @rnv/engine-rn-next > next-fonts@1.5.1" has unmet peer dependency "webpack@^4.0.0 || ^5.0.0".
warning "workspace-aggregator-d934dcb7-fd05-41f0-8aa0-ba22b50fcbbc > @rnv/engine-rn-next > next-images@1.8.4" has unmet peer dependency "webpack@^4.0.0 || ^5.0.0".
warning "workspace-aggregator-d934dcb7-fd05-41f0-8aa0-ba22b50fcbbc > @rnv/engine-rn-web > html-webpack-harddisk-plugin@1.0.2" has unmet peer dependency "webpack@^1.0.0 || ^2.0.0 || ^3.0.0 || ^4.0.0".
warning "workspace-aggregator-d934dcb7-fd05-41f0-8aa0-ba22b50fcbbc > @rnv/engine-rn-web > html-webpack-plugin@4.5.1" has unmet peer dependency "webpack@^4.0.0 || ^5.0.0".
warning "workspace-aggregator-d934dcb7-fd05-41f0-8aa0-ba22b50fcbbc > @rnv/engine-rn-web > mini-css-extract-plugin@0.8.0" has unmet peer dependency "webpack@^4.4.0".
warning "workspace-aggregator-d934dcb7-fd05-41f0-8aa0-ba22b50fcbbc > @rnv/engine-rn-windows > react-native-windows@0.72.10" has unmet peer dependency "react@18.2.0".
warning "workspace-aggregator-d934dcb7-fd05-41f0-8aa0-ba22b50fcbbc > @rnv/engine-rn-windows > react-native-windows@0.72.10" has unmet peer dependency "react-native@^0.72.3".
warning "workspace-aggregator-d934dcb7-fd05-41f0-8aa0-ba22b50fcbbc > @rnv/template-starter > babel-loader@9.1.3" has unmet peer dependency "@babel/core@^7.12.0".
warning "workspace-aggregator-d934dcb7-fd05-41f0-8aa0-ba22b50fcbbc > @rnv/template-starter > babel-loader@9.1.3" has unmet peer dependency "webpack@>=5".
warning "workspace-aggregator-d934dcb7-fd05-41f0-8aa0-ba22b50fcbbc > @rnv/template-starter > detox@18.20.2" has unmet peer dependency "jest-circus@26.0.x - 26.4.x || >=26.5.2".
warning "workspace-aggregator-d934dcb7-fd05-41f0-8aa0-ba22b50fcbbc > @rnv/template-starter > detox@18.20.2" has unmet peer dependency "jest-environment-node@>=25.0.0".
warning "workspace-aggregator-d934dcb7-fd05-41f0-8aa0-ba22b50fcbbc > @rnv/template-starter > detox@18.20.2" has unmet peer dependency "mocha@>=6.0.0".
warning "workspace-aggregator-d934dcb7-fd05-41f0-8aa0-ba22b50fcbbc > @rnv/template-starter > metro-react-native-babel-preset@0.76.8" has unmet peer dependency "@babel/core@*".
warning "workspace-aggregator-d934dcb7-fd05-41f0-8aa0-ba22b50fcbbc > @rnv/engine-rn-next > babel-preset-expo > @babel/plugin-proposal-decorators@7.22.15" has unmet peer dependency "@babel/core@^7.0.0-0".
warning "workspace-aggregator-d934dcb7-fd05-41f0-8aa0-ba22b50fcbbc > @rnv/engine-rn-next > babel-preset-expo > @babel/plugin-proposal-export-namespace-from@7.18.9" has unmet peer dependency "@babel/core@^7.0.0-0".
warning "workspace-aggregator-d934dcb7-fd05-41f0-8aa0-ba22b50fcbbc > @rnv/engine-rn-next > babel-preset-expo > @babel/plugin-proposal-object-rest-spread@7.20.7" has unmet peer dependency "@babel/core@^7.0.0-0".
warning "workspace-aggregator-d934dcb7-fd05-41f0-8aa0-ba22b50fcbbc > @rnv/engine-rn-next > babel-preset-expo > @babel/plugin-transform-react-jsx@7.22.15" has unmet peer dependency "@babel/core@^7.0.0-0".
warning "workspace-aggregator-d934dcb7-fd05-41f0-8aa0-ba22b50fcbbc > @rnv/engine-rn-next > next-fonts > url-loader@4.1.1" has unmet peer dependency "webpack@^4.0.0 || ^5.0.0".
warning "workspace-aggregator-d934dcb7-fd05-41f0-8aa0-ba22b50fcbbc > @rnv/engine-rn-windows > react-native-windows > @react-native-windows/cli@0.72.3" has unmet peer dependency "react-native@*".
warning "workspace-aggregator-d934dcb7-fd05-41f0-8aa0-ba22b50fcbbc > @rnv/engine-rn-windows > react-native-windows > @react-native/codegen@0.72.7" has unmet peer dependency "@babel/preset-env@^7.1.6".
warning "workspace-aggregator-d934dcb7-fd05-41f0-8aa0-ba22b50fcbbc > @rnv/engine-rn-windows > react-native-windows > @react-native/virtualized-lists@0.72.8" has unmet peer dependency "react-native@*".
warning "workspace-aggregator-d934dcb7-fd05-41f0-8aa0-ba22b50fcbbc > @rnv/engine-rn-windows > react-native-windows > react-shallow-renderer@16.15.0" has unmet peer dependency "react@^16.0.0 || ^17.0.0 || ^18.0.0".
warning "workspace-aggregator-d934dcb7-fd05-41f0-8aa0-ba22b50fcbbc > @rnv/engine-rn-windows > react-native-windows > use-sync-external-store@1.2.0" has unmet peer dependency "react@^16.8.0 || ^17.0.0 || ^18.0.0".
warning "workspace-aggregator-d934dcb7-fd05-41f0-8aa0-ba22b50fcbbc > @rnv/integration-ftp > ftp-deploy > promise-ftp@1.3.5" has unmet peer dependency "promise-ftp-common@^1.1.5".
warning "workspace-aggregator-d934dcb7-fd05-41f0-8aa0-ba22b50fcbbc > @rnv/template-starter > @react-native/metro-config > @react-native/metro-babel-transformer@0.73.12" has unmet peer dependency "@babel/core@*".
warning "workspace-aggregator-d934dcb7-fd05-41f0-8aa0-ba22b50fcbbc > @rnv/engine-rn-next > babel-preset-expo > @babel/plugin-proposal-decorators > @babel/helper-replace-supers@7.22.20" has unmet peer dependency "@babel/core@^7.0.0".
warning "workspace-aggregator-d934dcb7-fd05-41f0-8aa0-ba22b50fcbbc > @rnv/engine-rn-next > babel-preset-expo > @babel/plugin-proposal-decorators > @babel/plugin-syntax-decorators@7.22.10" has unmet peer dependency "@babel/core@^7.0.0-0".
warning "workspace-aggregator-d934dcb7-fd05-41f0-8aa0-ba22b50fcbbc > @rnv/engine-rn-windows > react-native-windows > @react-native-windows/cli > @react-native-windows/codegen@0.72.2" has unmet peer dependency "react-native@*".
warning "workspace-aggregator-d934dcb7-fd05-41f0-8aa0-ba22b50fcbbc > @rnv/engine-rn-windows > react-native-windows > @react-native/codegen > jscodeshift@0.14.0" has unmet peer dependency "@babel/preset-env@^7.1.6".
warning "workspace-aggregator-d934dcb7-fd05-41f0-8aa0-ba22b50fcbbc > @rnv/sdk-android > @react-native-community/cli > @react-native-community/cli-plugin-metro > metro-react-native-babel-transformer@0.76.8" has unmet peer dependency "@babel/core@*".
warning "workspace-aggregator-d934dcb7-fd05-41f0-8aa0-ba22b50fcbbc > @rnv/template-starter > @flexn/graybox > @wdio/allure-reporter > @wdio/types@7.19.5" has incorrect peer dependency "typescript@^4.6.2".
warning "workspace-aggregator-d934dcb7-fd05-41f0-8aa0-ba22b50fcbbc > @rnv/template-starter > react-native > @react-native-community/cli > @react-native-community/cli-plugin-metro > metro-react-native-babel-transformer@0.76.7" has unmet peer dependency "@babel/core@*".
warning "workspace-aggregator-d934dcb7-fd05-41f0-8aa0-ba22b50fcbbc > @rnv/template-starter > @react-native/metro-config > @react-native/metro-babel-transformer > @react-native/babel-preset > @react-native/babel-plugin-codegen > @react-native/codegen@0.74.0" has unmet peer dependency "@babel/preset-env@^7.1.6".
[5/5] Building fresh packages...
[7/20] ⠐ electron
[8/20] ⠐ cpu-features
[13/20] ⠈ chromedriver
[11/20] ⠈ @lightningjs/sdk
warning Error running install script for optional dependency: "C:\\Users\\dev\\Desktop\\renative\\node_modules\\cpu-features: Command failed.
Exit code: 1
Command: node buildcheck.js > buildcheck.gypi && node-gyp rebuild
Arguments:
Directory: C:\\Users\\dev\\Desktop\\renative\\node_modules\\cpu-features
Output:
C:\\Users\\dev\\Desktop\\renative\\node_modules\\buildcheck\\lib\\index.js:133
        throw new Error('Unable to detect compiler type');
        ^

Error: Unable to detect compiler type
    at new BuildEnvironment (C:\\Users\\dev\\Desktop\\renative\\node_modules\\buildcheck\\lib\\index.js:133:15)
    at Object.<anonymous> (C:\\Users\\dev\\Desktop\\renative\\node_modules\\cpu-features\\buildcheck.js:5:12)
    at Module._compile (node:internal/modules/cjs/loader:1254:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1308:10)
    at Module.load (node:internal/modules/cjs/loader:1117:32)
    at Module._load (node:internal/modules/cjs/loader:958:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:81:12)
$ npx lerna link --force-local && npx jetify
lerna notice cli v6.6.2
lerna info versioning independent
lerna info Symlinking packages and binaries
Jetifier found 2162 file(s) to forward-jetify. Using 4 workers...
$ lerna run build
lerna notice cli v6.6.2
lerna info versioning independent


    ×  @rnv/renative:build
$ yarn clean && yarn compile
$ rm -rf ./lib && rm -rf tsconfig.tsbuildinfo
'rm' is not recognized as an internal or external command,
       operable program or batch file.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.


    ×  @rnv/core:build
$ yarn clean && yarn compile
$ rm -rf ./lib && rm -rf tsconfig.tsbuildinfo
'rm' is not recognized as an internal or external command,
       operable program or batch file.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.


 ——————————————————————————————————————————————————————————————————————————————————————————————————————————————————————

 >  Lerna (powered by Nx)   Ran target build for 27 projects (2s)

    √    0/2 succeeded [0 read from cache]

    ×    2/2 targets failed, including the following:
         - @rnv/renative:build
         - @rnv/core:build

   Hint: Try "nx view-logs" to get structured, searchable errors logs in your browser.

error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
PS C:\Users\dev\Desktop\renative>
```

**Comment by GabrieleKaceviciute** [comment]
works on 1.0.0-canary.8
