### ISSUE TITLE
[Android, AndroidTV, Androidwear] Can't run template starter on macos

### ISSUE THREAD

**Issue by pauliusguzas** [flexn-io/renative#1196]
**Describe the bug**
Can't run all android platforms (sanity_1.0.0-2 tag)

**To Reproduce**
1. go to template-starter package
2. run `rnv run -p androidtv`

```
[ info ] [run] Found device Android_TV_1080p_API_27:emulator-5556!
[ task ] [run] _runGradleApp[1]
✔ Executing: npx react-native run-android --mode=Debug --no-packager --deviceId=emulator-5556

info Building the app...

> Task :react-native-gesture-handler:compileDebugKotlin
'compileDebugJavaWithJavac' task (current target is 11) and 'compileDebugKotlin' task (current target is 1.8) jvm target compatibility should be set to the same Java version.
w: /Users/pauliusguzas/Desktop/renative/renative/node_modules/react-native-gesture-handler/android/noreanimated/src/main/java/com/swmansion/gesturehandler/ReanimatedEventDispatcher.kt: (7, 31): Parameter 'event' is never used
w: /Users/pauliusguzas/Desktop/renative/renative/node_modules/react-native-gesture-handler/android/noreanimated/src/main/java/com/swmansion/gesturehandler/ReanimatedEventDispatcher.kt: (7, 41): Parameter 'reactApplicationContext' is never used
w: /Users/pauliusguzas/Desktop/renative/renative/node_modules/react-native-gesture-handler/android/src/main/java/com/swmansion/gesturehandler/core/GestureHandler.kt: (770, 11): Name shadowed: size
w: /Users/pauliusguzas/Desktop/renative/renative/node_modules/react-native-gesture-handler/android/src/main/java/com/swmansion/gesturehandler/react/RNGestureHandlerEnabledRootView.kt: (9, 51): Unreachable code
w: /Users/pauliusguzas/Desktop/renative/renative/node_modules/react-native-gesture-handler/android/src/main/java/com/swmansion/gesturehandler/react/RNGestureHandlerEnabledRootView.kt: (10, 80): Unreachable code
w: /Users/pauliusguzas/Desktop/renative/renative/node_modules/react-native-gesture-handler/android/src/main/java/com/swmansion/gesturehandler/react/RNGestureHandlerRootHelper.kt: (80, 18): 'onChildStartedNativeGesture(MotionEvent!): Unit' is deprecated. Deprecated in Java
w: /Users/pauliusguzas/Desktop/renative/renative/node_modules/react-native-gesture-handler/android/src/main/java/com/swmansion/gesturehandler/react/RNGestureHandlerRootHelper.kt: (86, 42): Parameter 'disallowIntercept' is never used
w: /Users/pauliusguzas/Desktop/renative/renative/node_modules/react-native-gesture-handler/android/src/main/java/com/swmansion/gesturehandler/react/RNGestureHandlerRootHelper.kt: (118, 28): Parameter 'viewTag' is never used
w: /Users/pauliusguzas/Desktop/renative/renative/node_modules/react-native-gesture-handler/android/src/main/java/com/swmansion/gesturehandler/react/RNGestureHandlerTouchEvent.kt: (7, 44): 'RCTEventEmitter' is deprecated. Deprecated in Java
w: /Users/pauliusguzas/Desktop/renative/renative/node_modules/react-native-gesture-handler/android/src/main/java/com/swmansion/gesturehandler/react/RNGestureHandlerTouchEvent.kt: (14, 11): 'init(Int): Unit' is deprecated. Deprecated in Java
w: /Users/pauliusguzas/Desktop/renative/renative/node_modules/react-native-gesture-handler/android/src/main/java/com/swmansion/gesturehandler/react/RNGestureHandlerTouchEvent.kt: (30, 42): 'RCTEventEmitter' is deprecated. Deprecated in Java
w: /Users/pauliusguzas/Desktop/renative/renative/node_modules/react-native-gesture-handler/android/src/main/java/com/swmansion/gesturehandler/react/RNGestureHandlerTouchEvent.kt: (31, 21): 'receiveEvent(Int, String!, WritableMap?): Unit' is deprecated. Deprecated in Java

> Task :react-native-gesture-handler:configureCMakeDebug[arm64-v8a]
C/C++: CMake Warning:
C/C++:   Manually-specified variables were not used by the project:
C/C++:     APP_BUILD_DIR

> Task :react-native-gesture-handler:configureCMakeDebug[armeabi-v7a]
C/C++: CMake Warning:
C/C++:   Manually-specified variables were not used by the project:
C/C++:     APP_BUILD_DIR

> Task :react-native-gesture-handler:configureCMakeDebug[x86]
C/C++: CMake Warning:
C/C++:   Manually-specified variables were not used by the project:
C/C++:     APP_BUILD_DIR

> Task :react-native-gesture-handler:configureCMakeDebug[x86_64]
C/C++: CMake Warning:
C/C++:   Manually-specified variables were not used by the project:
C/C++:     APP_BUILD_DIR

> Task :app:installDebug
Installing APK 'app-debug.apk' on 'Pixel_4_API_29(AVD) - 10' for :app:debug
Unable to install /Users/pauliusguzas/Desktop/renative/renative/packages/template-starter/platformBuilds/template_androidtv/app/build/outputs/apk/debug/app-debug.apk
com.android.ddmlib.InstallException: INSTALL_FAILED_VERSION_DOWNGRADE
        at com.android.ddmlib.internal.DeviceImpl.installRemotePackage(DeviceImpl.java:1373)
        at com.android.ddmlib.internal.DeviceImpl.installPackage(DeviceImpl.java:1199)
        at com.android.ddmlib.internal.DeviceImpl.installPackage(DeviceImpl.java:1175)
        at com.android.ddmlib.internal.DeviceImpl.installPackage(DeviceImpl.java:1164)
        at com.android.build.gradle.internal.testing.ConnectedDevice.installPackage(ConnectedDevice.java:127)
        at com.android.build.gradle.internal.tasks.InstallVariantTask.install(InstallVariantTask.java:164)
        at com.android.build.gradle.internal.tasks.InstallVariantTask.lambda$doTaskAction$1(InstallVariantTask.java:101)
        at com.android.builder.testing.api.DeviceProvider.use(DeviceProvider.java:55)
        at com.android.build.gradle.internal.tasks.InstallVariantTask.doTaskAction(InstallVariantTask.java:96)
        at com.android.build.gradle.internal.tasks.NonIncrementalTask$taskAction$$inlined$recordTaskAction$1.invoke(BaseTask.kt:66)
        at com.android.build.gradle.internal.tasks.Blocks.recordSpan(Blocks.java:51)
        at com.android.build.gradle.internal.tasks.NonIncrementalTask.taskAction(NonIncrementalTask.kt:97)
        at jdk.internal.reflect.GeneratedMethodAccessor748.invoke(Unknown Source)
        at java.base@11.0.11/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at org.gradle.internal.reflect.JavaMethod.invoke(JavaMethod.java:125)
        at org.gradle.api.internal.project.taskfactory.StandardTaskAction.doExecute(StandardTaskAction.java:58)
        at org.gradle.api.internal.project.taskfactory.StandardTaskAction.execute(StandardTaskAction.java:51)
        at org.gradle.api.internal.project.taskfactory.StandardTaskAction.execute(StandardTaskAction.java:29)
        at org.gradle.api.internal.tasks.execution.TaskExecution$3.run(TaskExecution.java:242)
        at org.gradle.internal.operations.DefaultBuildOperationRunner$1.execute(DefaultBuildOperationRunner.java:29)
        at org.gradle.internal.operations.DefaultBuildOperationRunner$1.execute(DefaultBuildOperationRunner.java:26)
        at org.gradle.internal.operations.DefaultBuildOperationRunner$2.execute(DefaultBuildOperationRunner.java:66)
        at org.gradle.internal.operations.DefaultBuildOperationRunner$2.execute(DefaultBuildOperationRunner.java:59)
        at org.gradle.internal.operations.DefaultBuildOperationRunner.execute(DefaultBuildOperationRunner.java:157)
        at org.gradle.internal.operations.DefaultBuildOperationRunner.execute(DefaultBuildOperationRunner.java:59)
        at org.gradle.internal.operations.DefaultBuildOperationRunner.run(DefaultBuildOperationRunner.java:47)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:68)
        at org.gradle.api.internal.tasks.execution.TaskExecution.executeAction(TaskExecution.java:227)
        at org.gradle.api.internal.tasks.execution.TaskExecution.executeActions(TaskExecution.java:210)
        at org.gradle.api.internal.tasks.execution.TaskExecution.executeWithPreviousOutputFiles(TaskExecution.java:193)
        at org.gradle.api.internal.tasks.execution.TaskExecution.execute(TaskExecution.java:166)
        at org.gradle.internal.execution.steps.ExecuteStep.executeInternal(ExecuteStep.java:93)
        at org.gradle.internal.execution.steps.ExecuteStep.access$000(ExecuteStep.java:44)
        at org.gradle.internal.execution.steps.ExecuteStep$1.call(ExecuteStep.java:57)
        at org.gradle.internal.execution.steps.ExecuteStep$1.call(ExecuteStep.java:54)
        at org.gradle.internal.operations.DefaultBuildOperationRunner$CallableBuildOperationWorker.execute(DefaultBuildOperationRunner.java:204)
        at org.gradle.internal.operations.DefaultBuildOperationRunner$CallableBuildOperationWorker.execute(DefaultBuildOperationRunner.java:199)
        at org.gradle.internal.operations.DefaultBuildOperationRunner$2.execute(DefaultBuildOperationRunner.java:66)
        at org.gradle.internal.operations.DefaultBuildOperationRunner$2.execute(DefaultBuildOperationRunner.java:59)
        at org.gradle.internal.operations.DefaultBuildOperationRunner.execute(DefaultBuildOperationRunner.java:157)
        at org.gradle.internal.operations.DefaultBuildOperationRunner.execute(DefaultBuildOperationRunner.java:59)
        at org.gradle.internal.operations.DefaultBuildOperationRunner.call(DefaultBuildOperationRunner.java:53)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor.call(DefaultBuildOperationExecutor.java:73)
        at org.gradle.internal.execution.steps.ExecuteStep.execute(ExecuteStep.java:54)
        at org.gradle.internal.execution.steps.ExecuteStep.execute(ExecuteStep.java:44)
        at org.gradle.internal.execution.steps.RemovePreviousOutputsStep.execute(RemovePreviousOutputsStep.java:67)
        at org.gradle.internal.execution.steps.RemovePreviousOutputsStep.execute(RemovePreviousOutputsStep.java:37)
        at org.gradle.internal.execution.steps.CancelExecutionStep.execute(CancelExecutionStep.java:41)
        at org.gradle.internal.execution.steps.TimeoutStep.executeWithoutTimeout(TimeoutStep.java:74)
        at org.gradle.internal.execution.steps.TimeoutStep.execute(TimeoutStep.java:55)
        at org.gradle.internal.execution.steps.CreateOutputsStep.execute(CreateOutputsStep.java:50)
        at org.gradle.internal.execution.steps.CreateOutputsStep.execute(CreateOutputsStep.java:28)
        at org.gradle.internal.execution.steps.CaptureStateAfterExecutionStep.executeDelegateBroadcastingChanges(CaptureStateAfterExecutionStep.java:100)
        at org.gradle.internal.execution.steps.CaptureStateAfterExecutionStep.execute(CaptureStateAfterExecutionStep.java:72)
        at org.gradle.internal.execution.steps.CaptureStateAfterExecutionStep.execute(CaptureStateAfterExecutionStep.java:50)
        at org.gradle.internal.execution.steps.ResolveInputChangesStep.execute(ResolveInputChangesStep.java:40)
        at org.gradle.internal.execution.steps.ResolveInputChangesStep.execute(ResolveInputChangesStep.java:29)
        at org.gradle.internal.execution.steps.BuildCacheStep.executeWithoutCache(BuildCacheStep.java:166)
        at org.gradle.internal.execution.steps.BuildCacheStep.lambda$execute$1(BuildCacheStep.java:70)
        at org.gradle.internal.Either$Right.fold(Either.java:175)
        at org.gradle.internal.execution.caching.CachingState.fold(CachingState.java:59)
        at org.gradle.internal.execution.steps.BuildCacheStep.execute(BuildCacheStep.java:68)
        at org.gradle.internal.execution.steps.BuildCacheStep.execute(BuildCacheStep.java:46)
        at org.gradle.internal.execution.steps.StoreExecutionStateStep.execute(StoreExecutionStateStep.java:36)
        at org.gradle.internal.execution.steps.StoreExecutionStateStep.execute(StoreExecutionStateStep.java:25)
        at org.gradle.internal.execution.steps.RecordOutputsStep.execute(RecordOutputsStep.java:36)
        at org.gradle.internal.execution.steps.RecordOutputsStep.execute(RecordOutputsStep.java:22)
        at org.gradle.internal.execution.steps.SkipUpToDateStep.executeBecause(SkipUpToDateStep.java:91)
        at org.gradle.internal.execution.steps.SkipUpToDateStep.lambda$execute$2(SkipUpToDateStep.java:55)
        at org.gradle.internal.execution.steps.SkipUpToDateStep.execute(SkipUpToDateStep.java:55)
        at org.gradle.internal.execution.steps.SkipUpToDateStep.execute(SkipUpToDateStep.java:37)
        at org.gradle.internal.execution.steps.ResolveChangesStep.execute(ResolveChangesStep.java:65)
        at org.gradle.internal.execution.steps.ResolveChangesStep.execute(ResolveChangesStep.java:36)
        at org.gradle.internal.execution.steps.legacy.MarkSnapshottingInputsFinishedStep.execute(MarkSnapshottingInputsFinishedStep.java:37)
        at org.gradle.internal.execution.steps.legacy.MarkSnapshottingInputsFinishedStep.execute(MarkSnapshottingInputsFinishedStep.java:27)
        at org.gradle.internal.execution.steps.ResolveCachingStateStep.execute(ResolveCachingStateStep.java:76)
        at org.gradle.internal.execution.steps.ResolveCachingStateStep.execute(ResolveCachingStateStep.java:37)
        at org.gradle.internal.execution.steps.ValidateStep.execute(ValidateStep.java:94)
        at org.gradle.internal.execution.steps.ValidateStep.execute(ValidateStep.java:49)
        at org.gradle.internal.execution.steps.CaptureStateBeforeExecutionStep.execute(CaptureStateBeforeExecutionStep.java:71)
        at org.gradle.internal.execution.steps.CaptureStateBeforeExecutionStep.execute(CaptureStateBeforeExecutionStep.java:45)
        at org.gradle.internal.execution.steps.SkipEmptyWorkStep.executeWithNonEmptySources(SkipEmptyWorkStep.java:177)
        at org.gradle.internal.execution.steps.SkipEmptyWorkStep.execute(SkipEmptyWorkStep.java:81)
        at org.gradle.internal.execution.steps.SkipEmptyWorkStep.execute(SkipEmptyWorkStep.java:53)
        at org.gradle.internal.execution.steps.RemoveUntrackedExecutionStateStep.execute(RemoveUntrackedExecutionStateStep.java:32)
        at org.gradle.internal.execution.steps.RemoveUntrackedExecutionStateStep.execute(RemoveUntrackedExecutionStateStep.java:21)
        at org.gradle.internal.execution.steps.legacy.MarkSnapshottingInputsStartedStep.execute(MarkSnapshottingInputsStartedStep.java:38)
        at org.gradle.internal.execution.steps.LoadPreviousExecutionStateStep.execute(LoadPreviousExecutionStateStep.java:36)
        at org.gradle.internal.execution.steps.LoadPreviousExecutionStateStep.execute(LoadPreviousExecutionStateStep.java:23)
        at org.gradle.internal.execution.steps.CleanupStaleOutputsStep.execute(CleanupStaleOutputsStep.java:75)
        at org.gradle.internal.execution.steps.CleanupStaleOutputsStep.execute(CleanupStaleOutputsStep.java:41)
        at org.gradle.internal.execution.steps.AssignWorkspaceStep.lambda$execute$0(AssignWorkspaceStep.java:32)
        at org.gradle.api.internal.tasks.execution.TaskExecution$4.withWorkspace(TaskExecution.java:287)
        at org.gradle.internal.execution.steps.AssignWorkspaceStep.execute(AssignWorkspaceStep.java:30)
        at org.gradle.internal.execution.steps.AssignWorkspaceStep.execute(AssignWorkspaceStep.java:21)
        at org.gradle.internal.execution.steps.IdentityCacheStep.execute(IdentityCacheStep.java:37)
        at org.gradle.internal.execution.steps.IdentityCacheStep.execute(IdentityCacheStep.java:27)
        at org.gradle.internal.execution.steps.IdentifyStep.execute(IdentifyStep.java:42)
        at org.gradle.internal.execution.steps.IdentifyStep.execute(IdentifyStep.java:31)
        at org.gradle.internal.execution.impl.DefaultExecutionEngine$1.execute(DefaultExecutionEngine.java:64)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeIfValid(ExecuteActionsTaskExecuter.java:146)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.execute(ExecuteActionsTaskExecuter.java:135)
        at org.gradle.api.internal.tasks.execution.FinalizePropertiesTaskExecuter.execute(FinalizePropertiesTaskExecuter.java:46)
        at org.gradle.api.internal.tasks.execution.ResolveTaskExecutionModeExecuter.execute(ResolveTaskExecutionModeExecuter.java:51)
        at org.gradle.api.internal.tasks.execution.SkipTaskWithNoActionsExecuter.execute(SkipTaskWithNoActionsExecuter.java:57)
        at org.gradle.api.internal.tasks.execution.SkipOnlyIfTaskExecuter.execute(SkipOnlyIfTaskExecuter.java:74)
        at org.gradle.api.internal.tasks.execution.CatchExceptionTaskExecuter.execute(CatchExceptionTaskExecuter.java:36)
        at org.gradle.api.internal.tasks.execution.EventFiringTaskExecuter$1.executeTask(EventFiringTaskExecuter.java:77)
        at org.gradle.api.internal.tasks.execution.EventFiringTaskExecuter$1.call(EventFiringTaskExecuter.java:55)
        at org.gradle.api.internal.tasks.execution.EventFiringTaskExecuter$1.call(EventFiringTaskExecuter.java:52)
        at org.gradle.internal.operations.DefaultBuildOperationRunner$CallableBuildOperationWorker.execute(DefaultBuildOperationRunner.java:204)
        at org.gradle.internal.operations.DefaultBuildOperationRunner$CallableBuildOperationWorker.execute(DefaultBuildOperationRunner.java:199)
        at org.gradle.internal.operations.DefaultBuildOperationRunner$2.execute(DefaultBuildOperationRunner.java:66)
        at org.gradle.internal.operations.DefaultBuildOperationRunner$2.execute(DefaultBuildOperationRunner.java:59)
        at org.gradle.internal.operations.DefaultBuildOperationRunner.execute(DefaultBuildOperationRunner.java:157)
        at org.gradle.internal.operations.DefaultBuildOperationRunner.execute(DefaultBuildOperationRunner.java:59)
        at org.gradle.internal.operations.DefaultBuildOperationRunner.call(DefaultBuildOperationRunner.java:53)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor.call(DefaultBuildOperationExecutor.java:73)
        at org.gradle.api.internal.tasks.execution.EventFiringTaskExecuter.execute(EventFiringTaskExecuter.java:52)
        at org.gradle.execution.plan.LocalTaskNodeExecutor.execute(LocalTaskNodeExecutor.java:42)
        at org.gradle.execution.taskgraph.DefaultTaskExecutionGraph$InvokeNodeExecutorsAction.execute(DefaultTaskExecutionGraph.java:338)
        at org.gradle.execution.taskgraph.DefaultTaskExecutionGraph$InvokeNodeExecutorsAction.execute(DefaultTaskExecutionGraph.java:325)
        at org.gradle.execution.taskgraph.DefaultTaskExecutionGraph$BuildOperationAwareExecutionAction.execute(DefaultTaskExecutionGraph.java:318)
        at org.gradle.execution.taskgraph.DefaultTaskExecutionGraph$BuildOperationAwareExecutionAction.execute(DefaultTaskExecutionGraph.java:304)
        at org.gradle.execution.plan.DefaultPlanExecutor$ExecutorWorker.execute(DefaultPlanExecutor.java:463)
        at org.gradle.execution.plan.DefaultPlanExecutor$ExecutorWorker.run(DefaultPlanExecutor.java:380)
        at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:64)
        at org.gradle.internal.concurrent.ManagedExecutorImpl$1.run(ManagedExecutorImpl.java:49)

> Task :app:installDebug FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:installDebug'.
> java.util.concurrent.ExecutionException: com.android.builder.testing.api.DeviceException: com.android.ddmlib.InstallException: INSTALL_FAILED_VERSION_DOWNGRADE

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.

* Get more help at https://help.gradle.org

Deprecated Gradle features were used in this build, making it incompatible with Gradle 9.0.

You can use '--warning-mode all' to show the individual deprecation warnings and determine if they come from your own scripts or plugins.

See https://docs.gradle.org/8.0.1/userguide/command_line_interface.html#sec:command_line_warnings

BUILD FAILED in 56s
79 actionable tasks: 23 executed, 56 up-to-date

info 💡 Tip: Make sure that you have set up your development environment correctly, by running react-native doctor. To read more about doctor command visit: https://github.com/react-native-community/cli/blob/main/packages/cli-doctor/README.md#doctor

error Failed to build the app.
Error: Command failed with exit code 1: ./gradlew app:installDebug -x lint -PreactNativeDevServerPort=8084
    at makeError (/Users/pauliusguzas/Desktop/renative/renative/node_modules/execa/lib/error.js:60:11)
    at Function.module.exports.sync (/Users/pauliusguzas/Desktop/renative/renative/node_modules/execa/index.js:194:17)
    at build (/Users/pauliusguzas/Desktop/renative/renative/node_modules/@react-native-community/cli-platform-android/build/commands/buildAndroid/index.js:95:22)
    at runOnSpecificDevice (/Users/pauliusguzas/Desktop/renative/renative/node_modules/@react-native-community/cli-platform-android/build/commands/runAndroid/index.js:205:33)
    at buildAndRun (/Users/pauliusguzas/Desktop/renative/renative/node_modules/@react-native-community/cli-platform-android/build/commands/runAndroid/index.js:167:12)
    at Object.runAndroid [as func] (/Users/pauliusguzas/Desktop/renative/renative/node_modules/@react-native-community/cli-platform-android/build/commands/runAndroid/index.js:100:10)
    at Command.handleAction (/Users/pauliusguzas/Desktop/renative/renative/node_modules/@react-native-community/cli/build/index.js:111:9)
info Run CLI with --verbose flag for more details.
COMMAND:

npx react-native run-android --mode=Debug --no-packager --deviceId=emulator-5556

FAILED with ERROR:

Command failed with exit code 1: npx react-native run-android --mode=Debug --no-packager --deviceId=emulator-5556

Error: Command failed with exit code 1: npx react-native run-android --mode=Debug --no-packager --deviceId=emulator-5556
    at makeError (/Users/pauliusguzas/Desktop/renative/renative/node_modules/execa/lib/error.js:60:11)
    at handlePromise (/Users/pauliusguzas/Desktop/renative/renative/node_modules/execa/index.js:118:26)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)



 $ rnv run -p androidtv - Done! 🚀
┌──────────────────────────────────────────────────────────────────────────────┐
│  🚀  SUMMARY | 10/24/2023, 11:31:21 AM                                       │
│  $ rnv run -p androidtv                                                      │
├──────────────────────────────────────────────────────────────────────────────┤
│  ReNative Version: 1.0.0-canary.7                                            │
│  Project Name ($package.name): @rnv/template-starter                         │
│  Project Version ($package.version): 1.0.0-canary.7                          │
│  Workspace ($.workspaceID): rnv                                              │
│  Platform (-p): androidtv                                                    │
│  Engine ($.platforms.androidtv.engine): engine-rn-tvos                       │
│  App Config (-c): template                                                   │
│  Build Scheme (-s): debug                                                    │
│  Target (-t): Android_TV_720p_API_22                                         │
│  Supported Platforms: androidtv                                              │
│  Master Template: @rnv/template-starter                                      │
│  Env Info: darwin | x64 | node v18.16.0                                      │
│  Executed Time: 0h:1m:11s:93ms                                               │
│                                                                              │
│ You are trying to run global rnv command in your current project.
│ This might lead to unexpected behaviour.
│ Run your rnv command with npx prefix:
│ npx rnv run -p androidtv
│                                                                              │
│  Project location:                                                           │
│  ./platformBuilds/template_androidtv                                         │
└──────────────────────────────────────────────────────────────────────────────┘
pauliusguzas@MBP-de-Flexn template-starter %
```

**Expected behavior**
Template app should start in Android simulator

**Desktop (please complete the following information):**

-   OS: Ventura 13.5.2 (Intel)
-   Node Version 18.16.0
-   RNV Version 1.0.0-canary.7
-   rnv/template-starter Version 1.0.0-canary.7

**Comment by GabrieleKaceviciute** [comment]
AndroidTV and androidwear works for me (on macos).
On android I get this error (`rnv run -p android`):
```
<=======------> 58% EXECUTING [9s]
> Task :app:compileDebugJavaWithJavac FAILED
/Users/gabriele/Desktop/renative/packages/template-starter/platformBuilds/template_android/app/src/main/java/renative/helloworld/MainApplication.java:19: error: cannot find symbol
          return BuildConfig.DEBUG;gabriele/Library/Caches/TemporaryItems/avd/running/pid_34570.ini
                 ^
  symbol: variable BuildConfig
/Users/gabriele/Desktop/renative/packages/template-starter/platformBuilds/template_android/app/src/main/java/renative/helloworld/MainApplication.java:38: error: cannot find symbol
          return BuildConfig.IS_NEW_ARCHITECTURE_ENABLED;
                 ^
  symbol: variable BuildConfig
/Users/gabriele/Desktop/renative/packages/template-starter/platformBuilds/template_android/app/src/main/java/renative/helloworld/MainApplication.java:43: error: cannot find symbol
          return BuildConfig.IS_HERMES_ENABLED;
                 ^
  symbol: variable BuildConfig
/Users/gabriele/Desktop/renative/packages/template-starter/platformBuilds/template_android/app/src/main/java/renative/helloworld/MainApplication.java:56: error: cannot find symbol
    if (BuildConfig.IS_NEW_ARCHITECTURE_ENABLED) {
        ^
  symbol:   variable BuildConfig
  location: class MainApplication
/Users/gabriele/Desktop/renative/packages/template-starter/platformBuilds/template_android/app/src/main/java/renative/helloworld/MainApplication.java:56: error: illegal parenthesized expression
    if (BuildConfig.IS_NEW_ARCHITECTURE_ENABLED) {
       ^
5 errors

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:compileDebugJavaWithJavac'.
> Compilation failed; see the compiler error output for details.

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.

* Get more help at https://help.gradle.org

Deprecated Gradle features were used in this build, making it incompatible with Gradle 9.0.

You can use '--warning-mode all' to show the individual deprecation warnings and determine if they come from your own scripts or plugins.

See https://docs.gradle.org/8.0.1/userguide/command_line_interface.html#sec:command_line_warnings

BUILD FAILED in 10s
45 actionable tasks: 7 executed, 38 up-to-date
⠧ INFO    | Advertising in: /Users/gabriele/Library/Caches/TemporaryItems/avd/running/pid_34570.ini
info 💡 Tip: Make sure that you have set up your development environment correctly, by running react-native doctor. To read more about doctor command visit: https://github.com/react-native-community/cli/blob/main/packages/cli-doctor/README.md#doctor

error Failed to build the app.
Error: Command failed with exit code 1: ./gradlew app:installDebug -x lint -PreactNativeDevServerPort=8083
    at makeError (/Users/gabriele/Desktop/renative/node_modules/execa/lib/error.js:60:11)
    at Function.module.exports.sync (/Users/gabriele/Desktop/renative/node_modules/execa/index.js:194:17)
    at build (/Users/gabriele/Desktop/renative/node_modules/@react-native-community/cli-platform-android/build/commands/buildAndroid/index.js:95:22)
    at runOnSpecificDevice (/Users/gabriele/Desktop/renative/node_modules/@react-native-community/cli-platform-android/build/commands/runAndroid/index.js:205:33)
    at buildAndRun (/Users/gabriele/Desktop/renative/node_modules/@react-native-community/cli-platform-android/build/commands/runAndroid/index.js:167:12)
    at Object.runAndroid [as func] (/Users/gabriele/Desktop/renative/node_modules/@react-native-community/cli-platform-android/build/commands/runAndroid/index.js:100:10)
    at Command.handleAction (/Users/gabriele/Desktop/renative/node_modules/@react-native-community/cli/build/index.js:111:9)
info Run CLI with --verbose flag for more details.
COMMAND:

npx react-native run-android --mode=Debug --no-packager --deviceId=emulator-5554

FAILED with ERROR:

Command failed with exit code 1: npx react-native run-android --mode=Debug --no-packager --deviceId=emulator-5554

Error: Command failed with exit code 1: npx react-native run-android --mode=Debug --no-packager --deviceId=emulator-5554
    at makeError (/Users/gabriele/Desktop/renative/node_modules/execa/lib/error.js:60:11)
    at handlePromise (/Users/gabriele/Desktop/renative/node_modules/execa/index.js:118:26)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)



 $ rnv run -p android - Done! 🚀
┌──────────────────────────────────────────────────────────────────────────────┐
│  🚀  SUMMARY | 10/24/2023, 12:19:28 PM                                       │
│  $ rnv run -p android                                                        │
├──────────────────────────────────────────────────────────────────────────────┤
│  ReNative Version: 1.0.0-canary.7                                            │
│  Project Name ($package.name): @rnv/template-starter                         │
│  Project Version ($package.version): 1.0.0-canary.7                          │
│  Workspace ($.workspaceID): rnv                                              │
│  Platform (-p): android                                                      │
│  Engine ($.platforms.android.engine): engine-rn                              │
│  App Config (-c): template                                                   │
│  Build Scheme (-s): debug                                                    │
│  Target (-t): android                                                        │
│  Supported Platforms: android                                                │
│  Master Template: @rnv/template-starter                                      │
│  Env Info: darwin | x64 | node v18.14.2                                      │
│  Executed Time: 0h:0m:43s:861ms                                              │
│                                                                              │
│ [ warn ] [configure] _mergeNodeParameters: nodeParamsExt value is null
│ [ success ] [run] Found active emulator! emulator-5554. Will use it
│ You are trying to run global rnv command in your current project.
│ This might lead to unexpected behaviour.
│ Run your rnv command with npx prefix:
│ npx rnv run -p android
│                                                                              │
│  Project location:                                                           │
│  ./platformBuilds/template_android                                           │
└──────────────────────────────────────────────────────────────────────────────┘
➜  ~/Desktop/renative/packages/template-starter git:(2daeade0c)
```

OS: Ventura 13.5.2 (intel)
Node: 18.14.2
RNV Version 1.0.0-canary.7

**Comment by GabrieleKaceviciute** [comment]
not reproduced on 1.0.0-feat-pin-cli.2
