### ISSUE TITLE
[FireTV] Can't run template starter

### ISSUE THREAD

**Issue by pauliusguzas** [flexn-io/renative#1197]
**Describe the bug**
Can't run firetv (sanity_1.0.0-2 tag)

**To Reproduce**
1. go to template-starter package
2. run `rnv run -p firetv`

```
[ info ] [run] Found device Android_TV_1080p_API_27:emulator-5556!
[ task ] [run] _runGradleApp[1]
✔ Executing: npx react-native run-android --mode=Debug --no-packager --deviceId=emulator-5556

error Command failed with exit code 1: ./gradlew tasks

FAILURE: Build failed with an exception.

* Where:
Build file '/Users/pauliusguzas/Desktop/renative/renative/packages/template-starter/platformBuilds/template_firetv/app/build.gradle' line: 22

* What went wrong:
A problem occurred evaluating project ':app'.
> Could not read script '/Users/pauliusguzas/Desktop/renative/renative/node_modules/react-native-tvos/react.gradle' as it does not exist.

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 920ms
Configuration on demand is an incubating feature.

> Configure project :app
Warning: The 'kotlin-android-extensions' Gradle plugin is deprecated. Please use this migration guide (https://goo.gle/kotlin-android-extensions-deprecation) to start working with View Binding (https://developer.android.com/topic/libraries/view-binding) and the 'kotlin-parcelize' plugin.
Error: Command failed with exit code 1: ./gradlew tasks

FAILURE: Build failed with an exception.

* Where:
Build file '/Users/pauliusguzas/Desktop/renative/renative/packages/template-starter/platformBuilds/template_firetv/app/build.gradle' line: 22

* What went wrong:
A problem occurred evaluating project ':app'.
> Could not read script '/Users/pauliusguzas/Desktop/renative/renative/node_modules/react-native-tvos/react.gradle' as it does not exist.

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 920ms
Configuration on demand is an incubating feature.

> Configure project :app
Warning: The 'kotlin-android-extensions' Gradle plugin is deprecated. Please use this migration guide (https://goo.gle/kotlin-android-extensions-deprecation) to start working with View Binding (https://developer.android.com/topic/libraries/view-binding) and the 'kotlin-parcelize' plugin.
    at makeError (/Users/pauliusguzas/Desktop/renative/renative/node_modules/execa/lib/error.js:60:11)
    at Function.module.exports.sync (/Users/pauliusguzas/Desktop/renative/renative/node_modules/execa/index.js:194:17)
    at getGradleTasks (/Users/pauliusguzas/Desktop/renative/renative/node_modules/@react-native-community/cli-platform-android/build/commands/runAndroid/listAndroidTasks.js:53:32)
    at getTaskNames (/Users/pauliusguzas/Desktop/renative/renative/node_modules/@react-native-community/cli-platform-android/build/commands/runAndroid/getTaskNames.js:21:73)
    at runOnSpecificDevice (/Users/pauliusguzas/Desktop/renative/renative/node_modules/@react-native-community/cli-platform-android/build/commands/runAndroid/index.js:184:55)
    at buildAndRun (/Users/pauliusguzas/Desktop/renative/renative/node_modules/@react-native-community/cli-platform-android/build/commands/runAndroid/index.js:167:12)
    at Object.runAndroid [as func] (/Users/pauliusguzas/Desktop/renative/renative/node_modules/@react-native-community/cli-platform-android/build/commands/runAndroid/index.js:100:10)
    at Command.handleAction (/Users/pauliusguzas/Desktop/renative/renative/node_modules/@react-native-community/cli/build/index.js:111:9)
COMMAND:

npx react-native run-android --mode=Debug --no-packager --deviceId=emulator-5556

FAILED with ERROR:

Command failed with exit code 1: npx react-native run-android --mode=Debug --no-packager --deviceId=emulator-5556

Error: Command failed with exit code 1: npx react-native run-android --mode=Debug --no-packager --deviceId=emulator-5556
    at makeError (/Users/pauliusguzas/Desktop/renative/renative/node_modules/execa/lib/error.js:60:11)
    at handlePromise (/Users/pauliusguzas/Desktop/renative/renative/node_modules/execa/index.js:118:26)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)



 $ rnv run -p firetv - Done! 🚀
┌──────────────────────────────────────────────────────────────────────────────┐
│  🚀  SUMMARY | 10/24/2023, 11:40:11 AM                                       │
│  $ rnv run -p firetv                                                         │
├──────────────────────────────────────────────────────────────────────────────┤
│  ReNative Version: 1.0.0-canary.7                                            │
│  Project Name ($package.name): @rnv/template-starter                         │
│  Project Version ($package.version): 1.0.0-canary.7                          │
│  Workspace ($.workspaceID): rnv                                              │
│  Platform (-p): firetv                                                       │
│  Engine ($.platforms.firetv.engine): engine-rn-tvos                          │
│  App Config (-c): template                                                   │
│  Build Scheme (-s): debug                                                    │
│  Target (-t): Android_TV_720p_API_22                                         │
│  Supported Platforms: firetv                                                 │
│  Master Template: @rnv/template-starter                                      │
│  Env Info: darwin | x64 | node v18.16.0                                      │
│  Executed Time: 0h:0m:9s:668ms                                               │
│                                                                              │
│ [ error ] [configure] Cannot write file. source path doesn't exists: /Users/pauliusguzas/Desktop/renative/renative/packages/engine-rn-tvos/templates/platforms/firetv/app/src/main/java/rnv_template/MainActivity.java.tpl
│ [ error ] [configure] Cannot write file. source path doesn't exists: /Users/pauliusguzas/Desktop/renative/renative/packages/engine-rn-tvos/templates/platforms/firetv/app/src/main/java/rnv_template/MainApplication.java.tpl
│ [ error ] [configure] Cannot write file. source path doesn't exists: /Users/pauliusguzas/Desktop/renative/renative/packages/engine-rn-tvos/templates/platforms/firetv/app/src/main/java/rnv_template/SplashActivity.java.tpl
│ [ error ] [configure] Cannot write file. source path doesn't exists: /Users/pauliusguzas/Desktop/renative/renative/packages/engine-rn-tvos/templates/platforms/firetv/app/src/debug/java/rnv_template/ReactNativeFlipper.java.tpl
│ [ error ] [configure] Cannot write file. source path doesn't exists: /Users/pauliusguzas/Desktop/renative/renative/packages/engine-rn-tvos/templates/platforms/firetv/app/src/release/java/rnv_template/ReactNativeFlipper.java.tpl
│ You are trying to run global rnv command in your current project.
│ This might lead to unexpected behaviour.
│ Run your rnv command with npx prefix:
│ npx rnv run -p firetv
│                                                                              │
│  Project location:                                                           │
│  ./platformBuilds/template_firetv                                            │
└──────────────────────────────────────────────────────────────────────────────┘
pauliusguzas@MBP-de-Flexn template-starter
```

**Expected behavior**
Template app should start in Androidtv simulator

**Desktop (please complete the following information):**

-   OS: Ventura 13.5.2 (Intel)
-   Node Version 18.16.0
-   RNV Version 1.0.0-canary.7
-   rnv/template-starter Version 1.0.0-canary.7
***
-   OS: Windows 10 Pro
-   Node Version 18.14.2
-   RNV Version 1.0.0-canary.7
-   rnv/template-starter Version 1.0.0-canary.7
***
-   OS: macOS Big Sur 11.6
-   Node Version 18.14.2
-   RNV Version 1.0.0-canary.7
-   rnv/template-starter Version 1.0.0-canary.7

**Comment by GabrieleKaceviciute** [comment]
1.0.0-canary.8 - not reproduced on macos (Intel and M1)
Issue on windows moved to separate ticket - https://github.com/flexn-io/renative/issues/1199
