### ISSUE TITLE
[android, androidTV, androidwear, fireTV] can't run/build/export template starter on windows

### ISSUE THREAD

**Issue by GabrieleKaceviciute** [flexn-io/renative#1199]
**Describe the bug**
Can't run/build/export all android platforms (sanity_1.0.0-2 tag)

**To Reproduce**
1. go to template-starter package
2. run `rnv run -p android` ->  another terminal window opens and error appears 

**Expected behavior**
Template app should start in Android simulator

**Screenshots or copy&paste**
```
[ task ] [run] _runGradleApp[1]
✔ Executing: npx react-native run-android --mode=Debug --no-packager --deviceId=emulator-5554

| Executing: C:\Users\dev\AppData\Local\Android\sdk\emulator\emulator.exe -avd "Android_TV_1080p_API_29"error Command failed with exit code 1: gradlew.bat tasks

FAILURE: Build failed with an exception.

* Where:
Settings file 'C:\Users\dev\Desktop\renative\packages\template-starter\platformBuilds\template_androidtv\settings.gradle' line: 2

* What went wrong:
Could not compile settings file 'C:\Users\dev\Desktop\renative\packages\template-starter\platformBuilds\template_androidtv\settings.gradle'.
> startup failed:
  settings file 'C:\Users\dev\Desktop\renative\packages\template-starter\platformBuilds\template_androidtv\settings.gradle': 2: Unexpected character: '"' @ line 2, column 18.
     apply from: file("..\..\..\..\node_modules\@react-native-community\cli-platform-android/native_modules.gradle"); applyNativeModulesSettingsGradle(settings)
                      ^

  1 error


* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 3s.
Error: Command failed with exit code 1: gradlew.bat tasks

FAILURE: Build failed with an exception.

* Where:
Settings file 'C:\Users\dev\Desktop\renative\packages\template-starter\platformBuilds\template_androidtv\settings.gradle' line: 2

* What went wrong:
Could not compile settings file 'C:\Users\dev\Desktop\renative\packages\template-starter\platformBuilds\template_androidtv\settings.gradle'.
> startup failed:
  settings file 'C:\Users\dev\Desktop\renative\packages\template-starter\platformBuilds\template_androidtv\settings.gradle': 2: Unexpected character: '"' @ line 2, column 18.
     apply from: file("..\..\..\..\node_modules\@react-native-community\cli-platform-android/native_modules.gradle"); applyNativeModulesSettingsGradle(settings)
                      ^

  1 error


* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 3s
    at makeError (C:\Users\dev\Desktop\renative\node_modules\execa\lib\error.js:60:11)
    at Function.module.exports.sync (C:\Users\dev\Desktop\renative\node_modules\execa\index.js:194:17)
    at getGradleTasks (C:\Users\dev\Desktop\renative\node_modules\@react-native-community\cli-platform-android\build\commands\runAndroid\listAndroidTasks.js:53:32)
    at getTaskNames (C:\Users\dev\Desktop\renative\node_modules\@react-native-community\cli-platform-android\build\commands\runAndroid\getTaskNames.js:21:73)
    at runOnSpecificDevice (C:\Users\dev\Desktop\renative\node_modules\@react-native-community\cli-platform-android\build\commands\runAndroid\index.js:184:55)
    at buildAndRun (C:\Users\dev\Desktop\renative\node_modules\@react-native-community\cli-platform-android\build\commands\runAndroid\index.js:167:12)
    at Object.runAndroid [as func] (C:\Users\dev\Desktop\renative\node_modules\@react-native-community\cli-platform-android\build\commands\runAndroid\index.js:100:10)
    at Command.handleAction (C:\Users\dev\Desktop\renative\node_modules\@react-native-community\cli\build\index.js:111:9)
/ Executing: C:\Users\dev\AppData\Local\Android\sdk\emulator\emulator.exe -avd "Android_TV_1080p_API_29"COMMAND:

npx react-native run-android --mode=Debug --no-packager --deviceId=emulator-5554

FAILED with ERROR:

Command failed with exit code 1: npx react-native run-android --mode=Debug --no-packager --deviceId=emulator-5554

Error: Command failed with exit code 1: npx react-native run-android --mode=Debug --no-packager --deviceId=emulator-5554
    at makeError (C:\Users\dev\Desktop\renative\node_modules\execa\lib\error.js:60:11)
    at handlePromise (C:\Users\dev\Desktop\renative\node_modules\execa\index.js:118:26)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)



 $ rnv run -p androidtv - Done! RNV
┌──────────────────────────────────────────────────────────────────────────────┐
│  RNV  SUMMARY | 24/10/2023, 12:18:56                                         │
│  $ rnv run -p androidtv                                                      │
├──────────────────────────────────────────────────────────────────────────────┤
│  ReNative Version: 1.0.0-canary.7                                            │
│  Project Name ($package.name): @rnv/template-starter                         │
│  Project Version ($package.version): 1.0.0-canary.7                          │
│  Workspace ($.workspaceID): rnv                                              │
│  Platform (-p): androidtv                                                    │
│  Engine ($.platforms.androidtv.engine): engine-rn-tvos                       │
│  App Config (-c): template                                                   │
│  Build Scheme (-s): debug                                                    │
│  Target (-t): Android_TV_1080p_API_29                                        │
│  Supported Platforms: androidtv                                              │
│  Master Template: @rnv/template-starter                                      │
│  Env Info: win32 | x64 | node v18.14.2                                       │
│  Executed Time: 0h:0m:27s:497ms                                              │
│                                                                              │
│ [ success ] [run] Found active emulator! emulator-5554. Will use it
│ You are trying to run global rnv command in your current project.
│ This might lead to unexpected behaviour.
│ Run your rnv command with npx prefix:
│ npx rnv run -p androidtv
│                                                                              │
│  Project location:                                                           │
│  C:\Users\dev\Desktop\renative\packages\template-starter\platformBuilds\template_androidtv
└──────────────────────────────────────────────────────────────────────────────┘
PS C:\Users\dev\Desktop\renative\packages\template-starter>
```

**Desktop (please complete the following information):**

-   OS: Windows 10 Pro
-   Node Version 18.14.2
-   RNV Version 1.0.0-canary.7
-   rnv/template-starter Version 1.0.0-canary.7

**Comment by ElenaDiachenko** [comment]
Should be fixed in thisPR https://github.com/flexn-io/renative/pull/1301

**Comment by GabrieleKaceviciute** [comment]
1.0.0-rc.8

````
[ task ] <= [build] <= package
[ task ] [build] buildAndroid[1]
× FAILED: npx react-native build-android --mode=Debug --no-packager --tasks assembleDebug
┌──────────────────────────────────────────────────────────────────────────────┐
│  RNV  SUMMARY | 05/01/2024, 14:06:40                                         │
│  $ npx rnv build -p android                                                  │
├──────────────────────────────────────────────────────────────────────────────┤
│  ReNative Version: 1.0.0-rc.8                                                │
│  Project Name ($package.name): @rnv/template-starter                         │
│  Project Version ($package.version): 1.0.0-rc.8                              │
│  Workspace ($.workspaceID): rnv                                              │
│  Platform (-p): android                                                      │
│  Engine ($.platforms.android.engine): engine-rn                              │
│  App Config (-c): template                                                   │
│  Build Scheme (-s): debug                                                    │
│  Target (-t): Pixel_4_API_29                                                 │
│  Supported Platforms: android                                                │
│  Env Info: win32 | x64 | node v18.19.0                                       │
│  Executed Time: 0h:0m:16s:346ms                                              │
│                                                                              │
│ [ error ] [build] COMMAND:

npx react-native build-android --mode=Debug --no-packager --tasks assembleDebug

FAILED with ERROR:

FAILURE: Build failed with an exception.

* What went wrong:
A problem occurred configuring root project '@rnv-template-starter'.
> Could not determine the dependencies of null.
   > Could not resolve all task dependencies for configuration ':classpath'.
      > Could not find com.android.tools.build:gradle:.
        Required by:
            project :
      > Could not resolve com.facebook.react:react-native-gradle-plugin.
        Required by:
            project :
         > No matching variant of project :gradle-plugin was found. The consumer was configured to find a library for use during runtime, compatible with Java 8, packaged as a jar, and its dependencies declared externally, as well as attribute 'org.gradle.plugin.api-version' with value '8.0.1' but:
             - Variant 'apiElements' capability com.facebook.react:react-native-gradle-plugin:unspecified declares a library, packaged as a jar, and its dependencies declared externally:
                 - Incompatible because this component declares a component for use during compile-time, compatible with Java 11 and the consumer needed a component for use during runtime, compatible with Java 8
                 - Other compatible attribute:
                     - Doesn't say anything about org.gradle.plugin.api-version (required '8.0.1')
             - Variant 'mainSourceElements' capability com.facebook.react:react-native-gradle-plugin:unspecified declares a component, and its dependencies declared externally:
                 - Incompatible because this component declares a component of category 'verification' and the consumer needed a library
                 - Other compatible attributes:
                     - Doesn't say anything about its target Java version (required compatibility with Java 8)
                     - Doesn't say anything about its elements (required them packaged as a jar)
                     - Doesn't say anything about org.gradle.plugin.api-version (required '8.0.1')
                     - Doesn't say anything about its usage (required runtime)
             - Variant 'runtimeElements' capability com.facebook.react:react-native-gradle-plugin:unspecified declares a library for use during runtime, packaged as a jar, and its dependencies declared externally:
                 - Incompatible because this component declares a component, compatible with Java 11 and the consumer needed a component, compatible with Java 8
                 - Other compatible attribute:
                     - Doesn't say anything about org.gradle.plugin.api-version (required '8.0.1')
             - Variant 'testResultsElementsForTest' capability com.facebook.react:react-native-gradle-plugin:unspecified:
                 - Incompatible because this component declares a component of category 'verification' and the consumer needed a library
                 - Other compatible attributes:
                     - Doesn't say anything about how its dependencies are found (required its dependencies declared externally)
                     - Doesn't say anything about its target Java version (required compatibility with Java 8)
                     - Doesn't say anything about its elements (required them packaged as a jar)
                     - Doesn't say anything about org.gradle.plugin.api-version (required '8.0.1')
                     - Doesn't say anything about its usage (required runtime)

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 8s

info 💡 Tip: Make sure that you have set up your development environment correctly, by running react-native doctor. To read more about doctor command visit: https://github.com/react-native-community/cli/blob/main/packages/cli-doctor/README.md#doctor

error Failed to build the app.
Error: Command failed with exit code 1: gradlew.bat app:assembleDebug
    at makeError (C:\Users\dev\Desktop\renative\node_modules\execa\lib\error.js:60:11)
    at Function.module.exports.sync (C:\Users\dev\Desktop\renative\node_modules\execa\index.js:194:17)
    at build (C:\Users\dev\Desktop\renative\node_modules\@react-native-community\cli-platform-android\build\commands\buildAndroid\index.js:95:22)
    at Object.buildAndroid [as func] (C:\Users\dev\Desktop\renative\node_modules\@react-native-community\cli-platform-android\build\commands\buildAndroid\index.js:87:10)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at Command.handleAction (C:\Users\dev\Desktop\renative\node_modules\@react-native-community\cli\build\index.js:111:9)
info Run CLI with --verbose flag for more details.

Command failed with exit code 1: npx react-native build-android --mode=Debug --no-packager --tasks assembleDebug
warn Both "tasks" and "mode" parameters were passed to "build" command. Using "tasks" for building the app.

FAILURE: Build failed with an exception.

* What went wrong:
A problem occurred configuring root project '@rnv-template-starter'.
> Could not determine the dependencies of null.
   > Could not resolve all task dependencies for configuration ':classpath'.
      > Could not find com.android.tools.build:gradle:.
        Required by:
            project :
      > Could not resolve com.facebook.react:react-native-gradle-plugin.
        Required by:
            project :
         > No matching variant of project :gradle-plugin was found. The consumer was configured to find a library for use during runtime, compatible with Java 8, packaged as a jar, and its dependencies declared externally, as well as attribute 'org.gradle.plugin.api-version' with value '8.0.1' but:
             - Variant 'apiElements' capability com.facebook.react:react-native-gradle-plugin:unspecified declares a library, packaged as a jar, and its dependencies declared externally:
                 - Incompatible because this component declares a component for use during compile-time, compatible with Java 11 and the consumer needed a component for use during runtime, compatible with Java 8
                 - Other compatible attribute:
                     - Doesn't say anything about org.gradle.plugin.api-version (required '8.0.1')
             - Variant 'mainSourceElements' capability com.facebook.react:react-native-gradle-plugin:unspecified declares a component, and its dependencies declared externally:
                 - Incompatible because this component declares a component of category 'verification' and the consumer needed a library
                 - Other compatible attributes:
                     - Doesn't say anything about its target Java version (required compatibility with Java 8)
                     - Doesn't say anything about its elements (required them packaged as a jar)
                     - Doesn't say anything about org.gradle.plugin.api-version (required '8.0.1')
                     - Doesn't say anything about its usage (required runtime)
             - Variant 'runtimeElements' capability com.facebook.react:react-native-gradle-plugin:unspecified declares a library for use during runtime, packaged as a jar, and its dependencies declared externally:
                 - Incompatible because this component declares a component, compatible with Java 11 and the consumer needed a component, compatible with Java 8
                 - Other compatible attribute:
                     - Doesn't say anything about org.gradle.plugin.api-version (required '8.0.1')
             - Variant 'testResultsElementsForTest' capability com.facebook.react:react-native-gradle-plugin:unspecified:
                 - Incompatible because this component declares a component of category 'verification' and the consumer needed a library
                 - Other compatible attributes:
                     - Doesn't say anything about how its dependencies are found (required its dependencies declared externally)
                     - Doesn't say anything about its target Java version (required compatibility with Java 8)
                     - Doesn't say anything about its elements (required them packaged as a jar)
                     - Doesn't say anything about org.gradle.plugin.api-version (required '8.0.1')
                     - Doesn't say anything about its usage (required runtime)

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 8s
error Failed to build the app.
info Building the app...

info 💡 Tip: Make sure that you have set up your development environment correctly, by running react-native doctor. To read more about doctor command visit: https://github.com/react-native-community/cli/blob/main/packages/cli-doctor/README.md#doctor

Error: Command failed with exit code 1: gradlew.bat app:assembleDebug
    at makeError (C:\Users\dev\Desktop\renative\node_modules\execa\lib\error.js:60:11)
    at Function.module.exports.sync (C:\Users\dev\Desktop\renative\node_modules\execa\index.js:194:17)
    at build (C:\Users\dev\Desktop\renative\node_modules\@react-native-community\cli-platform-android\build\commands\buildAndroid\index.js:95:22)
    at Object.buildAndroid [as func] (C:\Users\dev\Desktop\renative\node_modules\@react-native-community\cli-platform-android\build\commands\buildAndroid\index.js:87:10)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at Command.handleAction (C:\Users\dev\Desktop\renative\node_modules\@react-native-community\cli\build\index.js:111:9)
info Run CLI with --verbose flag for more details.

warn Both "tasks" and "mode" parameters were passed to "build" command. Using "tasks" for building the app.

FAILURE: Build failed with an exception.

* What went wrong:
A problem occurred configuring root project '@rnv-template-starter'.
> Could not determine the dependencies of null.
   > Could not resolve all task dependencies for configuration ':classpath'.
      > Could not find com.android.tools.build:gradle:.
        Required by:
            project :
      > Could not resolve com.facebook.react:react-native-gradle-plugin.
        Required by:
            project :
         > No matching variant of project :gradle-plugin was found. The consumer was configured to find a library for use during runtime, compatible with Java 8, packaged as a jar, and its dependencies declared externally, as well as attribute 'org.gradle.plugin.api-version' with value '8.0.1' but:
             - Variant 'apiElements' capability com.facebook.react:react-native-gradle-plugin:unspecified declares a library, packaged as a jar, and its dependencies declared externally:
                 - Incompatible because this component declares a component for use during compile-time, compatible with Java 11 and the consumer needed a component for use during runtime, compatible with Java 8
                 - Other compatible attribute:
                     - Doesn't say anything about org.gradle.plugin.api-version (required '8.0.1')
             - Variant 'mainSourceElements' capability com.facebook.react:react-native-gradle-plugin:unspecified declares a component, and its dependencies declared externally:
                 - Incompatible because this component declares a component of category 'verification' and the consumer needed a library
                 - Other compatible attributes:
                     - Doesn't say anything about its target Java version (required compatibility with Java 8)
                     - Doesn't say anything about its elements (required them packaged as a jar)
                     - Doesn't say anything about org.gradle.plugin.api-version (required '8.0.1')
                     - Doesn't say anything about its usage (required runtime)
             - Variant 'runtimeElements' capability com.facebook.react:react-native-gradle-plugin:unspecified declares a library for use during runtime, packaged as a jar, and its dependencies declared externally:
                 - Incompatible because this component declares a component, compatible with Java 11 and the consumer needed a component, compatible with Java 8
                 - Other compatible attribute:
                     - Doesn't say anything about org.gradle.plugin.api-version (required '8.0.1')
             - Variant 'testResultsElementsForTest' capability com.facebook.react:react-native-gradle-plugin:unspecified:
                 - Incompatible because this component declares a component of category 'verification' and the consumer needed a library
                 - Other compatible attributes:
                     - Doesn't say anything about how its dependencies are found (required its dependencies declared externally)
                     - Doesn't say anything about its target Java version (required compatibility with Java 8)
                     - Doesn't say anything about its elements (required them packaged as a jar)
                     - Doesn't say anything about org.gradle.plugin.api-version (required '8.0.1')
                     - Doesn't say anything about its usage (required runtime)

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 8s
error Failed to build the app.

Error: Command failed with exit code 1: npx react-native build-android --mode=Debug --no-packager --tasks assembleDebug
warn Both "tasks" and "mode" parameters were passed to "build" command. Using "tasks" for building the app.

FAILURE: Build failed with an exception.

* What went wrong:
A problem occurred configuring root project '@rnv-template-starter'.
> Could not determine the dependencies of null.
   > Could not resolve all task dependencies for configuration ':classpath'.
      > Could not find com.android.tools.build:gradle:.
        Required by:
            project :
      > Could not resolve com.facebook.react:react-native-gradle-plugin.
        Required by:
            project :
         > No matching variant of project :gradle-plugin was found. The consumer was configured to find a library for use during runtime, compatible with Java 8, packaged as a jar, and its dependencies declared externally, as well as attribute 'org.gradle.plugin.api-version' with value '8.0.1' but:
             - Variant 'apiElements' capability com.facebook.react:react-native-gradle-plugin:unspecified declares a library, packaged as a jar, and its dependencies declared externally:
                 - Incompatible because this component declares a component for use during compile-time, compatible with Java 11 and the consumer needed a component for use during runtime, compatible with Java 8
                 - Other compatible attribute:
                     - Doesn't say anything about org.gradle.plugin.api-version (required '8.0.1')
             - Variant 'mainSourceElements' capability com.facebook.react:react-native-gradle-plugin:unspecified declares a component, and its dependencies declared externally:
                 - Incompatible because this component declares a component of category 'verification' and the consumer needed a library
                 - Other compatible attributes:
                     - Doesn't say anything about its target Java version (required compatibility with Java 8)
                     - Doesn't say anything about its elements (required them packaged as a jar)
                     - Doesn't say anything about org.gradle.plugin.api-version (required '8.0.1')
                     - Doesn't say anything about its usage (required runtime)
             - Variant 'runtimeElements' capability com.facebook.react:react-native-gradle-plugin:unspecified declares a library for use during runtime, packaged as a jar, and its dependencies declared externally:
                 - Incompatible because this component declares a component, compatible with Java 11 and the consumer needed a component, compatible with Java 8
                 - Other compatible attribute:
                     - Doesn't say anything about org.gradle.plugin.api-version (required '8.0.1')
             - Variant 'testResultsElementsForTest' capability com.facebook.react:react-native-gradle-plugin:unspecified:
                 - Incompatible because this component declares a component of category 'verification' and the consumer needed a library
                 - Other compatible attributes:
                     - Doesn't say anything about how its dependencies are found (required its dependencies declared externally)
                     - Doesn't say anything about its target Java version (required compatibility with Java 8)
                     - Doesn't say anything about its elements (required them packaged as a jar)
                     - Doesn't say anything about org.gradle.plugin.api-version (required '8.0.1')
                     - Doesn't say anything about its usage (required runtime)

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 8s
error Failed to build the app.
info Building the app...

info 💡 Tip: Make sure that you have set up your development environment correctly, by running react-native doctor. To read more about doctor command visit: https://github.com/react-native-community/cli/blob/main/packages/cli-doctor/README.md#doctor

Error: Command failed with exit code 1: gradlew.bat app:assembleDebug
    at makeError (C:\Users\dev\Desktop\renative\node_modules\execa\lib\error.js:60:11)
    at Function.module.exports.sync (C:\Users\dev\Desktop\renative\node_modules\execa\index.js:194:17)
    at build (C:\Users\dev\Desktop\renative\node_modules\@react-native-community\cli-platform-android\build\commands\buildAndroid\index.js:95:22)
    at Object.buildAndroid [as func] (C:\Users\dev\Desktop\renative\node_modules\@react-native-community\cli-platform-android\build\commands\buildAndroid\index.js:87:10)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at Command.handleAction (C:\Users\dev\Desktop\renative\node_modules\@react-native-community\cli\build\index.js:111:9)
info Run CLI with --verbose flag for more details.
    at makeError (C:\Users\dev\Desktop\renative\node_modules\execa\lib\error.js:60:11)
    at handlePromise (C:\Users\dev\Desktop\renative\node_modules\execa\index.js:118:26)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)


│                                                                              │
│  Project location:                                                           │
│  C:\Users\dev\Desktop\renative\packages\template-starter\platformBuilds\template_android
└──────────────────────────────────────────────────────────────────────────────┘

C:\Users\dev\Desktop\renative\packages\template-starter>

**Comment by ElenaDiachenko** [comment]
Can’t reproduce.

**Comment by GabrieleKaceviciute** [comment]
1.0.0-rc.8 `build` works, `run` issue is tracked on this ticket https://github.com/flexn-io/renative/issues/1083
