### ISSUE TITLE
[REGRESSION] tizenwatch/tizenmobile fails to build/export

### ISSUE THREAD

**Issue by pauliusguzas** [flexn-io/renative#1201]
**Describe the bug**
tizenwatch/tizenmobile build and export fails on template starter (sanity_1.0.0-2 tag)

**To Reproduce**
1. go to template-starter package
2. run `rnv build -p tizenwatch`

```
pauliusguzas@MBP-de-Flexn template-starter % rnv build -p tizenwatch

┌──────────────────────────────────────────────────────────────────────────────┐
│                                                                              │
│        ██████╗ ███████╗███╗   ██╗ █████╗ ████████╗██╗██╗   ██╗███████╗       │
│        ██╔══██╗██╔════╝████╗  ██║██╔══██╗╚══██╔══╝██║██║   ██║██╔════╝       │
│        ██████╔╝█████╗  ██╔██╗ ██║███████║   ██║   ██║██║   ██║█████╗         │
│        ██╔══██╗██╔══╝  ██║╚██╗██║██╔══██║   ██║   ██║╚██╗ ██╔╝██╔══╝         │
│        ██║  ██║███████╗██║ ╚████║██║  ██║   ██║   ██║ ╚████╔╝ ███████╗       │
│        ╚═╝  ╚═╝╚══════╝╚═╝  ╚═══╝╚═╝  ╚═╝   ╚═╝   ╚═╝  ╚═══╝  ╚══════╝       │
│                                                                              │
│        Version: 1.0.0-canary.7                                               │
│        https://renative.org                                                  │
│        🚀 Firing up!...                                                      │
│        $ rnv build -p tizenwatch                                             │
│        Start Time: 10/24/2023, 4:39:32 PM                                    │
│                                                                              │
└──────────────────────────────────────────────────────────────────────────────┘

[ task ] registerEngine:engine-core[1]
[ task ] configureRuntimeDefaults[1] appId:undefined
[ task ] checkAndMigrateProject[1]
[ task ] loadPluginTemplates[1]
[ task ] parseRenativeConfigs[1]
[ task ] getWorkspaceDirPath[1]
[ task ] generatePlatformTemplatePaths[1]
[ task ] checkAndBootstrapIfRequired[1]
[ task ] loadIntegrations[1]
[ task ] loadEngines[1]
[ task ] loadEnginePluginDeps[1]
[ task ] loadEnginePackageDeps[1]
[ task ] registerEngine:engine-rn-web[1]
[ task ] findSuitableTask[1]
[ info ] Current Engine: engine-rn-web path: /Users/pauliusguzas/Desktop/renative/renative/packages/engine-rn-web
[ task ] registerMissingPlatformEngines[1]
[ task ] initializeTask[1] build
[ task ] => [build]
[ task ] [build] checkIfProjectAndNodeModulesExists[1]
[ hook ] [build] executePipe ('build:before')
[ task ] [build] taskRnvBuild[1] parent:undefined
[ task ] => [build] => [package]
[ hook ] [package] executePipe ('package:before')
[ task ] [package] taskRnvPackage[1] parent:build
[ task ] => [package] => [configure]
[ hook ] [configure] executePipe ('configure:before')
[ task ] [configure] taskRnvConfigure[1]
[ task ] => [configure] => [platform configure]
[ hook ] [platform configure] executePipe ('platform:configure:before')
[ task ] [platform configure] taskRnvPlatformConfigure[1]
[ task ] => [platform configure] => [project configure]
[ hook ] [project configure] executePipe ('project:configure:before')
[ task ] [project configure] taskRnvProjectConfigure[1]
[ task ] [project configure] checkAndMigrateProject[2]
[ task ] [project configure] loadPluginTemplates[2]
[ task ] [project configure] parseRenativeConfigs[2]
[ task ] [project configure] getWorkspaceDirPath[2]
[ task ] [project configure] generatePlatformTemplatePaths[2]
[ task ] => [project configure] => [workspace configure]
[ task ] [workspace configure] taskRnvWorkspaceConfigure[1]
[ task ] <= [project configure] <= workspace configure
[ task ] [project configure] checkIfTemplateConfigured[1]
[ task ] => [project configure] => [install]
[ hook ] [install] executePipe ('install:before')
[ task ] [install] taskRnvInstall[1] requiresInstall:false:true
[ hook ] [install] executePipe ('install:after')
[ task ] <= [project configure] <= install
[ task ] [project configure] checkCrypto[1]
[ task ] [project configure] configureRuntimeDefaults[2] appId:template
[ task ] [project configure] applyTemplate[1] @rnv/template-starter=>undefined
[ task ] [project configure] configureRuntimeDefaults[3] appId:template
[ task ] => [project configure] => [install]
[ hook ] [install] executePipe ('install:before')
[ task ] [install] taskRnvInstall[2] requiresInstall:false:true
[ hook ] [install] executePipe ('install:after')
[ task ] <= [project configure] <= install
[ task ] => [project configure] => [app configure]
[ hook ] [app configure] executePipe ('app:configure:before')
[ task ] [app configure] taskRnvAppConfigure[1]
[ task ] [app configure] listAppConfigsFoldersSync[1] ignoreHiddenConfigs:true
[ task ] [app configure] loadPluginTemplates[3]
[ task ] [app configure] parseRenativeConfigs[3]
[ task ] [app configure] generateBuildConfig[1] size:195.48 KB
[ task ] [app configure] getWorkspaceDirPath[3]
[ task ] [app configure] generateBuildConfig[2] size:195.48 KB
[ task ] [app configure] generateBuildConfig[3] size:195.48 KB
[ task ] [app configure] generateBuildConfig[4] size:195.48 KB
[ task ] [app configure] generatePlatformTemplatePaths[3]
[ task ] [app configure] generateBuildConfig[5] size:209.01 KB
[ task ] [app configure] generateBuildConfig[6] size:209.01 KB
[ task ] [app configure] getWorkspaceDirPath[4]
[ task ] [app configure] generateBuildConfig[7] size:209.01 KB
[ task ] [app configure] generateLocalConfig[1] resetAppId:false
[ task ] [app configure] generateBuildConfig[8] size:209.01 KB
[ info ] [app configure] Current App Config: template
[ hook ] [app configure] executePipe ('app:configure:after')
[ task ] <= [project configure] <= app configure
[ task ] [project configure] versionCheck[1]
[ task ] [project configure] versionCheck:rnvRunner:1.0.0-canary.7,rnvProject:1.0.0-canary.7[1]
[ task ] [project configure] configureEngines[1]
[ task ] [project configure] resolvePluginDependants[1]
[ task ] [project configure] configurePlugins[1]
[ info ] [project configure] Missing dependency @react-native-community/cli v(^6.0.0) in package.json. This is template. NO ACTION
[ task ] [project configure] configureRuntimeDefaults[4] appId:template
[ task ] [project configure] copyRuntimeAssets[1]
[ task ] [project configure] configureTemplateFiles[1]
[ task ] [project configure] checkAndCreateGitignore[1]
[ task ] [project configure] generateRuntimeConfig[1]
[ task ] [project configure] overrideTemplatePlugins[1]
[ task ] [project configure] parsePlugins[1]
[ info ] [project configure] /@react-native-community/cli-platform-ios/build/tools/listIOSDevices.js overriden by: /Users/pauliusguzas/Desktop/renative/renative/packages/rnv/pluginTemplates/@react-native-community/cli-platform-ios/overrides@11.3.7.json
[ info ] [project configure] /@react-native-community/cli-platform-ios/build/tools/findMatchingSimulator.js overriden by: /Users/pauliusguzas/Desktop/renative/renative/packages/rnv/pluginTemplates/@react-native-community/cli-platform-ios/overrides@11.3.7.json
[ info ] [project configure] /@react-native-community/cli-platform-ios/build/commands/runIOS/index.js overriden by: /Users/pauliusguzas/Desktop/renative/renative/packages/rnv/pluginTemplates/@react-native-community/cli-platform-ios/overrides@11.3.7.json
[ info ] [project configure] /react-native-gesture-handler/ios/Handlers/RNHoverHandler.m overriden by: /Users/pauliusguzas/Desktop/renative/renative/packages/rnv/pluginTemplates/react-native-gesture-handler/overrides.json
[ info ] [project configure] /react-native-gesture-handler/ios/RNGestureHandlerButtonComponentView.mm overriden by: /Users/pauliusguzas/Desktop/renative/renative/packages/rnv/pluginTemplates/react-native-gesture-handler/overrides.json
[ info ] [project configure] Plugin overrides disabled for: next with disablePluginTemplateOverrides. SKIPPING
[ task ] [project configure] parseFonts[1]
[ task ] [project configure] parsePlugins[2]
[ hook ] [project configure] executePipe ('project:configure:after')
[ task ] <= [platform configure] <= project configure
[ task ] [platform configure] isPlatformSupported[1]
[ task ] [platform configure] isBuildSchemeSupported[1]
[ info ] [platform configure] Current Build Scheme: debug
[ task ] [platform configure] checkAndConfigureSdks[1]
[ task ] [platform configure] checkAndConfigureTizenSdks:tizenwatch[1]
[ task ] [platform configure] checkSdk[1]
[ task ] [platform configure] checkTizenSdk[1]
[ task ] [platform configure] _isSdkInstalled[1]
[ task ] [platform configure] configureRuntimeDefaults[5] appId:template
[ task ] => [platform configure] => [install]
[ hook ] [install] executePipe ('install:before')
[ task ] [install] taskRnvInstall[3] requiresInstall:false:true
[ hook ] [install] executePipe ('install:after')
[ task ] <= [platform configure] <= install
[ task ] [platform configure] [1] taskRnvPlatformConfigure hasBuildFolderPresent:true
[ task ] [platform configure] createPlatformBuild[1]
[ task ] [platform configure] injectPlatformDependencies[1]
[ hook ] [platform configure] executePipe ('platform:configure:after')
[ task ] <= [configure] <= platform configure
[ task ] [configure] configureEntryPoint[1]
[ task ] [configure] copySharedPlatforms[1]
[ task ] [configure] configureTizenProject[1]
[ task ] [configure] configureTizenGlobal[1]
[ task ] [configure] copyAssetsFolder[1]
[ warn ] [configure] Your app is missing assets at ./appConfigs/base,./appConfigs/template.
[ task ] [configure] configureCoreWebProject[1]
[ task ] [configure] _configureProject[1]
[ task ] [configure] copyBuildsFolder[1]
[ task ] [configure] copyTemplatePluginsSync[1] (./platformBuilds/template_tizenwatch)
[ task ] [configure] parsePlugins[3]
[ hook ] [configure] executePipe ('configure:after')
[ task ] <= [package] <= configure
[ hook ] [package] executePipe ('package:after')
[ task ] <= [build] <= package
[ task ] [build] buildTizenProject[1]
[ task ] [build] buildCoreWebpackProject[1]
[ task ] [build] parsePlugins[4]
[ info ] [build] File sizes after gzip:

  129.75 kB  build/static/js/main.bf65e6ba.js
The project was built assuming it is hosted at ./.
You can control this with the homepage field in your package.json.

The platformBuilds/template_tizenwatch/build folder is ready to be deployed.

Find out more about deployment here:

  https://cra.link/deployment

Error: ENOENT: no such file or directory, open '/Users/pauliusguzas/Desktop/renative/renative/packages/template-starter/platformBuilds/template_tizenwatch/.project'
    at Object.openSync (node:fs:601:3)
    at Object.readFileSync (node:fs:469:35)
    at copyFileSync (/Users/pauliusguzas/Desktop/renative/renative/packages/core/src/system/fs.ts:92:24)
    at /Users/pauliusguzas/Desktop/renative/renative/packages/sdk-tizen/src/runner.ts:139:21
    at step (/Users/pauliusguzas/Desktop/renative/renative/node_modules/tslib/tslib.js:195:27)
    at Object.next (/Users/pauliusguzas/Desktop/renative/renative/node_modules/tslib/tslib.js:176:57)
    at fulfilled (/Users/pauliusguzas/Desktop/renative/renative/node_modules/tslib/tslib.js:166:62)
    at processTicksAndRejections (node:internal/process/task_queues:95:5) {
  errno: -2,
  syscall: 'open',
  code: 'ENOENT',
  path: '/Users/pauliusguzas/Desktop/renative/renative/packages/template-starter/platformBuilds/template_tizenwatch/.project'
}

 $ rnv build -p tizenwatch - Done! 🚀
┌──────────────────────────────────────────────────────────────────────────────┐
│  🚀  SUMMARY | 10/24/2023, 4:39:42 PM                                        │
│  $ rnv build -p tizenwatch                                                   │
├──────────────────────────────────────────────────────────────────────────────┤
│  ReNative Version: 1.0.0-canary.7                                            │
│  Project Name ($package.name): @rnv/template-starter                         │
│  Project Version ($package.version): 1.0.0-canary.7                          │
│  Workspace ($.workspaceID): rnv                                              │
│  Platform (-p): tizenwatch                                                   │
│  Engine ($.platforms.tizenwatch.engine): engine-rn-web                       │
│  App Config (-c): template                                                   │
│  Build Scheme (-s): debug                                                    │
│  Target (-t): W-5.5-circle-x86                                               │
│  Supported Platforms: tizenwatch                                             │
│  Master Template: @rnv/template-starter                                      │
│  Env Info: darwin | x64 | node v18.16.0                                      │
│  Executed Time: 0h:0m:10s:373ms                                              │
│                                                                              │
│ [ warn ] [configure] Your app is missing assets at ./appConfigs/base,./appConfigs/template.
│ You are trying to run global rnv command in your current project.
│ This might lead to unexpected behaviour.
│ Run your rnv command with npx prefix:
│ npx rnv build -p tizenwatch
│                                                                              │
│  Project location:                                                           │
│  ./platformBuilds/template_tizenwatch                                        │
└──────────────────────────────────────────────────────────────────────────────┘
pauliusguzas@MBP-de-Flexn template-starter %
```

**Expected behavior**
Binary is generated

**Desktop (please complete the following information):**

-   OS: Ventura 13.5.2 (Intel)
-   Node Version 18.16.0
-   RNV Version 1.0.0-canary.7
-   rnv/template-starter Version 1.0.0-canary.7

**Comment by GabrieleKaceviciute** [comment]
not reproduced on 1.0.0-canary.8, but related issue is on this ticket - https://github.com/flexn-io/renative/issues/1246
