### ISSUE TITLE
[macos] @rnv/template-starter@1.0.0-canary.7 doesn't work on macos

### ISSUE THREAD

**Issue by GabrieleKaceviciute** [flexn-io/renative#1209]
**Describe the bug**
@rnv/template-starter@1.0.0-canary.7 doesn't work on macos

**To Reproduce**

1. Install rnv@1.0.0-canary.7 with npm globally
2. Create new project with `rnv new` and choose rnv/template-starter version 1.0.0-canary.7
3. do `npx rnv run -p macos`

**Screenshots or copy&paste**
```
│  $ npx rnv run -p macos                                                      │
├──────────────────────────────────────────────────────────────────────────────┤
│  ReNative Version: 1.0.0-canary.7                                            │
│  Project Name ($package.name): second                                        │
│  Project Version ($package.version): 0.1.0                                   │
│  Workspace ($.workspaceID): rnv                                              │
│  Platform (-p): macos                                                        │
│  Engine ($.platforms.macos.engine): engine-rn-electron                       │
│  Template: @rnv/template-starter@1.0.0-canary.7                              │
│  App Config (-c): app                                                        │
│  Build Scheme (-s): debug                                                    │
│  Supported Platforms: macos                                                  │
│  Env Info: darwin | x64 | node v18.14.2                                      │
│  Executed Time: 0h:0m:0s:200ms                                               │
│                                                                              │
│  All good as 🦄                                                              │
│                                                                              │
│  Project location:                                                           │
│  ./platformBuilds/app_macos                                                  │
└──────────────────────────────────────────────────────────────────────────────┘
[ task ] [run] _runWebDevServer[1]
[ task ] [run] parsePlugins[4]
Error: Cannot find module 'babel-loader'
Require stack:
- /Users/gabriele/Desktop/tests/second/node_modules/@rnv/sdk-webpack/lib/config/webpack.config.js
- /Users/gabriele/Desktop/tests/second/node_modules/@rnv/sdk-webpack/lib/scripts/start.js
- /Users/gabriele/Desktop/tests/second/node_modules/@rnv/sdk-webpack/lib/index.js
- /Users/gabriele/Desktop/tests/second/node_modules/@rnv/sdk-tizen/lib/runner.js
- /Users/gabriele/Desktop/tests/second/node_modules/@rnv/sdk-tizen/lib/index.js
- /Users/gabriele/Desktop/tests/second/node_modules/@rnv/engine-core/lib/common.js
- /Users/gabriele/Desktop/tests/second/node_modules/@rnv/engine-core/lib/tasks/task.rnv.platform.configure.js
- /Users/gabriele/Desktop/tests/second/node_modules/@rnv/engine-core/lib/index.js
- /Users/gabriele/Desktop/tests/second/node_modules/rnv/lib/runner.js
- /Users/gabriele/Desktop/tests/second/node_modules/rnv/lib/index.js
- /Users/gabriele/Desktop/tests/second/node_modules/@rnv/cli/lib/index.js
- /Users/gabriele/Desktop/tests/second/node_modules/rnv/bin/index.js
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:1075:15)
    at Function.resolve (node:internal/modules/cjs/helpers:116:19)
    at module.exports (/Users/gabriele/Desktop/tests/second/node_modules/@rnv/sdk-webpack/src/config/webpack.config.js:389:45)
    at /Users/gabriele/Desktop/tests/second/node_modules/@rnv/sdk-webpack/src/scripts/start.js:56:24
    at new Promise (<anonymous>)
    at /Users/gabriele/Desktop/tests/second/node_modules/@rnv/sdk-webpack/src/scripts/start.js:30:5
    at step (/Users/gabriele/Desktop/tests/second/node_modules/tslib/tslib.js:195:27)
    at Object.next (/Users/gabriele/Desktop/tests/second/node_modules/tslib/tslib.js:176:57)
    at /Users/gabriele/Desktop/tests/second/node_modules/tslib/tslib.js:169:75
    at new Promise (<anonymous>) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/Users/gabriele/Desktop/tests/second/node_modules/@rnv/sdk-webpack/lib/config/webpack.config.js',
    '/Users/gabriele/Desktop/tests/second/node_modules/@rnv/sdk-webpack/lib/scripts/start.js',
    '/Users/gabriele/Desktop/tests/second/node_modules/@rnv/sdk-webpack/lib/index.js',
    '/Users/gabriele/Desktop/tests/second/node_modules/@rnv/sdk-tizen/lib/runner.js',
    '/Users/gabriele/Desktop/tests/second/node_modules/@rnv/sdk-tizen/lib/index.js',
    '/Users/gabriele/Desktop/tests/second/node_modules/@rnv/engine-core/lib/common.js',
    '/Users/gabriele/Desktop/tests/second/node_modules/@rnv/engine-core/lib/tasks/task.rnv.platform.configure.js',
    '/Users/gabriele/Desktop/tests/second/node_modules/@rnv/engine-core/lib/index.js',
    '/Users/gabriele/Desktop/tests/second/node_modules/rnv/lib/runner.js',
    '/Users/gabriele/Desktop/tests/second/node_modules/rnv/lib/index.js',
    '/Users/gabriele/Desktop/tests/second/node_modules/@rnv/cli/lib/index.js',
    '/Users/gabriele/Desktop/tests/second/node_modules/rnv/bin/index.js'
  ]
}

 $ npx rnv run -p macos - Done! 🚀
┌──────────────────────────────────────────────────────────────────────────────┐
│  🚀  SUMMARY | 10/25/2023, 6:08:08 PM                                        │
│  $ npx rnv run -p macos                                                      │
├──────────────────────────────────────────────────────────────────────────────┤
│  ReNative Version: 1.0.0-canary.7                                            │
│  Project Name ($package.name): second                                        │
│  Project Version ($package.version): 0.1.0                                   │
│  Workspace ($.workspaceID): rnv                                              │
│  Platform (-p): macos                                                        │
│  Engine ($.platforms.macos.engine): engine-rn-electron                       │
│  Template: @rnv/template-starter@1.0.0-canary.7                              │
│  App Config (-c): app                                                        │
│  Build Scheme (-s): debug                                                    │
│  Supported Platforms: macos                                                  │
│  Env Info: darwin | x64 | node v18.14.2                                      │
│  Executed Time: 0h:0m:1s:255ms                                               │
│                                                                              │
│  All good as 🦄                                                              │
│                                                                              │
│  Project location:                                                           │
│  ./platformBuilds/app_macos                                                  │
└──────────────────────────────────────────────────────────────────────────────┘
➜  ~/Desktop/tests/second
```

**Desktop (please complete the following information):**

-   OS: macOS Ventura 13.5.2
-   Node Version 18.14.2
-   RNV Version 1.0.0-canary.7

**Comment by pauliusguzas** [comment]
1.0.0-rc-6 fails with https://github.com/flexn-io/renative/issues/1133
