### ISSUE TITLE
[androidwear, fireTV] Build is not created

### ISSUE THREAD

**Issue by GabrieleKaceviciute** [flexn-io/renative#1218]
**Describe the bug**
Build/export is not created

**To Reproduce**
1. Go to template-starter package
2. Do `rnv build -p androidwear`
3. Check APK location

 
**Screenshots or copy&paste**
```
[ task ] <= build

 $ rnv build -p androidwear - Done! 🚀
┌──────────────────────────────────────────────────────────────────────────────┐
│  🚀  SUMMARY | 10/30/2023, 4:53:30 PM                                        │
│  $ rnv build -p androidwear                                                  │
├──────────────────────────────────────────────────────────────────────────────┤
│  ReNative Version: 1.0.0-feat-pin-cli.2                                      │
│  Project Name ($package.name): @rnv/template-starter                         │
│  Project Version ($package.version): 1.0.0-feat-pin-cli.2                    │
│  Workspace ($.workspaceID): rnv                                              │
│  Platform (-p): androidwear                                                  │
│  Engine ($.platforms.androidwear.engine): engine-rn                          │
│  App Config (-c): template                                                   │
│  Build Scheme (-s): debug                                                    │
│  Target (-t): Wear_OS_Square_API_30                                          │
│  Supported Platforms: androidwear                                            │
│  Master Template: @rnv/template-starter                                      │
│  Env Info: darwin | x64 | node v18.14.2                                      │
│  Executed Time: 0h:0m:29s:866ms                                              │
│                                                                              │
│ [ success ] [build] Your APK is located in ./platformBuilds/template_androidwear/app/build/outputs/apk/debug .
│ You are trying to run global rnv command in your current project.
│ This might lead to unexpected behaviour.
│ Run your rnv command with npx prefix:
│ npx rnv build -p androidwear
│                                                                              │
│  Project location:                                                           │
│  ./platformBuilds/template_androidwear                                       │
└──────────────────────────────────────────────────────────────────────────────┘
➜  ~/Desktop/renative/packages/template-starter git:(3b7cb02f8) cd platformBuilds/template_androidwear/app/build/outputs/apk/debug
cd: no such file or directory: platformBuilds/template_androidwear/app/build/outputs/apk/debug
➜  ~/Desktop/renative/packages/template-starter git:(3b7cb02f8)
```

**Desktop:**
-   OS: Ventura 13.5.2 (Intel)
-   Node Version 18.14.2
-   RNV Version 1.0.0-feat-pin-cli.2
-   rnv/template-starter Version 1.0.0-feat-pin-cli.2 
***

**Comment by pauliusguzas** [comment]
1.0.0-feat-bonanza.4
```
✖ FAILED: npx react-native build-android --mode=Debug --no-packager --tasks assembleDebug
COMMAND:

npx react-native build-android --mode=Debug --no-packager --tasks assembleDebug

FAILED with ERROR:

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:processDebugMainManifest'.
> com.android.manifmerger.ManifestMerger2$MergeFailureException: Error parsing /Users/pauliusguzas/Desktop/renative/renative/packages/template-starter/platformBuilds/template_androidwear/app/src/main/AndroidManifest.xml

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.

* Get more help at https://help.gradle.org

Deprecated Gradle features were used in this build, making it incompatible with Gradle 9.0.

You can use '--warning-mode all' to show the individual deprecation warnings and determine if they come from your own scripts or plugins.

See https://docs.gradle.org/8.0.1/userguide/command_line_interface.html#sec:command_line_warnings

BUILD FAILED in 13s
25 actionable tasks: 25 executed

info 💡 Tip: Make sure that you have set up your development environment correctly, by running react-native doctor. To read more about doctor command visit: https://github.com/react-native-community/cli/blob/main/packages/cli-doctor/README.md#doctor

error Failed to build the app.
Error: Command failed with exit code 1: ./gradlew app:assembleDebug
    at makeError (/Users/pauliusguzas/Desktop/renative/renative/node_modules/execa/lib/error.js:60:11)
    at Function.module.exports.sync (/Users/pauliusguzas/Desktop/renative/renative/node_modules/execa/index.js:194:17)
    at build (/Users/pauliusguzas/Desktop/renative/renative/node_modules/@react-native-community/cli-platform-android/build/commands/buildAndroid/index.js:95:22)
    at Object.buildAndroid [as func] (/Users/pauliusguzas/Desktop/renative/renative/node_modules/@react-native-community/cli-platform-android/build/commands/buildAndroid/index.js:87:10)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at Command.handleAction (/Users/pauliusguzas/Desktop/renative/renative/node_modules/react-native/node_modules/@react-native-community/cli/build/index.js:111:9)
info Run CLI with --verbose flag for more details.

Command failed with exit code 1: npx react-native build-android --mode=Debug --no-packager --tasks assembleDebug
warn Both "tasks" and "mode" parameters were passed to "build" command. Using "tasks" for building the app.

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:processDebugMainManifest'.
> com.android.manifmerger.ManifestMerger2$MergeFailureException: Error parsing /Users/pauliusguzas/Desktop/renative/renative/packages/template-starter/platformBuilds/template_androidwear/app/src/main/AndroidManifest.xml

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 13s
error Failed to build the app.
info Building the app...
> Task :gradle-plugin:pluginDescriptors
> Task :gradle-plugin:processResources
> Task :gradle-plugin:compileKotlin
> Task :gradle-plugin:compileJava NO-SOURCE
> Task :gradle-plugin:classes
> Task :gradle-plugin:jar
> Task :gradle-plugin:inspectClassesForKotlinIC
> Task :app:buildCodegenCLI SKIPPED
> Task :app:generateCodegenSchemaFromJavaScript SKIPPED
> Task :app:generateCodegenArtifactsFromSchema SKIPPED
> Task :app:generateNewArchitectureFiles
> Task :app:generatePackageList
> Task :app:preBuild
> Task :app:preDebugBuild
> Task :app:mergeDebugNativeDebugMetadata NO-SOURCE
> Task :react-native-gesture-handler:buildCodegenCLI SKIPPED
> Task :react-native-gesture-handler:generateCodegenSchemaFromJavaScript
> Task :react-native-gesture-handler:generateCodegenArtifactsFromSchema
> Task :react-native-gesture-handler:preBuild
> Task :react-native-gesture-handler:preDebugBuild
> Task :react-native-gesture-handler:compileDebugAidl NO-SOURCE
> Task :app:compileDebugAidl NO-SOURCE
> Task :react-native-gesture-handler:packageDebugRenderscript NO-SOURCE
> Task :app:compileDebugRenderscript NO-SOURCE
> Task :app:generateDebugBuildConfig
> Task :app:javaPreCompileDebug
> Task :react-native-gesture-handler:writeDebugAarMetadata
> Task :app:generateDebugResValues
> Task :react-native-gesture-handler:compileDebugRenderscript NO-SOURCE
> Task :react-native-gesture-handler:generateDebugResValues
> Task :react-native-gesture-handler:generateDebugResources
> Task :app:checkDebugAarMetadata
> Task :react-native-gesture-handler:packageDebugResources
> Task :app:mapDebugSourceSetPaths
> Task :app:generateDebugResources
> Task :app:createDebugCompatibleScreenManifests
> Task :app:extractDeepLinksDebug
> Task :react-native-gesture-handler:extractDeepLinksDebug
> Task :react-native-gesture-handler:compileDebugLibraryResources

> Task :react-native-gesture-handler:processDebugManifest
package="com.swmansion.gesturehandler" found in source AndroidManifest.xml: /Users/pauliusguzas/Desktop/renative/renative/node_modules/react-native-gesture-handler/android/src/main/AndroidManifest.xml.
Setting the namespace via a source AndroidManifest.xml's package attribute is deprecated.
Please instead set the namespace (or testNamespace) in the module's build.gradle file, as described here: https://developer.android.com/studio/build/configure-app-module#set-namespace
This migration can be done automatically using the AGP Upgrade Assistant, please refer to https://developer.android.com/studio/build/agp-upgrade-assistant for more information.

> Task :app:processDebugMainManifest FAILED
> Task :app:mergeDebugResources
> Task :react-native-gesture-handler:parseDebugLocalResources

Deprecated Gradle features were used in this build, making it incompatible with Gradle 9.0.

You can use '--warning-mode all' to show the individual deprecation warnings and determine if they come from your own scripts or plugins.

See https://docs.gradle.org/8.0.1/userguide/command_line_interface.html#sec:command_line_warnings
25 actionable tasks: 25 executed

info 💡 Tip: Make sure that you have set up your development environment correctly, by running react-native doctor. To read more about doctor command visit: https://github.com/react-native-community/cli/blob/main/packages/cli-doctor/README.md#doctor

Error: Command failed with exit code 1: ./gradlew app:assembleDebug
    at makeError (/Users/pauliusguzas/Desktop/renative/renative/node_modules/execa/lib/error.js:60:11)
    at Function.module.exports.sync (/Users/pauliusguzas/Desktop/renative/renative/node_modules/execa/index.js:194:17)
    at build (/Users/pauliusguzas/Desktop/renative/renative/node_modules/@react-native-community/cli-platform-android/build/commands/buildAndroid/index.js:95:22)
    at Object.buildAndroid [as func] (/Users/pauliusguzas/Desktop/renative/renative/node_modules/@react-native-community/cli-platform-android/build/commands/buildAndroid/index.js:87:10)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at Command.handleAction (/Users/pauliusguzas/Desktop/renative/renative/node_modules/react-native/node_modules/@react-native-community/cli/build/index.js:111:9)
info Run CLI with --verbose flag for more details.

warn Both "tasks" and "mode" parameters were passed to "build" command. Using "tasks" for building the app.

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:processDebugMainManifest'.
> com.android.manifmerger.ManifestMerger2$MergeFailureException: Error parsing /Users/pauliusguzas/Desktop/renative/renative/packages/template-starter/platformBuilds/template_androidwear/app/src/main/AndroidManifest.xml

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 13s
error Failed to build the app.

Error: Command failed with exit code 1: npx react-native build-android --mode=Debug --no-packager --tasks assembleDebug
warn Both "tasks" and "mode" parameters were passed to "build" command. Using "tasks" for building the app.

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:processDebugMainManifest'.
> com.android.manifmerger.ManifestMerger2$MergeFailureException: Error parsing /Users/pauliusguzas/Desktop/renative/renative/packages/template-starter/platformBuilds/template_androidwear/app/src/main/AndroidManifest.xml

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 13s
error Failed to build the app.
info Building the app...
> Task :gradle-plugin:pluginDescriptors
> Task :gradle-plugin:processResources
> Task :gradle-plugin:compileKotlin
> Task :gradle-plugin:compileJava NO-SOURCE
> Task :gradle-plugin:classes
> Task :gradle-plugin:jar
> Task :gradle-plugin:inspectClassesForKotlinIC
> Task :app:buildCodegenCLI SKIPPED
> Task :app:generateCodegenSchemaFromJavaScript SKIPPED
> Task :app:generateCodegenArtifactsFromSchema SKIPPED
> Task :app:generateNewArchitectureFiles
> Task :app:generatePackageList
> Task :app:preBuild
> Task :app:preDebugBuild
> Task :app:mergeDebugNativeDebugMetadata NO-SOURCE
> Task :react-native-gesture-handler:buildCodegenCLI SKIPPED
> Task :react-native-gesture-handler:generateCodegenSchemaFromJavaScript
> Task :react-native-gesture-handler:generateCodegenArtifactsFromSchema
> Task :react-native-gesture-handler:preBuild
> Task :react-native-gesture-handler:preDebugBuild
> Task :react-native-gesture-handler:compileDebugAidl NO-SOURCE
> Task :app:compileDebugAidl NO-SOURCE
> Task :react-native-gesture-handler:packageDebugRenderscript NO-SOURCE
> Task :app:compileDebugRenderscript NO-SOURCE
> Task :app:generateDebugBuildConfig
> Task :app:javaPreCompileDebug
> Task :react-native-gesture-handler:writeDebugAarMetadata
> Task :app:generateDebugResValues
> Task :react-native-gesture-handler:compileDebugRenderscript NO-SOURCE
> Task :react-native-gesture-handler:generateDebugResValues
> Task :react-native-gesture-handler:generateDebugResources
> Task :app:checkDebugAarMetadata
> Task :react-native-gesture-handler:packageDebugResources
> Task :app:mapDebugSourceSetPaths
> Task :app:generateDebugResources
> Task :app:createDebugCompatibleScreenManifests
> Task :app:extractDeepLinksDebug
> Task :react-native-gesture-handler:extractDeepLinksDebug
> Task :react-native-gesture-handler:compileDebugLibraryResources

> Task :react-native-gesture-handler:processDebugManifest
package="com.swmansion.gesturehandler" found in source AndroidManifest.xml: /Users/pauliusguzas/Desktop/renative/renative/node_modules/react-native-gesture-handler/android/src/main/AndroidManifest.xml.
Setting the namespace via a source AndroidManifest.xml's package attribute is deprecated.
Please instead set the namespace (or testNamespace) in the module's build.gradle file, as described here: https://developer.android.com/studio/build/configure-app-module#set-namespace
This migration can be done automatically using the AGP Upgrade Assistant, please refer to https://developer.android.com/studio/build/agp-upgrade-assistant for more information.

> Task :app:processDebugMainManifest FAILED
> Task :app:mergeDebugResources
> Task :react-native-gesture-handler:parseDebugLocalResources

Deprecated Gradle features were used in this build, making it incompatible with Gradle 9.0.

You can use '--warning-mode all' to show the individual deprecation warnings and determine if they come from your own scripts or plugins.

See https://docs.gradle.org/8.0.1/userguide/command_line_interface.html#sec:command_line_warnings
25 actionable tasks: 25 executed

info 💡 Tip: Make sure that you have set up your development environment correctly, by running react-native doctor. To read more about doctor command visit: https://github.com/react-native-community/cli/blob/main/packages/cli-doctor/README.md#doctor

Error: Command failed with exit code 1: ./gradlew app:assembleDebug
    at makeError (/Users/pauliusguzas/Desktop/renative/renative/node_modules/execa/lib/error.js:60:11)
    at Function.module.exports.sync (/Users/pauliusguzas/Desktop/renative/renative/node_modules/execa/index.js:194:17)
    at build (/Users/pauliusguzas/Desktop/renative/renative/node_modules/@react-native-community/cli-platform-android/build/commands/buildAndroid/index.js:95:22)
    at Object.buildAndroid [as func] (/Users/pauliusguzas/Desktop/renative/renative/node_modules/@react-native-community/cli-platform-android/build/commands/buildAndroid/index.js:87:10)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at Command.handleAction (/Users/pauliusguzas/Desktop/renative/renative/node_modules/react-native/node_modules/@react-native-community/cli/build/index.js:111:9)
info Run CLI with --verbose flag for more details.
    at makeError (/Users/pauliusguzas/Desktop/renative/renative/node_modules/execa/lib/error.js:60:11)
    at handlePromise (/Users/pauliusguzas/Desktop/renative/renative/node_modules/execa/index.js:118:26)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)



 $ rnv build -p androidwear - Done! 🚀
┌──────────────────────────────────────────────────────────────────────────────┐
│  🚀  SUMMARY | 11/6/2023, 3:17:09 PM                                         │
│  $ rnv build -p androidwear                                                  │
├──────────────────────────────────────────────────────────────────────────────┤
│  ReNative Version: 1.0.0-feat-bonanza.4                                      │
│  Project Name ($package.name): @rnv/template-starter                         │
│  Project Version ($package.version): 1.0.0-feat-bonanza.4                    │
│  Workspace ($.workspaceID): rnv                                              │
│  Platform (-p): androidwear                                                  │
│  Engine ($.platforms.androidwear.engine): engine-rn                          │
│  App Config (-c): template                                                   │
│  Build Scheme (-s): debug                                                    │
│  Target (-t): Android_Wear_Round_API_28                                      │
│  Supported Platforms: androidwear                                            │
│  Master Template: @rnv/template-starter                                      │
│  Env Info: darwin | x64 | node v18.16.0                                      │
│  Executed Time: 0h:0m:18s:54ms                                               │
│                                                                              │
│ [ success ] [project configure] /react-native-gesture-handler/ios/Handlers/RNHoverHandler.m requires override by: /Users/pauliusguzas/Desktop/renative/renative/packages/rnv/pluginTemplates/react-native-gesture-handler/overrides.json. FIXING...DONE
│ [ success ] [project configure] /react-native-gesture-handler/ios/RNGestureHandlerButtonComponentView.mm requires override by: /Users/pauliusguzas/Desktop/renative/renative/packages/rnv/pluginTemplates/react-native-gesture-handler/overrides.json. FIXING...DONE
│ [ success ] [project configure] /@react-native-community/cli-platform-ios/build/tools/listIOSDevices.js requires override by: /Users/pauliusguzas/Desktop/renative/renative/packages/rnv/pluginTemplates/@react-native-community/cli-platform-ios/overrides@11.3.7.json. FIXING...DONE
│ [ success ] [project configure] /@react-native-community/cli-platform-ios/build/tools/findMatchingSimulator.js requires override by: /Users/pauliusguzas/Desktop/renative/renative/packages/rnv/pluginTemplates/@react-native-community/cli-platform-ios/overrides@11.3.7.json. FIXING...DONE
│ [ success ] [project configure] /@react-native-community/cli-platform-ios/build/commands/runIOS/index.js requires override by: /Users/pauliusguzas/Desktop/renative/renative/packages/rnv/pluginTemplates/@react-native-community/cli-platform-ios/overrides@11.3.7.json. FIXING...DONE
│ You are trying to run global rnv command in your current project.
│ This might lead to unexpected behaviour.
│ Run your rnv command with npx prefix:
│ npx rnv build -p androidwear
│                                                                              │
│  Project location:                                                           │
│  ./platformBuilds/template_androidwear                                       │
└──────────────────────────────────────────────────────────────────────────────┘
pauliusguzas@MBP-de-Flexn template-starter %
```
