### ISSUE TITLE
Unable to compile iOS/tvOs with default template

### ISSUE THREAD

**Issue by VMBindraban** [flexn-io/renative#1238]
**Describe the bug**
Unable to compile iOS and tvOS on a new project.

**To Reproduce**

1. Run command 'rnv run -p ios'
2. See error

```
[ error ] [run] COMMAND: 

node /project-path/node_modules/react-native/local-cli/cli.js run-ios --project-path platformBuilds/app_ios --scheme RNVApp --configuration Debug --simulator iPhone\ 15 --allowProvisioningUpdates 

FAILED with ERROR: 

error Failed to build iOS project. We ran "xcodebuild" command but it exited with error code 65. To debug build logs further, consider building your app with Xcode.app, by opening RNVApp.xcworkspace.
Command line invocation:
 /Applications/Xcode.app/Contents/Developer/usr/bin/xcodebuild -workspace RNVApp.xcworkspace -configuration Debug -scheme RNVApp -destination id=5D80CBD7-760B-4F50-B8C9-B563661082DD -derivedDataPath build/RNVApp -allowProvisioningUpdates
User defaults from command line:
 IDEDerivedDataPathOverride = /project-path/platformBuilds/app_ios/build/RNVApp
 IDEPackageSupportUseBuiltinSCM = YES

Command failed with exit code 1: node /project-path/node_modules/react-native/local-cli/cli.js run-ios --project-path platformBuilds/app_ios --scheme RNVApp --configuration Debug --simulator iPhone 15 --allowProvisioningUpdates
error React Native CLI uses autolinking for native dependencies, but the following modules are linked manually: 
  - react-native-gesture-handler (to unlink run: "react-native unlink react-native-gesture-handler")
This is likely happening when upgrading React Native from below 0.60 to 0.60 or above. Going forward, you can unlink this dependency via "react-native unlink <dependency>" and it will be included in your app automatically. If a library isn't compatible with autolinking, disregard this message and notify the library maintainers.
Read more about autolinking: https://github.com/react-native-community/cli/blob/master/docs/autolinking.md

error Failed to build iOS project. We ran "xcodebuild" command but it exited with error code 65. To debug build logs further, consider building your app with Xcode.app, by opening RNVApp.xcworkspace.
info Found Xcode workspace "RNVApp.xcworkspace"
info Building (using "xcodebuild -workspace RNVApp.xcworkspace -configuration Debug -scheme RNVApp -destination id=5D80CBD7-760B-4F50-B8C9-B563661082DD -derivedDataPath build/RNVApp -allowProvisioningUpdates")
Command line invocation:
    /Applications/Xcode.app/Contents/Developer/usr/bin/xcodebuild -workspace RNVApp.xcworkspace -configuration Debug -scheme RNVApp -destination id=5D80CBD7-760B-4F50-B8C9-B563661082DD -derivedDataPath build/RNVApp -allowProvisioningUpdates

User defaults from command line:
    IDEDerivedDataPathOverride = /project-path/platformBuilds/app_ios/build/RNVApp
    IDEPackageSupportUseBuiltinSCM = YES

Prepare packages

ComputeTargetDependencyGraph
note: Building targets in dependency order
note: Target dependency graph (35 targets)
    Target 'RNVApp' in project 'RNVApp'
        ➜ Implicit dependency on target 'Pods-RNVApp' in project 'Pods' via file 'Pods_RNVApp.framework' in build phase 'Link Binary'
        ➜ Implicit dependency on target 'React-CoreModules' in project 'Pods' via options '-framework CoreModules' in build setting 'OTHER_LDFLAGS'
        ➜ Implicit dependency on target 'DoubleConversion' in project 'Pods' via options '-framework DoubleConversion' in build setting 'OTHER_LDFLAGS'
        ➜ Implicit dependency on target 'FBReactNativeSpec' in project 'Pods' via options '-framework FBReactNativeSpec' in build setting 'OTHER_LDFLAGS'
        ➜ Implicit dependency on target 'React-RCTAnimation' in project 'Pods' via options '-framework RCTAnimation' in build setting 'OTHER_LDFLAGS'
        ➜ Implicit dependency on target 'React-RCTBlob' in project 'Pods' via options '-framework RCTBlob' in build setting 'OTHER_LDFLAGS'
        ➜ Implicit dependency on target 'React-RCTImage' in project 'Pods' via options '-framework RCTImage' in build setting 'OTHER_LDFLAGS'
        ➜ Implicit dependency on target 'React-RCTLinking' in project 'Pods' via options '-framework RCTLinking' in build setting 'OTHER_LDFLAGS'
        ➜ Implicit dependency on target 'React-RCTNetwork' in project 'Pods' via options '-framework RCTNetwork' in build setting 'OTHER_LDFLAGS'
        ➜ Implicit dependency on target 'React-RCTSettings' in project 'Pods' via options '-framework RCTSettings' in build setting 'OTHER_LDFLAGS'
        ➜ Implicit dependency on target 'React-RCTText' in project 'Pods' via options '-framework RCTText' in build setting 'OTHER_LDFLAGS'
        ➜ Implicit dependency on target 'RCTTypeSafety' in project 'Pods' via options '-framework RCTTypeSafety' in build setting 'OTHER_LDFLAGS'
        ➜ Implicit dependency on target 'React-RCTVibration' in project 'Pods' via options '-framework RCTVibration' in build setting 'OTHER_LDFLAGS'
        ➜ Implicit dependency on target 'RNGestureHandler' in project 'Pods' via options '-framework RNGestureHandler' in build setting 'OTHER_LDFLAGS'
        ➜ Implicit dependency on target 'React-Core' in project 'Pods' via options '-framework React' in build setting 'OTHER_LDFLAGS'
        ➜ Implicit dependency on target 'ReactCommon' in project 'Pods' via options '-framework ReactCommon' in build setting 'OTHER_LDFLAGS'
        ➜ Implicit dependency on target 'React-cxxreact' in project 'Pods' via options '-framework cxxreact' in build setting 'OTHER_LDFLAGS'
        ➜ Implicit dependency on target 'fmt' in project 'Pods' via options '-framework fmt' in build setting 'OTHER_LDFLAGS'
        ➜ Implicit dependency on target 'RCT-Folly' in project 'Pods' via options '-framework folly' in build setting 'OTHER_LDFLAGS'
        ➜ Implicit dependency on target 'glog' in project 'Pods' via options '-framework glog' in build setting 'OTHER_LDFLAGS'
        ➜ Implicit dependency on target 'React-jsi' in project 'Pods' via options '-framework jsi' in build setting 'OTHER_LDFLAGS'
        ➜ Implicit dependency on target 'React-jsinspector' in project 'Pods' via options '-framework jsinspector' in build setting 'OTHER_LDFLAGS'
        ➜ Implicit dependency on target 'React-jsiexecutor' in project 'Pods' via options '-framework jsireact' in build setting 'OTHER_LDFLAGS'
        ➜ Implicit dependency on target 'React-logger' in project 'Pods' via options '-framework logger' in build setting 'OTHER_LDFLAGS'
        ➜ Implicit dependency on target 'React-perflogger' in project 'Pods' via options '-framework reactperflogger' in build setting 'OTHER_LDFLAGS'
        ➜ Implicit dependency on target 'Yoga' in project 'Pods' via options '-framework yoga' in build setting 'OTHER_LDFLAGS'
    Target 'Pods-RNVApp' in project 'Pods'
        ➜ Explicit dependency on target 'DoubleConversion' in project 'Pods'
        ➜ Explicit dependency on target 'FBLazyVector' in project 'Pods'
        ➜ Explicit dependency on target 'FBReactNativeSpec' in project 'Pods'
        ➜ Explicit dependency on target 'RCT-Folly' in project 'Pods'
        ➜ Explicit dependency on target 'RCTRequired' in project 'Pods'
        ➜ Explicit dependency on target 'RCTTypeSafety' in project 'Pods'
        ➜ Explicit dependency on target 'RNGestureHandler' in project 'Pods'
        ➜ Explicit dependency on target 'React' in project 'Pods'
        ➜ Explicit dependency on target 'React-Core' in project 'Pods'
        ➜ Explicit dependency on target 'React-CoreModules' in project 'Pods'
        ➜ Explicit dependency on target 'React-RCTActionSheet' in project 'Pods'
        ➜ Explicit dependency on target 'React-RCTAnimation' in project 'Pods'
        ➜ Explicit dependency on target 'React-RCTBlob' in project 'Pods'
        ➜ Explicit dependency on target 'React-RCTImage' in project 'Pods'
        ➜ Explicit dependency on target 'React-RCTLinking' in project 'Pods'
        ➜ Explicit dependency on target 'React-RCTNetwork' in project 'Pods'
        ➜ Explicit dependency on target 'React-RCTSettings' in project 'Pods'
        ➜ Explicit dependency on target 'React-RCTText' in project 'Pods'
        ➜ Explicit dependency on target 'React-RCTVibration' in project 'Pods'
        ➜ Explicit dependency on target 'React-callinvoker' in project 'Pods'
        ➜ Explicit dependency on target 'React-cxxreact' in project 'Pods'
        ➜ Explicit dependency on target 'React-jsi' in project 'Pods'
        ➜ Explicit dependency on target 'React-jsiexecutor' in project 'Pods'
        ➜ Explicit dependency on target 'React-jsinspector' in project 'Pods'
        ➜ Explicit dependency on target 'React-logger' in project 'Pods'
        ➜ Explicit dependency on target 'React-perflogger' in project 'Pods'
        ➜ Explicit dependency on target 'React-runtimeexecutor' in project 'Pods'
        ➜ Explicit dependency on target 'ReactCommon' in project 'Pods'
        ➜ Explicit dependency on target 'Yoga' in project 'Pods'
        ➜ Explicit dependency on target 'boost' in project 'Pods'
        ➜ Explicit dependency on target 'fmt' in project 'Pods'
        ➜ Explicit dependency on target 'glog' in project 'Pods'
    Target 'React-CoreModules' in project 'Pods'
        ➜ Explicit dependency on target 'FBReactNativeSpec' in project 'Pods'
        ➜ Explicit dependency on target 'RCT-Folly' in project 'Pods'
        ➜ Explicit dependency on target 'RCTTypeSafety' in project 'Pods'
        ➜ Explicit dependency on target 'React-Core' in project 'Pods'
        ➜ Explicit dependency on target 'React-RCTImage' in project 'Pods'
        ➜ Explicit dependency on target 'React-jsi' in project 'Pods'
        ➜ Explicit dependency on target 'ReactCommon' in project 'Pods'
    Target 'React' in project 'Pods'
        ➜ Explicit dependency on target 'React-Core' in project 'Pods'
        ➜ Explicit dependency on target 'React-RCTActionSheet' in project 'Pods'
        ➜ Explicit dependency on target 'React-RCTAnimation' in project 'Pods'
        ➜ Explicit dependency on target 'React-RCTBlob' in project 'Pods'
        ➜ Explicit dependency on target 'React-RCTImage' in project 'Pods'
        ➜ Explicit dependency on target 'React-RCTLinking' in project 'Pods'
        ➜ Explicit dependency on target 'React-RCTNetwork' in project 'Pods'
        ➜ Explicit dependency on target 'React-RCTSettings' in project 'Pods'
        ➜ Explicit dependency on target 'React-RCTText' in project 'Pods'
        ➜ Exp

error React Native CLI uses autolinking for native dependencies, but the following modules are linked manually: 
  - react-native-gesture-handler (to unlink run: "react-native unlink react-native-gesture-handler")
This is likely happening when upgrading React Native from below 0.60 to 0.60 or above. Going forward, you can unlink this dependency via "react-native unlink <dependency>" and it will be included in your app automatically. If a library isn't compatible with autolinking, disregard this message and notify the library maintainers.
Read more about autolinking: https://github.com/react-native-community/cli/blob/master/docs/autolinking.md

error Failed to build iOS project. We ran "xcodebuild" command but it exited with error code 65. To debug build logs further, consider building your app with Xcode.app, by opening RNVApp.xcworkspace.

Error: Command failed with exit code 1: node /project-path/node_modules/react-native/local-cli/cli.js run-ios --project-path platformBuilds/app_ios --scheme RNVApp --configuration Debug --simulator iPhone 15 --allowProvisioningUpdates
error React Native CLI uses autolinking for native dependencies, but the following modules are linked manually: 
  - react-native-gesture-handler (to unlink run: "react-native unlink react-native-gesture-handler")
This is likely happening when upgrading React Native from below 0.60 to 0.60 or above. Going forward, you can unlink this dependency via "react-native unlink <dependency>" and it will be included in your app automatically. If a library isn't compatible with autolinking, disregard this message and notify the library maintainers.
Read more about autolinking: https://github.com/react-native-community/cli/blob/master/docs/autolinking.md

error Failed to build iOS project. We ran "xcodebuild" command but it exited with error code 65. To debug build logs further, consider building your app with Xcode.app, by opening RNVApp.xcworkspace.
info Found Xcode workspace "RNVApp.xcworkspace"
info Building (using "xcodebuild -workspace RNVApp.xcworkspace -configuration Debug -scheme RNVApp -destination id=5D80CBD7-760B-4F50-B8C9-B563661082DD -derivedDataPath build/RNVApp -allowProvisioningUpdates")
Command line invocation:
    /Applications/Xcode.app/Contents/Developer/usr/bin/xcodebuild -workspace RNVApp.xcworkspace -configuration Debug -scheme RNVApp -destination id=5D80CBD7-760B-4F50-B8C9-B563661082DD -derivedDataPath build/RNVApp -allowProvisioningUpdates

User defaults from command line:
    IDEDerivedDataPathOverride = /project-path/platformBuilds/app_ios/build/RNVApp
    IDEPackageSupportUseBuiltinSCM = YES

Prepare packages

ComputeTargetDependencyGraph
note: Building targets in dependency order
note: Target dependency graph (35 targets)
    Target 'RNVApp' in project 'RNVApp'
        ➜ Implicit dependency on target 'Pods-RNVApp' in project 'Pods' via file 'Pods_RNVApp.framework' in build phase 'Link Binary'
        ➜ Implicit dependency on target 'React-CoreModules' in project 'Pods' via options '-framework CoreModules' in build setting 'OTHER_LDFLAGS'
        ➜ Implicit dependency on target 'DoubleConversion' in project 'Pods' via options '-framework DoubleConversion' in build setting 'OTHER_LDFLAGS'
        ➜ Implicit dependency on target 'FBReactNativeSpec' in project 'Pods' via options '-framework FBReactNativeSpec' in build setting 'OTHER_LDFLAGS'
        ➜ Implicit dependency on target 'React-RCTAnimation' in project 'Pods' via options '-framework RCTAnimation' in build setting 'OTHER_LDFLAGS'
        ➜ Implicit dependency on target 'React-RCTBlob' in project 'Pods' via options '-framework RCTBlob' in build setting 'OTHER_LDFLAGS'
        ➜ Implicit dependency on target 'React-RCTImage' in project 'Pods' via options '-framework RCTImage' in build setting 'OTHER_LDFLAGS'
        ➜ Implicit dependency on target 'React-RCTLinking' in project 'Pods' via options '-framework RCTLinking' in build setting 'OTHER_LDFLAGS'
        ➜ Implicit dependency on target 'React-RCTNetwork' in project 'Pods' via options '-framework RCTNetwork' in build setting 'OTHER_LDFLAGS'
        ➜ Implicit dependency on target 'React-RCTSettings' in project 'Pods' via options '-framework RCTSettings' in build setting 'OTHER_LDFLAGS'
        ➜ Implicit dependency on target 'React-RCTText' in project 'Pods' via options '-framework RCTText' in build setting 'OTHER_LDFLAGS'
        ➜ Implicit dependency on target 'RCTTypeSafety' in project 'Pods' via options '-framework RCTTypeSafety' in build setting 'OTHER_LDFLAGS'
        ➜ Implicit dependency on target 'React-RCTVibration' in project 'Pods' via options '-framework RCTVibration' in build setting 'OTHER_LDFLAGS'
        ➜ Implicit dependency on target 'RNGestureHandler' in project 'Pods' via options '-framework RNGestureHandler' in build setting 'OTHER_LDFLAGS'
        ➜ Implicit dependency on target 'React-Core' in project 'Pods' via options '-framework React' in build setting 'OTHER_LDFLAGS'
        ➜ Implicit dependency on target 'ReactCommon' in project 'Pods' via options '-framework ReactCommon' in build setting 'OTHER_LDFLAGS'
        ➜ Implicit dependency on target 'React-cxxreact' in project 'Pods' via options '-framework cxxreact' in build setting 'OTHER_LDFLAGS'
        ➜ Implicit dependency on target 'fmt' in project 'Pods' via options '-framework fmt' in build setting 'OTHER_LDFLAGS'
        ➜ Implicit dependency on target 'RCT-Folly' in project 'Pods' via options '-framework folly' in build setting 'OTHER_LDFLAGS'
        ➜ Implicit dependency on target 'glog' in project 'Pods' via options '-framework glog' in build setting 'OTHER_LDFLAGS'
        ➜ Implicit dependency on target 'React-jsi' in project 'Pods' via options '-framework jsi' in build setting 'OTHER_LDFLAGS'
        ➜ Implicit dependency on target 'React-jsinspector' in project 'Pods' via options '-framework jsinspector' in build setting 'OTHER_LDFLAGS'
        ➜ Implicit dependency on target 'React-jsiexecutor' in project 'Pods' via options '-framework jsireact' in build setting 'OTHER_LDFLAGS'
        ➜ Implicit dependency on target 'React-logger' in project 'Pods' via options '-framework logger' in build setting 'OTHER_LDFLAGS'
        ➜ Implicit dependency on target 'React-perflogger' in project 'Pods' via options '-framework reactperflogger' in build setting 'OTHER_LDFLAGS'
        ➜ Implicit dependency on target 'Yoga' in project 'Pods' via options '-framework yoga' in build setting 'OTHER_LDFLAGS'
    Target 'Pods-RNVApp' in project 'Pods'
        ➜ Explicit dependency on target 'DoubleConversion' in project 'Pods'
        ➜ Explicit dependency on target 'FBLazyVector' in project 'Pods'
        ➜ Explicit dependency on target 'FBReactNativeSpec' in project 'Pods'
        ➜ Explicit dependency on target 'RCT-Folly' in project 'Pods'
        ➜ Explicit dependency on target 'RCTRequired' in project 'Pods'
        ➜ Explicit dependency on target 'RCTTypeSafety' in project 'Pods'
        ➜ Explicit dependency on target 'RNGestureHandler' in project 'Pods'
        ➜ Explicit dependency on target 'React' in project 'Pods'
        ➜ Explicit dependency on target 'React-Core' in project 'Pods'
        ➜ Explicit dependency on target 'React-CoreModules' in project 'Pods'
        ➜ Explicit dependency on target 'React-RCTActionSheet' in project 'Pods'
        ➜ Explicit dependency on target 'React-RCTAnimation' in project 'Pods'
        ➜ Explicit dependency on target 'React-RCTBlob' in project 'Pods'
        ➜ Explicit dependency on target 'React-RCTImage' in project 'Pods'
        ➜ Explicit dependency on target 'React-RCTLinking' in project 'Pods'
        ➜ Explicit dependency on target 'React-RCTNetwork' in project 'Pods'
        ➜ Explicit dependency on target 'React-RCTSettings' in project 'Pods'
        ➜ Explicit dependency on target 'React-RCTText' in project 'Pods'
        ➜ Explicit dependency on target 'React-RCTVibration' in project 'Pods'
        ➜ Explicit dependency on target 'React-callinvoker' in project 'Pods'
        ➜ Explicit dependency on target 'React-cxxreact' in project 'Pods'
        ➜ Explicit dependency on target 'React-jsi' in project 'Pods'
        ➜ Explicit dependency on target 'React-jsiexecutor' in project 'Pods'
        ➜ Explicit dependency on target 'React-jsinspector' in project 'Pods'
        ➜ Explicit dependency on target 'React-logger' in project 'Pods'
        ➜ Explicit dependency on target 'React-perflogger' in project 'Pods'
        ➜ Explicit dependency on target 'React-runtimeexecutor' in project 'Pods'
        ➜ Explicit dependency on target 'ReactCommon' in project 'Pods'
        ➜ Explicit dependency on target 'Yoga' in project 'Pods'
        ➜ Explicit dependency on target 'boost' in project 'Pods'
        ➜ Explicit dependency on target 'fmt' in project 'Pods'
        ➜ Explicit dependency on target 'glog' in project 'Pods'
    Target 'React-CoreModules' in project 'Pods'
        ➜ Explicit dependency on target 'FBReactNativeSpec' in project 'Pods'
        ➜ Explicit dependency on target 'RCT-Folly' in project 'Pods'
        ➜ Explicit dependency on target 'RCTTypeSafety' in project 'Pods'
        ➜ Explicit dependency on target 'React-Core' in project 'Pods'
        ➜ Explicit dependency on target 'React-RCTImage' in project 'Pods'
        ➜ Explicit dependency on target 'React-jsi' in project 'Pods'
        ➜ Explicit dependency on target 'ReactCommon' in project 'Pods'
    Target 'React' in project 'Pods'
        ➜ Explicit dependency on target 'React-Core' in project 'Pods'
        ➜ Explicit dependency on target 'React-RCTActionSheet' in project 'Pods'
        ➜ Explicit dependency on target 'React-RCTAnimation' in project 'Pods'
        ➜ Explicit dependency on target 'React-RCTBlob' in project 'Pods'
        ➜ Explicit dependency on target 'React-RCTImage' in project 'Pods'
        ➜ Explicit dependency on target 'React-RCTLinking' in project 'Pods'
        ➜ Explicit dependency on target 'React-RCTNetwork' in project 'Pods'
        ➜ Explicit dependency on target 'React-RCTSettings' in project 'Pods'
        ➜ Explicit dependency on target 'React-RCTText' in project 'Pods'
        ➜ Exp
    at makeError (/project-path/node_modules/rnv/node_modules/execa/lib/error.js:60:11)
    at handlePromise (/project-path/node_modules/rnv/node_modules/execa/index.js:118:26)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
```

Running the xcode command manually in de `app_ios` directory it gives me an error:

```
>> xcodebuild -workspace RNVApp.xcworkspace -configuration Debug -scheme RNVApp -destination id=5D80CBD7-760B-4F50-B8C9-B563661082DD -derivedDataPath build/RNVApp -allowProvisioningUpdates

/project-path/node_modules/react-native/ReactCommon/yoga/yoga/Yoga.cpp:2232:9: error: use of bitwise '|' with boolean operands [-Werror,-Wbitwise-instead-of-logical]
        node->getLayout().hadOverflow() |
```

When i fixed this i am getting:

```
/project-path/platformBuilds/app_ios/Pods/RCT-Folly/folly/Range.h:93:20: note: in instantiation of template class 'folly::Range<const unsigned char *>' requested here
    const typename Range<Iter>::value_type& needle);
                   ^
/project-path/platformBuilds/app_ios/Pods/RCT-Folly/folly/Range.h:1407:15: note: while substituting deduced template arguments into function template 'qfind' [with Iter = const unsigned char *]
inline size_t qfind(

/project-path/platformBuilds/app_ios/Pods/RCT-Folly/folly/Range.h:1096:16: note: in instantiation of template class 'folly::Range<folly::Range<const char *> *>' requested here
constexpr auto range(Collection& v) -> Range<decltype(v.data())> {
               ^
/project-path/platformBuilds/app_ios/Pods/RCT-Folly/folly/String.cpp:721:17: note: in instantiation of function template specialization 'folly::range<std::vector<folly::Range<const char *>>>' requested here
  auto piecer = range(pieces);
```

**Desktop (please complete the following information):**

-   OS: OSX Ventura 13 and Sonoma 14.1.1 (m1)
-   Node Version: v18.18.2 and v16.17.0
-   RNV Version 0.37.4

**Additional context**
Also checked the following:

- No spaces / uppercase in path
- Removal of /build directory
- Unlinking `react-native-gesture-handler`
- `pod install` in ios directory
- Changing build location to legacy
- Comment `use_flipper()` in pod file
- Running terminal with `Rosetta
- Using only a bare minimum JS (strip down template)

**Comment by VMBindraban** [comment]
Noticed that this version of rnv doesn't support xcode 15.
