### ISSUE TITLE
[Tizen] Tizen certificate is not generated automatically

### ISSUE THREAD

**Issue by GabrieleKaceviciute** [flexn-io/renative#1254]
**Describe the bug**
If you run rnv on debug mode Tizen certificate is not generated and not added to Tizen certificate manager. And app fails to launch.

**To Reproduce**
1. make sure you don’t have certificates added to Tizen certificate manager
2. go to template-starter package
3. do `rnv run -p tizen`
4. check Tizen certificate manager

**Expected behavior**
Certificate should appear in Tizen certificate manager and app should start

**Screenshots or copy&paste**
```
× FAILED: C:\tizen-studio\tools\ide\bin\tizen.bat install -- C:\Users\dev\Desktop\renative\packages\template-starter\platformBuilds\template_tizen\output -n RNVanillaTV.wgt -t T-samsung-7.0-x86
[ error ] [run] COMMAND:

C:\tizen-studio\tools\ide\bin\tizen.bat install -- C:\Users\dev\Desktop\renative\packages\template-starter\platformBuilds\template_tizen\output -n RNVanillaTV.wgt -t T-samsung-7.0-x86

FAILED with ERROR:

app_id[NkVRhWHJST.RNVanillaTV] install failed[118, -12], reason: Check certificate error :
spend time for wascmd is [1769]ms
Failed to install Tizen application.
Total time: 00:00:04.117

Command failed with exit code 1: C:\tizen-studio\tools\ide\bin\tizen.bat install -- C:\Users\dev\Desktop\renative\packages\template-starter\platformBuilds\template_tizen\output -n RNVanillaTV.wgt -t T-samsung-7.0-x86
Transferring the package...
Transferred the package: C:\Users\dev\Desktop\renative\packages\template-starter\platformBuilds\template_tizen\output\RNVanillaTV.wgt -> /home/owner/share/tmp/sdk_tools/tmp
Installing the package...
--------------------
Platform log view
--------------------
install NkVRhWHJST.RNVanillaTV
package_path /home/owner/share/tmp/sdk_tools/tmp/RNVanillaTV.wgt
app_id[NkVRhWHJST.RNVanillaTV] install start
app_id[NkVRhWHJST.RNVanillaTV] installing[2]
app_id[NkVRhWHJST.RNVanillaTV] installing[5]
app_id[NkVRhWHJST.RNVanillaTV] installing[7]
app_id[NkVRhWHJST.RNVanillaTV] installing[10]
app_id[NkVRhWHJST.RNVanillaTV] installing[13]
app_id[NkVRhWHJST.RNVanillaTV] installing[15]
app_id[NkVRhWHJST.RNVanillaTV] installing[18]
app_id[NkVRhWHJST.RNVanillaTV] installing[21]
app_id[NkVRhWHJST.RNVanillaTV] installing[23]
app_id[NkVRhWHJST.RNVanillaTV] install failed[118, -12], reason: Check certificate error :
spend time for wascmd is [1769]ms
Failed to install Tizen application.
Total time: 00:00:04.117

Error: Command failed with exit code 1: C:\tizen-studio\tools\ide\bin\tizen.bat install -- C:\Users\dev\Desktop\renative\packages\template-starter\platformBuilds\template_tizen\output -n RNVanillaTV.wgt -t T-samsung-7.0-x86
Transferring the package...
Transferred the package: C:\Users\dev\Desktop\renative\packages\template-starter\platformBuilds\template_tizen\output\RNVanillaTV.wgt -> /home/owner/share/tmp/sdk_tools/tmp
Installing the package...
--------------------
Platform log view
--------------------
install NkVRhWHJST.RNVanillaTV
package_path /home/owner/share/tmp/sdk_tools/tmp/RNVanillaTV.wgt
app_id[NkVRhWHJST.RNVanillaTV] install start
app_id[NkVRhWHJST.RNVanillaTV] installing[2]
app_id[NkVRhWHJST.RNVanillaTV] installing[5]
app_id[NkVRhWHJST.RNVanillaTV] installing[7]
app_id[NkVRhWHJST.RNVanillaTV] installing[10]
app_id[NkVRhWHJST.RNVanillaTV] installing[13]
app_id[NkVRhWHJST.RNVanillaTV] installing[15]
app_id[NkVRhWHJST.RNVanillaTV] installing[18]
app_id[NkVRhWHJST.RNVanillaTV] installing[21]
app_id[NkVRhWHJST.RNVanillaTV] installing[23]
app_id[NkVRhWHJST.RNVanillaTV] install failed[118, -12], reason: Check certificate error :
spend time for wascmd is [1769]ms
Failed to install Tizen application.
Total time: 00:00:04.117
    at makeError (C:\Users\dev\Desktop\renative\node_modules\execa\lib\error.js:60:11)
    at handlePromise (C:\Users\dev\Desktop\renative\node_modules\execa\index.js:118:26)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)

```

![tizen](https://github.com/flexn-io/renative/assets/106537292/9f0d9a6d-0df0-4def-ae8b-0eee87918913)

**Desktop (please complete the following information):**
-   OS: windows 10 Pro
-   Node Version 18.14.2
-   RNV Version 1.0.0-canary.8
---
- OS: macOS Ventura 13.5.2 (Intel)
- Node Version 18.14.2
- RNV Version 1.0.0-canary.8
---
- OS: macOS Big Sur 11.6 (M1)
- Node Version 18.14.2
- RNV Version 1.0.0-canary.8
---

**Additional context**
Note: Same issue was on 0.37.3

**Comment by pauliusguzas** [comment]
On linux sertifiacte was generated but when laucnhing app still getting same error, so sertificate wasn't generated in correct way probably

**Comment by GabrieleKaceviciute** [comment]
1.0.0-rc.3
Certificate is generated but still getting same error on CLI ->
```
✔ Executing: /Users/gabriele/tizen-studio/tools/ide/bin/tizen uninstall -p NkVRhWHJST.RNVanillaTV -t T-samsung-7.0-x86
✖ FAILED: /Users/gabriele/tizen-studio/tools/ide/bin/tizen install -- /Users/gabriele/Desktop/renative/packages/template-starter/platformBuilds/template_tizen/output -n RNVanillaTV.wgt -t T-samsung-7.0-x86
[ error ] [run] COMMAND:

/Users/gabriele/tizen-studio/tools/ide/bin/tizen install -- /Users/gabriele/Desktop/renative/packages/template-starter/platformBuilds/template_tizen/output -n RNVanillaTV.wgt -t T-samsung-7.0-x86

FAILED with ERROR:

app_id[NkVRhWHJST.RNVanillaTV] install failed[118, -12], reason: Check certificate error : :Invalid certificate chain with certificate in signature.:<-3>
spend time for wascmd is [535]ms
Failed to install Tizen application.
Total time: 00:00:01.323

Command failed with exit code 1: /Users/gabriele/tizen-studio/tools/ide/bin/tizen install -- /Users/gabriele/Desktop/renative/packages/template-starter/platformBuilds/template_tizen/output -n RNVanillaTV.wgt -t T-samsung-7.0-x86
Transferring the package...
Transferred the package: /Users/gabriele/Desktop/renative/packages/template-starter/platformBuilds/template_tizen/output/RNVanillaTV.wgt -> /home/owner/share/tmp/sdk_tools/tmp
Installing the package...
--------------------
Platform log view
--------------------
install NkVRhWHJST.RNVanillaTV
package_path /home/owner/share/tmp/sdk_tools/tmp/RNVanillaTV.wgt
app_id[NkVRhWHJST.RNVanillaTV] install start
app_id[NkVRhWHJST.RNVanillaTV] installing[2]
app_id[NkVRhWHJST.RNVanillaTV] installing[5]
app_id[NkVRhWHJST.RNVanillaTV] installing[7]
app_id[NkVRhWHJST.RNVanillaTV] installing[10]
app_id[NkVRhWHJST.RNVanillaTV] installing[13]
app_id[NkVRhWHJST.RNVanillaTV] installing[15]
app_id[NkVRhWHJST.RNVanillaTV] installing[18]
app_id[NkVRhWHJST.RNVanillaTV] installing[21]
app_id[NkVRhWHJST.RNVanillaTV] installing[23]
app_id[NkVRhWHJST.RNVanillaTV] install failed[118, -12], reason: Check certificate error : :Invalid certificate chain with certificate in signature.:<-3>
spend time for wascmd is [535]ms
Failed to install Tizen application.
Total time: 00:00:01.323

Error: Command failed with exit code 1: /Users/gabriele/tizen-studio/tools/ide/bin/tizen install -- /Users/gabriele/Desktop/renative/packages/template-starter/platformBuilds/template_tizen/output -n RNVanillaTV.wgt -t T-samsung-7.0-x86
Transferring the package...
Transferred the package: /Users/gabriele/Desktop/renative/packages/template-starter/platformBuilds/template_tizen/output/RNVanillaTV.wgt -> /home/owner/share/tmp/sdk_tools/tmp
Installing the package...
--------------------
Platform log view
--------------------
install NkVRhWHJST.RNVanillaTV
package_path /home/owner/share/tmp/sdk_tools/tmp/RNVanillaTV.wgt
app_id[NkVRhWHJST.RNVanillaTV] install start
app_id[NkVRhWHJST.RNVanillaTV] installing[2]
app_id[NkVRhWHJST.RNVanillaTV] installing[5]
app_id[NkVRhWHJST.RNVanillaTV] installing[7]
app_id[NkVRhWHJST.RNVanillaTV] installing[10]
app_id[NkVRhWHJST.RNVanillaTV] installing[13]
app_id[NkVRhWHJST.RNVanillaTV] installing[15]
app_id[NkVRhWHJST.RNVanillaTV] installing[18]
app_id[NkVRhWHJST.RNVanillaTV] installing[21]
app_id[NkVRhWHJST.RNVanillaTV] installing[23]
app_id[NkVRhWHJST.RNVanillaTV] install failed[118, -12], reason: Check certificate error : :Invalid certificate chain with certificate in signature.:<-3>
spend time for wascmd is [535]ms
Failed to install Tizen application.
Total time: 00:00:01.323
    at makeError (/Users/gabriele/Desktop/renative/node_modules/execa/lib/error.js:60:11)
    at handlePromise (/Users/gabriele/Desktop/renative/node_modules/execa/index.js:118:26)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)


[ warn ] [run] There is no emulator or device connected! Let's try to launch it. "rnv target launch -p tizen -t T-samsung-7.0-x86"
[ task ] [run] launchTizenSimulator:T-samsung-7.0-x86[2]
✖ FAILED: /Users/gabriele/tizen-studio/tools/emulator/bin/em-cli launch --name T-samsung-7.0-x86
[ error ] [run] COMMAND:

/Users/gabriele/tizen-studio/tools/emulator/bin/em-cli launch --name T-samsung-7.0-x86

FAILED with ERROR:

Error: Failed to start this VM.
[T-samsung-7.0-x86] is running now...

Command failed with exit code 2: /Users/gabriele/tizen-studio/tools/emulator/bin/em-cli launch --name T-samsung-7.0-x86
Error: Failed to start this VM.
[T-samsung-7.0-x86] is running now...

Error: Command failed with exit code 2: /Users/gabriele/tizen-studio/tools/emulator/bin/em-cli launch --name T-samsung-7.0-x86
Error: Failed to start this VM.
[T-samsung-7.0-x86] is running now...
    at makeError (/Users/gabriele/Desktop/renative/node_modules/execa/lib/error.js:60:11)
    at handlePromise (/Users/gabriele/Desktop/renative/node_modules/execa/index.js:118:26)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
```

**Comment by pauliusguzas** [comment]
Windows OS 1.0.0-rc.3 `npx rnv run -p tizenwatch -t ip` sdb devices do show watch as connected successfully
```
√ Executing: C:\tizen-studio\tools\ide\bin\tizen.bat uninstall -p cHIP2fIRQZ -t SM-R500
× FAILED: C:\tizen-studio\tools\ide\bin\tizen.bat install -- C:\Users\dev\Desktop\renative\packages\template-starter\platformBuilds\template_tizenwatch\output -n RNVanillaWatch.wgt -t SM-R500
[ error ] [run] COMMAND:

C:\tizen-studio\tools\ide\bin\tizen.bat install -- C:\Users\dev\Desktop\renative\packages\template-starter\platformBuilds\template_tizenwatch\output -n RNVanillaWatch.wgt -t SM-R500

FAILED with ERROR:

__return_cb req_id[1] pkg_type[wgt] pkgid[cHIP2fIRQZ] key[error] val[-12] error message: :Non trusted certificate is used. Register valid certificate:<-32>
__return_cb req_id[1] pkg_type[wgt] pkgid[cHIP2fIRQZ] key[end] val[fail]
processing result : Check certificate error [-12] failed
spend time for pkgcmd is [1192]ms

Failed to install Tizen application.
Total time: 00:00:03.908

Command failed with exit code 1: C:\tizen-studio\tools\ide\bin\tizen.bat install -- C:\Users\dev\Desktop\renative\packages\template-starter\platformBuilds\template_tizenwatch\output -n RNVanillaWatch.wgt -t SM-R500
path is /home/owner/share/tmp/sdk_tools/tmp/RNVanillaWatch.wgt
__return_cb req_id[1] pkg_type[wgt] pkgid[cHIP2fIRQZ] key[start] val[install]
__return_cb req_id[1] pkg_type[wgt] pkgid[cHIP2fIRQZ] key[install_percent] val[10]
__return_cb req_id[1] pkg_type[wgt] pkgid[cHIP2fIRQZ] key[install_percent] val[13]
__return_cb req_id[1] pkg_type[wgt] pkgid[cHIP2fIRQZ] key[install_percent] val[16]
__return_cb req_id[1] pkg_type[wgt] pkgid[cHIP2fIRQZ] key[install_percent] val[18]
__return_cb req_id[1] pkg_type[wgt] pkgid[cHIP2fIRQZ] key[install_percent] val[21]
__return_cb req_id[1] pkg_type[wgt] pkgid[cHIP2fIRQZ] key[install_percent] val[24]
__return_cb req_id[1] pkg_type[wgt] pkgid[cHIP2fIRQZ] key[error] val[-12] error message: :Non trusted certificate is used. Register valid certificate:<-32>
__return_cb req_id[1] pkg_type[wgt] pkgid[cHIP2fIRQZ] key[end] val[fail]
processing result : Check certificate error [-12] failed
spend time for pkgcmd is [1192]ms

Failed to install Tizen application.
Total time: 00:00:03.908

Error: Command failed with exit code 1: C:\tizen-studio\tools\ide\bin\tizen.bat install -- C:\Users\dev\Desktop\renative\packages\template-starter\platformBuilds\template_tizenwatch\output -n RNVanillaWatch.wgt -t SM-R500
path is /home/owner/share/tmp/sdk_tools/tmp/RNVanillaWatch.wgt
__return_cb req_id[1] pkg_type[wgt] pkgid[cHIP2fIRQZ] key[start] val[install]
__return_cb req_id[1] pkg_type[wgt] pkgid[cHIP2fIRQZ] key[install_percent] val[10]
__return_cb req_id[1] pkg_type[wgt] pkgid[cHIP2fIRQZ] key[install_percent] val[13]
__return_cb req_id[1] pkg_type[wgt] pkgid[cHIP2fIRQZ] key[install_percent] val[16]
__return_cb req_id[1] pkg_type[wgt] pkgid[cHIP2fIRQZ] key[install_percent] val[18]
__return_cb req_id[1] pkg_type[wgt] pkgid[cHIP2fIRQZ] key[install_percent] val[21]
__return_cb req_id[1] pkg_type[wgt] pkgid[cHIP2fIRQZ] key[install_percent] val[24]
__return_cb req_id[1] pkg_type[wgt] pkgid[cHIP2fIRQZ] key[error] val[-12] error message: :Non trusted certificate is used. Register valid certificate:<-32>
__return_cb req_id[1] pkg_type[wgt] pkgid[cHIP2fIRQZ] key[end] val[fail]
processing result : Check certificate error [-12] failed
spend time for pkgcmd is [1192]ms

Failed to install Tizen application.
Total time: 00:00:03.908
    at makeError (C:\Users\dev\Desktop\renative\node_modules\execa\lib\error.js:60:11)
    at handlePromise (C:\Users\dev\Desktop\renative\node_modules\execa\index.js:118:26)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)


[ warn ] [run] There is no emulator or device connected! Let's try to launch it. "rnv target launch -p tizenwatch -t 192.168.1.31"
[ task ] [run] launchTizenSimulator:192.168.1.31[1]
× FAILED: C:\tizen-studio\tools\emulator\bin\em-cli.bat launch --name 192.168.1.31
[ error ] [run] COMMAND:

C:\tizen-studio\tools\emulator\bin\em-cli.bat launch --name 192.168.1.31

FAILED with ERROR:

Command failed with exit code 2: C:\tizen-studio\tools\emulator\bin\em-cli.bat launch --name 192.168.1.31

Error: Command failed with exit code 2: C:\tizen-studio\tools\emulator\bin\em-cli.bat launch --name 192.168.1.31
    at makeError (C:\Users\dev\Desktop\renative\node_modules\execa\lib\error.js:60:11)
    at handlePromise (C:\Users\dev\Desktop\renative\node_modules\execa\index.js:118:26)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
```

**Comment by pauliusguzas** [comment]
remaining issues moved to https://github.com/flexn-io/renative/issues/1268
