### ISSUE TITLE
[Regression] `rnv new` doesn't work on 1.0.0-rc.2

### ISSUE THREAD

**Issue by GabrieleKaceviciute** [flexn-io/renative#1285]
**Describe the bug**
Can't create new project on rnv 1.0.0-rc.2

**To Reproduce**
1. Install rnv via npm
2. Do `rnv new` -> error `TypeError: Cannot read properties of undefined (reading 'gray')`

**Expected behavior**
Project is created successfully

**Screenshots or copy&paste**
```
➜  ~/Desktop/tests rnv new

/Users/gabriele/.nvm/versions/node/v18.14.2/lib/node_modules/rnv/node_modules/@rnv/cli/lib/logger/index.js:116
    _defaultColor = currentChalk.gray;
                                 ^
TypeError: Cannot read properties of undefined (reading 'gray')
    at _updateDefaultColors (/Users/gabriele/.nvm/versions/node/v18.14.2/lib/node_modules/rnv/node_modules/@rnv/cli/lib/logger/index.js:116:34)
    at Object.<anonymous> (/Users/gabriele/.nvm/versions/node/v18.14.2/lib/node_modules/rnv/node_modules/@rnv/cli/lib/logger/index.js:119:1)
    at Module._compile (node:internal/modules/cjs/loader:1254:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1308:10)
    at Module.load (node:internal/modules/cjs/loader:1117:32)
    at Function.Module._load (node:internal/modules/cjs/loader:958:12)
    at Module.require (node:internal/modules/cjs/loader:1141:19)
    at require (node:internal/modules/cjs/helpers:110:18)
    at Object.<anonymous> (/Users/gabriele/.nvm/versions/node/v18.14.2/lib/node_modules/rnv/node_modules/@rnv/cli/lib/ora.js:82:16)
    at Module._compile (node:internal/modules/cjs/loader:1254:14)
➜  ~/Desktop/tests
```

**Desktop (please complete the following information):**
-   OS: macOS Ventura 13.5.2
-   Node Version 18.14.2
-   RNV Version 1.0.0-rc.2

**Comment by pavjacko** [comment]
@GabrieleKaceviciute RC.2 is corrupted please retest in RC.3

**Comment by GabrieleKaceviciute** [comment]
works on 1.0.0-rc.3
