### ISSUE TITLE
[linux] can't run template starter on linux for first time after bootstrapping 

### ISSUE THREAD

**Issue by GabrieleKaceviciute** [flexn-io/renative#1289]
**Describe the bug**
Can't run app on linux for first time after bootstrapping. After that, from the second time - it works fine.

**To Reproduce**
1. clone renative repo
2. do `yarn bootstrap`
3. go to template-starter package
4. do `npx rnv run -p linux`
 
**Screenshots or copy&paste**
```
? Platform linux is not supported by your project. Would you like to enable it? Yes
[ task ] [platform configure] isBuildSchemeSupported[1]
[ info ] [platform configure] Current Build Scheme: debug
[ task ] [platform configure] checkAndConfigureSdks[1]
[ task ] [platform configure] checkSdk[1]
[ task ] [platform configure] configureRuntimeDefaults[5] appId:template
[ task ] => [platform configure] => [install]
[ hook ] [install] executePipe ('install:before')
[ task ] [install] taskRnvInstall[3] requiresInstall:false:true
[ hook ] [install] executePipe ('install:after')
[ task ] <= [platform configure] <= install
[ task ] [platform configure] [1] taskRnvPlatformConfigure hasBuildFolderPresent:true
[ task ] [platform configure] createPlatformBuild[1]
TypeError: The "path" argument must be of type string. Received undefined
    at new NodeError (node:internal/errors:399:5)
    at validateString (node:internal/validators:163:11)
    at Object.join (node:path:1172:7)
    at /home/testlab-ubuntu/Desktop/renative/packages/core/src/platforms/index.ts:61:29
    at new Promise (<anonymous>)
    at createPlatformBuild (/home/testlab-ubuntu/Desktop/renative/packages/core/src/platforms/index.ts:55:5)
    at /home/testlab-ubuntu/Desktop/renative/packages/engine-core/src/tasks/task.rnv.platform.configure.ts:52:30
    at step (/home/testlab-ubuntu/Desktop/renative/node_modules/tslib/tslib.js:195:27)
    at Object.next (/home/testlab-ubuntu/Desktop/renative/node_modules/tslib/tslib.js:176:57)
    at fulfilled (/home/testlab-ubuntu/Desktop/renative/node_modules/tslib/tslib.js:166:62)
    at processTicksAndRejections (node:internal/process/task_queues:95:5) {
  code: 'ERR_INVALID_ARG_TYPE'
}

 $ npx rnv run -p linux - Done! 🚀
┌──────────────────────────────────────────────────────────────────────────────┐
│  🚀  SUMMARY | 12/13/2023, 10:59:25 AM                                       │
│  $ npx rnv run -p linux                                                      │
├──────────────────────────────────────────────────────────────────────────────┤
│  ReNative Version: 1.0.0-rc.3                                                │
│  Project Name ($package.name): @rnv/template-starter                         │
│  Project Version ($package.version): 1.0.0-rc.3                              │
│  Workspace ($.workspaceID): rnv                                              │
│  Platform (-p): linux                                                        │
│  Engine ($.platforms.linux.engine): engine-rn-electron                       │
│  App Config (-c): template                                                   │
│  Build Scheme (-s): debug                                                    │
│  Supported Platforms: linux(ejected)                                         │
│  Env Info: linux | x64 | node v18.14.2                                       │
│  Executed Time: 0h:0m:11s:586ms                                              │
│                                                                              │
│  All good as 🦄                                                              │
│                                                                              │
└──────────────────────────────────────────────────────────────────────────────┘
testlab-ubuntu@testlabubuntu-KBL-U-Pro-Cubi-3-Silent-S-MS-B159:~/Desktop/renative/packages/template-starter$
```

**Desktop:**
-   OS: Ubuntu 20.04.5
-   Node Version 18.14.2
-   RNV Version 1.0.0-rc.3

**Comment by mihaiblaga89** [comment]
@GabrieleKaceviciute can you retest this with latest rnv please?
