### ISSUE TITLE
[tvos]  app-harness export fails

### ISSUE THREAD

**Issue by GabrieleKaceviciute** [flexn-io/renative#1354]
**Describe the bug**
Can't export app-harness

**To Reproduce**

1. go to app-harness package
2. do `npx rnv export -p tvos -s release -r`

**Screenshots or copy&paste**
[tvos_export.txt](https://github.com/flexn-io/renative/files/14008233/tvos_export.txt)

**Desktop (please complete the following information):**

- OS: macOS Ventura 13.5.2
- Node Version 18.19.0
- RNV Version 1.0.0-rc.9

**Comment by GabrieleKaceviciute** [comment]
1.0.0-rc.12 ->
```
✖ FAILED: bundle exec pod install
┌──────────────────────────────────────────────────────────────────────────────┐
│  🚀  SUMMARY | 2/29/2024, 4:14:40 PM                                         │
│  $ npx rnv export -p tvos -s release -r                                      │
├──────────────────────────────────────────────────────────────────────────────┤
│  ReNative Version: 1.0.0-rc.12                                               │
│  Project Name ($package.name): @rnv/app-harness                              │
│  Project Version ($package.version): 1.0.0-rc.12                             │
│  Workspace ($.workspaceID): rnv                                              │
│  Platform (-p): tvos                                                         │
│  Engine ($.platforms.tvos.engine): engine-rn-tvos                            │
│  Template: @rnv/template-starter@1.0.0-rc.12                                 │
│  App Config (-c): harness                                                    │
│  Build Scheme (-s): release                                                  │
│  Bundle assets ($.platforms.tvos.bundleAssets): true                         │
│  Reset Project (-r): true                                                    │
│  Supported Platforms: tvos                                                   │
│  Env Info: darwin | arm64 | node v18.19.0                                    │
│  Executed Time: 0h:0m:6s:616ms                                               │
│                                                                              │
│ [ error ] [configure] COMMAND:

bundle exec pod install

FAILED with ERROR:

[!] The platform of the target `RNVApp-tvOS` (tvOS 14.0) is not compatible with `RNCPushNotificationIOS (1.11.0)`, which does not support `tvOS`.

Error: Command failed with exit code 1: bundle exec pod install
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 21.1M  100 21.1M    0     0  20.8M      0  0:00:01  0:00:01 --:--:-- 20.8M
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 15.5M  100 15.5M    0     0  18.8M      0 --:--:-- --:--:-- --:--:-- 18.8M
/Users/gabriele/.cocoapods/repos/react-native-tvos-react-native-tvos-podspecs/libevent/2.1.12.1/libevent.podspec:17: warning: already initialized constant Pod::CONFIG_WITHOUT_OPENSSL
/Users/gabriele/.cocoapods/repos/react-native-tvos-react-native-tvos-podspecs/libevent/2.1.12.1/libevent.podspec:17: warning: previous definition of CONFIG_WITHOUT_OPENSSL was here
/Users/gabriele/.cocoapods/repos/react-native-tvos-react-native-tvos-podspecs/libevent/2.1.12.1/libevent.podspec:17: warning: already initialized constant Pod::CONFIG_WITHOUT_OPENSSL
/Users/gabriele/.cocoapods/repos/react-native-tvos-react-native-tvos-podspecs/libevent/2.1.12.1/libevent.podspec:17: warning: previous definition of CONFIG_WITHOUT_OPENSSL was here
Auto-linking React Native modules for target `RNVApp`: RNCPushNotificationIOS, RNGestureHandler, and react-native-orientation-locker
Framework build type is static library
[Codegen] Generating ./build/generated/ios/React-Codegen.podspec.json
Auto-linking React Native modules for target `RNVApp-tvOS`: RNCPushNotificationIOS, RNGestureHandler, and react-native-orientation-locker
Framework build type is static library
[Codegen] Skipping React-Codegen podspec generation.
Analyzing dependencies
Fetching podspec for `DoubleConversion` from `../../../../node_modules/react-native-tvos/third-party-podspecs/DoubleConversion.podspec`
[Codegen] Found FBReactNativeSpec
Fetching podspec for `RCT-Folly` from `../../../../node_modules/react-native-tvos/third-party-podspecs/RCT-Folly.podspec`
[Codegen] Found rncore
Fetching podspec for `boost` from `../../../../node_modules/react-native-tvos/third-party-podspecs/boost.podspec`
Fetching podspec for `fmt` from `../../../../node_modules/react-native-tvos/third-party-podspecs/fmt.podspec`
Fetching podspec for `glog` from `../../../../node_modules/react-native-tvos/third-party-podspecs/glog.podspec`
Fetching podspec for `hermes-engine` from `../../../../node_modules/react-native-tvos/sdks/hermes-engine/hermes-engine.podspec`
[Hermes] Using release tarball from URL: https://repo1.maven.org/maven2/io/github/react-native-tvos/react-native-artifacts/0.73.1-3/react-native-artifacts-0.73.1-3-hermes-ios-debug.tar.gz
[!] The platform of the target `RNVApp-tvOS` (tvOS 14.0) is not compatible with `RNCPushNotificationIOS (1.11.0)`, which does not support `tvOS`.
    at makeError (/Users/gabriele/Desktop/tests/renative/node_modules/execa/lib/error.js:60:11)
    at handlePromise (/Users/gabriele/Desktop/tests/renative/node_modules/execa/index.js:118:26)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)

Auto-linking React Native modules for target `RNVApp`: RNCPushNotificationIOS, RNGestureHandler, and react-native-orientation-locker
Framework build type is static library
[Codegen] Generating ./build/generated/ios/React-Codegen.podspec.json
Auto-linking React Native modules for target `RNVApp-tvOS`: RNCPushNotificationIOS, RNGestureHandler, and react-native-orientation-locker
Framework build type is static library
[Codegen] Skipping React-Codegen podspec generation.
Analyzing dependencies
Fetching podspec for `DoubleConversion` from `../../../../node_modules/react-native-tvos/third-party-podspecs/DoubleConversion.podspec`
[Codegen] Found FBReactNativeSpec
Fetching podspec for `RCT-Folly` from `../../../../node_modules/react-native-tvos/third-party-podspecs/RCT-Folly.podspec`
[Codegen] Found rncore
Fetching podspec for `boost` from `../../../../node_modules/react-native-tvos/third-party-podspecs/boost.podspec`
Fetching podspec for `fmt` from `../../../../node_modules/react-native-tvos/third-party-podspecs/fmt.podspec`
Fetching podspec for `glog` from `../../../../node_modules/react-native-tvos/third-party-podspecs/glog.podspec`
Fetching podspec for `hermes-engine` from `../../../../node_modules/react-native-tvos/sdks/hermes-engine/hermes-engine.podspec`
[Hermes] Using release tarball from URL: https://repo1.maven.org/maven2/io/github/react-native-tvos/react-native-artifacts/0.73.1-3/react-native-artifacts-0.73.1-3-hermes-ios-debug.tar.gz
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 21.1M  100 21.1M    0     0  20.8M      0  0:00:01  0:00:01 --:--:-- 20.8M
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 15.5M  100 15.5M    0     0  18.8M      0 --:--:-- --:--:-- --:--:-- 18.8M
/Users/gabriele/.cocoapods/repos/react-native-tvos-react-native-tvos-podspecs/libevent/2.1.12.1/libevent.podspec:17: warning: already initialized constant Pod::CONFIG_WITHOUT_OPENSSL
/Users/gabriele/.cocoapods/repos/react-native-tvos-react-native-tvos-podspecs/libevent/2.1.12.1/libevent.podspec:17: warning: previous definition of CONFIG_WITHOUT_OPENSSL was here
/Users/gabriele/.cocoapods/repos/react-native-tvos-react-native-tvos-podspecs/libevent/2.1.12.1/libevent.podspec:17: warning: already initialized constant Pod::CONFIG_WITHOUT_OPENSSL
/Users/gabriele/.cocoapods/repos/react-native-tvos-react-native-tvos-podspecs/libevent/2.1.12.1/libevent.podspec:17: warning: previous definition of CONFIG_WITHOUT_OPENSSL was here
[!] The platform of the target `RNVApp-tvOS` (tvOS 14.0) is not compatible with `RNCPushNotificationIOS (1.11.0)`, which does not support `tvOS`.


│                                                                              │
│  Project location:                                                           │
│  ./platformBuilds/harness_tvos/RNVApp.xcworkspace                            │
└──────────────────────────────────────────────────────────────────────────────┘
➜  app-harness git:(1.0.0-rc.12) ✗
```
