### ISSUE TITLE
[ios, tvos] target launch does not launch simulator's ui, only cli sees it as launched

### ISSUE THREAD

**Issue by pauliusguzas** [flexn-io/renative#1381]
**Describe the bug**
Target launch does not launch simulator's ui, only cli sees it as launched

**To Reproduce**
1. Go to template-starter package (or harness)
2. Do `npx rnv target launch -p ios -t valid_target` -> command exits successfully but no sim is open
3. Do same command again -> cli shows that sim is running meaning that it is running but the UI isn't displayed

**Expected behavior**
Simulator with UI opens

**Desktop (please complete the following information):**
-   OS: macOS Ventura 13.5.2
-   Node Version 18.19.0
-   RNV Version 1.0.0-rc.10
-   @rnv/template-starter 1.0.0-rc.10

**Comment by pauliusguzas** [comment]
```
pauliusguzas@MBP-de-Flexn template-starter % npx rnv target launch -p
ios -t

┌──────────────────────────────────────────────────────────────────────────────┐
│                                                                              │
│        ██████╗ ███████╗███╗   ██╗ █████╗ ████████╗██╗██╗   ██╗███████╗       │
│        ██╔══██╗██╔════╝████╗  ██║██╔══██╗╚══██╔══╝██║██║   ██║██╔════╝       │
│        ██████╔╝█████╗  ██╔██╗ ██║███████║   ██║   ██║██║   ██║█████╗         │
│        ██╔══██╗██╔══╝  ██║╚██╗██║██╔══██║   ██║   ██║╚██╗ ██╔╝██╔══╝         │
│        ██║  ██║███████╗██║ ╚████║██║  ██║   ██║   ██║ ╚████╔╝ ███████╗       │
│        ╚═╝  ╚═╝╚══════╝╚═╝  ╚═══╝╚═╝  ╚═╝   ╚═╝   ╚═╝  ╚═══╝  ╚══════╝       │
│                                                                              │
│        Version: 1.0.0-rc.11                                                  │
│        https://renative.org                                                  │
│        🚀 Firing up!...                                                      │
│        $ npx rnv target launch -p ios -t                                     │
│        Start Time: 2/8/2024, 3:50:30 PM                                      │
│                                                                              │
└──────────────────────────────────────────────────────────────────────────────┘

[ task ] registerEngine:engine-core[1]
[ task ] configureRuntimeDefaults[1] appId:undefined
[ task ] checkAndMigrateProject[1]
[ task ] loadPluginTemplates[1]
[ task ] parseRenativeConfigs[1]
[ task ] getWorkspaceDirPath[1]
[ task ] generatePlatformTemplatePaths[1]
[ task ] checkAndBootstrapIfRequired[1]
[ task ] loadIntegrations[1]
[ task ] loadEngines[1]
[ task ] loadEnginePluginDeps[1]
[ task ] loadEnginePackageDeps[1]
[ task ] registerEngine:engine-rn[1]
[ task ] findSuitableTask[1]
[ info ] Current Engine: engine-core path: /Users/pauliusguzas/Desktop/renative/renative/packages/engine-core/lib
[ task ] registerMissingPlatformEngines[1]
[ task ] initializeTask[1] target launch
[ task ] => [target launch]
[ task ] [target launch] taskRnvTargetLaunch[1]
[ task ] [target launch] isPlatformSupported[1]
[ task ] [target launch] checkAndConfigureSdks[1]
[ task ] => [target launch] => [workspace configure]
[ task ] [workspace configure] taskRnvWorkspaceConfigure[1]
[ task ] <= [target launch] <= workspace configure
[ task ] [target launch] checkSdk[1]
[ task ] [target launch] launchAppleSimulator[1] true
[ task ] [target launch] getAppleDevices[1] ignoreDevices:true ignoreSimulators:undefined
✔ Executing: xcrun simctl list --json
? Select the simulator you want to launch iPhone SE (3rd generation) |
 Phone 📱 | v: iOS-16-4 | udid: 9C33B73E-AF8A-412B-9BB6-5B4D12576955
┌──────────────────────────────────────────────────────────────────────────────┐
│  🚀  SUMMARY | 2/8/2024, 3:50:53 PM                                          │
│  $ npx rnv target launch -p ios -t                                           │
├──────────────────────────────────────────────────────────────────────────────┤
│  ReNative Version: 1.0.0-rc.11                                               │
│  Project Name ($package.name): @rnv/template-starter                         │
│  Project Version ($package.version): 1.0.0-rc.11                             │
│  Workspace ($.workspaceID): rnv                                              │
│  Platform (-p): ios                                                          │
│  Engine ($.platforms.ios.engine): engine-core                                │
│  App Config (-c): template                                                   │
│  Build Scheme (-s): debug                                                    │
│  Env Info: darwin | x64 | node v18.17.0                                      │
│  Executed Time: 0h:0m:22s:691ms                                              │
│                                                                              │
│ [ error ] [target launch] COMMAND:

xcrun simctl boot 9C33B73E-AF8A-412B-9BB6-5B4D12576955

FAILED with ERROR:

Error: Command failed with exit code 60: xcrun simctl boot 9C33B73E-AF8A-412B-9BB6-5B4D12576955
An error was encountered processing the command (domain=NSPOSIXErrorDomain, code=60):
Unable to boot the Simulator.
launchd failed to respond.
Underlying error (domain=com.apple.SimLaunchHostService.RequestError, code=4):
	Failed to start launchd_sim: could not bind to session, launchd_sim may have crashed or quit responding
    at makeError (/Users/pauliusguzas/Desktop/renative/renative/node_modules/execa/lib/error.js:60:11)
    at handlePromise (/Users/pauliusguzas/Desktop/renative/renative/node_modules/execa/index.js:118:26)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)


│                                                                              │
└──────────────────────────────────────────────────────────────────────────────┘
pauliusguzas@MBP-de-Flexn template-starter %
```
