### ISSUE TITLE
[Tizen] App is not launched on simulator

### ISSUE THREAD

**Issue by pauliusguzas** [flexn-io/renative#1397]
**Describe the bug**
Can't run tizen on template-starter (current release/1.0)

**To Reproduce**
1. Go to template-starter package
2. Do `npx rnv run -p tizen` -> error

```
pauliusguzas@MBP-de-Flexn template-starter % npx rnv run -p tizen

┌──────────────────────────────────────────────────────────────────────────────┐
│                                                                              │
│        ██████╗ ███████╗███╗   ██╗ █████╗ ████████╗██╗██╗   ██╗███████╗       │
│        ██╔══██╗██╔════╝████╗  ██║██╔══██╗╚══██╔══╝██║██║   ██║██╔════╝       │
│        ██████╔╝█████╗  ██╔██╗ ██║███████║   ██║   ██║██║   ██║█████╗         │
│        ██╔══██╗██╔══╝  ██║╚██╗██║██╔══██║   ██║   ██║╚██╗ ██╔╝██╔══╝         │
│        ██║  ██║███████╗██║ ╚████║██║  ██║   ██║   ██║ ╚████╔╝ ███████╗       │
│        ╚═╝  ╚═╝╚══════╝╚═╝  ╚═══╝╚═╝  ╚═╝   ╚═╝   ╚═╝  ╚═══╝  ╚══════╝       │
│                                                                              │
│        Version: 1.0.0-rc.11                                                  │
│        https://renative.org                                                  │
│        🚀 Firing up!...                                                      │
│        $ npx rnv run -p tizen                                                │
│        Start Time: 2/14/2024, 12:08:45 PM                                    │
│                                                                              │
└──────────────────────────────────────────────────────────────────────────────┘

[ task ] registerEngine:engine-core[1]
[ task ] configureRuntimeDefaults[1] appId:undefined
[ task ] checkAndMigrateProject[1]
[ task ] loadPluginTemplates[1]
[ task ] parseRenativeConfigs[1]
[ task ] getWorkspaceDirPath[1]
[ task ] generatePlatformTemplatePaths[1]
[ task ] checkAndBootstrapIfRequired[1]
[ task ] loadIntegrations[1]
[ task ] loadEngines[1]
[ task ] loadEnginePluginDeps[1]
[ task ] loadEnginePackageDeps[1]
[ task ] registerEngine:engine-rn-web[1]
[ task ] findSuitableTask[1]
[ info ] Current Engine: engine-rn-web path: /Users/pauliusguzas/Desktop/renative/renative/packages/engine-rn-web
[ task ] registerMissingPlatformEngines[1]
[ task ] initializeTask[1] run
[ task ] => [run]
[ task ] [run] checkIfProjectAndNodeModulesExists[1]
[ hook ] [run] executePipe ('run:before')
[ task ] [run] taskRnvRun[1] parent:undefined port:NaN target:undefined hosted:undefined
[ task ] => [run] => [configure]
[ hook ] [configure] executePipe ('configure:before')
[ task ] [configure] taskRnvConfigure[1]
[ task ] => [configure] => [platform configure]
[ hook ] [platform configure] executePipe ('platform:configure:before')
[ task ] [platform configure] taskRnvPlatformConfigure[1]
[ task ] => [platform configure] => [project configure]
[ hook ] [project configure] executePipe ('project:configure:before')
[ task ] [project configure] taskRnvProjectConfigure[1]
[ task ] [project configure] checkAndMigrateProject[2]
[ task ] [project configure] loadPluginTemplates[2]
[ task ] [project configure] parseRenativeConfigs[2]
[ task ] [project configure] getWorkspaceDirPath[2]
[ task ] [project configure] generatePlatformTemplatePaths[2]
[ task ] => [project configure] => [workspace configure]
[ task ] [workspace configure] taskRnvWorkspaceConfigure[1]
[ task ] <= [project configure] <= workspace configure
[ task ] [project configure] checkIfTemplateConfigured[1]
[ task ] => [project configure] => [install]
[ hook ] [install] executePipe ('install:before')
[ task ] [install] taskRnvInstall[1] requiresInstall:false:true
[ hook ] [install] executePipe ('install:after')
[ task ] <= [project configure] <= install
[ task ] [project configure] checkCrypto[1]
[ task ] [project configure] configureRuntimeDefaults[2] appId:template
[ task ] [project configure] applyTemplate[1] @rnv/template-starter=>undefined
[ task ] [project configure] configureRuntimeDefaults[3] appId:template
[ task ] => [project configure] => [install]
[ hook ] [install] executePipe ('install:before')
[ task ] [install] taskRnvInstall[2] requiresInstall:false:true
[ hook ] [install] executePipe ('install:after')
[ task ] <= [project configure] <= install
[ task ] => [project configure] => [app configure]
[ hook ] [app configure] executePipe ('app:configure:before')
[ task ] [app configure] taskRnvAppConfigure[1]
[ task ] [app configure] listAppConfigsFoldersSync[1] ignoreHiddenConfigs:true
[ task ] [app configure] loadPluginTemplates[3]
[ task ] [app configure] parseRenativeConfigs[3]
[ task ] [app configure] generateBuildConfig[1] size:195.57 KB
[ task ] [app configure] getWorkspaceDirPath[3]
[ task ] [app configure] generateBuildConfig[2] size:195.57 KB
[ task ] [app configure] generateBuildConfig[3] size:195.57 KB
[ task ] [app configure] generateBuildConfig[4] size:195.57 KB
[ task ] [app configure] generatePlatformTemplatePaths[3]
[ task ] [app configure] generateBuildConfig[5] size:209.11 KB
[ task ] [app configure] generateBuildConfig[6] size:209.11 KB
[ task ] [app configure] getWorkspaceDirPath[4]
[ task ] [app configure] generateBuildConfig[7] size:209.11 KB
[ task ] [app configure] generateLocalConfig[1] resetAppId:false
[ task ] [app configure] generateBuildConfig[8] size:209.11 KB
[ info ] [app configure] Current App Config: template
[ hook ] [app configure] executePipe ('app:configure:after')
[ task ] <= [project configure] <= app configure
[ task ] [project configure] versionCheck[1]
[ task ] [project configure] versionCheck:rnvRunner:1.0.0-rc.11,rnvProject:1.0.0-rc.11[1]
[ task ] [project configure] configureEngines[1]
[ task ] [project configure] resolvePluginDependants[1]
[ task ] [project configure] configurePlugins[1]
[ task ] [project configure] configureRuntimeDefaults[4] appId:template
[ task ] [project configure] copyRuntimeAssets[1]
[ task ] [project configure] configureTemplateFiles[1]
[ task ] [project configure] checkAndCreateGitignore[1]
[ task ] [project configure] generateRuntimeConfig[1]
[ task ] [project configure] overrideTemplatePlugins[1]
[ task ] [project configure] parsePlugins[1]
[ info ] [project configure] Plugin overrides disabled for: react-native-gesture-handler with disablePluginTemplateOverrides. SKIPPING
[ info ] [project configure] /@react-native-community/cli-platform-ios/build/tools/listIOSDevices.js overriden by: /Users/pauliusguzas/Desktop/renative/renative/packages/rnv/pluginTemplates/@react-native-community/cli-platform-ios/overrides@11.3.7.json
[ info ] [project configure] Plugin overrides disabled for: next with disablePluginTemplateOverrides. SKIPPING
[ task ] [project configure] parseFonts[1]
[ task ] [project configure] parsePlugins[2]
[ hook ] [project configure] executePipe ('project:configure:after')
[ task ] <= [platform configure] <= project configure
[ task ] [platform configure] isPlatformSupported[1]
[ task ] [platform configure] isBuildSchemeSupported[1]
[ info ] [platform configure] Current Build Scheme: debug
[ task ] [platform configure] checkAndConfigureSdks[1]
[ task ] [platform configure] checkAndConfigureTizenSdks:tizen[1]
[ task ] [platform configure] checkSdk[1]
[ task ] [platform configure] checkTizenSdk[1]
[ task ] [platform configure] _isSdkInstalled[1]
[ task ] [platform configure] configureRuntimeDefaults[5] appId:template
[ task ] => [platform configure] => [install]
[ hook ] [install] executePipe ('install:before')
[ task ] [install] taskRnvInstall[3] requiresInstall:false:true
[ hook ] [install] executePipe ('install:after')
[ task ] <= [platform configure] <= install
[ task ] [platform configure] [1] taskRnvPlatformConfigure hasBuildFolderPresent:true
[ task ] [platform configure] createPlatformBuild[1]
[ task ] [platform configure] injectPlatformDependencies[1]
[ task ] [platform configure] injectProjectDependency[1]
[ task ] [platform configure] generateBuildConfig[9] size:208.99 KB
[ info ] [platform configure] Found extra npm dependencies required by engine-rn-web engine. project marked as monorepo. SKIPPING
[ hook ] [platform configure] executePipe ('platform:configure:after')
[ task ] <= [configure] <= platform configure
[ task ] [configure] configureEntryPoint[1]
[ task ] [configure] copySharedPlatforms[1]
[ task ] [configure] configureTizenProject[1]
[ task ] [configure] configureTizenGlobal[1]
✔ Executing: /Users/pauliusguzas/tizen-studio/tools/ide/bin/tizen security-profiles list -n RNVanillaCert
[ task ] [configure] copyAssetsFolder[1]
[ info ] [configure] Found custom assetSources at /Users/pauliusguzas/Desktop/renative/renative/node_modules/@flexn/assets-renative-outline/assets/tizen. Will be used to generate assets.
[ task ] [configure] configureCoreWebProject[1]
[ task ] [configure] _configureProject[1]
[ task ] [configure] copyBuildsFolder[1]
[ task ] [configure] copyTemplatePluginsSync[1] (./platformBuilds/template_tizen)
[ task ] [configure] parsePlugins[3]
[ hook ] [configure] executePipe ('configure:after')
[ task ] <= [run] <= configure
[ task ] [run] _configureHostedIfRequired[1]
[ task ] [run] runTizen[1] target:undefined
[ task ] [run] runTizen[2] target:undefined hosted:false
[ info ] [run] Your tizen devServer at port 8087 is not running. Starting it up for you...
[ task ] [run] waitForHost[1] port:8087
[ task ] [run] runWeb[1] port:8087 debugger:true
[ info ] [run] Your tizen devServerHost 127.0.0.1 at port 8087 is not running. Starting it up for you...
[ task ] [run] _runWebBrowser[1] ip:127.0.0.1 port:8087 openBrowser:false
┌──────────────────────────────────────────────────────────────────────────────┐
│  🚀  BUNDLER STARTED | 2/14/2024, 12:08:48 PM                                │
│  $ npx rnv run -p tizen                                                      │
├──────────────────────────────────────────────────────────────────────────────┤
│  ReNative Version: 1.0.0-rc.11                                               │
│  Project Name ($package.name): @rnv/template-starter                         │
│  Project Version ($package.version): 1.0.0-rc.11                             │
│  Workspace ($.workspaceID): rnv                                              │
│  Platform (-p): tizen                                                        │
│  Engine ($.platforms.tizen.engine): engine-rn-web                            │
│  App Config (-c): template                                                   │
│  Build Scheme (-s): debug                                                    │
│  Target (-t): T-samsung-7.0-x86                                              │
│  Supported Platforms: tizen                                                  │
│  Env Info: darwin | x64 | node v18.17.0                                      │
│  Executed Time: 0h:0m:2s:882ms                                               │
│                                                                              │
│  All good as 🦄                                                              │
│                                                                              │
│  Project location:                                                           │
│  ./platformBuilds/template_tizen                                             │
└──────────────────────────────────────────────────────────────────────────────┘
[ task ] [run] _runWebDevServer[1]
[ task ] [run] parsePlugins[4]
[ warn ] [run] You are missing chii. You can install via npm i -g chii) Trying to use weinre next
[ warn ] [run] You are missing weinre. Skipping debug. install via npm i -g weinre
(node:63574) [DEP_WEBPACK_DEV_SERVER_ON_AFTER_SETUP_MIDDLEWARE] DeprecationWarning: 'onAfterSetupMiddleware' option is deprecated. Please use the 'setupMiddlewares' option.
(Use `node --trace-deprecation ...` to show where the warning was created)
(node:63574) [DEP_WEBPACK_DEV_SERVER_ON_BEFORE_SETUP_MIDDLEWARE] DeprecationWarning: 'onBeforeSetupMiddleware' option is deprecated. Please use the 'setupMiddlewares' option.
Starting the development server...

Compiled successfully!

You can now view @rnv/template-starter in the browser.

  Local:            http://localhost:8087
  On Your Network:  http://192.168.8.181:8087

Note that the development build is not optimized.
To create a production build, use npm run build.

assets by path static/ 2.94 MiB
  asset static/js/bundle.js 2.64 MiB [emitted] (name: main) 1 related asset
  asset static/media/Inter-Light.58a136ec3193fa8a63e5.ttf 303 KiB [emitted] [immutable] [from: appConfigs/base/fonts/Inter-Light.ttf] (auxiliary name: main)
  asset static/media/logo.63d54a55b067ffc3e842.png 12.1 KiB [emitted] [immutable] [from: platformAssets/runtime/logo.png] (auxiliary name: main)
asset index.html 1.77 KiB [emitted]
asset asset-manifest.json 356 bytes [emitted]
runtime modules 28.5 KiB 14 modules
modules by path ./ 1.82 MiB (javascript) 315 KiB (asset)
  modules by path ./node_modules/react-native-web/dist/ 727 KiB 196 modules
  modules by path ./platformAssets/ 3.24 KiB (javascript) 12.1 KiB (asset) 4 modules
  modules by path ./src/ 13.2 KiB 3 modules
  modules by path ./node_modules/react-dom/ 1.07 MiB 3 modules
  modules by path ./node_modules/scheduler/ 19 KiB 2 modules
  + 4 modules
modules by path ../ 519 KiB
  modules by path ../../node_modules/ 467 KiB 159 modules
  modules by path ../renative/lib/ 18.8 KiB 8 modules
  modules by path ../sdk-webpack/node_modules/ 33.9 KiB
    modules by path ../sdk-webpack/node_modules/@pmmmwh/react-refresh-webpack-plugin/ 9.96 KiB 2 modules
    modules by path ../sdk-webpack/node_modules/react-refresh/ 24 KiB 2 modules
webpack 5.90.1 compiled successfully in 3090 ms
Files successfully emitted, waiting for typecheck results...
Issues checking in progress...
✔ Executing: /Users/pauliusguzas/tizen-studio/tools/sdb devices
[ task ] [run] launchTizenSimulator:T-samsung-7.0-x86[1]
⠙ Launch command : "/Users/pauliusguzas/tizen-studio/platforms/tizen-7.0/tv-samsung/emulator/bin/emulator.sh" --conf "/Users
✔ Executing: /Users/pauliusguzas/tizen-studio/tools/emulator/bin/em-cli launch --name T-samsung-7.0-x86
✔ Waiting for emulator to boot...
✔ Executing: /Users/pauliusguzas/tizen-studio/tools/ide/bin/tizen build-web -- /Users/pauliusguzas/Desktop/renative/renative/packages/template-starter/platformBuilds/template_tizen -out /Users/pauliusguzas/Desktop/renative/renative/packages/template-starter/platformBuilds/template_tizen/build
⠙ Executing: /Users/pauliusguzas/tizen-studio/tools/ide/bin/tizen package -- /Users/pauliusguzas/Desktop/renative/renative/packages/template-starter/platformBuilds/template_tizen/build -s RNVanillaCert -t wgt -o /Users/pauliusguzas/Desktop/renative/renative/packages/template-starter/platformBuilds/template_tizen/outputCompiled successfully!

You can now view @rnv/template-starter in the browser.

  Local:            http://localhost:8087
  On Your Network:  http://192.168.8.181:8087

Note that the development build is not optimized.
To create a production build, use npm run build.

assets by status 317 KiB [cached] 3 assets
assets by status 2.64 MiB [emitted]
  assets by chunk 2.64 MiB (name: main)
    asset static/js/bundle.js 2.64 MiB [emitted] (name: main) 1 related asset
    asset main.74bf0fae77e3f425c283.hot-update.js 372 bytes [emitted] [immutable] [hmr] (name: main) 1 related asset
  assets by path *.json 509 bytes
    asset asset-manifest.json 481 bytes [emitted]
    asset main.74bf0fae77e3f425c283.hot-update.json 28 bytes [emitted] [immutable] [hmr]
Entrypoint main 2.64 MiB (2.91 MiB) = static/js/bundle.js 2.64 MiB main.74bf0fae77e3f425c283.hot-update.js 372 bytes 4 auxiliary assets
cached modules 2.33 MiB (javascript) 315 KiB (asset) [cached] 383 modules
⠹ Executing: /Users/pauliusguzas/tizen-studio/tools/ide/bin/tizen package -- /Users/pauliusguzas/Desktop/renative/renative/packages/template-starter/platformBuilds/template_tizen/build -s RNVanillaCert -t wgt -o /Users/pauliusguzas/Desktop/renative
⠼ Package File Location: /Users/pauliusguzas/Desktop/renative/renative/packages/template-starter/platformBuilds/template_tizen/output/RNVanillaTV.wgtCompiled successfully!

You can now view @rnv/template-starter in the browser.

  Local:            http://localhost:8087
  On Your Network:  http://192.168.8.181:8087

Note that the development build is not optimized.
To create a production build, use npm run build.

assets by status 2.95 MiB [cached] 4 assets
asset asset-manifest.json 356 bytes [emitted]
cached modules 2.33 MiB (javascript) 315 KiB (asset) 28.5 KiB (runtime) [cached] 397 modules
webpack 5.90.1 compiled successfully in 2597 ms
✔ Executing: /Users/pauliusguzas/tizen-studio/tools/ide/bin/tizen package -- /Users/pauliusguzas/Desktop/renative/renative/packages/template-starter/platformBuilds/template_tizen/build -s RNVanillaCert -t wgt -o /Users/pauliusguzas/Desktop/renative/renative/packages/template-starter/platformBuilds/template_tizen/output
✔ Executing: /Users/pauliusguzas/tizen-studio/tools/ide/bin/tizen uninstall -p NkVRhWHJST.RNVanillaTV -t T-samsung-7.0-x86
✖ FAILED: /Users/pauliusguzas/tizen-studio/tools/ide/bin/tizen install -- /Users/pauliusguzas/Desktop/renative/renative/packages/template-starter/platformBuilds/template_tizen/output -n RNVanillaTV.wgt -t T-samsung-7.0-x86
[ error ] [run] COMMAND:

/Users/pauliusguzas/tizen-studio/tools/ide/bin/tizen install -- /Users/pauliusguzas/Desktop/renative/renative/packages/template-starter/platformBuilds/template_tizen/output -n RNVanillaTV.wgt -t T-samsung-7.0-x86

FAILED with ERROR:

app_id[NkVRhWHJST.RNVanillaTV] install failed[118, -12], reason: Check certificate error : :Invalid file reference. An unsinged file was found.:<-5>
spend time for wascmd is [1233]ms
Failed to install Tizen application.
Total time: 00:00:03.259

Error: Command failed with exit code 1: /Users/pauliusguzas/tizen-studio/tools/ide/bin/tizen install -- /Users/pauliusguzas/Desktop/renative/renative/packages/template-starter/platformBuilds/template_tizen/output -n RNVanillaTV.wgt -t T-samsung-7.0-x86
Transferring the package...
Transferred the package: /Users/pauliusguzas/Desktop/renative/renative/packages/template-starter/platformBuilds/template_tizen/output/RNVanillaTV.wgt -> /home/owner/share/tmp/sdk_tools/tmp
Installing the package...
--------------------
Platform log view
--------------------
install NkVRhWHJST.RNVanillaTV
package_path /home/owner/share/tmp/sdk_tools/tmp/RNVanillaTV.wgt
app_id[NkVRhWHJST.RNVanillaTV] install start
app_id[NkVRhWHJST.RNVanillaTV] installing[10]
app_id[NkVRhWHJST.RNVanillaTV] installing[13]
app_id[NkVRhWHJST.RNVanillaTV] installing[15]
app_id[NkVRhWHJST.RNVanillaTV] installing[18]
app_id[NkVRhWHJST.RNVanillaTV] installing[21]
app_id[NkVRhWHJST.RNVanillaTV] installing[23]
app_id[NkVRhWHJST.RNVanillaTV] install failed[118, -12], reason: Check certificate error : :Invalid file reference. An unsinged file was found.:<-5>
spend time for wascmd is [1233]ms
Failed to install Tizen application.
Total time: 00:00:03.259
    at makeError (/Users/pauliusguzas/Desktop/renative/renative/node_modules/execa/lib/error.js:60:11)
    at handlePromise (/Users/pauliusguzas/Desktop/renative/renative/node_modules/execa/index.js:118:26)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)


[ warn ] [run] There is no target connected! Let's try to launch it. "rnv target launch -p tizen -t T-samsung-7.0-x86"
[ task ] [run] launchTizenSimulator:T-samsung-7.0-x86[2]
✖ FAILED: /Users/pauliusguzas/tizen-studio/tools/emulator/bin/em-cli launch --name T-samsung-7.0-x86
[ error ] [run] The VM "T-samsung-7.0-x86" is already running.
✔ Waiting for emulator to boot...
✖ FAILED: /Users/pauliusguzas/tizen-studio/tools/ide/bin/tizen run -p NkVRhWHJST.RNVanillaTV -t T-samsung-7.0-x86
[ error ] [run] COMMAND:

/Users/pauliusguzas/tizen-studio/tools/ide/bin/tizen run -p NkVRhWHJST.RNVanillaTV -t T-samsung-7.0-x86

FAILED with ERROR:

Error: Command failed with exit code 1: /Users/pauliusguzas/tizen-studio/tools/ide/bin/tizen run -p NkVRhWHJST.RNVanillaTV -t T-samsung-7.0-x86
Launching the Tizen application...
--------------------
Platform log view
--------------------
The app with ID: NkVRhWHJST.RNVanillaTV is not available for the user 5001
Could not launch the null application.
    at makeError (/Users/pauliusguzas/Desktop/renative/renative/node_modules/execa/lib/error.js:60:11)
    at handlePromise (/Users/pauliusguzas/Desktop/renative/renative/node_modules/execa/index.js:118:26)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)



```

**Expected behavior**
app is launched on simulaor

**Desktop (please complete the following information):**
-   OS: macOS Ventura 13.5.2
-   Node Version 18.19.0
-   RNV Version 1.0.0-rc.11
-   @rnv/template-starter 1.0.0-rc.11

**Comment by pauliusguzas** [comment]
was solved with -r
