### ISSUE TITLE
[tvos] Scheme specified breaks the run

### ISSUE THREAD

**Issue by mihaiblaga89** [flexn-io/renative#1463]
**Describe the bug**
```json
"platform": {
    "tvos": {
        "scheme": "Something else than RNVApp-tvOS"
    }
}
```

would produce the following error. Removing the scheme or setting it to that works

```
info: Current Build Scheme: debug
task: ○ install [3]
task: ✔ install [3]
info: You passed -r argument. "./platformBuilds/template_tvos" CLEANING...DONE
task: ✔ platform configure [1]
info: Found custom assetSources at ../../node_modules/@flexn/assets-create-outline/assets/tvos. Will be used to generate assets.
error: ⨯ ○ configure: Cannot write file. source path doesn't exist: /Users/lego/work/renative/packages/engine-rn-tvos/templates/platforms/tvos/RNVAppTVOS/AppDelegate.mm
error: ⨯ ○ configure: Cannot write file. source path doesn't exist: /Users/lego/work/renative/packages/engine-rn-tvos/templates/platforms/tvos/RNVAppTVOS/AppDelegate.h
error: ⨯ ○ configure: Cannot write file. source path doesn't exist: /Users/lego/work/renative/packages/engine-rn-tvos/templates/platforms/tvos/RNVAppTVOS.xcodeproj/xcshareddata/xcschemes/RNVAppTVOS.xcscheme
info: Podfile.lock does not exist. Will execute pod actions...
✔ Executing: bundle install
✔ Executing: bundle exec pod install
TypeError: Cannot read properties of undefined (reading 'project')
    at pbxProject.pbxXCBuildConfigurationSection (/Users/lego/work/create/node_modules/xcode/lib/pbxProject.js:963:22)
    at pbxProject.updateBuildProperty (/Users/lego/work/create/node_modules/xcode/lib/pbxProject.js:1129:24)
    at pbxProject.<anonymous> (/Users/lego/work/renative/packages/sdk-apple/src/xcodeParser.ts:119:27)
    at pbxProject.emit (node:events:517:28)
    at pbxProject.emit (node:domain:489:12)
    at pbxProject.<anonymous> (/Users/lego/work/create/node_modules/xcode/lib/pbxProject.js:45:18)
    at ChildProcess.emit (node:events:517:28)
    at ChildProcess.emit (node:domain:489:12)
    at emit (node:internal/child_process:944:14)
    at processTicksAndRejections (node:internal/process/task_queues:83:21)
```

**To Reproduce**
Set above scheme to something else rather than RNVApp-tvOS. 

1. Run command '...'
2. See error

**Expected behavior**

**Screenshots or copy&paste**
If applicable, copy&paste the output of the command. **Run the command with `-i` to get more debugging informations**

**Desktop (please complete the following information):**

-   OS: [e.g. osx, windows 7, ubuntu 16.04]
-   Node Version [e.g. v10.16.3]
-   RNV Version [e.g. 0.25.0]

**Additional context**

**Comment by RicardasN** [comment]
There is a line in code indicating, that this feature is deprecated. As confirmed by @mihaiblaga89 this ticket should be considered closed and not worked on. 
https://flexn-io.slack.com/archives/C01QA6CMVH6/p1713803695707469?thread_ts=1713797756.601459&cid=C01QA6CMVH6
