### ISSUE TITLE
[Tizen] run fails on simulator on Windows and Ubuntu

### ISSUE THREAD

**Issue by GabrieleKaceviciute** [flexn-io/renative#1487]
**Describe the bug**
Tizen run fails on template starter and app-harness, tested on release/1.0 branch

**To Reproduce**
1. go to template-starter or app-harness
2. do `npx rnv run -p tizen`

**Expected behavior**
app runs on tizen simulator

**Screenshots or copy&paste**
```
flexn-minion-4@FlexnMion4sMini app-harness % npx rnv run -p tizen

┌─────────────────────────────────────────────────────────────────┐
│ ██████╗ ███████╗███╗   ██╗ █████╗ ████████╗██╗██╗   ██╗███████╗ │
│ ██╔══██╗██╔════╝████╗  ██║██╔══██╗╚══██╔══╝██║██║   ██║██╔════╝ │
│ ██████╔╝█████╗  ██╔██╗ ██║███████║   ██║   ██║██║   ██║█████╗   │
│ ██╔══██╗██╔══╝  ██║╚██╗██║██╔══██║   ██║   ██║╚██╗ ██╔╝██╔══╝   │
│ ██║  ██║███████╗██║ ╚████║██║  ██║   ██║   ██║ ╚████╔╝ ███████╗ │
│ ╚═╝  ╚═╝╚══════╝╚═╝  ╚═══╝╚═╝  ╚═╝   ╚═╝   ╚═╝  ╚═══╝  ╚══════╝ │
│ 🚀 v:1.0.0-rc.12 | renative.org | 4/4/2024, 9:45:09 AM          │
│ $ rnv run -p tizen                                              │
└─────────────────────────────────────────────────────────────────┘
info: Current engine: engine-rn-web (../engine-rn-web)
task: ○ run (1x)
task: ○ configure (1x)
task: ○ platform configure (1x)
task: ○ project configure (1x)
task: ○ workspace configure (1x)
task: ✔ workspace configure
task: ○ app configure (1x)
info: Current app config: harness
task: ✔ app configure
info: ../../node_modules/@react-native-community/cli-platform-ios/build/tools/listIOSDevices.js overriden by: /@rnv/config-templates/pluginTemplates/@react-native-community/cli-platform-ios/overrides@11.3.7.json
info: ../../node_modules/react-native-photo-editor overriden by: /@rnv/config-templates/pluginTemplates/react-native-photo-editor/overrides
info: Plugin overrides disabled for: react-native-permissions with disablePluginTemplateOverrides. SKIPPING
task: ✔ project configure
info: Current Build Scheme: debug
task: ○ sdk configure (1x)
task: ✔ sdk configure
task: ✔ platform configure
✔ Executing: /Users/flexn-minion-4/tizen-studio/tools/ide/bin/tizen security-profiles list -n RNVanillaCert
info: Found custom assetSources at ../../node_modules/@flexn/assets-renative-outline/assets/tizen. Will be used to generate assets.
task: ✔ configure
info: Your tizen devServer at port 8097 is not running. Starting it up for you...
info: Your tizen devServerHost 127.0.0.1 at port 8097 is not running. Starting it up for you...
┌─────────────────────────────────────────────────────────────────┐
│ ✔ BUNDLER STARTED | 4/4/2024, 9:45:13 AM | rnv@1.0.0-rc.12      │
│ $ rnv run -p tizen                                              │
├─────────────────────────────────────────────────────────────────┤
│ Project: @rnv/app-harness@1.0.0-rc.12                           │
│ Workspace: rnv                                                  │
│ Platform (-p): tizen                                            │
│ Engine: engine-rn-web                                           │
│ Template: @rnv/template-starter                                 │
│ App Config (-c): harness                                        │
│ Build Scheme (-s): debug                                        │
│ Target (-t): T-samsung-7.0-x86                                  │
│ Supported Platforms: ios, android, androidtv, firetv, androidwear, web, tizen, tvos, webos, macos, tizenwatch, kaios, chromecast, linux
│ Env Info: darwin | x64 | node v18.19.0                          │
│ Executed Time: 0h:0m:3s:237ms                                   │
│ Project location: ./platformBuilds/harness_tizen                │
└─────────────────────────────────────────────────────────────────┘
warn: ○ run: You are missing chii. You can install via npm i -g chii) Trying to use weinre next
warn: ○ run: You are missing weinre. Skipping debug. install via npm i -g weinre
(node:54675) [DEP_WEBPACK_DEV_SERVER_ON_AFTER_SETUP_MIDDLEWARE] DeprecationWarning: 'onAfterSetupMiddleware' option is deprecated. Please use the 'setupMiddlewares' option.
(Use `node --trace-deprecation ...` to show where the warning was created)
(node:54675) [DEP_WEBPACK_DEV_SERVER_ON_BEFORE_SETUP_MIDDLEWARE] DeprecationWarning: 'onBeforeSetupMiddleware' option is deprecated. Please use the 'setupMiddlewares' option.
Starting the development server...

Compiled successfully!

You can now view @rnv/app-harness in the browser.

  Local:            http://localhost:8097
  On Your Network:  http://192.168.1.8:8097

Note that the development build is not optimized.
To create a production build, use npm run build.

assets by path static/ 3.54 MiB
  asset static/js/bundle.js 3.23 MiB [emitted] (name: main) 1 related asset
  asset static/media/Inter-Light.58a136ec3193fa8a63e5.ttf 303 KiB [emitted] [immutable] [from: appConfigs/base/fonts/Inter-Light.ttf] (auxiliary name: main)
  asset static/media/logo.63d54a55b067ffc3e842.png 12.1 KiB [emitted] [immutable] [from: platformAssets/runtime/logo.png] (auxiliary name: main)
asset index.html 1.77 KiB [emitted]
asset asset-manifest.json 356 bytes [emitted]
runtime modules 28.8 KiB 14 modules
modules by path ../ 896 KiB 452 modules
modules by path ./ 1.83 MiB (javascript) 315 KiB (asset)
  modules by path ./node_modules/react-native-web/dist/ 712 KiB 196 modules
  modules by path ./src/ 32.4 KiB 13 modules
  modules by path ./platformAssets/ 3.32 KiB (javascript) 12.1 KiB (asset)
    javascript modules 3.24 KiB 2 modules
    + 2 modules
  modules by path ./node_modules/react-dom/ 1.07 MiB
    ./node_modules/react-dom/client.js 620 bytes [built] [code generated]
    + 2 modules
  modules by path ./node_modules/scheduler/ 19 KiB
    ./node_modules/scheduler/index.js 197 bytes [built] [code generated]
    ./node_modules/scheduler/cjs/scheduler.development.js 18.8 KiB [built] [code generated]
  + 4 modules
webpack 5.90.1 compiled successfully in 10059 ms
No issues found.
✔ Executing: /Users/flexn-minion-4/tizen-studio/tools/sdb devices
✔ Executing: /Users/flexn-minion-4/tizen-studio/tools/emulator/bin/em-cli launch --name T-samsung-7.0-x86
✔ Waiting for emulator to boot...
✔ Executing: /Users/flexn-minion-4/tizen-studio/tools/ide/bin/tizen build-web -- /Users/flexn-minion-4/Desktop/renative/packages/app-harness/platformBuilds/harness_tizen -out /Users/flexn-minion-4/Desktop/renative/packages/app-harness/platformBuilds/harness_tizen/intermediate
✔ Executing: /Users/flexn-minion-4/tizen-studio/tools/ide/bin/tizen package -- /Users/flexn-minion-4/Desktop/renative/packages/app-harness/platformBuilds/harness_tizen/intermediate -s RNVanillaCert -t wgt -o /Users/flexn-minion-4/Desktop/renative/packages/app-harness/platformBuilds/harness_tizen/output
✔ Executing: /Users/flexn-minion-4/tizen-studio/tools/ide/bin/tizen uninstall -p NkVRhWHJST.RNVanillaTV -t T-samsung-7.0-x86
✖ FAILED: /Users/flexn-minion-4/tizen-studio/tools/ide/bin/tizen install -- /Users/flexn-minion-4/Desktop/renative/packages/app-harness/platformBuilds/harness_tizen/output -n RNVanillaTV.wgt -t T-samsung-7.0-x86
error: ⨯ ○ run: COMMAND:

/Users/flexn-minion-4/tizen-studio/tools/ide/bin/tizen install -- /Users/flexn-minion-4/Desktop/renative/packages/app-harness/platformBuilds/harness_tizen/output -n RNVanillaTV.wgt -t T-samsung-7.0-x86

FAILED with ERROR:

app_id[NkVRhWHJST.RNVanillaTV] install failed[118, -12], reason: Check certificate error : :Invalid certificate chain with certificate in signature.:<-3>
spend time for wascmd is [708]ms
Failed to install Tizen application.
Total time: 00:00:01.468

Error: Command failed with exit code 1: /Users/flexn-minion-4/tizen-studio/tools/ide/bin/tizen install -- /Users/flexn-minion-4/Desktop/renative/packages/app-harness/platformBuilds/harness_tizen/output -n RNVanillaTV.wgt -t T-samsung-7.0-x86
Transferring the package...
Transferred the package: /Users/flexn-minion-4/Desktop/renative/packages/app-harness/platformBuilds/harness_tizen/output/RNVanillaTV.wgt -> /home/owner/share/tmp/sdk_tools/tmp
Installing the package...
--------------------
Platform log view
--------------------
install NkVRhWHJST.RNVanillaTV
package_path /home/owner/share/tmp/sdk_tools/tmp/RNVanillaTV.wgt
app_id[NkVRhWHJST.RNVanillaTV] install start
app_id[NkVRhWHJST.RNVanillaTV] installing[2]
app_id[NkVRhWHJST.RNVanillaTV] installing[5]
app_id[NkVRhWHJST.RNVanillaTV] installing[7]
app_id[NkVRhWHJST.RNVanillaTV] installing[10]
app_id[NkVRhWHJST.RNVanillaTV] installing[13]
app_id[NkVRhWHJST.RNVanillaTV] installing[15]
app_id[NkVRhWHJST.RNVanillaTV] installing[18]
app_id[NkVRhWHJST.RNVanillaTV] installing[21]
app_id[NkVRhWHJST.RNVanillaTV] installing[23]
app_id[NkVRhWHJST.RNVanillaTV] install failed[118, -12], reason: Check certificate error : :Invalid certificate chain with certificate in signature.:<-3>
spend time for wascmd is [708]ms
Failed to install Tizen application.
Total time: 00:00:01.468
    at makeError (/Users/flexn-minion-4/Desktop/renative/node_modules/execa/lib/error.js:60:11)
    at handlePromise (/Users/flexn-minion-4/Desktop/renative/node_modules/execa/index.js:118:26)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)


warn: ○ run: There is no target connected! Let's try to launch it. "rnv target launch -p tizen -t T-samsung-7.0-x86"
✖ FAILED: /Users/flexn-minion-4/tizen-studio/tools/emulator/bin/em-cli launch --name T-samsung-7.0-x86
error: ⨯ ○ run: The VM "T-samsung-7.0-x86" is already running.
✔ Waiting for emulator to boot...
✖ FAILED: /Users/flexn-minion-4/tizen-studio/tools/ide/bin/tizen run -p NkVRhWHJST.RNVanillaTV -t T-samsung-7.0-x86
error: ⨯ ○ run: COMMAND:

/Users/flexn-minion-4/tizen-studio/tools/ide/bin/tizen run -p NkVRhWHJST.RNVanillaTV -t T-samsung-7.0-x86

FAILED with ERROR:

Error: Command failed with exit code 1: /Users/flexn-minion-4/tizen-studio/tools/ide/bin/tizen run -p NkVRhWHJST.RNVanillaTV -t T-samsung-7.0-x86
Launching the Tizen application...
--------------------
Platform log view
--------------------
The app with ID: NkVRhWHJST.RNVanillaTV is not available for the user 5001
Could not launch the null application.
    at makeError (/Users/flexn-minion-4/Desktop/renative/node_modules/execa/lib/error.js:60:11)
    at handlePromise (/Users/flexn-minion-4/Desktop/renative/node_modules/execa/index.js:118:26)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
```

**Desktop (please complete the following information):**

- OS: macOS Ventura 13.2.1 (intel)
- Node Version 18.19.0
- RNV Version 1.0.0-rc.12

**Comment by pauliusguzas** [comment]
this was an environment issue, solved by reinstalling tizen-studio

**Comment by GabrieleKaceviciute** [comment]
1.0.0-rc.19
Issue remains on Windows 10 Pro
