### ISSUE TITLE
`npx rnv run` doesn't work first time after new project creating

### ISSUE THREAD

**Issue by GabrieleKaceviciute** [flexn-io/renative#1508]
**Describe the bug**
`npx rnv run` doesn't work first time after new project creating on 1.0.0-rc.16

**To Reproduce**

1. Install rnv via npm
2. Create new project
3. Do `npx rnv run` -> error

**Screenshots or copy&paste**
```
➜  asd git:(master) ✗ npx rnv run

┌─────────────────────────────────────────────────────────────────┐
│ ██████╗ ███████╗███╗   ██╗ █████╗ ████████╗██╗██╗   ██╗███████╗ │
│ ██╔══██╗██╔════╝████╗  ██║██╔══██╗╚══██╔══╝██║██║   ██║██╔════╝ │
│ ██████╔╝█████╗  ██╔██╗ ██║███████║   ██║   ██║██║   ██║█████╗   │
│ ██╔══██╗██╔══╝  ██║╚██╗██║██╔══██║   ██║   ██║╚██╗ ██╔╝██╔══╝   │
│ ██║  ██║███████╗██║ ╚████║██║  ██║   ██║   ██║ ╚████╔╝ ███████╗ │
│ ╚═╝  ╚═╝╚══════╝╚═╝  ╚═══╝╚═╝  ╚═╝   ╚═╝   ╚═╝  ╚═══╝  ╚══════╝ │
│ $ npx rnv run                                                   │
└─────────────────────────────────────────────────────────────────┘
info: Some engines not installed in your project:
> @rnv/engine-rn-next@1.0.0-rc.16
> @rnv/engine-rn@1.0.0-rc.16
> @rnv/engine-rn-tvos@1.0.0-rc.16
> @rnv/engine-rn-electron@1.0.0-rc.16
> @rnv/engine-rn-web@1.0.0-rc.16
 ADDING TO PACKAGE.JSON...DONE
✔ Executing: yarn
error: ⨯  Error: Cannot find module '/Users/gabriele/Desktop/rnv_new/asd/node_modules/@rnv/engine-rn-next'
Require stack:
- /Users/gabriele/Desktop/rnv_new/asd/node_modules/@rnv/core/lib/engines/index.js
- /Users/gabriele/Desktop/rnv_new/asd/node_modules/@rnv/core/lib/tasks/taskHelpers.js
- /Users/gabriele/Desktop/rnv_new/asd/node_modules/@rnv/core/lib/tasks/taskFinder.js
- /Users/gabriele/Desktop/rnv_new/asd/node_modules/@rnv/core/lib/index.js
- /Users/gabriele/Desktop/rnv_new/asd/node_modules/@rnv/cli/lib/index.js
- /Users/gabriele/Desktop/rnv_new/asd/node_modules/@rnv/cli/lib/bin.js
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:1134:15)
    at Function.Module._load (node:internal/modules/cjs/loader:975:27)
    at Module.require (node:internal/modules/cjs/loader:1225:19)
    at require (node:internal/modules/helpers:177:18)
    at /Users/gabriele/Desktop/rnv_new/asd/node_modules/@rnv/core/src/engines/index.ts:517:21
    at step (/Users/gabriele/Desktop/rnv_new/asd/node_modules/@rnv/core/node_modules/tslib/tslib.js:193:27)
    at Object.next (/Users/gabriele/Desktop/rnv_new/asd/node_modules/@rnv/core/node_modules/tslib/tslib.js:174:57)
    at /Users/gabriele/Desktop/rnv_new/asd/node_modules/@rnv/core/node_modules/tslib/tslib.js:167:75
    at new Promise (<anonymous>)
    at Object.__awaiter (/Users/gabriele/Desktop/rnv_new/asd/node_modules/@rnv/core/node_modules/tslib/tslib.js:163:16)

┌─────────────────────────────────────────────────────────────────┐
│ ⨯ SUMMARY | 4/11/2024, 9:09:03 AM | rnv@                        │
│ $ npx rnv run                                                   │
├─────────────────────────────────────────────────────────────────┤
│ Project: asd@0.1.0                                              │
│ Workspace: rnv                                                  │
│ Build Scheme (-s): debug                                        │
│ Env Info: darwin | arm64 | node v18.19.0                        │
│ Executed Time: 0h:0m:40s:486ms                                  │
│ error: ⨯  Error: Cannot find module '/Users/gabriele/Desktop/rnv_new/asd/node_modules/@rnv/engine-rn-next'
Require stack:
- /Users/gabriele/Desktop/rnv_new/asd/node_modules/@rnv/core/lib/engines/index.js
- /Users/gabriele/Desktop/rnv_new/asd/node_modules/@rnv/core/lib/tasks/taskHelpers.js
- /Users/gabriele/Desktop/rnv_new/asd/node_modules/@rnv/core/lib/tasks/taskFinder.js
- /Users/gabriele/Desktop/rnv_new/asd/node_modules/@rnv/core/lib/index.js
- /Users/gabriele/Desktop/rnv_new/asd/node_modules/@rnv/cli/lib/index.js
- /Users/gabriele/Desktop/rnv_new/asd/node_modules/@rnv/cli/lib/bin.js
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:1134:15)
    at Function.Module._load (node:internal/modules/cjs/loader:975:27)
    at Module.require (node:internal/modules/cjs/loader:1225:19)
    at require (node:internal/modules/helpers:177:18)
    at /Users/gabriele/Desktop/rnv_new/asd/node_modules/@rnv/core/src/engines/index.ts:517:21
    at step (/Users/gabriele/Desktop/rnv_new/asd/node_modules/@rnv/core/node_modules/tslib/tslib.js:193:27)
    at Object.next (/Users/gabriele/Desktop/rnv_new/asd/node_modules/@rnv/core/node_modules/tslib/tslib.js:174:57)
    at /Users/gabriele/Desktop/rnv_new/asd/node_modules/@rnv/core/node_modules/tslib/tslib.js:167:75
    at new Promise (<anonymous>)
    at Object.__awaiter (/Users/gabriele/Desktop/rnv_new/asd/node_modules/@rnv/core/node_modules/tslib/tslib.js:163:16)

└─────────────────────────────────────────────────────────────────┘
➜  asd git:(master)
```

NOTE: if you repeat `npx rnv run` command, it will work successfully ->
```
➜  asd git:(master) ✗ npx rnv run

┌─────────────────────────────────────────────────────────────────┐
│ ██████╗ ███████╗███╗   ██╗ █████╗ ████████╗██╗██╗   ██╗███████╗ │
│ ██╔══██╗██╔════╝████╗  ██║██╔══██╗╚══██╔══╝██║██║   ██║██╔════╝ │
│ ██████╔╝█████╗  ██╔██╗ ██║███████║   ██║   ██║██║   ██║█████╗   │
│ ██╔══██╗██╔══╝  ██║╚██╗██║██╔══██║   ██║   ██║╚██╗ ██╔╝██╔══╝   │
│ ██║  ██║███████╗██║ ╚████║██║  ██║   ██║   ██║ ╚████╔╝ ███████╗ │
│ ╚═╝  ╚═╝╚══════╝╚═╝  ╚═══╝╚═╝  ╚═╝   ╚═╝   ╚═╝  ╚═══╝  ╚══════╝ │
│ $ npx rnv run                                                   │
└─────────────────────────────────────────────────────────────────┘
? Pick a platform for task: "rnv run" (Use arrow keys)
❯ web
  ios
  android
  androidtv
  firetv
  tvos
  macos
```

**Desktop (please complete the following information):**
-   OS: macOS Ventura 13.6.4 (M2)
-   Node Version 18.19.0
-   RNV Version 1.0.0-rc.16
- @rnv/template-starter 1.0.0-rc.16

**Additional context**
New project was created in this way ->
```➜  rnv_new rnv new

┌─────────────────────────────────────────────────────────────────┐
│ ██████╗ ███████╗███╗   ██╗ █████╗ ████████╗██╗██╗   ██╗███████╗ │
│ ██╔══██╗██╔════╝████╗  ██║██╔══██╗╚══██╔══╝██║██║   ██║██╔════╝ │
│ ██████╔╝█████╗  ██╔██╗ ██║███████║   ██║   ██║██║   ██║█████╗   │
│ ██╔══██╗██╔══╝  ██║╚██╗██║██╔══██║   ██║   ██║╚██╗ ██╔╝██╔══╝   │
│ ██║  ██║███████╗██║ ╚████║██║  ██║   ██║   ██║ ╚████╔╝ ███████╗ │
│ ╚═╝  ╚═╝╚══════╝╚═╝  ╚═══╝╚═╝  ╚═╝   ╚═╝   ╚═╝  ╚═══╝  ╚══════╝ │
│ 🚀 v:1.0.0-rc.16 | renative.org | 4/11/2024, 8:55:51 AM         │
│ $ rnv new                                                       │
└─────────────────────────────────────────────────────────────────┘
info: Current engine: engine-core (../../.nvm/versions/node/v18.19.0/lib/node_modules/rnv/node_modules/@rnv/engine-core/lib)
task: ○ new ↺1
? What's your project Name? (folder will be created) qwe
? What workspace to use? rnv
? What template to use? @rnv/template-starter - Multiplatform 'hello world' template
✔ Executing: npm view @rnv/template-starter versions
✔ Executing: npm dist-tag ls @rnv/template-starter
? What @rnv/template-starter version to use? 1.0.0-rc.16 (@next)
✔ Executing: yarn add @rnv/template-starter@1.0.0-rc.16 --dev
✔ Executing: yarn add @rnv/config-templates@1.0.0-rc.16 --dev
? How to create config renative.json? Extend template (cleaner, overridable)
? What's your project Title? qwe
? What's your App ID? com.mycompany.qwe
? What's your project version? 0.1.0
? What platforms would you like to use? web, ios, android, androidtv, firetv, tvos, macos, linux, tizen, webos, chromecast, kaios, androidwear, tizen
watch
? Do you want to set-up git in your new project? Yes
info: Your project does not have a git repo. Creating one...DONE
✔ Executing: git init
info: Missing directory ./qwe/buildHooks.js. COPYING from TEMPATE...DONE
info: Missing directory ./qwe/src/app.js. COPYING from TEMPATE...DONE
info: Missing directory ./qwe/src/entry.js. COPYING from TEMPATE...DONE
info: Missing file ./qwe/src/config.tsx.js. COPYING from TEMPATE...DONE
info: Missing file ./qwe/index.js.js. COPYING from TEMPATE...DONE
info: Missing file ./qwe/tsconfig.json.js. COPYING from TEMPATE...DONE
info: Missing file ./qwe/babel.config.js.js. COPYING from TEMPATE...DONE
info: Missing directory ./qwe/typings.js. COPYING from TEMPATE...DONE
info: Missing file ./qwe/.gitignore.js. COPYING from TEMPATE...DONE
info: Missing directory ./qwe/appConfigs/app.js. COPYING from TEMPATE...DONE
info: Missing directory ./qwe/appConfigs/base/assets.js. COPYING from TEMPATE...DONE
info: Missing directory ./qwe/appConfigs/base/fonts.js. COPYING from TEMPATE...DONE
info: Missing file ./qwe/Gemfile.js. COPYING from TEMPATE...DONE
info: Missing file ./qwe/metro.config.js.js. COPYING from TEMPATE...DONE
info: Missing file ./qwe/react-native.config.js.js. COPYING from TEMPATE...DONE
info: Missing file ./qwe/next.config.js.js. COPYING from TEMPATE...DONE
info: Missing file ./qwe/next-env.d.ts.js. COPYING from TEMPATE...DONE
info: Missing directory ./qwe/src/pages.js. COPYING from TEMPATE...DONE
info: Missing file ./qwe/webpack.config.js.js. COPYING from TEMPATE...DONE
info: .rnv folder missing. CREATING...DONE
info: .rnv/schemas folder missing. CREATING...DONE
info: Updating appConfig app with title: qwe and id: com.mycompany.qwe
? Project is ready. Do you want to install all dependencies now? Yes
✔ Executing: yarn
task: ✔ new
┌─────────────────────────────────────────────────────────────────┐
│ ✔ SUMMARY | 4/11/2024, 8:57:17 AM | rnv@1.0.0-rc.16             │
│ $ rnv new                                                       │
├─────────────────────────────────────────────────────────────────┤
│ Project: qwe@0.1.0                                              │
│ Workspace: rnv                                                  │
│ Engine: engine-core                                             │
│ Template: @rnv/template-starter                                 │
│ Build Scheme (-s): debug                                        │
│ Env Info: darwin | arm64 | node v18.19.0                        │
│ Executed Time: 0h:1m:25s:860ms                                  │
│
  Generated Project Summary:
  -------------------------
  Project Name (--projectName): qwe
  Package name: qwe
  Project Version (--appVersion): 0.1.0
  Workspace (--workspace): rnv
  App Title (--title): qwe
  App ID (--id): com.mycompany.qwe
  Project Template (--template): @rnv/template-starter@1.0.0-rc.16
  Git Enabled (--gitEnabled): true
  Enabled Platforms: web, ios, android, androidtv, firetv, tvos, macos, linux, tizen, webos, chromecast, kaios, androidwear, tizenwatch
  -------------------------
  ✔ Your project is ready! Run it with:

  cd qwe
  npx rnv run
│ You are trying to run global rnv command in your current project.
│ This might lead to unexpected behaviour.
│ Run your rnv command with npx prefix:
│ npx rnv new
└─────────────────────────────────────────────────────────────────┘
➜  rnv_new
```

**Comment by ParvinderjitSF** [comment]
@ElenaDiachenko  Do you guys have any Estimation Date to release the stable version of 1.0.0 ?

**Comment by GabrieleKaceviciute** [comment]
1.0.0-rc.18

```
➜  nauji rnv new

┌─────────────────────────────────────────────────────────────────┐
│ ██████╗ ███████╗███╗   ██╗ █████╗ ████████╗██╗██╗   ██╗███████╗ │
│ ██╔══██╗██╔════╝████╗  ██║██╔══██╗╚══██╔══╝██║██║   ██║██╔════╝ │
│ ██████╔╝█████╗  ██╔██╗ ██║███████║   ██║   ██║██║   ██║█████╗   │
│ ██╔══██╗██╔══╝  ██║╚██╗██║██╔══██║   ██║   ██║╚██╗ ██╔╝██╔══╝   │
│ ██║  ██║███████╗██║ ╚████║██║  ██║   ██║   ██║ ╚████╔╝ ███████╗ │
│ ╚═╝  ╚═╝╚══════╝╚═╝  ╚═══╝╚═╝  ╚═╝   ╚═╝   ╚═╝  ╚═══╝  ╚══════╝ │
│ 🚀 v:1.0.0-rc.18 | renative.org | 5/3/2024, 12:53:42 PM         │
│ $ rnv new                                                       │
└─────────────────────────────────────────────────────────────────┘
info: Current engine: @rnv/engine-core (../../.nvm/versions/node/v18.19.0/lib/node_modules/rnv/node_modules/@rnv/engine-core/lib)
task: ○ new ↺1
? What's your project Name? (folder will be created) pirmas
? What workspace to use? rnv
? What template to use? @rnv/template-starter - Multiplatform 'hello world' template
✔ Executing: npm view @rnv/template-starter versions
✔ Executing: npm dist-tag ls @rnv/template-starter
? What @rnv/template-starter version to use? 1.0.0-rc.18 (@next)
✔ Executing: yarn add @rnv/template-starter@1.0.0-rc.18 --dev
✔ Executing: yarn add @rnv/config-templates@1.0.0-rc.18 --dev
? How to create config renative.json? Extend template (cleaner, overridable)
? What's your project Title? pirmas
? What's your App ID? com.mycompany.pirmas
? What's your project version? 0.1.0
? What platforms would you like to use? web, ios, android, androidtv, firetv, tvos, macos, linux, tizen, webos, chromecast, kaios, androidwear, tizenwatch
? Do you want to set-up git in your new project? Yes
info: Your project does not have a git repo. Creating one...DONE
✔ Executing: git init
info: Missing directory ./pirmas/buildHooks.js. COPYING from TEMPATE...DONE
info: Missing directory ./pirmas/src/app.js. COPYING from TEMPATE...DONE
info: Missing directory ./pirmas/src/entry.js. COPYING from TEMPATE...DONE
info: Missing file ./pirmas/src/config.tsx.js. COPYING from TEMPATE...DONE
info: Missing file ./pirmas/index.js.js. COPYING from TEMPATE...DONE
info: Missing file ./pirmas/tsconfig.json.js. COPYING from TEMPATE...DONE
info: Missing file ./pirmas/babel.config.js.js. COPYING from TEMPATE...DONE
info: Missing directory ./pirmas/typings.js. COPYING from TEMPATE...DONE
info: Missing file ./pirmas/.gitignore.js. COPYING from TEMPATE...DONE
info: Missing directory ./pirmas/appConfigs/app.js. COPYING from TEMPATE...DONE
info: Missing directory ./pirmas/appConfigs/base/assets.js. COPYING from TEMPATE...DONE
info: Missing directory ./pirmas/appConfigs/base/fonts.js. COPYING from TEMPATE...DONE
info: Missing file ./pirmas/Gemfile.js. COPYING from TEMPATE...DONE
info: Missing file ./pirmas/metro.config.js.js. COPYING from TEMPATE...DONE
info: Missing file ./pirmas/react-native.config.js.js. COPYING from TEMPATE...DONE
info: Missing file ./pirmas/next.config.js.js. COPYING from TEMPATE...DONE
info: Missing file ./pirmas/next-env.d.ts.js. COPYING from TEMPATE...DONE
info: Missing directory ./pirmas/src/pages.js. COPYING from TEMPATE...DONE
info: Missing file ./pirmas/webpack.config.js.js. COPYING from TEMPATE...DONE
info: .rnv folder missing. CREATING...DONE
info: .rnv/schemas folder missing. CREATING...DONE
info: Updating appConfig app with title: pirmas and id: com.mycompany.pirmas
? Project is ready. Do you want to install all dependencies now? Yes
✔ Executing: yarn
task: ✔ new
┌─────────────────────────────────────────────────────────────────┐
│ ✔ SUMMARY | 5/3/2024, 12:54:08 PM | rnv@1.0.0-rc.18             │
│ $ rnv new                                                       │
├─────────────────────────────────────────────────────────────────┤
│ Project: pirmas@0.1.0                                           │
│ Workspace: rnv                                                  │
│ Engine: @rnv/engine-core                                        │
│ Template: @rnv/template-starter                                 │
│ Build Scheme (-s): debug                                        │
│ Env Info: darwin | arm64 | node v18.19.0                        │
│ Executed Time: 0h:0m:25s:945ms                                  │
│
  Generated Project Summary:
  -------------------------
  Project Name (--projectName): pirmas
  Package name: pirmas
  Project Version (--appVersion): 0.1.0
  Workspace (--workspace): rnv
  App Title (--title): pirmas
  App ID (--id): com.mycompany.pirmas
  Project Template (--template): @rnv/template-starter@1.0.0-rc.18
  Git Enabled (--gitEnabled): true
  Enabled Platforms: web, ios, android, androidtv, firetv, tvos, macos, linux, tizen, webos, chromecast, kaios, androidwear, tizenwatch
  -------------------------
  ✔ Your project is ready! Run it with:

  cd pirmas
  npx rnv run
│ You are trying to run global rnv command in your current project.
│ This might lead to unexpected behaviour.
│ Run your rnv command with npx prefix:
│ npx rnv new
└─────────────────────────────────────────────────────────────────┘
➜  nauji cd pirmas
RVM used your Gemfile for selecting Ruby, it is all fine - Heroku does that too,
you can ignore these warnings with 'rvm rvmrc warning ignore /Users/gabriele/Desktop/nauji/pirmas/Gemfile'.
To ignore the warning for all files run 'rvm rvmrc warning ignore allGemfiles'.

Unknown ruby interpreter version (do not know how to handle): >=2.6.10.
➜  pirmas git:(master) ✗ npx rnv run

┌─────────────────────────────────────────────────────────────────┐
│ ██████╗ ███████╗███╗   ██╗ █████╗ ████████╗██╗██╗   ██╗███████╗ │
│ ██╔══██╗██╔════╝████╗  ██║██╔══██╗╚══██╔══╝██║██║   ██║██╔════╝ │
│ ██████╔╝█████╗  ██╔██╗ ██║███████║   ██║   ██║██║   ██║█████╗   │
│ ██╔══██╗██╔══╝  ██║╚██╗██║██╔══██║   ██║   ██║╚██╗ ██╔╝██╔══╝   │
│ ██║  ██║███████╗██║ ╚████║██║  ██║   ██║   ██║ ╚████╔╝ ███████╗ │
│ ╚═╝  ╚═╝╚══════╝╚═╝  ╚═══╝╚═╝  ╚═╝   ╚═╝   ╚═╝  ╚═══╝  ╚══════╝ │
│ $ npx rnv run                                                   │
└─────────────────────────────────────────────────────────────────┘
info: Some engines not installed in your project:
> @rnv/engine-rn-next@1.0.0-rc.18
> @rnv/engine-rn@1.0.0-rc.18
> @rnv/engine-rn-tvos@1.0.0-rc.18
> @rnv/engine-rn-electron@1.0.0-rc.18
> @rnv/engine-rn-web@1.0.0-rc.18
 ADDING TO PACKAGE.JSON...DONE
✔ Executing: yarn
error: ⨯  Error: Cannot find module '/Users/gabriele/Desktop/nauji/pirmas/node_modules/readable-stream/readable.js'. Please verify that the package.json has a valid "main" entry
    at tryPackage (node:internal/modules/cjs/loader:437:19)
    at Function.Module._findPath (node:internal/modules/cjs/loader:705:18)
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:1120:27)
    at Function.Module._load (node:internal/modules/cjs/loader:975:27)
    at Module.require (node:internal/modules/cjs/loader:1225:19)
    at require (node:internal/modules/helpers:177:18)
    at Object.<anonymous> (/Users/gabriele/Desktop/nauji/pirmas/node_modules/archiver-utils/index.js:16:19)
    at Module._compile (node:internal/modules/cjs/loader:1356:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1414:10)
    at Module.load (node:internal/modules/cjs/loader:1197:32)
    at Function.Module._load (node:internal/modules/cjs/loader:1013:12)
    at Module.require (node:internal/modules/cjs/loader:1225:19)
    at require (node:internal/modules/helpers:177:18)
    at Object.<anonymous> (/Users/gabriele/Desktop/nauji/pirmas/node_modules/archiver/lib/core.js:12:12)
    at Module._compile (node:internal/modules/cjs/loader:1356:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1414:10)

┌─────────────────────────────────────────────────────────────────┐
│ ⨯ SUMMARY | 5/3/2024, 12:54:36 PM | rnv@                        │
│ $ npx rnv run                                                   │
├─────────────────────────────────────────────────────────────────┤
│ Project: pirmas@0.1.0                                           │
│ Workspace: rnv                                                  │
│ Build Scheme (-s): debug                                        │
│ Env Info: darwin | arm64 | node v18.19.0                        │
│ Executed Time: 0h:0m:15s:905ms                                  │
│ error: ⨯  Error: Cannot find module '/Users/gabriele/Desktop/nauji/pirmas/node_modules/readable-stream/readable.js'. Please verify that the package.json has a valid "main" entry
    at tryPackage (node:internal/modules/cjs/loader:437:19)
    at Function.Module._findPath (node:internal/modules/cjs/loader:705:18)
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:1120:27)
    at Function.Module._load (node:internal/modules/cjs/loader:975:27)
    at Module.require (node:internal/modules/cjs/loader:1225:19)
    at require (node:internal/modules/helpers:177:18)
    at Object.<anonymous> (/Users/gabriele/Desktop/nauji/pirmas/node_modules/archiver-utils/index.js:16:19)
    at Module._compile (node:internal/modules/cjs/loader:1356:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1414:10)
    at Module.load (node:internal/modules/cjs/loader:1197:32)
    at Function.Module._load (node:internal/modules/cjs/loader:1013:12)
    at Module.require (node:internal/modules/cjs/loader:1225:19)
    at require (node:internal/modules/helpers:177:18)
    at Object.<anonymous> (/Users/gabriele/Desktop/nauji/pirmas/node_modules/archiver/lib/core.js:12:12)
    at Module._compile (node:internal/modules/cjs/loader:1356:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1414:10)

└─────────────────────────────────────────────────────────────────┘
➜  pirmas git:(master) ✗
```

**Comment by justinasRm** [comment]
Running `npx rnv run` for the first time in a new project using rc.18 now gives a different error:

```
justinas@Justinass-MacBook-Pro hello-renative % npx rnv run

┌─────────────────────────────────────────────────────────────────┐
│ ██████╗ ███████╗███╗   ██╗ █████╗ ████████╗██╗██╗   ██╗███████╗ │
│ ██╔══██╗██╔════╝████╗  ██║██╔══██╗╚══██╔══╝██║██║   ██║██╔════╝ │
│ ██████╔╝█████╗  ██╔██╗ ██║███████║   ██║   ██║██║   ██║█████╗   │
│ ██╔══██╗██╔══╝  ██║╚██╗██║██╔══██║   ██║   ██║╚██╗ ██╔╝██╔══╝   │
│ ██║  ██║███████╗██║ ╚████║██║  ██║   ██║   ██║ ╚████╔╝ ███████╗ │
│ ╚═╝  ╚═╝╚══════╝╚═╝  ╚═══╝╚═╝  ╚═╝   ╚═╝   ╚═╝  ╚═══╝  ╚══════╝ │
│ $ npx rnv run                                                   │
└─────────────────────────────────────────────────────────────────┘
info: Some engines not installed in your project:
> @rnv/engine-rn-next@1.0.0-rc.18
> @rnv/engine-rn@1.0.0-rc.18
> @rnv/engine-rn-tvos@1.0.0-rc.18
> @rnv/engine-rn-electron@1.0.0-rc.18
> @rnv/engine-rn-web@1.0.0-rc.18
 ADDING TO PACKAGE.JSON...DONE
✔ Executing: yarn
error: ⨯  Error: Cannot find module '/Users/justinas/Documents/repos/hello-renative/node_modules/minipass/index.js'. Please verify that the package.json has a valid "main" entry
    at tryPackage (node:internal/modules/cjs/loader:438:19)
    at Function.Module._findPath (node:internal/modules/cjs/loader:680:18)
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:1063:27)
    at Function.Module._load (node:internal/modules/cjs/loader:922:27)
    at Module.require (node:internal/modules/cjs/loader:1143:19)
    at require (node:internal/modules/cjs/helpers:110:18)
    at Object.<anonymous> (/Users/justinas/Documents/repos/hello-renative/node_modules/path-scurry/src/index.ts:21:1)
    at Module._compile (node:internal/modules/cjs/loader:1256:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1310:10)
    at Module.load (node:internal/modules/cjs/loader:1119:32)
    at Function.Module._load (node:internal/modules/cjs/loader:960:12)
    at Module.require (node:internal/modules/cjs/loader:1143:19)
    at require (node:internal/modules/cjs/helpers:110:18)
    at Object.<anonymous> (/Users/justinas/Documents/repos/hello-renative/node_modules/@appium/support/node_modules/glob/src/glob.ts:3:1)
    at Module._compile (node:internal/modules/cjs/loader:1256:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1310:10)

```

Same as before - if it is ran a second time, it works fine.

**Comment by GabrieleKaceviciute** [comment]
1.0.0-rc.19
```
➜  qwe git:(master) ✗ npx rnv run

┌─────────────────────────────────────────────────────────────────┐
│ ██████╗ ███████╗███╗   ██╗ █████╗ ████████╗██╗██╗   ██╗███████╗ │
│ ██╔══██╗██╔════╝████╗  ██║██╔══██╗╚══██╔══╝██║██║   ██║██╔════╝ │
│ ██████╔╝█████╗  ██╔██╗ ██║███████║   ██║   ██║██║   ██║█████╗   │
│ ██╔══██╗██╔══╝  ██║╚██╗██║██╔══██║   ██║   ██║╚██╗ ██╔╝██╔══╝   │
│ ██║  ██║███████╗██║ ╚████║██║  ██║   ██║   ██║ ╚████╔╝ ███████╗ │
│ ╚═╝  ╚═╝╚══════╝╚═╝  ╚═══╝╚═╝  ╚═╝   ╚═╝   ╚═╝  ╚═══╝  ╚══════╝ │
│ $ npx rnv run                                                   │
└─────────────────────────────────────────────────────────────────┘
info: Some engines not installed in your project:
> @rnv/engine-rn-next@1.0.0-rc.19
> @rnv/engine-rn@1.0.0-rc.19
> @rnv/engine-rn-tvos@1.0.0-rc.19
> @rnv/engine-rn-electron@1.0.0-rc.19
> @rnv/engine-rn-web@1.0.0-rc.19
 ADDING TO PACKAGE.JSON...DONE
✔ Executing: yarn
error: ⨯  Error: Cannot find module '/Users/gabriele/Desktop/nauji/qwe/node_modules/minipass/index.js'. Please verify that the package.json has a valid "main" entry
    at tryPackage (node:internal/modules/cjs/loader:437:19)
    at Function.Module._findPath (node:internal/modules/cjs/loader:705:18)
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:1120:27)
    at Function.Module._load (node:internal/modules/cjs/loader:975:27)
    at Module.require (node:internal/modules/cjs/loader:1225:19)
    at require (node:internal/modules/helpers:177:18)
    at Object.<anonymous> (/Users/gabriele/Desktop/nauji/qwe/node_modules/path-scurry/src/index.ts:21:1)
    at Module._compile (node:internal/modules/cjs/loader:1356:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1414:10)
    at Module.load (node:internal/modules/cjs/loader:1197:32)
    at Function.Module._load (node:internal/modules/cjs/loader:1013:12)
    at Module.require (node:internal/modules/cjs/loader:1225:19)
    at require (node:internal/modules/helpers:177:18)
    at Object.<anonymous> (/Users/gabriele/Desktop/nauji/qwe/node_modules/@appium/support/node_modules/glob/src/glob.ts:3:1)
    at Module._compile (node:internal/modules/cjs/loader:1356:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1414:10)

┌─────────────────────────────────────────────────────────────────┐
│ ⨯ SUMMARY | 5/16/2024, 1:52:38 PM | rnv@                        │
│ $ npx rnv run                                                   │
├─────────────────────────────────────────────────────────────────┤
│ Project: qwe@0.1.0                                              │
│ Workspace: rnv                                                  │
│ Build Scheme (-s): debug                                        │
│ Env Info: darwin | arm64 | node v18.19.0                        │
│ Executed Time: 0h:1m:13s:320ms                                  │
│ error: ⨯  Error: Cannot find module '/Users/gabriele/Desktop/nauji/qwe/node_modules/minipass/index.js'. Please verify that the package.json has a valid "main" entry
    at tryPackage (node:internal/modules/cjs/loader:437:19)
    at Function.Module._findPath (node:internal/modules/cjs/loader:705:18)
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:1120:27)
    at Function.Module._load (node:internal/modules/cjs/loader:975:27)
    at Module.require (node:internal/modules/cjs/loader:1225:19)
    at require (node:internal/modules/helpers:177:18)
    at Object.<anonymous> (/Users/gabriele/Desktop/nauji/qwe/node_modules/path-scurry/src/index.ts:21:1)
    at Module._compile (node:internal/modules/cjs/loader:1356:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1414:10)
    at Module.load (node:internal/modules/cjs/loader:1197:32)
    at Function.Module._load (node:internal/modules/cjs/loader:1013:12)
    at Module.require (node:internal/modules/cjs/loader:1225:19)
    at require (node:internal/modules/helpers:177:18)
    at Object.<anonymous> (/Users/gabriele/Desktop/nauji/qwe/node_modules/@appium/support/node_modules/glob/src/glob.ts:3:1)
    at Module._compile (node:internal/modules/cjs/loader:1356:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1414:10)

└─────────────────────────────────────────────────────────────────┘
➜  qwe git:(master) ✗
```
