### ISSUE TITLE
New project with all default options doesn't work on android and ios

### ISSUE THREAD

**Issue by pauliusguzas** [flexn-io/renative#1564]
**Describe the bug**
New project with all default options doesn't work on android and ios

**To Reproduce**
1. create new project with all default values (not reproduced if all platforms are selected)
2. do `npx rnv run -p android` -> error (due to https://github.com/flexn-io/renative/issues/1508 first time run will fail, so need to rerun)
2. do `npx rnv run -p ios` -> error (due to https://github.com/flexn-io/renative/issues/1508 first time run will fail, so need to rerun)

**Expected behavior**
Android and iOS runs

**Screenshots or copy&paste**
Android:
```
pauliusguzas@MBP-de-Flexn erroras % npx rnv run -p android

┌─────────────────────────────────────────────────────────────────┐
│ ██████╗ ███████╗███╗   ██╗ █████╗ ████████╗██╗██╗   ██╗███████╗ │
│ ██╔══██╗██╔════╝████╗  ██║██╔══██╗╚══██╔══╝██║██║   ██║██╔════╝ │
│ ██████╔╝█████╗  ██╔██╗ ██║███████║   ██║   ██║██║   ██║█████╗   │
│ ██╔══██╗██╔══╝  ██║╚██╗██║██╔══██║   ██║   ██║╚██╗ ██╔╝██╔══╝   │
│ ██║  ██║███████╗██║ ╚████║██║  ██║   ██║   ██║ ╚████╔╝ ███████╗ │
│ ╚═╝  ╚═╝╚══════╝╚═╝  ╚═══╝╚═╝  ╚═╝   ╚═╝   ╚═╝  ╚═══╝  ╚══════╝ │
│ $ npx rnv run -p android                                        │
└─────────────────────────────────────────────────────────────────┘
info: Current engine: @rnv/engine-rn (./node_modules/@rnv/engine-rn)
task: ○ run ↺1
info: Build hooks not complied. BUILDING...
task: ○ configure ↺1
task: ○ platform configure ↺1
task: ○ project configure ↺1
info: Creating folder ./platformBuilds ...DONE
task: ○ workspace configure ↺1
task: ✔ workspace configure
task: ○ app configure ↺1
info: Found only one app config available. Will use app
info: Current app config: app
task: ✔ app configure
task: ✔ project configure
info: Current Build Scheme: debug
task: ○ sdk configure ↺1
task: ✔ sdk configure
warn: ○ platform configure: Updates to package.json are required:
- react (N/A) => (18.2.0) Missing dependency | plugin (renative.json)
- react-art (N/A) => (18.2.0) Missing dependency | plugin (renative.json)
- react-dom (N/A) => (18.2.0) Missing dependency | plugin (renative.json)
- react-native (N/A) => (0.73.4) Missing dependency | plugin (renative.json)
- @rnv/renative (N/A) => (1.0.0-rc.19) Missing dependency | plugin (renative.json)
- react-native-gesture-handler (N/A) => (2.14.1) Missing dependency | plugin (renative.json)

? What to do? Update package and install (recommended)
✔ Executing: yarn
info: ✔ /@react-native-community/cli-platform-ios/build/tools/listIOSDevices.js requires override by: /@rnv/config-templates/pluginTemplates/@react-native-community/cli-platform-ios/overrides@11.3.7.json. FIXING...DONE
info: ✔ /@react-native-community/cli/build/bin.js requires override by: /@rnv/config-templates/pluginTemplates/@react-native-community/cli/overrides.json. FIXING...DONE
task: ✔ platform configure
info: Found custom assetSources at ./node_modules/@flexn/assets-renative-outline/assets/android. Will be used to generate assets.
✔ Executing: npx jetify
task: ✔ configure
✔ Executing: /Users/pauliusguzas/Library/Android/sdk/platform-tools/adb devices -l
✔ Executing: /Users/pauliusguzas/Library/Android/sdk/emulator/emulator -list-avds
✔ Executing: /Users/pauliusguzas/Library/Android/sdk/platform-tools/adb -s 192.168.1.15:5555 shell wm size
✔ Executing: /Users/pauliusguzas/Library/Android/sdk/platform-tools/adb -s 192.168.1.15:5555 shell wm density
✔ Executing: /Users/pauliusguzas/Library/Android/sdk/platform-tools/adb -s 192.168.1.15:5555 shell getprop
✔ Executing: /Users/pauliusguzas/Library/Android/sdk/platform-tools/adb devices -l
✔ Waiting for emulator to boot...
✔ Executing: /Users/pauliusguzas/Library/Android/sdk/platform-tools/adb -s 192.168.1.15:5555 shell wm size
✔ Executing: /Users/pauliusguzas/Library/Android/sdk/platform-tools/adb -s emulator-5554 shell wm size
✔ Executing: /Users/pauliusguzas/Library/Android/sdk/platform-tools/adb -s 192.168.1.15:5555 shell wm density
✔ Executing: /Users/pauliusguzas/Library/Android/sdk/platform-tools/adb -s emulator-5554 shell wm density
✔ Executing: /Users/pauliusguzas/Library/Android/sdk/platform-tools/adb -s emulator-5554 shell getprop
info: ✔ Found active emulator! emulator-5554. Will use it
task: ○ start ↺1
task: ○ configureSoft ↺1
task: ○ app configure ↺2
info: Current app config: app
task: ✔ app configure
info: Current Build Scheme: debug
task: ○ sdk configure ↺2
task: ✔ sdk configure
task: ✔ configureSoft

Dev server running at: http://0.0.0.0:8083/index.bundle?platform=android

task: ✔ start
⠇ Waiting for bundler to finish...warn =================================================================================================
warn From React Native 0.73, your project's Metro config should extend '@react-native/metro-config'
warn or it will fail to build. Please copy the template at:
warn https://github.com/facebook/react-native/blob/main/packages/react-native/template/metro.config.js
warn This warning will be removed in future (https://github.com/facebook/metro/issues/1018).
warn =================================================================================================
info Welcome to React Native v0.73
info Starting dev server on port 8083...

                        ▒▒▓▓▓▓▒▒
                     ▒▓▓▓▒▒░░▒▒▓▓▓▒
                  ▒▓▓▓▓░░░▒▒▒▒░░░▓▓▓▓▒
                 ▓▓▒▒▒▓▓▓▓▓▓▓▓▓▓▓▓▒▒▒▓▓
                 ▓▓░░░░░▒▓▓▓▓▓▓▒░░░░░▓▓
                 ▓▓░░▓▓▒░░░▒▒░░░▒▓▒░░▓▓
                 ▓▓░░▓▓▓▓▓▒▒▒▒▓▓▓▓▒░░▓▓
                 ▓▓░░▓▓▓▓▓▓▓▓▓▓▓▓▓▒░░▓▓
                 ▓▓▒░░▒▒▓▓▓▓▓▓▓▓▒░░░▒▓▓
                  ▒▓▓▓▒░░░▒▓▓▒░░░▒▓▓▓▒
                     ▒▓▓▓▒░░░░▒▓▓▓▒
                        ▒▒▓▓▓▓▒▒


                Welcome to Metro v0.80.9
              Fast - Scalable - Integrated


⠙ Waiting for bundler to finish...info React Native v0.74.1 is now available (your project is running on v0.73.4).
info Changelog: https://github.com/facebook/react-native/releases/tag/v0.74.1
info Diff: https://react-native-community.github.io/upgrade-helper/?from=0.74.1
info For more info, check out "https://reactnative.dev/docs/upgrading?os=macos".
✔ Waiting for bundler to finish...

  WARNING: You should run npx react-native@latest to ensure you're always using the most current version of the CLI. NPX has cached version (0.73.4) != current release (0.74.1)

info Building the app...
Starting a Gradle Daemon (subsequent builds will be faster)
:ReactNative:Unexpected empty result of running '[node, /Users/pauliusguzas/Desktop/erroras/node_modules/@react-native-community/cli/build/bin.js, config]' command.
:ReactNative:Running '[node, /Users/pauliusguzas/Desktop/erroras/node_modules/@react-native-community/cli/build/bin.js, config]' command failed.

FAILURE: Build failed with an exception.

* Where:
Script '/Users/pauliusguzas/Desktop/erroras/node_modules/@react-native-community/cli-platform-android/native_modules.gradle' line: 391

* What went wrong:
A problem occurred evaluating script.
> node:internal/modules/cjs/loader:1080  throw err;  ^Error: Cannot find module 'dotenv'Require stack:- /Users/pauliusguzas/Desktop/erroras/node_modules/@react-native-community/cli/build/bin.js    at Module._resolveFilename (node:internal/modules/cjs/loader:1077:15)    at Module._load (node:internal/modules/cjs/loader:922:27)    at Module.require (node:internal/modules/cjs/loader:1143:19)    at require (node:internal/modules/cjs/helpers:110:18)    at Object.<anonymous> (/Users/pauliusguzas/Desktop/erroras/node_modules/@react-native-community/cli/build/bin.js:4:55)    at Module._compile (node:internal/modules/cjs/loader:1256:14)    at Module._extensions..js (node:internal/modules/cjs/loader:1310:10)    at Module.load (node:internal/modules/cjs/loader:1119:32)    at Module._load (node:internal/modules/cjs/loader:960:12)    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:81:12) {  code: 'MODULE_NOT_FOUND',  requireStack: [    '/Users/pauliusguzas/Desktop/erroras/node_modules/@react-native-community/cli/build/bin.js'  ]}Node.js v18.17.0

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.
> Get more help at https://help.gradle.org.

BUILD FAILED in 5s

info 💡 Tip: Make sure that you have set up your development environment correctly, by running npx react-native doctor. To read more about doctor command visit: https://github.com/react-native-community/cli/blob/main/packages/cli-doctor/README.md#doctor

error Failed to build the app.
Error: Command failed with exit code 1: ./gradlew app:installDebug -x lint -PreactNativeDevServerPort=8083
    at makeError (/Users/pauliusguzas/Desktop/erroras/node_modules/execa/lib/error.js:60:11)
    at Function.module.exports.sync (/Users/pauliusguzas/Desktop/erroras/node_modules/execa/index.js:194:17)
    at build (/Users/pauliusguzas/Desktop/erroras/node_modules/@react-native-community/cli-platform-android/build/commands/buildAndroid/index.js:68:22)
    at runOnSpecificDevice (/Users/pauliusguzas/Desktop/erroras/node_modules/@react-native-community/cli-platform-android/build/commands/runAndroid/index.js:221:33)
    at buildAndRun (/Users/pauliusguzas/Desktop/erroras/node_modules/@react-native-community/cli-platform-android/build/commands/runAndroid/index.js:183:12)
    at Object.runAndroid [as func] (/Users/pauliusguzas/Desktop/erroras/node_modules/@react-native-community/cli-platform-android/build/commands/runAndroid/index.js:116:10)
    at Command.handleAction (/Users/pauliusguzas/Desktop/erroras/node_modules/@react-native-community/cli/build/index.js:118:23)
    at Command.listener [as _actionHandler] (/Users/pauliusguzas/Desktop/erroras/node_modules/@react-native-community/cli/node_modules/commander/lib/command.js:482:17)
    at /Users/pauliusguzas/Desktop/erroras/node_modules/@react-native-community/cli/node_modules/commander/lib/command.js:1283:65
    at Command._chainOrCall (/Users/pauliusguzas/Desktop/erroras/node_modules/@react-native-community/cli/node_modules/commander/lib/command.js:1177:12)
    at Command._parseCommand (/Users/pauliusguzas/Desktop/erroras/node_modules/@react-native-community/cli/node_modules/commander/lib/command.js:1283:27)
    at /Users/pauliusguzas/Desktop/erroras/node_modules/@react-native-community/cli/node_modules/commander/lib/command.js:1081:27
    at Command._chainOrCall (/Users/pauliusguzas/Desktop/erroras/node_modules/@react-native-community/cli/node_modules/commander/lib/command.js:1177:12)
    at Command._dispatchSubcommand (/Users/pauliusguzas/Desktop/erroras/node_modules/@react-native-community/cli/node_modules/commander/lib/command.js:1077:23)
    at Command._parseCommand (/Users/pauliusguzas/Desktop/erroras/node_modules/@react-native-community/cli/node_modules/commander/lib/command.js:1248:19)
    at Command.parse (/Users/pauliusguzas/Desktop/erroras/node_modules/@react-native-community/cli/node_modules/commander/lib/command.js:909:10)
info Run CLI with --verbose flag for more details.
error: ⨯ ○ run: COMMAND:

node  /Users/pauliusguzas/Desktop/erroras/node_modules/react-native/cli.js run-android --mode=Debug --no-packager --main-activity=SplashActivity --deviceId=emulator-5554

FAILED with ERROR:

Error: Command failed with exit code 1: node /Users/pauliusguzas/Desktop/erroras/node_modules/react-native/cli.js run-android --mode=Debug --no-packager --main-activity=SplashActivity --deviceId=emulator-5554
    at makeError (/Users/pauliusguzas/Desktop/erroras/node_modules/execa/lib/error.js:60:11)
    at handlePromise (/Users/pauliusguzas/Desktop/erroras/node_modules/execa/index.js:118:26)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)


┌─────────────────────────────────────────────────────────────────┐
│ ⨯ SUMMARY | 5/21/2024, 10:19:26 PM | rnv@                       │
│ $ npx rnv run -p android                                        │
├─────────────────────────────────────────────────────────────────┤
│ Project: erroras@0.1.0                                          │
│ Workspace: rnv                                                  │
│ Platform (-p): android                                          │
│ Engine: @rnv/engine-rn                                          │
│ Template: @rnv/template-starter                                 │
│ App Config (-c): app                                            │
│ Build Scheme (-s): debug                                        │
│ Target (-t): Pixel_4_API_29                                     │
│ Supported Platforms: web, ios, android                          │
│ Env Info: darwin | x64 | node v18.17.0                          │
│ Executed Time: 0h:0m:53s:335ms                                  │
│ warn: ○ platform configure: Updates to package.json are required:
│ info: ✔ /@react-native-community/cli-platform-ios/build/tools/listIOSDevices.js requires override by: /@rnv/config-templates/pluginTemplates/@react-native-community/cli-platform-ios/overrides@11.3.7.json. FIXING...DONE
│ info: ✔ /@react-native-community/cli/build/bin.js requires override by: /@rnv/config-templates/pluginTemplates/@react-native-community/cli/overrides.json. FIXING...DONE
│ info: ✔ Found active emulator! emulator-5554. Will use it
│ error: ⨯ ○ run: COMMAND:

node  /Users/pauliusguzas/Desktop/erroras/node_modules/react-native/cli.js run-android --mode=Debug --no-packager --main-activity=SplashActivity --deviceId=emulator-5554

FAILED with ERROR:

Error: Command failed with exit code 1: node /Users/pauliusguzas/Desktop/erroras/node_modules/react-native/cli.js run-android --mode=Debug --no-packager --main-activity=SplashActivity --deviceId=emulator-5554
    at makeError (/Users/pauliusguzas/Desktop/erroras/node_modules/execa/lib/error.js:60:11)
    at handlePromise (/Users/pauliusguzas/Desktop/erroras/node_modules/execa/index.js:118:26)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)


│ Project location: ./platformBuilds/app_android                  │
└─────────────────────────────────────────────────────────────────┘
error: ⨯ ○ run: COMMAND:

node /Users/pauliusguzas/Desktop/erroras/node_modules/react-native/local-cli/cli.js start --port 8083 --no-interactive --config=metro.config.js

FAILED with ERROR:

Error: Command was killed with SIGTERM (Termination): node /Users/pauliusguzas/Desktop/erroras/node_modules/react-native/local-cli/cli.js start --port 8083 --no-interactive --config=metro.config.js
    at makeError (/Users/pauliusguzas/Desktop/erroras/node_modules/execa/lib/error.js:60:11)
    at handlePromise (/Users/pauliusguzas/Desktop/erroras/node_modules/execa/index.js:118:26)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
```
iOS:
```
pauliusguzas@MBP-de-Flexn erroras % npx rnv run -p ios

┌─────────────────────────────────────────────────────────────────┐
│ ██████╗ ███████╗███╗   ██╗ █████╗ ████████╗██╗██╗   ██╗███████╗ │
│ ██╔══██╗██╔════╝████╗  ██║██╔══██╗╚══██╔══╝██║██║   ██║██╔════╝ │
│ ██████╔╝█████╗  ██╔██╗ ██║███████║   ██║   ██║██║   ██║█████╗   │
│ ██╔══██╗██╔══╝  ██║╚██╗██║██╔══██║   ██║   ██║╚██╗ ██╔╝██╔══╝   │
│ ██║  ██║███████╗██║ ╚████║██║  ██║   ██║   ██║ ╚████╔╝ ███████╗ │
│ ╚═╝  ╚═╝╚══════╝╚═╝  ╚═══╝╚═╝  ╚═╝   ╚═╝   ╚═╝  ╚═══╝  ╚══════╝ │
│ $ npx rnv run -p ios                                            │
└─────────────────────────────────────────────────────────────────┘
info: Current engine: @rnv/engine-rn (./node_modules/@rnv/engine-rn)
task: ○ run ↺1
task: ○ configure ↺1
task: ○ platform configure ↺1
task: ○ project configure ↺1
task: ○ workspace configure ↺1
task: ✔ workspace configure
task: ○ app configure ↺1
info: Current app config: app
task: ✔ app configure
info: ./node_modules/@react-native-community/cli-platform-ios/build/tools/listIOSDevices.js overriden by: /@rnv/config-templates/pluginTemplates/@react-native-community/cli-platform-ios/overrides@11.3.7.json
info: ./node_modules/@react-native-community/cli/build/bin.js overriden by: /@rnv/config-templates/pluginTemplates/@react-native-community/cli/overrides.json
task: ✔ project configure
info: Current Build Scheme: debug
task: ✔ platform configure
info: Found custom assetSources at ./node_modules/@flexn/assets-renative-outline/assets/ios. Will be used to generate assets.
info: Podfile.lock does not exist. Will execute pod actions...
✔ Executing: bundle install
✖ FAILED: bundle exec pod install
error: ⨯ ○ configure: COMMAND:

bundle exec pod install

FAILED with ERROR:

Error: Cannot find module 'dotenv'
Require stack:
- /Users/pauliusguzas/Desktop/erroras/node_modules/@react-native-community/cli/build/bin.js
 at Module._resolveFilename (node:internal/modules/cjs/loader:1077:15)
 at Module._load (node:internal/modules/cjs/loader:922:27)
 at Module.require (node:internal/modules/cjs/loader:1143:19)
 at require (node:internal/modules/cjs/helpers:110:18)
 at Object.<anonymous> (/Users/pauliusguzas/Desktop/erroras/node_modules/@react-native-community/cli/build/bin.js:4:55)
 at Module._compile (node:internal/modules/cjs/loader:1256:14)
 at Module._extensions..js (node:internal/modules/cjs/loader:1310:10)
 at Module.load (node:internal/modules/cjs/loader:1119:32)
 at Module._load (node:internal/modules/cjs/loader:960:12)
 at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:81:12) {
 '/Users/pauliusguzas/Desktop/erroras/node_modules/@react-native-community/cli/build/bin.js'
 ]
}
Node.js v18.17.0
[!] Invalid `Podfile` file: unexpected token at ''.
 # from /Users/pauliusguzas/Desktop/erroras/platformBuilds/app_ios/Podfile:38
 # -------------------------------------------
 # target 'RNVApp' do
 > config = use_native_modules!
 #
 # -------------------------------------------

Error: Command failed with exit code 1: bundle exec pod install
node:internal/modules/cjs/loader:1080
  throw err;
  ^

Error: Cannot find module 'dotenv'
Require stack:
- /Users/pauliusguzas/Desktop/erroras/node_modules/@react-native-community/cli/build/bin.js
    at Module._resolveFilename (node:internal/modules/cjs/loader:1077:15)
    at Module._load (node:internal/modules/cjs/loader:922:27)
    at Module.require (node:internal/modules/cjs/loader:1143:19)
    at require (node:internal/modules/cjs/helpers:110:18)
    at Object.<anonymous> (/Users/pauliusguzas/Desktop/erroras/node_modules/@react-native-community/cli/build/bin.js:4:55)
    at Module._compile (node:internal/modules/cjs/loader:1256:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1310:10)
    at Module.load (node:internal/modules/cjs/loader:1119:32)
    at Module._load (node:internal/modules/cjs/loader:960:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:81:12) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/Users/pauliusguzas/Desktop/erroras/node_modules/@react-native-community/cli/build/bin.js'
  ]
}

Node.js v18.17.0

[!] Invalid `Podfile` file: unexpected token at ''.

 #  from /Users/pauliusguzas/Desktop/erroras/platformBuilds/app_ios/Podfile:38
 #  -------------------------------------------
 #  target 'RNVApp' do
 >    config = use_native_modules!
 #
 #  -------------------------------------------
    at makeError (/Users/pauliusguzas/Desktop/erroras/node_modules/execa/lib/error.js:60:11)
    at handlePromise (/Users/pauliusguzas/Desktop/erroras/node_modules/execa/index.js:118:26)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)


┌─────────────────────────────────────────────────────────────────┐
│ ⨯ SUMMARY | 5/21/2024, 10:20:46 PM | rnv@                       │
│ $ npx rnv run -p ios                                            │
├─────────────────────────────────────────────────────────────────┤
│ Project: erroras@0.1.0                                          │
│ Workspace: rnv                                                  │
│ Platform (-p): ios                                              │
│ Engine: @rnv/engine-rn                                          │
│ Template: @rnv/template-starter                                 │
│ App Config (-c): app                                            │
│ Build Scheme (-s): debug                                        │
│ Target (-t): iPhone 14                                          │
│ Supported Platforms: web, ios, android                          │
│ Env Info: darwin | x64 | node v18.17.0                          │
│ Executed Time: 0h:0m:6s:191ms                                   │
│ error: ⨯ ○ configure: COMMAND:

bundle exec pod install

FAILED with ERROR:

Error: Cannot find module 'dotenv'
Require stack:
- /Users/pauliusguzas/Desktop/erroras/node_modules/@react-native-community/cli/build/bin.js
 at Module._resolveFilename (node:internal/modules/cjs/loader:1077:15)
 at Module._load (node:internal/modules/cjs/loader:922:27)
 at Module.require (node:internal/modules/cjs/loader:1143:19)
 at require (node:internal/modules/cjs/helpers:110:18)
 at Object.<anonymous> (/Users/pauliusguzas/Desktop/erroras/node_modules/@react-native-community/cli/build/bin.js:4:55)
 at Module._compile (node:internal/modules/cjs/loader:1256:14)
 at Module._extensions..js (node:internal/modules/cjs/loader:1310:10)
 at Module.load (node:internal/modules/cjs/loader:1119:32)
 at Module._load (node:internal/modules/cjs/loader:960:12)
 at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:81:12) {
 '/Users/pauliusguzas/Desktop/erroras/node_modules/@react-native-community/cli/build/bin.js'
 ]
}
Node.js v18.17.0
[!] Invalid `Podfile` file: unexpected token at ''.
 # from /Users/pauliusguzas/Desktop/erroras/platformBuilds/app_ios/Podfile:38
 # -------------------------------------------
 # target 'RNVApp' do
 > config = use_native_modules!
 #
 # -------------------------------------------

Error: Command failed with exit code 1: bundle exec pod install
node:internal/modules/cjs/loader:1080
  throw err;
  ^

Error: Cannot find module 'dotenv'
Require stack:
- /Users/pauliusguzas/Desktop/erroras/node_modules/@react-native-community/cli/build/bin.js
    at Module._resolveFilename (node:internal/modules/cjs/loader:1077:15)
    at Module._load (node:internal/modules/cjs/loader:922:27)
    at Module.require (node:internal/modules/cjs/loader:1143:19)
    at require (node:internal/modules/cjs/helpers:110:18)
    at Object.<anonymous> (/Users/pauliusguzas/Desktop/erroras/node_modules/@react-native-community/cli/build/bin.js:4:55)
    at Module._compile (node:internal/modules/cjs/loader:1256:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1310:10)
    at Module.load (node:internal/modules/cjs/loader:1119:32)
    at Module._load (node:internal/modules/cjs/loader:960:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:81:12) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/Users/pauliusguzas/Desktop/erroras/node_modules/@react-native-community/cli/build/bin.js'
  ]
}

Node.js v18.17.0

[!] Invalid `Podfile` file: unexpected token at ''.

 #  from /Users/pauliusguzas/Desktop/erroras/platformBuilds/app_ios/Podfile:38
 #  -------------------------------------------
 #  target 'RNVApp' do
 >    config = use_native_modules!
 #
 #  -------------------------------------------
    at makeError (/Users/pauliusguzas/Desktop/erroras/node_modules/execa/lib/error.js:60:11)
    at handlePromise (/Users/pauliusguzas/Desktop/erroras/node_modules/execa/index.js:118:26)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)


│ Project location: ./platformBuilds/app_ios/RNVApp.xcworkspace   │
└─────────────────────────────────────────────────────────────────┘
pauliusguzas@MBP-de-Flexn erroras %
```

**Desktop (please complete the following information):**
-   OS: macOS Ventura
-   Node Version 18.19.0
-   RNV Version 1.0.0-rc.19
-   rnv/app-harness Version 1.0.0-rc.19

**Comment by Marius456** [comment]
Fixed in https://github.com/flexn-io/renative/pull/1555
