### ISSUE TITLE
[Regression] [iOS] fails to run app via `npx rnv`

### ISSUE THREAD

**Issue by GabrieleKaceviciute** [flexn-io/renative#1568]
**Describe the bug**
Fails to run app via `npx rnv` on ios. Note `npx rnv run -p ios` works fine

**To Reproduce**
1. Install rnv via npm
2. Create new project
3. Do `npx rnv` 
4. Choose `run`
5. Pick `web` platform ->  rnv asks to update packages - update -> pass
6. Do `npx rnv`
7. Choose `run`
8. Pick `ios`-> error

**Expected behavior**
App launches on simulator

**Screenshots or copy&paste**
```
➜  naujas git:(master) ✗ npx rnv

┌─────────────────────────────────────────────────────────────────┐
│ ██████╗ ███████╗███╗   ██╗ █████╗ ████████╗██╗██╗   ██╗███████╗ │
│ ██╔══██╗██╔════╝████╗  ██║██╔══██╗╚══██╔══╝██║██║   ██║██╔════╝ │
│ ██████╔╝█████╗  ██╔██╗ ██║███████║   ██║   ██║██║   ██║█████╗   │
│ ██╔══██╗██╔══╝  ██║╚██╗██║██╔══██║   ██║   ██║╚██╗ ██╔╝██╔══╝   │
│ ██║  ██║███████╗██║ ╚████║██║  ██║   ██║   ██║ ╚████╔╝ ███████╗ │
│ ╚═╝  ╚═╝╚══════╝╚═╝  ╚═══╝╚═╝  ╚═╝   ╚═╝   ╚═╝  ╚═══╝  ╚══════╝ │
│ $ npx rnv                                                       │
└─────────────────────────────────────────────────────────────────┘
? Pick a command run...
? Pick a platform ios
info: Current engine: @rnv/engine-rn (./node_modules/@rnv/engine-rn)
task: ○ run ↺1
task: ○ configure ↺1
task: ○ platform configure ↺1
task: ○ project configure ↺1
task: ○ workspace configure ↺1
task: ✔ workspace configure
task: ○ app configure ↺1
info: Current app config: app
task: ✔ app configure
info: ./node_modules/@react-native-community/cli-platform-ios/build/tools/listIOSDevices.js overriden by: /@rnv/config-templates/pluginTemplates/@react-native-community/cli-platform-ios/overrides@11.3.7.json
info: ./node_modules/@react-native-community/cli/build/bin.js overriden by: /@rnv/config-templates/pluginTemplates/@react-native-community/cli/overrides.json
info: ./node_modules/react-native-tvos/Libraries/Components/ScrollView/ScrollViewNativeComponent.js overriden by: /@rnv/config-templates/pluginTemplates/react-native-tvos/overrides.json
info: ./node_modules/react-native-tvos/Libraries/Components/ScrollView/ScrollViewNativeComponent.js overriden by: /@rnv/config-templates/pluginTemplates/react-native-tvos/overrides.json
info: ./node_modules/react-native-tvos/Libraries/Components/ScrollView/ScrollViewNativeComponent.js overriden by: /@rnv/config-templates/pluginTemplates/react-native-tvos/overrides.json
task: ✔ project configure
info: Current Build Scheme: debug
task: ✔ platform configure
info: Found custom assetSources at ./node_modules/@flexn/assets-renative-outline/assets/ios. Will be used to generate assets.
info: Skipping pod action. Reason: Podfile.checksum matches current value
task: ✔ configure
✔ Executing: xcrun simctl list --json
task: ○ start ↺1
task: ○ configureSoft ↺1
task: ○ app configure ↺2
info: Current app config: app
task: ✔ app configure
info: Current Build Scheme: debug
task: ✔ configureSoft

Dev server running at: http://0.0.0.0:8082/index.bundle?platform=ios

task: ✔ start
⠇ Waiting for bundler to finish...warn =================================================================================================
warn From React Native 0.73, your project's Metro config should extend '@react-native/metro-config'
warn or it will fail to build. Please copy the template at:
warn https://github.com/facebook/react-native/blob/main/packages/react-native/template/metro.config.js
warn This warning will be removed in future (https://github.com/facebook/metro/issues/1018).
warn =================================================================================================
info Welcome to React Native v0.73
info Starting dev server on port 8082...

                        ▒▒▓▓▓▓▒▒
                     ▒▓▓▓▒▒░░▒▒▓▓▓▒
                  ▒▓▓▓▓░░░▒▒▒▒░░░▓▓▓▓▒
                 ▓▓▒▒▒▓▓▓▓▓▓▓▓▓▓▓▓▒▒▒▓▓
                 ▓▓░░░░░▒▓▓▓▓▓▓▒░░░░░▓▓
                 ▓▓░░▓▓▒░░░▒▒░░░▒▓▒░░▓▓
                 ▓▓░░▓▓▓▓▓▒▒▒▒▓▓▓▓▒░░▓▓
                 ▓▓░░▓▓▓▓▓▓▓▓▓▓▓▓▓▒░░▓▓
                 ▓▓▒░░▒▒▓▓▓▓▓▓▓▓▒░░░▒▓▓
                  ▒▓▓▓▒░░░▒▓▓▒░░░▒▓▓▓▒
                     ▒▓▓▓▒░░░░▒▓▓▓▒
                        ▒▒▓▓▓▓▒▒


                Welcome to Metro v0.80.9
              Fast - Scalable - Integrated


⠙ Waiting for bundler to finish...info React Native v0.74.1 is now available (your project is running on v0.73.4).
info Changelog: https://github.com/facebook/react-native/releases/tag/v0.74.1
info Diff: https://react-native-community.github.io/upgrade-helper/?from=0.74.1
info For more info, check out "https://reactnative.dev/docs/upgrading?os=macos".
✔ Waiting for bundler to finish...
✖ FAILED: npx react-native run-ios --scheme=RNVApp --mode=Debug --no-packager --simulator iPhone\ 15
error: ⨯ ○ run: COMMAND:

npx react-native run-ios --scheme=RNVApp --mode=Debug --no-packager --simulator iPhone\ 15

FAILED with ERROR:

❌ error: Build input file cannot be found: '/Users/gabriele/Desktop/nauji/naujas/node_modules/react-native/React/Fabric/RCTThirdPartyFabricComponentsProvider.mm'. Did you forget to declare this file as an output of a script phase or custom build rule which produces it? (in target 'React-RCTFabric' from project 'Pods')
▸ Compiling RCTTextInputUtils.mm
 Run script build phase 'Bundle React Native code and images' will be run during every build because it does not specify any outputs. To address this warning, either add output dependencies to the script phase, or configure it to run in every build by unchecking "Based on dependency analysis" in the script phase. (in target 'RNVApp' from project 'RNVApp')
 Run script build phase '[CP-User] [Hermes] Replace Hermes for the right configuration, if needed' will be run during every build because it does not specify any outputs. To address this warning, either add output dependencies to the script phase, or configure it to run in every build by unchecking "Based on dependency analysis" in the script phase. (in target 'hermes-engine' from project 'Pods')
info 💡 Tip: Make sure that you have set up your development environment correctly, by running npx react-native doctor. To read more about doctor command visit: https://github.com/react-native-community/cli/blob/main/packages/cli-doctor/README.md#doctor
UnhandledPromiseRejection: This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). The promise rejected with the reason "Error: Failed to build iOS project. "xcodebuild" exited with error code '65'. To debug build logs further, consider building your app with Xcode.app, by opening 'RNVApp.xcworkspace'.".

Error: Command failed with exit code 1: npx react-native run-ios --scheme=RNVApp --mode=Debug --no-packager --simulator iPhone 15

  WARNING: You should run npx react-native@latest to ensure you're always using the most current version of the CLI. NPX has cached version (0.73.4) != current release (0.74.1)

UnhandledPromiseRejection: This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). The promise rejected with the reason "Error: Failed to build iOS project. "xcodebuild" exited with error code '65'. To debug build logs further, consider building your app with Xcode.app, by opening 'RNVApp.xcworkspace'.".
info Found Xcode workspace "RNVApp.xcworkspace"
info Launching iPhone 15 (iOS 17.2)
info Building (using "xcodebuild -workspace RNVApp.xcworkspace -configuration Debug -scheme RNVApp -destination id=7BAAF5DC-D50A-483A-87D0-BB3D69D25E38")
▸ Running script '[CP-User] [Hermes] Replace Hermes for the right configuration, if needed'
▸ Processing ResourceBundle-RCTI18nStrings-React-Core-Info.plist
▸ Compiling UIView+ComponentViewProtocol.mm
▸ Compiling React-RCTFabric-dummy.m
▸ Compiling RCTViewComponentView.mm
▸ Compiling RCTImageLoader.mm
▸ Compiling RCTImageBlurUtils.mm
▸ Compiling RCTAnimatedImage.mm
▸ Compiling RCTUnimplementedViewComponentView.mm
▸ Compiling RCTBundleAssetImageLoader.mm
▸ Compiling RCTUnimplementedNativeComponentView.mm
▸ Compiling RCTThirdPartyFabricComponentsProvider.mm

❌  error: Build input file cannot be found: '/Users/gabriele/Desktop/nauji/naujas/node_modules/react-native/React/Fabric/RCTThirdPartyFabricComponentsProvider.mm'. Did you forget to declare this file as an output of a script phase or custom build rule which produces it? (in target 'React-RCTFabric' from project 'Pods')


▸ Compiling RCTTextInputUtils.mm
    Run script build phase 'Bundle React Native code and images' will be run during every build because it does not specify any outputs. To address this warning, either add output dependencies to the script phase, or configure it to run in every build by unchecking "Based on dependency analysis" in the script phase. (in target 'RNVApp' from project 'RNVApp')
    Run script build phase '[CP-User] [Hermes] Replace Hermes for the right configuration, if needed' will be run during every build because it does not specify any outputs. To address this warning, either add output dependencies to the script phase, or configure it to run in every build by unchecking "Based on dependency analysis" in the script phase. (in target 'hermes-engine' from project 'Pods')

info 💡 Tip: Make sure that you have set up your development environment correctly, by running npx react-native doctor. To read more about doctor command visit: https://github.com/react-native-community/cli/blob/main/packages/cli-doctor/README.md#doctor

    at makeError (/Users/gabriele/Desktop/nauji/naujas/node_modules/execa/lib/error.js:60:11)
    at handlePromise (/Users/gabriele/Desktop/nauji/naujas/node_modules/execa/index.js:118:26)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)


  WARNING: You should run npx react-native@latest to ensure you're always using the most current version of the CLI. NPX has cached version (0.73.4) != current release (0.74.1)

info Found Xcode workspace "RNVApp.xcworkspace"
info Launching iPhone 15 (iOS 17.2)
info Building (using "xcodebuild -workspace RNVApp.xcworkspace -configuration Debug -scheme RNVApp -destination id=7BAAF5DC-D50A-483A-87D0-BB3D69D25E38")
▸ Running script '[CP-User] [Hermes] Replace Hermes for the right configuration, if needed'
▸ Processing ResourceBundle-RCTI18nStrings-React-Core-Info.plist
▸ Compiling UIView+ComponentViewProtocol.mm
▸ Compiling React-RCTFabric-dummy.m
▸ Compiling RCTViewComponentView.mm
▸ Compiling RCTImageLoader.mm
▸ Compiling RCTImageBlurUtils.mm
▸ Compiling RCTAnimatedImage.mm
▸ Compiling RCTUnimplementedViewComponentView.mm
▸ Compiling RCTBundleAssetImageLoader.mm
▸ Compiling RCTUnimplementedNativeComponentView.mm
▸ Compiling RCTThirdPartyFabricComponentsProvider.mm

❌  error: Build input file cannot be found: '/Users/gabriele/Desktop/nauji/naujas/node_modules/react-native/React/Fabric/RCTThirdPartyFabricComponentsProvider.mm'. Did you forget to declare this file as an output of a script phase or custom build rule which produces it? (in target 'React-RCTFabric' from project 'Pods')


▸ Compiling RCTTextInputUtils.mm
    Run script build phase 'Bundle React Native code and images' will be run during every build because it does not specify any outputs. To address this warning, either add output dependencies to the script phase, or configure it to run in every build by unchecking "Based on dependency analysis" in the script phase. (in target 'RNVApp' from project 'RNVApp')
    Run script build phase '[CP-User] [Hermes] Replace Hermes for the right configuration, if needed' will be run during every build because it does not specify any outputs. To address this warning, either add output dependencies to the script phase, or configure it to run in every build by unchecking "Based on dependency analysis" in the script phase. (in target 'hermes-engine' from project 'Pods')

info 💡 Tip: Make sure that you have set up your development environment correctly, by running npx react-native doctor. To read more about doctor command visit: https://github.com/react-native-community/cli/blob/main/packages/cli-doctor/README.md#doctor

UnhandledPromiseRejection: This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). The promise rejected with the reason "Error: Failed to build iOS project. "xcodebuild" exited with error code '65'. To debug build logs further, consider building your app with Xcode.app, by opening 'RNVApp.xcworkspace'.".


┌─────────────────────────────────────────────────────────────────┐
│ ⨯ SUMMARY | 5/22/2024, 4:30:18 PM | rnv@                        │
│ $ npx rnv                                                       │
├─────────────────────────────────────────────────────────────────┤
│ Project: naujas@0.1.0                                           │
│ Workspace: rnv                                                  │
│ Platform (-p): ios                                              │
│ Engine: @rnv/engine-rn                                          │
│ Template: @rnv/template-starter                                 │
│ App Config (-c): app                                            │
│ Build Scheme (-s): debug                                        │
│ Target (-t): iPhone 15                                          │
│ Supported Platforms: web, ios, android, androidtv, firetv, tvos, macos, linux, windows, windows, tizen, webos, chromecast, kaios, androidwear, tizenwatch
│ Env Info: darwin | arm64 | node v18.19.0                        │
│ Executed Time: 0h:0m:24s:263ms                                  │
│ error: ⨯ ○ run: COMMAND:

npx react-native run-ios --scheme=RNVApp --mode=Debug --no-packager --simulator iPhone\ 15

FAILED with ERROR:

❌ error: Build input file cannot be found: '/Users/gabriele/Desktop/nauji/naujas/node_modules/react-native/React/Fabric/RCTThirdPartyFabricComponentsProvider.mm'. Did you forget to declare this file as an output of a script phase or custom build rule which produces it? (in target 'React-RCTFabric' from project 'Pods')
▸ Compiling RCTTextInputUtils.mm
 Run script build phase 'Bundle React Native code and images' will be run during every build because it does not specify any outputs. To address this warning, either add output dependencies to the script phase, or configure it to run in every build by unchecking "Based on dependency analysis" in the script phase. (in target 'RNVApp' from project 'RNVApp')
 Run script build phase '[CP-User] [Hermes] Replace Hermes for the right configuration, if needed' will be run during every build because it does not specify any outputs. To address this warning, either add output dependencies to the script phase, or configure it to run in every build by unchecking "Based on dependency analysis" in the script phase. (in target 'hermes-engine' from project 'Pods')
info 💡 Tip: Make sure that you have set up your development environment correctly, by running npx react-native doctor. To read more about doctor command visit: https://github.com/react-native-community/cli/blob/main/packages/cli-doctor/README.md#doctor
UnhandledPromiseRejection: This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). The promise rejected with the reason "Error: Failed to build iOS project. "xcodebuild" exited with error code '65'. To debug build logs further, consider building your app with Xcode.app, by opening 'RNVApp.xcworkspace'.".

Error: Command failed with exit code 1: npx react-native run-ios --scheme=RNVApp --mode=Debug --no-packager --simulator iPhone 15

  WARNING: You should run npx react-native@latest to ensure you're always using the most current version of the CLI. NPX has cached version (0.73.4) != current release (0.74.1)

UnhandledPromiseRejection: This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). The promise rejected with the reason "Error: Failed to build iOS project. "xcodebuild" exited with error code '65'. To debug build logs further, consider building your app with Xcode.app, by opening 'RNVApp.xcworkspace'.".
info Found Xcode workspace "RNVApp.xcworkspace"
info Launching iPhone 15 (iOS 17.2)
info Building (using "xcodebuild -workspace RNVApp.xcworkspace -configuration Debug -scheme RNVApp -destination id=7BAAF5DC-D50A-483A-87D0-BB3D69D25E38")
▸ Running script '[CP-User] [Hermes] Replace Hermes for the right configuration, if needed'
▸ Processing ResourceBundle-RCTI18nStrings-React-Core-Info.plist
▸ Compiling UIView+ComponentViewProtocol.mm
▸ Compiling React-RCTFabric-dummy.m
▸ Compiling RCTViewComponentView.mm
▸ Compiling RCTImageLoader.mm
▸ Compiling RCTImageBlurUtils.mm
▸ Compiling RCTAnimatedImage.mm
▸ Compiling RCTUnimplementedViewComponentView.mm
▸ Compiling RCTBundleAssetImageLoader.mm
▸ Compiling RCTUnimplementedNativeComponentView.mm
▸ Compiling RCTThirdPartyFabricComponentsProvider.mm

❌  error: Build input file cannot be found: '/Users/gabriele/Desktop/nauji/naujas/node_modules/react-native/React/Fabric/RCTThirdPartyFabricComponentsProvider.mm'. Did you forget to declare this file as an output of a script phase or custom build rule which produces it? (in target 'React-RCTFabric' from project 'Pods')


▸ Compiling RCTTextInputUtils.mm
    Run script build phase 'Bundle React Native code and images' will be run during every build because it does not specify any outputs. To address this warning, either add output dependencies to the script phase, or configure it to run in every build by unchecking "Based on dependency analysis" in the script phase. (in target 'RNVApp' from project 'RNVApp')
    Run script build phase '[CP-User] [Hermes] Replace Hermes for the right configuration, if needed' will be run during every build because it does not specify any outputs. To address this warning, either add output dependencies to the script phase, or configure it to run in every build by unchecking "Based on dependency analysis" in the script phase. (in target 'hermes-engine' from project 'Pods')

info 💡 Tip: Make sure that you have set up your development environment correctly, by running npx react-native doctor. To read more about doctor command visit: https://github.com/react-native-community/cli/blob/main/packages/cli-doctor/README.md#doctor

    at makeError (/Users/gabriele/Desktop/nauji/naujas/node_modules/execa/lib/error.js:60:11)
    at handlePromise (/Users/gabriele/Desktop/nauji/naujas/node_modules/execa/index.js:118:26)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)


  WARNING: You should run npx react-native@latest to ensure you're always using the most current version of the CLI. NPX has cached version (0.73.4) != current release (0.74.1)

info Found Xcode workspace "RNVApp.xcworkspace"
info Launching iPhone 15 (iOS 17.2)
info Building (using "xcodebuild -workspace RNVApp.xcworkspace -configuration Debug -scheme RNVApp -destination id=7BAAF5DC-D50A-483A-87D0-BB3D69D25E38")
▸ Running script '[CP-User] [Hermes] Replace Hermes for the right configuration, if needed'
▸ Processing ResourceBundle-RCTI18nStrings-React-Core-Info.plist
▸ Compiling UIView+ComponentViewProtocol.mm
▸ Compiling React-RCTFabric-dummy.m
▸ Compiling RCTViewComponentView.mm
▸ Compiling RCTImageLoader.mm
▸ Compiling RCTImageBlurUtils.mm
▸ Compiling RCTAnimatedImage.mm
▸ Compiling RCTUnimplementedViewComponentView.mm
▸ Compiling RCTBundleAssetImageLoader.mm
▸ Compiling RCTUnimplementedNativeComponentView.mm
▸ Compiling RCTThirdPartyFabricComponentsProvider.mm

❌  error: Build input file cannot be found: '/Users/gabriele/Desktop/nauji/naujas/node_modules/react-native/React/Fabric/RCTThirdPartyFabricComponentsProvider.mm'. Did you forget to declare this file as an output of a script phase or custom build rule which produces it? (in target 'React-RCTFabric' from project 'Pods')


▸ Compiling RCTTextInputUtils.mm
    Run script build phase 'Bundle React Native code and images' will be run during every build because it does not specify any outputs. To address this warning, either add output dependencies to the script phase, or configure it to run in every build by unchecking "Based on dependency analysis" in the script phase. (in target 'RNVApp' from project 'RNVApp')
    Run script build phase '[CP-User] [Hermes] Replace Hermes for the right configuration, if needed' will be run during every build because it does not specify any outputs. To address this warning, either add output dependencies to the script phase, or configure it to run in every build by unchecking "Based on dependency analysis" in the script phase. (in target 'hermes-engine' from project 'Pods')

info 💡 Tip: Make sure that you have set up your development environment correctly, by running npx react-native doctor. To read more about doctor command visit: https://github.com/react-native-community/cli/blob/main/packages/cli-doctor/README.md#doctor

UnhandledPromiseRejection: This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). The promise rejected with the reason "Error: Failed to build iOS project. "xcodebuild" exited with error code '65'. To debug build logs further, consider building your app with Xcode.app, by opening 'RNVApp.xcworkspace'.".


│ Project location: ./platformBuilds/app_ios/RNVApp.xcworkspace   │
└─────────────────────────────────────────────────────────────────┘
error: ⨯ ○ run: COMMAND:

node /Users/gabriele/Desktop/nauji/naujas/node_modules/react-native/local-cli/cli.js start --port 8082 --no-interactive --config=metro.config.js

FAILED with ERROR:

Error: Command was killed with SIGTERM (Termination): node /Users/gabriele/Desktop/nauji/naujas/node_modules/react-native/local-cli/cli.js start --port 8082 --no-interactive --config=metro.config.js
    at makeError (/Users/gabriele/Desktop/nauji/naujas/node_modules/execa/lib/error.js:60:11)
    at handlePromise (/Users/gabriele/Desktop/nauji/naujas/node_modules/execa/index.js:118:26)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)


➜  naujas git:(master) ✗
```

**Desktop (please complete the following information):**

-   OS: macOS Ventura 13.6.4 (M2)
-   Node Version 18.19.0
-   RNV Version 1.0.0-rc.19
-  @rnv/template-starter 1.0.0-rc.19

**Comment by GabrieleKaceviciute** [comment]
can't reproduced anymore
