### ISSUE TITLE
[kaios] fails to run app-harness

### ISSUE THREAD

**Issue by GabrieleKaceviciute** [flexn-io/renative#1584]
**Describe the bug**
Cant' run app-harness on kaios

**To Reproduce**
1. Go to app-harness packages
2. Do `npx rnv run -p kaios` -> observe (simulator opens, but app not installed and errors on cli)

**Expected behavior**
App launches on simulator

**Screenshots or copy&paste**
```
~/Desktop/qa/renative/packages/app-harness$ npx rnv run -p kaios

┌─────────────────────────────────────────────────────────────────┐
│ ██████╗ ███████╗███╗   ██╗ █████╗ ████████╗██╗██╗   ██╗███████╗ │
│ ██╔══██╗██╔════╝████╗  ██║██╔══██╗╚══██╔══╝██║██║   ██║██╔════╝ │
│ ██████╔╝█████╗  ██╔██╗ ██║███████║   ██║   ██║██║   ██║█████╗   │
│ ██╔══██╗██╔══╝  ██║╚██╗██║██╔══██║   ██║   ██║╚██╗ ██╔╝██╔══╝   │
│ ██║  ██║███████╗██║ ╚████║██║  ██║   ██║   ██║ ╚████╔╝ ███████╗ │
│ ╚═╝  ╚═╝╚══════╝╚═╝  ╚═══╝╚═╝  ╚═╝   ╚═╝   ╚═╝  ╚═══╝  ╚══════╝ │
│ $ rnv run -p kaios                                              │
└─────────────────────────────────────────────────────────────────┘
info: Current engine: @rnv/engine-rn-web (./node_modules/@rnv/engine-rn-web)
task: ○ run ↺1
task: ○ configure ↺1
task: ○ platform configure ↺1
task: ○ project configure ↺1
task: ○ workspace configure ↺1
task: ✔ workspace configure
task: ○ app configure ↺1
info: Current app config: harness
task: ✔ app configure
info: ../../node_modules/@react-native-community/cli-platform-ios/build/tools/listIOSDevices.js overriden by: /@rnv/config-templates/pluginTemplates/@react-native-community/cli-platform-ios/overrides@11.3.7.json
info: ../../node_modules/@react-native-community/cli/build/bin.js overriden by: /@rnv/config-templates/pluginTemplates/@react-native-community/cli/overrides.json
info: ../../node_modules/react-native-tvos/Libraries/Components/ScrollView/ScrollViewNativeComponent.js overriden by: /@rnv/config-templates/pluginTemplates/react-native-tvos/overrides.json
info: ../../node_modules/react-native-tvos/Libraries/Components/ScrollView/ScrollViewNativeComponent.js overriden by: /@rnv/config-templates/pluginTemplates/react-native-tvos/overrides.json
info: ../../node_modules/react-native-tvos/Libraries/Components/ScrollView/ScrollViewNativeComponent.js overriden by: /@rnv/config-templates/pluginTemplates/react-native-tvos/overrides.json
info: ../../node_modules/react-native-photo-editor overriden by: /@rnv/config-templates/pluginTemplates/react-native-photo-editor/overrides
task: ✔ project configure
info: Current Build Scheme: debug
task: ✔ platform configure
warn: ○ configure: AssetSources is specified as {{resolvePackage(@flexn/assets-renative-outline)}}/assets. But path ../../node_modules/@flexn/assets-renative-outline/assets/kaios was not found.
warn: ○ configure: Your app is missing assets at ./appConfigs/base,./appConfigs/harness.
task: ✔ configure
info: Your kaios devServer at port 8103 is not running. Starting it up for you...
info: Your kaios devServerHost 127.0.0.1 at port 8103 is not running. Starting it up for you...
┌─────────────────────────────────────────────────────────────────┐
│ ⚠ BUNDLER STARTED | 5/29/2024, 12:04:57 PM | rnv@               │
│ $ rnv run -p kaios                                              │
├─────────────────────────────────────────────────────────────────┤
│ Project: @rnv/app-harness@1.0.0-rc.19                           │
│ Workspace: rnv                                                  │
│ Platform (-p): kaios                                            │
│ Engine: @rnv/engine-rn-web                                      │
│ Template: @rnv/template-starter                                 │
│ App Config (-c): harness                                        │
│ Build Scheme (-s): debug                                        │
│ Target (-t): kaiosrt-v2.5.en-US.linux-x86_64                    │
│ Supported Platforms: ios, android, androidtv, firetv, androidwear, web, tizen, tvos, webos, macos, windows, tizenwatch, kaios, chromecast, linux, windows
│ Env Info: linux | x64 | node v18.20.2                           │
│ Executed Time: 0h:0m:1s:251ms                                   │
│ warn: ○ configure: AssetSources is specified as {{resolvePackage(@flexn/assets-renative-outline)}}/assets. But path ../../node_modules/@flexn/assets-renative-outline/assets/kaios was not found.
│ warn: ○ configure: Your app is missing assets at ./appConfigs/base,./appConfigs/harness.
│ You are trying to run global rnv command in your current project.
│ This might lead to unexpected behaviour.
│ Run your rnv command with npx prefix:
│ npx rnv run -p kaios
│ Project location: ./platformBuilds/harness_kaios                │
└─────────────────────────────────────────────────────────────────┘
warn: ○ run: You are missing chii. You can install via npm i -g chii) Trying to use weinre next
warn: ○ run: You are missing weinre. Skipping debug. install via npm i -g weinre
(node:28271) [DEP_WEBPACK_DEV_SERVER_ON_AFTER_SETUP_MIDDLEWARE] DeprecationWarning: 'onAfterSetupMiddleware' option is deprecated. Please use the 'setupMiddlewares' option.
(Use `node --trace-deprecation ...` to show where the warning was created)
(node:28271) [DEP_WEBPACK_DEV_SERVER_ON_BEFORE_SETUP_MIDDLEWARE] DeprecationWarning: 'onBeforeSetupMiddleware' option is deprecated. Please use the 'setupMiddlewares' option.
Starting the development server...

Failed to compile.

SyntaxError: /home/testlab-ubuntu/Desktop/qa/renative/node_modules/react-native-fs/FS.common.js: Unexpected token, expected "," (30:29)
  28 | };
  29 |
> 30 | var normalizeFilePath = (path: string) => (path.startsWith('file://') ? path.slice(7) : path);
     |                              ^
  31 |
  32 | type MkdirOptions = {
  33 |   NSURLIsExcludedFromBackupKey?: boolean; // iOS only
    at parser.next (<anonymous>)
    at normalizeFile.next (<anonymous>)
    at run.next (<anonymous>)
    at transform.next (<anonymous>)
assets by path static/ 4.25 MiB
  asset static/js/bundle.js 3.94 MiB [emitted] (name: main) 1 related asset
  asset static/media/Inter-Light.58a136ec3193fa8a63e5.ttf 303 KiB [emitted] [immutable] [from: appConfigs/base/fonts/Inter-Light.ttf] (auxiliary name: main)
  asset static/media/logo.63d54a55b067ffc3e842.png 12.1 KiB [emitted] [immutable] [from: platformAssets/runtime/logo.png] (auxiliary name: main)
asset index.html 1.68 KiB [emitted]
asset asset-manifest.json 356 bytes [emitted]
cached modules 3.36 MiB (javascript) 303 KiB (asset) [cached] 725 modules
runtime modules 28.8 KiB 14 modules
modules by layer 2.07 KiB (javascript) 12.1 KiB (asset)
  ./platformAssets/runtime/logo.png 42 bytes (javascript) 12.1 KiB (asset) [built]
  ./platformAssets/runtime/fontManager.web.js 1.99 KiB [built]
  ../../node_modules/react-native-fs/FS.common.js 39 bytes [built] [1 error]

ERROR in ../../node_modules/react-native-fs/FS.common.js
Module build failed (from ../../node_modules/babel-loader/lib/index.js):
SyntaxError: /home/testlab-ubuntu/Desktop/qa/renative/node_modules/react-native-fs/FS.common.js: Unexpected token, expected "," (30:29)

  28 | };
  29 |
> 30 | var normalizeFilePath = (path: string) => (path.startsWith('file://') ? path.slice(7) : path);
     |                              ^
  31 |
  32 | type MkdirOptions = {
  33 |   NSURLIsExcludedFromBackupKey?: boolean; // iOS only
    at toParseError (/home/testlab-ubuntu/Desktop/qa/renative/node_modules/@babel/parser/src/parse-error.ts:74:19)
    at JSXParserMixin.raise (/home/testlab-ubuntu/Desktop/qa/renative/node_modules/@babel/parser/src/tokenizer/index.ts:1490:19)
    at JSXParserMixin.unexpected (/home/testlab-ubuntu/Desktop/qa/renative/node_modules/@babel/parser/src/tokenizer/index.ts:1530:16)
    at JSXParserMixin.expect (/home/testlab-ubuntu/Desktop/qa/renative/node_modules/@babel/parser/src/parser/util.ts:150:28)
    at JSXParserMixin.parseParenAndDistinguishExpression (/home/testlab-ubuntu/Desktop/qa/renative/node_modules/@babel/parser/src/parser/expression.ts:1782:14)
    at JSXParserMixin.parseExprAtom (/home/testlab-ubuntu/Desktop/qa/renative/node_modules/@babel/parser/src/parser/expression.ts:1165:21)
    at JSXParserMixin.parseExprAtom (/home/testlab-ubuntu/Desktop/qa/renative/node_modules/@babel/parser/src/plugins/jsx/index.ts:576:22)
    at JSXParserMixin.parseExprSubscripts (/home/testlab-ubuntu/Desktop/qa/renative/node_modules/@babel/parser/src/parser/expression.ts:709:23)
    at JSXParserMixin.parseUpdate (/home/testlab-ubuntu/Desktop/qa/renative/node_modules/@babel/parser/src/parser/expression.ts:686:21)
    at JSXParserMixin.parseMaybeUnary (/home/testlab-ubuntu/Desktop/qa/renative/node_modules/@babel/parser/src/parser/expression.ts:649:23)
    at JSXParserMixin.parseMaybeUnaryOrPrivate (/home/testlab-ubuntu/Desktop/qa/renative/node_modules/@babel/parser/src/parser/expression.ts:390:14)
    at JSXParserMixin.parseExprOps (/home/testlab-ubuntu/Desktop/qa/renative/node_modules/@babel/parser/src/parser/expression.ts:402:23)
    at JSXParserMixin.parseMaybeConditional (/home/testlab-ubuntu/Desktop/qa/renative/node_modules/@babel/parser/src/parser/expression.ts:357:23)
    at JSXParserMixin.parseMaybeAssign (/home/testlab-ubuntu/Desktop/qa/renative/node_modules/@babel/parser/src/parser/expression.ts:297:21)
    at callback (/home/testlab-ubuntu/Desktop/qa/renative/node_modules/@babel/parser/src/parser/expression.ts:251:12)
    at JSXParserMixin.allowInAnd (/home/testlab-ubuntu/Desktop/qa/renative/node_modules/@babel/parser/src/parser/expression.ts:3126:16)
    at JSXParserMixin.parseMaybeAssignAllowIn (/home/testlab-ubuntu/Desktop/qa/renative/node_modules/@babel/parser/src/parser/expression.ts:250:17)
    at JSXParserMixin.parseVar (/home/testlab-ubuntu/Desktop/qa/renative/node_modules/@babel/parser/src/parser/statement.ts:1532:18)
    at JSXParserMixin.parseVarStatement (/home/testlab-ubuntu/Desktop/qa/renative/node_modules/@babel/parser/src/parser/statement.ts:1196:10)
    at JSXParserMixin.parseStatementContent (/home/testlab-ubuntu/Desktop/qa/renative/node_modules/@babel/parser/src/parser/statement.ts:550:21)
    at JSXParserMixin.parseStatementLike (/home/testlab-ubuntu/Desktop/qa/renative/node_modules/@babel/parser/src/parser/statement.ts:421:17)
    at JSXParserMixin.parseModuleItem (/home/testlab-ubuntu/Desktop/qa/renative/node_modules/@babel/parser/src/parser/statement.ts:358:17)
    at JSXParserMixin.parseBlockOrModuleBlockBody (/home/testlab-ubuntu/Desktop/qa/renative/node_modules/@babel/parser/src/parser/statement.ts:1388:16)
    at JSXParserMixin.parseBlockBody (/home/testlab-ubuntu/Desktop/qa/renative/node_modules/@babel/parser/src/parser/statement.ts:1362:10)
    at JSXParserMixin.parseProgram (/home/testlab-ubuntu/Desktop/qa/renative/node_modules/@babel/parser/src/parser/statement.ts:217:10)
    at JSXParserMixin.parseTopLevel (/home/testlab-ubuntu/Desktop/qa/renative/node_modules/@babel/parser/src/parser/statement.ts:199:25)
    at JSXParserMixin.parse (/home/testlab-ubuntu/Desktop/qa/renative/node_modules/@babel/parser/src/parser/index.ts:45:10)
    at parse (/home/testlab-ubuntu/Desktop/qa/renative/node_modules/@babel/parser/src/index.ts:66:38)
    at parser (/home/testlab-ubuntu/Desktop/qa/renative/node_modules/@babel/core/src/parser/index.ts:28:19)
    at parser.next (<anonymous>)
    at normalizeFile (/home/testlab-ubuntu/Desktop/qa/renative/node_modules/@babel/core/src/transformation/normalize-file.ts:50:24)
    at normalizeFile.next (<anonymous>)
    at run (/home/testlab-ubuntu/Desktop/qa/renative/node_modules/@babel/core/src/transformation/index.ts:39:36)
    at run.next (<anonymous>)
    at transform (/home/testlab-ubuntu/Desktop/qa/renative/node_modules/@babel/core/src/transform.ts:29:20)
    at transform.next (<anonymous>)
    at step (/home/testlab-ubuntu/Desktop/qa/renative/node_modules/gensync/index.js:261:32)
    at /home/testlab-ubuntu/Desktop/qa/renative/node_modules/gensync/index.js:273:13
    at async.call.result.err.err (/home/testlab-ubuntu/Desktop/qa/renative/node_modules/gensync/index.js:223:11)
    at cb (/home/testlab-ubuntu/Desktop/qa/renative/node_modules/gensync/index.js:189:28)
    at /home/testlab-ubuntu/Desktop/qa/renative/node_modules/@babel/core/src/gensync-utils/async.ts:90:7
    at /home/testlab-ubuntu/Desktop/qa/renative/node_modules/gensync/index.js:113:33
    at step (/home/testlab-ubuntu/Desktop/qa/renative/node_modules/gensync/index.js:287:14)
    at /home/testlab-ubuntu/Desktop/qa/renative/node_modules/gensync/index.js:273:13
    at async.call.result.err.err (/home/testlab-ubuntu/Desktop/qa/renative/node_modules/gensync/index.js:223:11)
 @ ./src/components/PhotoEditor/index.mobile.tsx 6:44-70
 @ ./src/app/index.tsx 19:19-55
 @ ./src/entry/index.web.tsx 5:34-51
 @ ./index.js 3:0-31 4:15-19

ERROR in ../../node_modules/react-native-photo-editor/RNPhotoEditor.js 9:7-20
export 'ViewPropTypes' (imported as 'ViewPropTypes') was not found in 'react-native' (possible exports: AccessibilityInfo, ActivityIndicator, Alert, Animated, AppRegistry, AppState, Appearance, BackHandler, Button, CheckBox, Clipboard, DeviceEventEmitter, Dimensions, Easing, FlatList, I18nManager, Image, ImageBackground, InteractionManager, Keyboard, KeyboardAvoidingView, LayoutAnimation, Linking, LogBox, Modal, NativeEventEmitter, NativeModules, PanResponder, Picker, PixelRatio, Platform, Pressable, ProgressBar, RefreshControl, SafeAreaView, ScrollView, SectionList, Share, StatusBar, StyleSheet, Switch, Text, TextInput, Touchable, TouchableHighlight, TouchableNativeFeedback, TouchableOpacity, TouchableWithoutFeedback, UIManager, Vibration, View, VirtualizedList, YellowBox, __esModule, findNodeHandle, processColor, render, unmountComponentAtNode, unstable_createElement, useColorScheme, useLocaleContext, useWindowDimensions)
 @ ./src/components/PhotoEditor/index.mobile.tsx 5:30-66
 @ ./src/app/index.tsx 19:19-55
 @ ./src/entry/index.web.tsx 5:34-51
 @ ./index.js 3:0-31 4:15-19

webpack 5.91.0 compiled with 2 errors in 4463 ms
Files successfully emitted, waiting for typecheck results...
Issues checking in progress...
? What simulator would you like to launch? (Use arrow keys)
? What simulator would you like to launch? kaiosrt-v2.5.en-US.linux-x86_64

```

**Desktop (please complete the following information):**
- OS: Ubuntu 20.04.5
- Node Version 18.20.2
- RNV Version 1.0.0-rc.19

**Comment by GabrieleKaceviciute** [comment]
can't reproduce it on 1.0.0-rc.21
