### ISSUE TITLE
[linux] rnv link breaks new project

### ISSUE THREAD

**Issue by pauliusguzas** [flexn-io/renative#1599]
**Describe the bug**
rnv link breaks new project

**To Reproduce**
1. checkout release/1.0
2. create new project using local template
3. do rnv link
4. do npx rnv run -> error

**Expected behavior**
asks to choose platform

**Screenshots or copy&paste**
```
testlab-ubuntu@testlabubuntu-KBL-U-Pro-Cubi-3-Silent-S-MS-B159:~/Desktop/qa/hello-renative$ npx rnv run
TypeError: (0 , provider_1.getApi)(...).logger.logInitialize is not a function
    at logInitialize (/home/testlab-ubuntu/node_modules/rnv/node_modules/@rnv/core/src/logger/index.ts:50:21)
    at /home/testlab-ubuntu/node_modules/rnv/src/runner.ts:46:22
    at step (/home/testlab-ubuntu/node_modules/tslib/tslib.js:193:27)
    at Object.next (/home/testlab-ubuntu/node_modules/tslib/tslib.js:174:57)
    at /home/testlab-ubuntu/node_modules/tslib/tslib.js:167:75
    at new Promise (<anonymous>)
    at Object.__awaiter (/home/testlab-ubuntu/node_modules/tslib/tslib.js:163:16)
    at executeRnv (/home/testlab-ubuntu/node_modules/rnv/lib/runner.js:11:20)
    at run (/home/testlab-ubuntu/node_modules/@rnv/cli/src/index.ts:62:5)
    at Object.<anonymous> (/home/testlab-ubuntu/node_modules/@rnv/cli/src/bin.ts:5:4)
TypeError: (0 , provider_1.getApi)(...).logger.logError is not a function
    at logError (/home/testlab-ubuntu/node_modules/@rnv/core/src/logger/index.ts:45:21)
    at /home/testlab-ubuntu/node_modules/@rnv/cli/src/index.ts:65:21
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
testlab-ubuntu@testlabubuntu-KBL-U-Pro-Cubi-3-Silent-S-MS-B159:~/Desktop/qa/hello-renative$ 
```
**Desktop (please complete the following information):**
- OS: Ubuntu 20.04.5
- Node Version 18.20.2
- RNV Version 1.0.0-rc.19

**Comment by pauliusguzas** [comment]
solved, env issue
