### ISSUE TITLE
[ios] [REGRESSION] app-harness fails to run when debug-static-pods scheme is used

### ISSUE THREAD

**Issue by pauliusguzas** [flexn-io/renative#1622]
**Describe the bug**
app-harness fails to run when debug-static-pods scheme is used

**To Reproduce**
1. go to app-harness
2. do `npx rnv run -p ios -r -s debug-static-pods`

**Expected behavior**
App runs

**Screenshots or copy&paste**
```
Last login: Tue Jul  9 09:59:32 on ttys000
Unknown ruby interpreter version (do not know how to handle): >=2.6.10.
pauliusguzas@MBP-de-Flexn app-harness % npx rnv run -p ios -r -s

┌─────────────────────────────────────────────────────────────────┐
│ ██████╗ ███████╗███╗   ██╗ █████╗ ████████╗██╗██╗   ██╗███████╗ │
│ ██╔══██╗██╔════╝████╗  ██║██╔══██╗╚══██╔══╝██║██║   ██║██╔════╝ │
│ ██████╔╝█████╗  ██╔██╗ ██║███████║   ██║   ██║██║   ██║█████╗   │
│ ██╔══██╗██╔══╝  ██║╚██╗██║██╔══██║   ██║   ██║╚██╗ ██╔╝██╔══╝   │
│ ██║  ██║███████╗██║ ╚████║██║  ██║   ██║   ██║ ╚████╔╝ ███████╗ │
│ ╚═╝  ╚═╝╚══════╝╚═╝  ╚═══╝╚═╝  ╚═╝   ╚═╝   ╚═╝  ╚═══╝  ╚══════╝ │
│ 🚀 v:1.0.0-rc.21 | renative.org | 7/9/2024, 2:10:34 PM          │
│ $ rnv run -p ios -r -s                                          │
└─────────────────────────────────────────────────────────────────┘
info: Current platform: ios
info: Current engine: @rnv/engine-rn (../engine-rn)
task: ○ run ↺1
info: Build hooks not complied. BUILDING...
info: Current platform: ios
task: ○ configure ↺1
task: ○ platform configure ↺1
task: ○ project configure ↺1
task: ○ workspace configure ↺1
task: ✔ workspace configure
task: ○ app configure ↺1
info: Current app config: harness
task: ✔ app configure
info: ../../node_modules/@react-native-community/cli-platform-ios/build/tools/listIOSDevices.js overriden by: /@rnv/config-templates/pluginTemplates/@react-native-community/cli-platform-ios/overrides@11.3.7.json
info: ../../node_modules/@react-native-community/cli/build/bin.js overriden by: /@rnv/config-templates/pluginTemplates/@react-native-community/cli/overrides.json
info: ../../node_modules/react-native-tvos/Libraries/Components/ScrollView/ScrollViewNativeComponent.js overriden by: /@rnv/config-templates/pluginTemplates/react-native-tvos/overrides.json
info: ../../node_modules/react-native-tvos/Libraries/Components/ScrollView/ScrollViewNativeComponent.js overriden by: /@rnv/config-templates/pluginTemplates/react-native-tvos/overrides.json
info: ../../node_modules/react-native-tvos/Libraries/Components/ScrollView/ScrollViewNativeComponent.js overriden by: /@rnv/config-templates/pluginTemplates/react-native-tvos/overrides.json
info: ../../node_modules/react-native-photo-editor overriden by: /@rnv/config-templates/pluginTemplates/react-native-photo-editor/overrides
task: ✔ project configure
? Pick one of available buildSchemes debug-static-pods
info: Current Build Scheme: debug-static-pods
info: You passed -r argument. "./platformBuilds/harness_ios" CLEANING...DONE
task: ✔ platform configure
info: Found custom assetSources at ../../node_modules/@flexn/assets-renative-outline/assets/ios. Will be used to generate assets.
info: Podfile.lock does not exist. Will execute pod actions...
✔ Executing: bundle install
✖ FAILED: bundle exec pod install
error: ⨯ ○ configure: COMMAND:

bundle exec pod install

FAILED with ERROR:

Calling `DidYouMean::SPELL_CHECKERS.merge!(error_name => spell_checker)' has been deprecated. Please call `DidYouMean.correct_error(error_name, spell_checker)' instead.
Calling `DidYouMean::SPELL_CHECKERS.merge!(error_name => spell_checker)' has been deprecated. Please call `DidYouMean.correct_error(error_name, spell_checker)' instead.
RNFBApp: Using overridden static_framework value of 'true'
Adding a custom script phase for Pod RNFBApp: [RNFB] Core Configuration
Auto-linking React Native modules for target `RNVApp`: RNCPushNotificationIOS, RNFBApp, RNFS, RNGestureHandler, RNPermissions, react-native-carplay, react-native-orientation-locker, react-native-safe-area-context, react-native-splash-screen, and rn-fetch-blob
Framework build type is static library
[Codegen] Generating ./build/generated/ios/React-Codegen.podspec.json
[!] CocoaPods could not find compatible versions for pod "Firebase/CoreOnly":
 In Podfile:
 RNFBApp (from `../../../../node_modules/@react-native-firebase/app`) was resolved to 20.0.0, which depends on
 Firebase/CoreOnly (= 10.25.0)
None of your spec sources contain a spec satisfying the dependency: `Firebase/CoreOnly (= 10.25.0)`.
You have either:

Error: Command failed with exit code 31: bundle exec pod install
Calling `DidYouMean::SPELL_CHECKERS.merge!(error_name => spell_checker)' has been deprecated. Please call `DidYouMean.correct_error(error_name, spell_checker)' instead.
Calling `DidYouMean::SPELL_CHECKERS.merge!(error_name => spell_checker)' has been deprecated. Please call `DidYouMean.correct_error(error_name, spell_checker)' instead.
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 16.2M  100 16.2M    0     0  3138k      0  0:00:05  0:00:05 --:--:-- 2976k
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 12.3M  100 12.3M    0     0  1278k      0  0:00:09  0:00:09 --:--:--  910k
RNFBApp: Using overridden static_framework value of 'true'
Adding a custom script phase for Pod RNFBApp: [RNFB] Core Configuration
Auto-linking React Native modules for target `RNVApp`: RNCPushNotificationIOS, RNFBApp, RNFS, RNGestureHandler, RNPermissions, react-native-carplay, react-native-orientation-locker, react-native-safe-area-context, react-native-splash-screen, and rn-fetch-blob
Framework build type is static library
[Codegen] Generating ./build/generated/ios/React-Codegen.podspec.json
Analyzing dependencies
Fetching podspec for `DoubleConversion` from `../../../../node_modules/react-native/third-party-podspecs/DoubleConversion.podspec`
[Codegen] Found FBReactNativeSpec
Fetching podspec for `RCT-Folly` from `../../../../node_modules/react-native/third-party-podspecs/RCT-Folly.podspec`
RNFBApp: Using overridden static_framework value of 'true'
[Codegen] Found rncore
Fetching podspec for `boost` from `../../../../node_modules/react-native/third-party-podspecs/boost.podspec`
Fetching podspec for `glog` from `../../../../node_modules/react-native/third-party-podspecs/glog.podspec`
Fetching podspec for `hermes-engine` from `../../../../node_modules/react-native/sdks/hermes-engine/hermes-engine.podspec`
[Hermes] Using release tarball from URL: https://repo1.maven.org/maven2/com/facebook/react/react-native-artifacts/0.73.4/react-native-artifacts-0.73.4-hermes-ios-debug.tar.gz
Pre-downloading: `iOSPhotoEditor` from `https://github.com/prscX/photo-editor`, commit `4924e9ec984d25d03644e58aa148282642171de9`
[!] CocoaPods could not find compatible versions for pod "Firebase/CoreOnly":
  In Podfile:
    RNFBApp (from `../../../../node_modules/@react-native-firebase/app`) was resolved to 20.0.0, which depends on
      Firebase/CoreOnly (= 10.25.0)

None of your spec sources contain a spec satisfying the dependency: `Firebase/CoreOnly (= 10.25.0)`.

You have either:
 * out-of-date source repos which you can update with `pod repo update` or with `pod install --repo-update`.
 * mistyped the name or version.
 * not added the source repo that hosts the Podspec to your Podfile.
    at makeError (/Users/pauliusguzas/Desktop/renative/renative/node_modules/execa/lib/error.js:60:11)
    at handlePromise (/Users/pauliusguzas/Desktop/renative/renative/node_modules/execa/index.js:118:26)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)

Calling `DidYouMean::SPELL_CHECKERS.merge!(error_name => spell_checker)' has been deprecated. Please call `DidYouMean.correct_error(error_name, spell_checker)' instead.
Calling `DidYouMean::SPELL_CHECKERS.merge!(error_name => spell_checker)' has been deprecated. Please call `DidYouMean.correct_error(error_name, spell_checker)' instead.
RNFBApp: Using overridden static_framework value of 'true'
Adding a custom script phase for Pod RNFBApp: [RNFB] Core Configuration
Auto-linking React Native modules for target `RNVApp`: RNCPushNotificationIOS, RNFBApp, RNFS, RNGestureHandler, RNPermissions, react-native-carplay, react-native-orientation-locker, react-native-safe-area-context, react-native-splash-screen, and rn-fetch-blob
Framework build type is static library
[Codegen] Generating ./build/generated/ios/React-Codegen.podspec.json
Analyzing dependencies
Fetching podspec for `DoubleConversion` from `../../../../node_modules/react-native/third-party-podspecs/DoubleConversion.podspec`
[Codegen] Found FBReactNativeSpec
Fetching podspec for `RCT-Folly` from `../../../../node_modules/react-native/third-party-podspecs/RCT-Folly.podspec`
RNFBApp: Using overridden static_framework value of 'true'
[Codegen] Found rncore
Fetching podspec for `boost` from `../../../../node_modules/react-native/third-party-podspecs/boost.podspec`
Fetching podspec for `glog` from `../../../../node_modules/react-native/third-party-podspecs/glog.podspec`
Fetching podspec for `hermes-engine` from `../../../../node_modules/react-native/sdks/hermes-engine/hermes-engine.podspec`
[Hermes] Using release tarball from URL: https://repo1.maven.org/maven2/com/facebook/react/react-native-artifacts/0.73.4/react-native-artifacts-0.73.4-hermes-ios-debug.tar.gz
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 16.2M  100 16.2M    0     0  3138k      0  0:00:05  0:00:05 --:--:-- 2976k
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 12.3M  100 12.3M    0     0  1278k      0  0:00:09  0:00:09 --:--:--  910k
Pre-downloading: `iOSPhotoEditor` from `https://github.com/prscX/photo-editor`, commit `4924e9ec984d25d03644e58aa148282642171de9`
[!] CocoaPods could not find compatible versions for pod "Firebase/CoreOnly":
  In Podfile:
    RNFBApp (from `../../../../node_modules/@react-native-firebase/app`) was resolved to 20.0.0, which depends on
      Firebase/CoreOnly (= 10.25.0)

None of your spec sources contain a spec satisfying the dependency: `Firebase/CoreOnly (= 10.25.0)`.

You have either:
 * out-of-date source repos which you can update with `pod repo update` or with `pod install --repo-update`.
 * mistyped the name or version.
 * not added the source repo that hosts the Podspec to your Podfile.


┌─────────────────────────────────────────────────────────────────┐
│ ⨯ SUMMARY | 7/9/2024, 2:10:58 PM | rnv@1.0.0-rc.21              │
│ $ rnv run -p ios -r -s                                          │
├─────────────────────────────────────────────────────────────────┤
│ Project: @rnv/app-harness@1.0.0-rc.21                           │
│ Workspace: rnv                                                  │
│ Platform (-p): ios                                              │
│ Engine: @rnv/engine-rn                                          │
│ Template: @rnv/template-starter                                 │
│ App Config (-c): harness                                        │
│ Build Scheme (-s): debug-static-pods                            │
│ Target (-t): iPhone 15                                          │
│ Reset Project (-r): true                                        │
│ Supported Platforms: ios, android, androidtv, firetv, androidwear, web, tizen, tvos, webos, macos, tizenwatch, kaios, chromecast, linux, windows
│ Env Info: darwin | x64 | node v18.18.0                          │
│ Executed Time: 0h:0m:23s:749ms                                  │
│ error: ⨯ ○ configure: COMMAND:

bundle exec pod install

FAILED with ERROR:

Calling `DidYouMean::SPELL_CHECKERS.merge!(error_name => spell_checker)' has been deprecated. Please call `DidYouMean.correct_error(error_name, spell_checker)' instead.
Calling `DidYouMean::SPELL_CHECKERS.merge!(error_name => spell_checker)' has been deprecated. Please call `DidYouMean.correct_error(error_name, spell_checker)' instead.
RNFBApp: Using overridden static_framework value of 'true'
Adding a custom script phase for Pod RNFBApp: [RNFB] Core Configuration
Auto-linking React Native modules for target `RNVApp`: RNCPushNotificationIOS, RNFBApp, RNFS, RNGestureHandler, RNPermissions, react-native-carplay, react-native-orientation-locker, react-native-safe-area-context, react-native-splash-screen, and rn-fetch-blob
Framework build type is static library
[Codegen] Generating ./build/generated/ios/React-Codegen.podspec.json
[!] CocoaPods could not find compatible versions for pod "Firebase/CoreOnly":
 In Podfile:
 RNFBApp (from `../../../../node_modules/@react-native-firebase/app`) was resolved to 20.0.0, which depends on
 Firebase/CoreOnly (= 10.25.0)
None of your spec sources contain a spec satisfying the dependency: `Firebase/CoreOnly (= 10.25.0)`.
You have either:

Error: Command failed with exit code 31: bundle exec pod install
Calling `DidYouMean::SPELL_CHECKERS.merge!(error_name => spell_checker)' has been deprecated. Please call `DidYouMean.correct_error(error_name, spell_checker)' instead.
Calling `DidYouMean::SPELL_CHECKERS.merge!(error_name => spell_checker)' has been deprecated. Please call `DidYouMean.correct_error(error_name, spell_checker)' instead.
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 16.2M  100 16.2M    0     0  3138k      0  0:00:05  0:00:05 --:--:-- 2976k
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 12.3M  100 12.3M    0     0  1278k      0  0:00:09  0:00:09 --:--:--  910k
RNFBApp: Using overridden static_framework value of 'true'
Adding a custom script phase for Pod RNFBApp: [RNFB] Core Configuration
Auto-linking React Native modules for target `RNVApp`: RNCPushNotificationIOS, RNFBApp, RNFS, RNGestureHandler, RNPermissions, react-native-carplay, react-native-orientation-locker, react-native-safe-area-context, react-native-splash-screen, and rn-fetch-blob
Framework build type is static library
[Codegen] Generating ./build/generated/ios/React-Codegen.podspec.json
Analyzing dependencies
Fetching podspec for `DoubleConversion` from `../../../../node_modules/react-native/third-party-podspecs/DoubleConversion.podspec`
[Codegen] Found FBReactNativeSpec
Fetching podspec for `RCT-Folly` from `../../../../node_modules/react-native/third-party-podspecs/RCT-Folly.podspec`
RNFBApp: Using overridden static_framework value of 'true'
[Codegen] Found rncore
Fetching podspec for `boost` from `../../../../node_modules/react-native/third-party-podspecs/boost.podspec`
Fetching podspec for `glog` from `../../../../node_modules/react-native/third-party-podspecs/glog.podspec`
Fetching podspec for `hermes-engine` from `../../../../node_modules/react-native/sdks/hermes-engine/hermes-engine.podspec`
[Hermes] Using release tarball from URL: https://repo1.maven.org/maven2/com/facebook/react/react-native-artifacts/0.73.4/react-native-artifacts-0.73.4-hermes-ios-debug.tar.gz
Pre-downloading: `iOSPhotoEditor` from `https://github.com/prscX/photo-editor`, commit `4924e9ec984d25d03644e58aa148282642171de9`
[!] CocoaPods could not find compatible versions for pod "Firebase/CoreOnly":
  In Podfile:
    RNFBApp (from `../../../../node_modules/@react-native-firebase/app`) was resolved to 20.0.0, which depends on
      Firebase/CoreOnly (= 10.25.0)

None of your spec sources contain a spec satisfying the dependency: `Firebase/CoreOnly (= 10.25.0)`.

You have either:
 * out-of-date source repos which you can update with `pod repo update` or with `pod install --repo-update`.
 * mistyped the name or version.
 * not added the source repo that hosts the Podspec to your Podfile.
    at makeError (/Users/pauliusguzas/Desktop/renative/renative/node_modules/execa/lib/error.js:60:11)
    at handlePromise (/Users/pauliusguzas/Desktop/renative/renative/node_modules/execa/index.js:118:26)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)

Calling `DidYouMean::SPELL_CHECKERS.merge!(error_name => spell_checker)' has been deprecated. Please call `DidYouMean.correct_error(error_name, spell_checker)' instead.
Calling `DidYouMean::SPELL_CHECKERS.merge!(error_name => spell_checker)' has been deprecated. Please call `DidYouMean.correct_error(error_name, spell_checker)' instead.
RNFBApp: Using overridden static_framework value of 'true'
Adding a custom script phase for Pod RNFBApp: [RNFB] Core Configuration
Auto-linking React Native modules for target `RNVApp`: RNCPushNotificationIOS, RNFBApp, RNFS, RNGestureHandler, RNPermissions, react-native-carplay, react-native-orientation-locker, react-native-safe-area-context, react-native-splash-screen, and rn-fetch-blob
Framework build type is static library
[Codegen] Generating ./build/generated/ios/React-Codegen.podspec.json
Analyzing dependencies
Fetching podspec for `DoubleConversion` from `../../../../node_modules/react-native/third-party-podspecs/DoubleConversion.podspec`
[Codegen] Found FBReactNativeSpec
Fetching podspec for `RCT-Folly` from `../../../../node_modules/react-native/third-party-podspecs/RCT-Folly.podspec`
RNFBApp: Using overridden static_framework value of 'true'
[Codegen] Found rncore
Fetching podspec for `boost` from `../../../../node_modules/react-native/third-party-podspecs/boost.podspec`
Fetching podspec for `glog` from `../../../../node_modules/react-native/third-party-podspecs/glog.podspec`
Fetching podspec for `hermes-engine` from `../../../../node_modules/react-native/sdks/hermes-engine/hermes-engine.podspec`
[Hermes] Using release tarball from URL: https://repo1.maven.org/maven2/com/facebook/react/react-native-artifacts/0.73.4/react-native-artifacts-0.73.4-hermes-ios-debug.tar.gz
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 16.2M  100 16.2M    0     0  3138k      0  0:00:05  0:00:05 --:--:-- 2976k
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 12.3M  100 12.3M    0     0  1278k      0  0:00:09  0:00:09 --:--:--  910k
Pre-downloading: `iOSPhotoEditor` from `https://github.com/prscX/photo-editor`, commit `4924e9ec984d25d03644e58aa148282642171de9`
[!] CocoaPods could not find compatible versions for pod "Firebase/CoreOnly":
  In Podfile:
    RNFBApp (from `../../../../node_modules/@react-native-firebase/app`) was resolved to 20.0.0, which depends on
      Firebase/CoreOnly (= 10.25.0)

None of your spec sources contain a spec satisfying the dependency: `Firebase/CoreOnly (= 10.25.0)`.

You have either:
 * out-of-date source repos which you can update with `pod repo update` or with `pod install --repo-update`.
 * mistyped the name or version.
 * not added the source repo that hosts the Podspec to your Podfile.


│ Project location: ./platformBuilds/harness_ios/RNVApp.xcworkspace
└─────────────────────────────────────────────────────────────────┘
pauliusguzas@MBP-de-Flexn app-harness %
```

**Desktop (please complete the following information):**
-   OS: macOS Ventura
-   Node Version 18.19.0
-   RNV Version 1.0.0-rc.21
-   template-starter Version 1.0.0-rc.21

**Comment by pauliusguzas** [comment]
Confirmed that `pod repo update` solved the issue
