### ISSUE TITLE
[web] Running npx rnv start -p web dumps ts errors

### ISSUE THREAD

**Issue by pauliusguzas** [flexn-io/renative#1637]
**Describe the bug**
Running npx rnv start -p web dumps ts errors

**To Reproduce**
1. Go to template or harness
2. Do `npx rnv start -p web` (or `yarn start:web-test`)

**Expected behavior**
No ts errors

**Screenshots or copy&paste**
```
 ⨯ TypeError: _interop_require_default._ is not a function
    at __webpack_require__ (/Users/pauliusguzas/Desktop/renative/renative/packages/template-starter/platformBuilds/template_web/output/server/webpack-runtime.js:33:42)
    at Function.__webpack_require__.t (/Users/pauliusguzas/Desktop/renative/renative/packages/template-starter/platformBuilds/template_web/output/server/webpack-runtime.js:73:38)
```

**Desktop (please complete the following information):**
-   OS: macOS Ventura
-   Node Version 18.19.0
-   RNV Version 1.0.0-rc.21
-   template-starter Version 1.0.0-rc.21

**Comment by justinasRm** [comment]
These type errors are not related to Renative functionality - they happen because of NextJS full reloads (another way to reproduce - already have a http://0.0.0.0:8080/ window open, then run `npx rnv run -p web`), and they don't cause any RNV crashes.

**Comment by pauliusguzas** [comment]
Closing as not an issue of renative
