### ISSUE TITLE
[tizen] template and harness fails to run

### ISSUE THREAD

**Issue by pauliusguzas** [flexn-io/renative#1686]
current main

**Describe the bug**
template and harness fails to run on tizen

**To Reproduce**
1. go to app-harness or template-starter package
2. do `npx rnv run -p tizen`

**Screenshots or copy&paste**
app-harness
```
pauliusguzas@MBP-de-Flexn app-harness % npx rnv run -p tizen

┌─────────────────────────────────────────────────────────────────┐
│ ██████╗ ███████╗███╗   ██╗ █████╗ ████████╗██╗██╗   ██╗███████╗ │
│ ██╔══██╗██╔════╝████╗  ██║██╔══██╗╚══██╔══╝██║██║   ██║██╔════╝ │
│ ██████╔╝█████╗  ██╔██╗ ██║███████║   ██║   ██║██║   ██║█████╗   │
│ ██╔══██╗██╔══╝  ██║╚██╗██║██╔══██║   ██║   ██║╚██╗ ██╔╝██╔══╝   │
│ ██║  ██║███████╗██║ ╚████║██║  ██║   ██║   ██║ ╚████╔╝ ███████╗ │
│ ╚═╝  ╚═╝╚══════╝╚═╝  ╚═══╝╚═╝  ╚═╝   ╚═╝   ╚═╝  ╚═══╝  ╚══════╝ │
│ 🚀 v:1.0.0 | renative.org | 9/4/2024, 1:26:31 PM                │
│ $ rnv run -p tizen                                              │
└─────────────────────────────────────────────────────────────────┘
info: Current engine: @rnv/engine-rn-web (../engine-rn-web)
task: ○ run ↺1
task: ○ configure ↺1
task: ○ platform configure ↺1
task: ○ project configure ↺1
task: ○ workspace configure ↺1
task: ✔ workspace configure
task: ○ app configure ↺1
info: Current app config: harness
task: ✔ app configure
info: ../../node_modules/@react-native-community/cli-platform-ios/build/tools/listIOSDevices.js overriden by: /@rnv/config-templates/pluginTemplates/@react-native-community/cli-platform-ios/overrides@11.3.7.json
info: ../../node_modules/@react-native-community/cli/build/bin.js overriden by: /@rnv/config-templates/pluginTemplates/@react-native-community/cli/overrides.json
info: ../../node_modules/react-native-tvos/Libraries/Components/ScrollView/ScrollViewNativeComponent.js overriden by: /@rnv/config-templates/pluginTemplates/react-native-tvos/overrides.json
info: ../../node_modules/react-native-tvos/Libraries/Components/ScrollView/ScrollViewNativeComponent.js overriden by: /@rnv/config-templates/pluginTemplates/react-native-tvos/overrides.json
info: ../../node_modules/react-native-tvos/Libraries/Components/ScrollView/ScrollViewNativeComponent.js overriden by: /@rnv/config-templates/pluginTemplates/react-native-tvos/overrides.json
info: ../../node_modules/react-native-photo-editor overriden by: /@rnv/config-templates/pluginTemplates/react-native-photo-editor/overrides
task: ✔ project configure
info: Current Build Scheme: debug
task: ○ sdk configure ↺1
task: ✔ sdk configure
task: ✔ platform configure
✔ Executing: "/Users/pauliusguzas/tizen-studio/tools/ide/bin/tizen" security-profiles list -n RNVanillaCert
info: Found custom assetSources at ../../node_modules/@flexn/assets-renative-outline/assets/tizen. Will be used to generate assets.
task: ✔ configure
info: Your tizen devServer at port 8097 is not running. Starting it up for you...
info: Your tizen devServerHost 127.0.0.1 at port 8097 is not running. Starting it up for you...
┌─────────────────────────────────────────────────────────────────┐
│ ✔ BUNDLER STARTED | 9/4/2024, 1:26:36 PM | rnv@1.0.0            │
│ $ rnv run -p tizen                                              │
├─────────────────────────────────────────────────────────────────┤
│ Project: @rnv/app-harness@1.0.0                                 │
│ Workspace: rnv                                                  │
│ Platform (-p): tizen                                            │
│ Engine: @rnv/engine-rn-web                                      │
│ Template: @rnv/template-starter                                 │
│ App Config (-c): harness                                        │
│ Build Scheme (-s): debug                                        │
│ Target (-t): T-samsung-7.0-x86                                  │
│ Supported Platforms: ios, android, androidtv, firetv, androidwear, web, tizen, tvos, webos, macos, tizenwatch, kaios, chromecast, linux, windows
│ Env Info: darwin | x64 | node v18.18.0                          │
│ Executed Time: 0h:0m:4s:868ms                                   │
│ Project location: ./platformBuilds/harness_tizen                │
└─────────────────────────────────────────────────────────────────┘
warn: ○ run: You are missing chii. You can install via npm i -g chii) Trying to use weinre next
warn: ○ run: You are missing weinre. Skipping debug. install via npm i -g weinre
(node:37989) [DEP_WEBPACK_DEV_SERVER_ON_AFTER_SETUP_MIDDLEWARE] DeprecationWarning: 'onAfterSetupMiddleware' option is deprecated. Please use the 'setupMiddlewares' option.
(Use `node --trace-deprecation ...` to show where the warning was created)
(node:37989) [DEP_WEBPACK_DEV_SERVER_ON_BEFORE_SETUP_MIDDLEWARE] DeprecationWarning: 'onBeforeSetupMiddleware' option is deprecated. Please use the 'setupMiddlewares' option.
Starting the development server...

Compiled successfully!

You can now view @rnv/app-harness in the browser.

  Local:            http://localhost:8097
  On Your Network:  http://192.168.8.181:8097

Note that the development build is not optimized.
To create a production build, use npm run build.

assets by path static/js/*.js 3.44 MiB
  asset static/js/bundle.js 3.35 MiB [emitted] (name: main) 1 related asset
  asset static/js/reactPlayerFilePlayer.chunk.js 15 KiB [emitted] (name: reactPlayerFilePlayer) (id hint: vendors) 1 related asset
  asset static/js/reactPlayerMux.chunk.js 8.72 KiB [emitted] (name: reactPlayerMux) 1 related asset
  asset static/js/reactPlayerYouTube.chunk.js 8.5 KiB [emitted] (name: reactPlayerYouTube) 1 related asset
  asset static/js/reactPlayerVimeo.chunk.js 6.4 KiB [emitted] (name: reactPlayerVimeo) 1 related asset
  asset static/js/reactPlayerWistia.chunk.js 6.33 KiB [emitted] (name: reactPlayerWistia) 1 related asset
  asset static/js/reactPlayerFacebook.chunk.js 5.73 KiB [emitted] (name: reactPlayerFacebook) 1 related asset
  asset static/js/reactPlayerTwitch.chunk.js 5.73 KiB [emitted] (name: reactPlayerTwitch) 1 related asset
  + 7 assets
assets by path static/media/ 315 KiB
  asset static/media/Inter-Light.58a136ec3193fa8a63e5.ttf 303 KiB [emitted] [immutable] [from: appConfigs/base/fonts/Inter-Light.ttf] (auxiliary name: main)
  asset static/media/logo.63d54a55b067ffc3e842.png 12.1 KiB [emitted] [immutable] [from: platformAssets/runtime/logo.png] (auxiliary name: main)
asset asset-manifest.json 2.51 KiB [emitted]
asset index.html 1.77 KiB [emitted]
cached modules 2.88 MiB (javascript) 303 KiB (asset) 33.2 KiB (runtime) [cached] 724 modules
modules by layer 2.01 KiB (javascript) 12.1 KiB (asset)
  ./platformAssets/runtime/logo.png 42 bytes (javascript) 12.1 KiB (asset) [built]
  ./platformAssets/runtime/fontManager.web.js 1.97 KiB [built]
webpack 5.94.0 compiled successfully in 2299 ms
No issues found.
✔ Executing: "/Users/pauliusguzas/tizen-studio/tools/sdb" devices
✔ Executing: /Users/pauliusguzas/tizen-studio/tools/emulator/bin/em-cli launch --name T-samsung-7.0-x86
✔ Waiting for emulator to boot...
✔ Executing: "/Users/pauliusguzas/tizen-studio/tools/ide/bin/tizen" build-web -- "/Users/pauliusguzas/Desktop/renative/renative/packages/app-harness/platformBuilds/harness_tizen" -out "/Users/pauliusguzas/Desktop/renative/renative/packages/app-harness/platformBuilds/harness_tizen/intermediate"
✔ Executing: "/Users/pauliusguzas/tizen-studio/tools/ide/bin/tizen" package -- "/Users/pauliusguzas/Desktop/renative/renative/packages/app-harness/platformBuilds/harness_tizen/intermediate" -s RNVanillaCert -t wgt -o "/Users/pauliusguzas/Desktop/renative/renative/packages/app-harness/platformBuilds/harness_tizen/output"
✔ Executing: "/Users/pauliusguzas/tizen-studio/tools/ide/bin/tizen" uninstall -p NkVRhWHJST -t T-samsung-7.0-x86
✖ FAILED: "/Users/pauliusguzas/tizen-studio/tools/ide/bin/tizen" install -- "/Users/pauliusguzas/Desktop/renative/renative/packages/app-harness/platformBuilds/harness_tizen/output" -n RNVanillaTV.wgt -t T-samsung-7.0-x86
error: ⨯ ○ run: COMMAND:

"/Users/pauliusguzas/tizen-studio/tools/ide/bin/tizen" install -- "/Users/pauliusguzas/Desktop/renative/renative/packages/app-harness/platformBuilds/harness_tizen/output" -n RNVanillaTV.wgt -t T-samsung-7.0-x86

FAILED with ERROR:

Error: Command failed with exit code 1: "/Users/pauliusguzas/tizen-studio/tools/ide/bin/tizen" install -- "/Users/pauliusguzas/Desktop/renative/renative/packages/app-harness/platformBuilds/harness_tizen/output" -n RNVanillaTV.wgt -t T-samsung-7.0-x86
Transferring the package...
Transferred the package: /Users/pauliusguzas/Desktop/renative/renative/packages/app-harness/platformBuilds/harness_tizen/output/RNVanillaTV.wgt -> /home/owner/share/tmp/sdk_tools/tmp
Installing the package...
--------------------
Platform log view
--------------------
Waiting for ready to work. Don't stop the process.
Failed to install Tizen application.
Total time: 00:00:53.133
    at makeError (/Users/pauliusguzas/Desktop/renative/renative/node_modules/execa/lib/error.js:60:11)
    at handlePromise (/Users/pauliusguzas/Desktop/renative/renative/node_modules/execa/index.js:118:26)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)


warn: ○ run: There is no target connected! Let's try to launch it. "rnv target launch -p tizen -t T-samsung-7.0-x86"
✖ FAILED: /Users/pauliusguzas/tizen-studio/tools/emulator/bin/em-cli launch --name T-samsung-7.0-x86
error: ⨯ ○ run: The VM "T-samsung-7.0-x86" is already running.
✔ Waiting for emulator to boot...
✖ FAILED: "/Users/pauliusguzas/tizen-studio/tools/ide/bin/tizen" run -p NkVRhWHJST -t T-samsung-7.0-x86
error: ⨯ ○ run: COMMAND:

"/Users/pauliusguzas/tizen-studio/tools/ide/bin/tizen" run -p NkVRhWHJST -t T-samsung-7.0-x86

FAILED with ERROR:

An error has occurred. See the log file tizen-studio-data/cli/logs/cli.log.

Error: Command failed with exit code 1: "/Users/pauliusguzas/tizen-studio/tools/ide/bin/tizen" run -p NkVRhWHJST -t T-samsung-7.0-x86
Launching the Tizen application...
An error has occurred. See the log file tizen-studio-data/cli/logs/cli.log.
    at makeError (/Users/pauliusguzas/Desktop/renative/renative/node_modules/execa/lib/error.js:60:11)
    at handlePromise (/Users/pauliusguzas/Desktop/renative/renative/node_modules/execa/index.js:118:26)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
```
template-starter
```
pauliusguzas@MBP-de-Flexn template-starter % npx rnv run -p tizen

┌─────────────────────────────────────────────────────────────────┐
│ ██████╗ ███████╗███╗   ██╗ █████╗ ████████╗██╗██╗   ██╗███████╗ │
│ ██╔══██╗██╔════╝████╗  ██║██╔══██╗╚══██╔══╝██║██║   ██║██╔════╝ │
│ ██████╔╝█████╗  ██╔██╗ ██║███████║   ██║   ██║██║   ██║█████╗   │
│ ██╔══██╗██╔══╝  ██║╚██╗██║██╔══██║   ██║   ██║╚██╗ ██╔╝██╔══╝   │
│ ██║  ██║███████╗██║ ╚████║██║  ██║   ██║   ██║ ╚████╔╝ ███████╗ │
│ ╚═╝  ╚═╝╚══════╝╚═╝  ╚═══╝╚═╝  ╚═╝   ╚═╝   ╚═╝  ╚═══╝  ╚══════╝ │
│ 🚀 v:1.0.0 | renative.org | 9/4/2024, 1:32:24 PM                │
│ $ rnv run -p tizen                                              │
└─────────────────────────────────────────────────────────────────┘
info: Current engine: @rnv/engine-rn-web (../engine-rn-web)
task: ○ run ↺1
info: Build hooks not complied. BUILDING...
task: ○ configure ↺1
task: ○ platform configure ↺1
task: ○ project configure ↺1
info: Creating folder ./platformBuilds ...DONE
task: ○ workspace configure ↺1
task: ✔ workspace configure
info: ../../node_modules/@react-native-community/cli-platform-ios/build/tools/listIOSDevices.js overriden by: /@rnv/config-templates/pluginTemplates/@react-native-community/cli-platform-ios/overrides@11.3.7.json
info: ../../node_modules/@react-native-community/cli/build/bin.js overriden by: /@rnv/config-templates/pluginTemplates/@react-native-community/cli/overrides.json
info: ../../node_modules/react-native-tvos/Libraries/Components/ScrollView/ScrollViewNativeComponent.js overriden by: /@rnv/config-templates/pluginTemplates/react-native-tvos/overrides.json
info: ../../node_modules/react-native-tvos/Libraries/Components/ScrollView/ScrollViewNativeComponent.js overriden by: /@rnv/config-templates/pluginTemplates/react-native-tvos/overrides.json
info: ../../node_modules/react-native-tvos/Libraries/Components/ScrollView/ScrollViewNativeComponent.js overriden by: /@rnv/config-templates/pluginTemplates/react-native-tvos/overrides.json
task: ○ app configure ↺1
? Which one would you like to pick? template
info: Current app config: template
warn: ○ project configure: Updates to package.json are required: (only info. skipping due to template mode)
- dotenv (N/A) => (16.4.5) Missing dependency for platform ios | engine.npm (@rnv/engine-rn)
- dotenv (N/A) => (16.4.5) Missing dependency for platform tvos | engine.npm (@rnv/engine-rn-tvos)
- raf (N/A) => (3.4.1) Missing dependency for platform tizen | engine.npm (@rnv/engine-rn-web)

task: ✔ app configure
info: ../../node_modules/@react-native-community/cli-platform-ios/build/tools/listIOSDevices.js overriden by: /@rnv/config-templates/pluginTemplates/@react-native-community/cli-platform-ios/overrides@11.3.7.json
info: ../../node_modules/@react-native-community/cli/build/bin.js overriden by: /@rnv/config-templates/pluginTemplates/@react-native-community/cli/overrides.json
info: ../../node_modules/react-native-tvos/Libraries/Components/ScrollView/ScrollViewNativeComponent.js overriden by: /@rnv/config-templates/pluginTemplates/react-native-tvos/overrides.json
info: ../../node_modules/react-native-tvos/Libraries/Components/ScrollView/ScrollViewNativeComponent.js overriden by: /@rnv/config-templates/pluginTemplates/react-native-tvos/overrides.json
info: ../../node_modules/react-native-tvos/Libraries/Components/ScrollView/ScrollViewNativeComponent.js overriden by: /@rnv/config-templates/pluginTemplates/react-native-tvos/overrides.json
task: ✔ project configure
info: Current Build Scheme: debug
task: ○ sdk configure ↺1
task: ✔ sdk configure
task: ✔ platform configure
✔ Executing: "/Users/pauliusguzas/tizen-studio/tools/ide/bin/tizen" security-profiles list -n RNVanillaCert
info: Found custom assetSources at ../../node_modules/@flexn/assets-renative-outline/assets/tizen. Will be used to generate assets.
task: ✔ configure
info: Your tizen devServer at port 8087 is not running. Starting it up for you...
info: Your tizen devServerHost 127.0.0.1 at port 8087 is not running. Starting it up for you...
┌─────────────────────────────────────────────────────────────────┐
│ ⚠ BUNDLER STARTED | 9/4/2024, 1:37:45 PM | rnv@1.0.0            │
│ $ rnv run -p tizen                                              │
├─────────────────────────────────────────────────────────────────┤
│ Project: @rnv/template-starter@1.0.0                            │
│ Workspace: rnv                                                  │
│ Platform (-p): tizen                                            │
│ Engine: @rnv/engine-rn-web                                      │
│ Template: @rnv/template-starter                                 │
│ App Config (-c): template                                       │
│ Build Scheme (-s): debug                                        │
│ Target (-t): T-samsung-7.0-x86                                  │
│ Supported Platforms: ios, android, androidtv, firetv, androidwear, web, tizen, tvos, webos, macos, tizenwatch, kaios, chromecast, linux, windows
│ Env Info: darwin | x64 | node v18.18.0                          │
│ Executed Time: 0h:5m:20s:893ms                                  │
│ warn: ○ project configure: Updates to package.json are required: (only info. skipping due to template mode)
│ Project location: ./platformBuilds/template_tizen               │
└─────────────────────────────────────────────────────────────────┘
warn: ○ run: You are missing chii. You can install via npm i -g chii) Trying to use weinre next
warn: ○ run: You are missing weinre. Skipping debug. install via npm i -g weinre
(node:39715) [DEP_WEBPACK_DEV_SERVER_ON_AFTER_SETUP_MIDDLEWARE] DeprecationWarning: 'onAfterSetupMiddleware' option is deprecated. Please use the 'setupMiddlewares' option.
(Use `node --trace-deprecation ...` to show where the warning was created)
(node:39715) [DEP_WEBPACK_DEV_SERVER_ON_BEFORE_SETUP_MIDDLEWARE] DeprecationWarning: 'onBeforeSetupMiddleware' option is deprecated. Please use the 'setupMiddlewares' option.
Starting the development server...

Compiled successfully!

You can now view @rnv/template-starter in the browser.

  Local:            http://localhost:8087
  On Your Network:  http://192.168.8.181:8087

Note that the development build is not optimized.
To create a production build, use npm run build.

assets by path static/ 3.48 MiB
  asset static/js/bundle.js 3.17 MiB [emitted] (name: main) 1 related asset
  asset static/media/Inter-Light.58a136ec3193fa8a63e5.ttf 303 KiB [emitted] [immutable] [from: appConfigs/base/fonts/Inter-Light.ttf] (auxiliary name: main)
  asset static/media/logo.63d54a55b067ffc3e842.png 12.1 KiB [emitted] [immutable] [from: platformAssets/runtime/logo.png] (auxiliary name: main)
asset index.html 1.77 KiB [emitted]
asset asset-manifest.json 356 bytes [emitted]
runtime modules 28.8 KiB 14 modules
modules by path ../ 845 KiB 446 modules
modules by path ./ 1.82 MiB (javascript) 315 KiB (asset)
  modules by path ./node_modules/react-native-web/dist/ 711 KiB 196 modules
  modules by path ./platformAssets/ 3.31 KiB (javascript) 12.1 KiB (asset) 4 modules
  modules by path ./src/ 15 KiB
    ./src/entry/index.web.tsx 1.47 KiB [built] [code generated]
    + 2 modules
  modules by path ./node_modules/react-dom/ 1.07 MiB
    ./node_modules/react-dom/client.js 620 bytes [built] [code generated]
    + 2 modules
  modules by path ./node_modules/scheduler/ 19 KiB
    ./node_modules/scheduler/index.js 197 bytes [built] [code generated]
    ./node_modules/scheduler/cjs/scheduler.development.js 18.8 KiB [built] [code generated]
  + 5 modules
webpack 5.94.0 compiled successfully in 10383 ms
No issues found.
✔ Executing: "/Users/pauliusguzas/tizen-studio/tools/sdb" devices
✔ Executing: /Users/pauliusguzas/tizen-studio/tools/emulator/bin/em-cli launch --name T-samsung-7.0-x86
✔ Waiting for emulator to boot...
✔ Executing: "/Users/pauliusguzas/tizen-studio/tools/ide/bin/tizen" build-web -- "/Users/pauliusguzas/Desktop/renative/renative/packages/template-starter/platformBuilds/template_tizen" -out "/Users/pauliusguzas/Desktop/renative/renative/packages/template-starter/platformBuilds/template_tizen/intermediate"
✔ Executing: "/Users/pauliusguzas/tizen-studio/tools/ide/bin/tizen" package -- "/Users/pauliusguzas/Desktop/renative/renative/packages/template-starter/platformBuilds/template_tizen/intermediate" -s RNVanillaCert -t wgt -o "/Users/pauliusguzas/Desktop/renative/renative/packages/template-starter/platformBuilds/template_tizen/output"
✔ Executing: "/Users/pauliusguzas/tizen-studio/tools/ide/bin/tizen" uninstall -p NkVRhWHJST -t T-samsung-7.0-x86
✔ Executing: "/Users/pauliusguzas/tizen-studio/tools/ide/bin/tizen" install -- "/Users/pauliusguzas/Desktop/renative/renative/packages/template-starter/platformBuilds/template_tizen/output" -n RNVanillaTV.wgt -t T-samsung-7.0-x86
✖ FAILED: "/Users/pauliusguzas/tizen-studio/tools/ide/bin/tizen" run -p NkVRhWHJST -t T-samsung-7.0-x86
error: ⨯ ○ run: COMMAND:

"/Users/pauliusguzas/tizen-studio/tools/ide/bin/tizen" run -p NkVRhWHJST -t T-samsung-7.0-x86

FAILED with ERROR:

An error has occurred. See the log file tizen-studio-data/cli/logs/cli.log.

Error: Command failed with exit code 1: "/Users/pauliusguzas/tizen-studio/tools/ide/bin/tizen" run -p NkVRhWHJST -t T-samsung-7.0-x86
Launching the Tizen application...
An error has occurred. See the log file tizen-studio-data/cli/logs/cli.log.
    at makeError (/Users/pauliusguzas/Desktop/renative/renative/node_modules/execa/lib/error.js:60:11)
    at handlePromise (/Users/pauliusguzas/Desktop/renative/renative/node_modules/execa/index.js:118:26)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
```

**Comment by pauliusguzas** [comment]
Not a bug, 8.0 simulator needs to be used
