### ISSUE TITLE
Tizen generated certificate isn't working and no option to override it

### ISSUE THREAD

**Issue by youssefali424** [flexn-io/renative#1712]
**Describe the bug**

Tizen generated certificate isn't working and no option to override the default certificate name that is added as static constant
i could only fix this issue by recreating the certificate with certificate manager that has the same name

**To Reproduce**

1. Generate template
2. `npx rnv run -p tizen` 
3. Error shows indicating that the certificate chain can't be validated

**Expected behavior**

- Generated certificate should work out of the box

OR

- Allow to override the used certificate

**Desktop (please complete the following information):**

-   OS: windows 11 pro
-   Node Version 10.8.0
-   RNV Version 1.1.0

**Comment by pauliusguzas** [comment]
@youssefali424 thanks for reporting, could you add cli logs? Also version of simualtor used

**Comment by youssefali424** [comment]
@pauliusguzas is there a way to override platformBuilds/appid.json ? or at least certificateProfile under tizen ?
that is the error and i am made sure the certificate exists in certificate manager
<details>

<summary>Cli error</summary>

```sh 
install NkVRhWHJST.RNVanillaTV
package_path /home/owner/share/tmp/sdk_tools/tmp/RNVanillaTV.wgt
app_id[NkVRhWHJST.RNVanillaTV] install start
app_id[NkVRhWHJST.RNVanillaTV] installing[9]
app_id[NkVRhWHJST.RNVanillaTV] installing[19]
app_id[NkVRhWHJST.RNVanillaTV] install failed[118, -12], reason: Check certificate error : :Invalid certificate chain with certificate in signature.:<-3>
spend time for wascmd is [228]ms
Failed to install Tizen application.
Total time: 00:00:00.968
    at makeError (C:\Users\User\Desktop\computer\projects\tizen\tizen_test\node_modules\execa\lib\error.js:60:11)    
    at handlePromise (C:\Users\User\Desktop\computer\projects\tizen\tizen_test\node_modules\execa\index.js:118:26)   
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
  ```
  </details>

**Comment by justinasRm** [comment]
We are currently working on a better solution, but before it is finished, to make running tizen work, you can create a Samsung certificate through certificate-manager, and then just add the name in appConfigs/app/renative.json platforms.tizen.certificateProfile(or platforms.tizenwatch, platforms.tizenmobile).

Take notice - you still have to have the default RNV certificate created (RNVanillaCert), because currently it still checks if it exists, even though it will use the one you set in renative.json when doing `rnv run -p tizen`.

**Comment by pauliusguzas** [comment]
`npx rnv tizen certificate` works on monorepo but fails on new project

```
pauliusguzas@MBP-de-Flexn bba % npx rnv tizen certificate

┌─────────────────────────────────────────────────────────────────┐
│ ██████╗ ███████╗███╗   ██╗ █████╗ ████████╗██╗██╗   ██╗███████╗ │
│ ██╔══██╗██╔════╝████╗  ██║██╔══██╗╚══██╔══╝██║██║   ██║██╔════╝ │
│ ██████╔╝█████╗  ██╔██╗ ██║███████║   ██║   ██║██║   ██║█████╗   │
│ ██╔══██╗██╔══╝  ██║╚██╗██║██╔══██║   ██║   ██║╚██╗ ██╔╝██╔══╝   │
│ ██║  ██║███████╗██║ ╚████║██║  ██║   ██║   ██║ ╚████╔╝ ███████╗ │
│ ╚═╝  ╚═╝╚══════╝╚═╝  ╚═══╝╚═╝  ╚═╝   ╚═╝   ╚═╝  ╚═══╝  ╚══════╝ │
│ $ npx rnv tizen certificate                                     │
└─────────────────────────────────────────────────────────────────┘
info: Current engine: @rnv/engine-rn-web (./node_modules/@rnv/engine-rn-web)
task: ○ tizen certificate ↺1
task: ○ app configure ↺1
info: Current app config: app
task: ✔ app configure
error: ⨯ ○ tizen certificate: Error: ENOENT: no such file or directory, open '/Users/pauliusguzas/Desktop/bba/appConfigs/base/renative.json'
    at Object.openSync (node:fs:603:3)
    at Object.readFileSync (node:fs:471:35)
    at /Users/pauliusguzas/Desktop/bba/node_modules/@rnv/sdk-tizen/src/tasks/taskChangeCertificate.ts:11:56
    at step (/Users/pauliusguzas/Desktop/bba/node_modules/tslib/tslib.js:196:27)
    at Object.next (/Users/pauliusguzas/Desktop/bba/node_modules/tslib/tslib.js:177:57)
    at /Users/pauliusguzas/Desktop/bba/node_modules/tslib/tslib.js:170:75
    at new Promise (<anonymous>)
    at Object.__awaiter (/Users/pauliusguzas/Desktop/bba/node_modules/tslib/tslib.js:166:16)
    at Object.fn (/Users/pauliusguzas/Desktop/bba/node_modules/@rnv/sdk-tizen/lib/tasks/taskChangeCertificate.js:12:24)
    at /Users/pauliusguzas/Desktop/bba/node_modules/@rnv/core/src/tasks/taskExecutors.ts:165:28

┌─────────────────────────────────────────────────────────────────┐
│ ⨯ SUMMARY | 17/10/2024, 14:08:15 | rnv@                         │
│ $ npx rnv tizen certificate                                     │
├─────────────────────────────────────────────────────────────────┤
│ Project: bba@0.1.0                                              │
│ Workspace: rnv                                                  │
│ Engine: @rnv/engine-rn-web                                      │
│ App Config (-c): app                                            │
│ Build Scheme (-s): debug                                        │
│ Env Info: darwin | x64 | node v18.18.0                          │
│ Executed Time: 0h:0m:0s:445ms                                   │
│ error: ⨯ ○ tizen certificate: Error: ENOENT: no such file or directory, open '/Users/pauliusguzas/Desktop/bba/appConfigs/base/renative.json'
    at Object.openSync (node:fs:603:3)
    at Object.readFileSync (node:fs:471:35)
    at /Users/pauliusguzas/Desktop/bba/node_modules/@rnv/sdk-tizen/src/tasks/taskChangeCertificate.ts:11:56
    at step (/Users/pauliusguzas/Desktop/bba/node_modules/tslib/tslib.js:196:27)
    at Object.next (/Users/pauliusguzas/Desktop/bba/node_modules/tslib/tslib.js:177:57)
    at /Users/pauliusguzas/Desktop/bba/node_modules/tslib/tslib.js:170:75
    at new Promise (<anonymous>)
    at Object.__awaiter (/Users/pauliusguzas/Desktop/bba/node_modules/tslib/tslib.js:166:16)
    at Object.fn (/Users/pauliusguzas/Desktop/bba/node_modules/@rnv/sdk-tizen/lib/tasks/taskChangeCertificate.js:12:24)
    at /Users/pauliusguzas/Desktop/bba/node_modules/@rnv/core/src/tasks/taskExecutors.ts:165:28

└─────────────────────────────────────────────────────────────────┘
pauliusguzas@MBP-de-Flexn bba %
```
