### ISSUE TITLE
[tizenwatch] App isn't installed to tizenwatch device

### ISSUE THREAD

**Issue by pauliusguzas** [flexn-io/renative#1739]
**Describe the bug**
app can't be installed to tizenwatch device

**To Reproduce**
1. Go to template-starter package
2. Be sure that tizenwatch device is connected on tizen studio
3. Do `npx rnv run -p tizen`

**Expected behavior**
App is installed to tizenwatch

**Screenshots or copy&paste**
```
pauliusguzas@MBP-de-Flexn template-starter % npx rnv run -p tizenwatch -t 192.16
8.1.31


┌─────────────────────────────────────────────────────────────────┐
│ ██████╗ ███████╗███╗   ██╗ █████╗ ████████╗██╗██╗   ██╗███████╗ │
│ ██╔══██╗██╔════╝████╗  ██║██╔══██╗╚══██╔══╝██║██║   ██║██╔════╝ │
│ ██████╔╝█████╗  ██╔██╗ ██║███████║   ██║   ██║██║   ██║█████╗   │
│ ██╔══██╗██╔══╝  ██║╚██╗██║██╔══██║   ██║   ██║╚██╗ ██╔╝██╔══╝   │
│ ██║  ██║███████╗██║ ╚████║██║  ██║   ██║   ██║ ╚████╔╝ ███████╗ │
│ ╚═╝  ╚═╝╚══════╝╚═╝  ╚═══╝╚═╝  ╚═╝   ╚═╝   ╚═╝  ╚═══╝  ╚══════╝ │
│ 🚀 v:1.3.0-rc.2 | renative.org | 10/1/2024, 1:43:07 PM          │
│ $ rnv run -p tizenwatch -t 192.168.1.31                         │
└─────────────────────────────────────────────────────────────────┘
info: Current engine: @rnv/engine-rn-web (../engine-rn-web)
task: ○ run ↺1
task: ○ configure ↺1
task: ○ platform configure ↺1
task: ○ project configure ↺1
task: ○ workspace configure ↺1
task: ✔ workspace configure
task: ○ app configure ↺1
info: Current app config: template
task: ✔ app configure
info: ../../node_modules/@react-native-community/cli-platform-ios/build/tools/listIOSDevices.js overridden by: /@rnv/config-templates/pluginTemplates/@react-native-community/cli-platform-ios/overrides@12.3.6.json
info: ../../node_modules/@react-native-community/cli-platform-ios/build/tools/listIOSDevices.js overridden by: /@rnv/config-templates/pluginTemplates/@react-native-community/cli-platform-ios/overrides@12.3.6.json
info: ../../node_modules/@react-native-community/cli-platform-ios/build/commands/runIOS/index.js overridden by: /@rnv/config-templates/pluginTemplates/@react-native-community/cli-platform-ios/overrides@12.3.6.json
info: ../../node_modules/@react-native-community/cli/build/bin.js overridden by: /@rnv/config-templates/pluginTemplates/@react-native-community/cli/overrides.json
info: ../../node_modules/react-native/node_modules/@react-native-community/cli/build/bin.js overridden by: /@rnv/config-templates/pluginTemplates/@react-native-community/cli/overrides.json
info: ../../node_modules/react-native-tvos/node_modules/@react-native-community/cli/build/bin.js overridden by: /@rnv/config-templates/pluginTemplates/@react-native-community/cli/overrides.json
info: ../../node_modules/react-native-tvos/Libraries/Components/ScrollView/ScrollViewNativeComponent.js overridden by: /@rnv/config-templates/pluginTemplates/react-native-tvos/overrides.json
info: ../../node_modules/react-native-tvos/Libraries/Components/ScrollView/ScrollViewNativeComponent.js overridden by: /@rnv/config-templates/pluginTemplates/react-native-tvos/overrides.json
info: ../../node_modules/react-native-tvos/Libraries/Components/ScrollView/ScrollViewNativeComponent.js overridden by: /@rnv/config-templates/pluginTemplates/react-native-tvos/overrides.json
task: ✔ project configure
info: Current Build Scheme: debug
task: ○ sdk configure ↺1
task: ✔ sdk configure
task: ✔ platform configure
✔ Executing: "/Users/pauliusguzas/tizen-studio/tools/ide/bin/tizen" security-profiles list -n RNVanillaCert
warn: ○ configure: AssetSources is specified as {{resolvePackage(@flexn/assets-renative-outline)}}/assets. But path ../../node_modules/@flexn/assets-renative-outline/assets/tizenwatch was not found.
warn: ○ configure: Your app is missing assets at ./appConfigs/base,./appConfigs/template.
task: ✔ configure
info: Your tizenwatch devServer at port 8090 is not running. Starting it up for you...
info: Your tizenwatch devServerHost 127.0.0.1 at port 8090 is not running. Starting it up for you...
┌─────────────────────────────────────────────────────────────────┐
│ ⚠ BUNDLER STARTED | 10/1/2024, 1:43:12 PM | rnv@1.3.0-rc.2      │
│ $ rnv run -p tizenwatch -t 192.168.1.31                         │
├─────────────────────────────────────────────────────────────────┤
│ Project: @rnv/template-starter@1.3.0-rc.2                       │
│ Workspace: rnv                                                  │
│ Platform (-p): tizenwatch                                       │
│ Engine: @rnv/engine-rn-web                                      │
│ App Config (-c): template                                       │
│ Build Scheme (-s): debug                                        │
│ Target (-t): 192.168.1.31                                       │
│ Supported Platforms: ios, android, androidtv, firetv, androidwear, web, tizen, tvos, webos, macos, tizenwatch, kaios, chromecast, linux, windows
│ Env Info: darwin | x64 | node v18.18.0                          │
│ Executed Time: 0h:0m:4s:380ms                                   │
│ warn: ○ configure: AssetSources is specified as {{resolvePackage(@flexn/assets-renative-outline)}}/assets. But path ../../node_modules/@flexn/assets-renative-outline/assets/tizenwatch was not found.
│ warn: ○ configure: Your app is missing assets at ./appConfigs/base,./appConfigs/template.
│ Project location: ./platformBuilds/template_tizenwatch          │
└─────────────────────────────────────────────────────────────────┘
warn: ○ run: You are missing chii. You can install via npm i -g chii) Trying to use weinre next
warn: ○ run: You are missing weinre. Skipping debug. install via npm i -g weinre
(node:2700) [DEP_WEBPACK_DEV_SERVER_ON_AFTER_SETUP_MIDDLEWARE] DeprecationWarning: 'onAfterSetupMiddleware' option is deprecated. Please use the 'setupMiddlewares' option.
(Use `node --trace-deprecation ...` to show where the warning was created)
(node:2700) [DEP_WEBPACK_DEV_SERVER_ON_BEFORE_SETUP_MIDDLEWARE] DeprecationWarning: 'onBeforeSetupMiddleware' option is deprecated. Please use the 'setupMiddlewares' option.
Starting the development server...

Compiled successfully!

You can now view @rnv/template-starter in the browser.

  Local:            http://localhost:8090
  On Your Network:  http://192.168.1.33:8090

Note that the development build is not optimized.
To create a production build, use npm run build.

assets by path static/ 3.48 MiB
  asset static/js/bundle.js 3.17 MiB [emitted] (name: main) 1 related asset
  asset static/media/Inter-Light.58a136ec3193fa8a63e5.ttf 303 KiB [emitted] [immutable] [from: appConfigs/base/fonts/Inter-Light.ttf] (auxiliary name: main)
  asset static/media/logo.63d54a55b067ffc3e842.png 12.1 KiB [emitted] [immutable] [from: platformAssets/runtime/logo.png] (auxiliary name: main)
asset index.html 1.9 KiB [emitted]
asset asset-manifest.json 356 bytes [emitted]
runtime modules 28.8 KiB 14 modules
modules by path ../ 845 KiB 446 modules
modules by path ./ 1.82 MiB (javascript) 315 KiB (asset)
  modules by path ./node_modules/react-native-web/dist/ 711 KiB 196 modules
  modules by path ./platformAssets/ 3.31 KiB (javascript) 12.1 KiB (asset) 4 modules
  modules by path ./src/ 15 KiB
    ./src/entry/index.web.tsx 1.47 KiB [built] [code generated]
    + 2 modules
  modules by path ./node_modules/react-dom/ 1.07 MiB
    ./node_modules/react-dom/client.js 620 bytes [built] [code generated]
    + 2 modules
  modules by path ./node_modules/scheduler/ 19 KiB
    ./node_modules/scheduler/index.js 197 bytes [built] [code generated]
    ./node_modules/scheduler/cjs/scheduler.development.js 18.8 KiB [built] [code generated]
  + 5 modules
webpack 5.94.0 compiled successfully in 3510 ms
No issues found.
✔ Executing: "/Users/pauliusguzas/tizen-studio/tools/sdb" devices
✔ Executing: "/Users/pauliusguzas/tizen-studio/tools/sdb" devices
✔ Executing: "/Users/pauliusguzas/tizen-studio/tools/ide/bin/tizen" build-web -- "/Users/pauliusguzas/Desktop/renative/renative/packages/template-starter/platformBuilds/template_tizenwatch" -out "/Users/pauliusguzas/Desktop/renative/renative/packages/template-starter/platformBuilds/template_tizenwatch/intermediate"
✔ Executing: "/Users/pauliusguzas/tizen-studio/tools/ide/bin/tizen" package -- "/Users/pauliusguzas/Desktop/renative/renative/packages/template-starter/platformBuilds/template_tizenwatch/intermediate" -s RNVanillaCert -t wgt -o "/Users/pauliusguzas/Desktop/renative/renative/packages/template-starter/platformBuilds/template_tizenwatch/output"
✔ Executing: "/Users/pauliusguzas/tizen-studio/tools/ide/bin/tizen" uninstall -p cHIP2fIRQZ -t SM-R500
✖ FAILED: "/Users/pauliusguzas/tizen-studio/tools/ide/bin/tizen" install -- "/Users/pauliusguzas/Desktop/renative/renative/packages/template-starter/platformBuilds/template_tizenwatch/output" -n RNVanillaWatch.wgt -t SM-R500
error: ⨯ ○ run: COMMAND:

"/Users/pauliusguzas/tizen-studio/tools/ide/bin/tizen" install -- "/Users/pauliusguzas/Desktop/renative/renative/packages/template-starter/platformBuilds/template_tizenwatch/output" -n RNVanillaWatch.wgt -t SM-R500

FAILED with ERROR:

__return_cb req_id[1] pkg_type[wgt] pkgid[cHIP2fIRQZ] key[error] val[-12] error message: :Non trusted certificate is used. Register valid certificate:<-32>
__return_cb req_id[1] pkg_type[wgt] pkgid[cHIP2fIRQZ] key[end] val[fail]
processing result : Check certificate error [-12] failed
spend time for pkgcmd is [1530]ms
Failed to install Tizen application.
Total time: 00:00:03.966

Error: Command failed with exit code 1: "/Users/pauliusguzas/tizen-studio/tools/ide/bin/tizen" install -- "/Users/pauliusguzas/Desktop/renative/renative/packages/template-starter/platformBuilds/template_tizenwatch/output" -n RNVanillaWatch.wgt -t SM-R500
path is /home/owner/share/tmp/sdk_tools/tmp/RNVanillaWatch.wgt
__return_cb req_id[1] pkg_type[wgt] pkgid[cHIP2fIRQZ] key[start] val[install]
__return_cb req_id[1] pkg_type[wgt] pkgid[cHIP2fIRQZ] key[install_percent] val[10]
__return_cb req_id[1] pkg_type[wgt] pkgid[cHIP2fIRQZ] key[install_percent] val[13]
__return_cb req_id[1] pkg_type[wgt] pkgid[cHIP2fIRQZ] key[install_percent] val[16]
__return_cb req_id[1] pkg_type[wgt] pkgid[cHIP2fIRQZ] key[install_percent] val[18]
__return_cb req_id[1] pkg_type[wgt] pkgid[cHIP2fIRQZ] key[install_percent] val[21]
__return_cb req_id[1] pkg_type[wgt] pkgid[cHIP2fIRQZ] key[install_percent] val[24]
__return_cb req_id[1] pkg_type[wgt] pkgid[cHIP2fIRQZ] key[error] val[-12] error message: :Non trusted certificate is used. Register valid certificate:<-32>
__return_cb req_id[1] pkg_type[wgt] pkgid[cHIP2fIRQZ] key[end] val[fail]
processing result : Check certificate error [-12] failed
spend time for pkgcmd is [1530]ms

Failed to install Tizen application.
Total time: 00:00:03.966
    at makeError (/Users/pauliusguzas/Desktop/renative/renative/node_modules/execa/lib/error.js:60:11)
    at handlePromise (/Users/pauliusguzas/Desktop/renative/renative/node_modules/execa/index.js:118:26)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)


warn: ○ run: There is no target connected! Let's try to launch it. "rnv target launch -p tizenwatch -t 192.168.1.31"
✖ FAILED: /Users/pauliusguzas/tizen-studio/tools/emulator/bin/em-cli launch --name 192.168.1.31
error: ⨯ ○ run: The VM/device "192.168.1.31" does not exist.
✔ Executing: "/Users/pauliusguzas/tizen-studio/tools/emulator/bin/em-cli" list-vm
✔ Executing: "/Users/pauliusguzas/tizen-studio/tools/sdb" devices
✔ Executing: "/Users/pauliusguzas/tizen-studio/tools/emulator/bin/em-cli" detail -n T-8.0-x86_64
✔ Executing: "/Users/pauliusguzas/tizen-studio/tools/emulator/bin/em-cli" detail -n T-samsung-7.0-x86
✔ Executing: "/Users/pauliusguzas/tizen-studio/tools/emulator/bin/em-cli" detail -n W-6.5-circle-x86
✔ Executing: "/Users/pauliusguzas/tizen-studio/tools/emulator/bin/em-cli" detail -n W-7.0-circle-x86
✔ Executing: "/Users/pauliusguzas/tizen-studio/tools/emulator/bin/em-cli" detail -n M-7.0-x86
✔ Executing: "/Users/pauliusguzas/tizen-studio/tools/emulator/bin/em-cli" detail -n M-6.5-x86
✔ Executing: "/Users/pauliusguzas/tizen-studio/tools/emulator/bin/em-cli" detail -n T-8.0-x86
? which emulator or device would you like to launch? (Use arrow keys)
❯ W-6.5-circle-x86
  W-7.0-circle-x86
  192.168.1.31:26101
```

**Desktop (please complete the following information):**
-   OS: Ventura 13.5.2
-   Node Version 18.18.0
-   RNV Version 1.3.0-rc.2
-   template-starter Version 1.3.0-rc.2

**Comment by Marius456** [comment]
How to create certificate for Samsung watch:

1. Connect your watch with computer using Tizen Device Manager.
2. Go to "Tizen Certificate Manager"
3. Press add new certificate profile.
<img width="663" alt="Screenshot 2024-11-13 at 10 18 20" src="https://github.com/user-attachments/assets/f532903b-2561-4873-8dfb-f9242852d7f1">

4. Select samsung certificate
<img width="595" alt="Screenshot 2024-11-13 at 10 19 56" src="https://github.com/user-attachments/assets/62706901-a335-4170-aafb-bda208f3f760">

5. Follow this by selecting these options:
- Mobile/Wearable
- Create new certificate profile. Write down new certificate name.
- Create a new author certificate.
- Write down your created user name and password.
- Sign in to your Samsung account in browser
- Skip backup (your preference)
- Create new distributor certificate
6. Now you should have certificate verified by Samsung
<img width="475" alt="Screenshot 2024-11-13 at 10 44 36" src="https://github.com/user-attachments/assets/24a53701-5a7d-438e-a8ce-164d441c4bd9">

7. Now to to ReNative project and run command `npx rnv tizen certificate` select `tizenwatch` and write down your new certificate name.

**Comment by pauliusguzas** [comment]
fails on new project, did all steps
![image](https://github.com/user-attachments/assets/39541ccd-0f1d-4a07-ac4f-f45dc958bf6b)
