### ISSUE TITLE
Error "ENOENT: no such file or directory, scandir 'C:\webOS_TV_SDK\Simulator'" when trying to run the webOS TV simulator on Windows

### ISSUE THREAD

**Issue by arielsardinha** [flexn-io/renative#1755]
I'm trying to run my webOS TV application on Windows using the command npx rnv run -p webos, but I get the following error:

`error: ⨯ ○ run: Error: ENOENT: no such file or directory, scandir 'C:\webOS_TV_SDK\Simulator'`

```text
PS D:\free-lancers\my_smart_app> npx rnv run -p webos

┌─────────────────────────────────────────────────────────────────┐
│ ██████╗ ███████╗███╗   ██╗ █████╗ ████████╗██╗██╗   ██╗███████╗ │
│ ██╔══██╗██╔════╝████╗  ██║██╔══██╗╚══██╔══╝██║██║   ██║██╔════╝ │
│ ██████╔╝█████╗  ██╔██╗ ██║███████║   ██║   ██║██║   ██║█████╗   │
│ ██╔══██╗██╔══╝  ██║╚██╗██║██╔══██║   ██║   ██║╚██╗ ██╔╝██╔══╝   │
│ ██║  ██║███████╗██║ ╚████║██║  ██║   ██║   ██║ ╚████╔╝ ███████╗ │
│ ╚═╝  ╚═╝╚══════╝╚═╝  ╚═══╝╚═╝  ╚═╝   ╚═╝   ╚═╝  ╚═══╝  ╚══════╝ │
│ $ rnv run -p webos                                              │
└─────────────────────────────────────────────────────────────────┘
info: Current engine: @rnv/engine-rn-web (D:\free-lancers\my_smart_app\node_modules\@rnv\engine-rn-web)
task: ○ run ↺1
task: ○ configure ↺1
task: ○ platform configure ↺1
task: ○ project configure ↺1
task: ○ workspace configure ↺1
task: ✔ workspace configure
task: ○ app configure ↺1
info: Current app config: app
task: ✔ app configure
info: D:\free-lancers\my_smart_app\node_modules\@react-native-community\cli-platform-ios\build\tools\listIOSDevices.js overridden by: \@rnv\config-templates\pluginTemplates\@react-native-community\cli-platform-ios\overrides@12.3.6.json
info: D:\free-lancers\my_smart_app\node_modules\@react-native-community\cli-platform-ios\build\tools\listIOSDevices.js overridden by: \@rnv\config-templates\pluginTemplates\@react-native-community\cli-platform-ios\overrides@12.3.6.json
info: D:\free-lancers\my_smart_app\node_modules\@react-native-community\cli-platform-ios\build\commands\runIOS\index.js overridden by: \@rnv\config-templates\pluginTemplates\@react-native-community\cli-platform-ios\overrides@12.3.6.json
info: D:\free-lancers\my_smart_app\node_modules\@react-native-community\cli\build\bin.js overridden by: \@rnv\config-templates\pluginTemplates\@react-native-community\cli\overrides.json
task: ✔ project configure
info: Current Build Scheme: debug
task: ○ sdk configure ↺1
task: ✔ sdk configure
task: ✔ platform configure
info: Found custom assetSources at D:\free-lancers\my_smart_app\node_modules\@flexn\assets-renative-outline\assets\webos. Will be used to generate assets.
task: ✔ configure
info: Your webos devServer at port 8088 is not running. Starting it up for you...
info: Your webos devServerHost 127.0.0.1 at port 8088 is not running. Starting it up for you...
┌─────────────────────────────────────────────────────────────────┐
│ ✔ BUNDLER STARTED | 13/10/2024, 19:39:43 | rnv@                 │
│ $ rnv run -p webos                                              │
├─────────────────────────────────────────────────────────────────┤
│ Project: my_smart_app@0.1.0                                     │
│ Workspace: rnv                                                  │
│ Platform (-p): webos                                            │
│ Engine: @rnv/engine-rn-web                                      │
│ Template: @rnv/template-starter                                 │
│ App Config (-c): app                                            │
│ Build Scheme (-s): debug                                        │
│ Supported Platforms: web, ios, android, tizen, webos            │
│ Env Info: win32 | x64 | node v20.18.0                           │
│ Executed Time: 0h:0m:2s:375ms                                   │
│ You are trying to run global rnv command in your current project.
│ This might lead to unexpected behaviour.
│ Run your rnv command with npx prefix:
│ npx rnv run -p webos
│ Project location: D:\free-lancers\my_smart_app\platformBuilds\app_webos
└─────────────────────────────────────────────────────────────────┘
(node:6540) [DEP_WEBPACK_DEV_SERVER_ON_AFTER_SETUP_MIDDLEWARE] DeprecationWarning: 'onAfterSetupMiddleware' option is deprecated. Please use the 'setupMiddlewares' option.
(Use `node --trace-deprecation ...` to show where the warning was created)
(node:6540) [DEP_WEBPACK_DEV_SERVER_ON_BEFORE_SETUP_MIDDLEWARE] DeprecationWarning: 'onBeforeSetupMiddleware' option is deprecated. Please use the 'setupMiddlewares' option.
Starting the development server...

Compiled successfully!

You can now view my_smart_app in the browser.

  Local:            http://localhost:8088
  On Your Network:  http://192.168.1.15:8088

Note that the development build is not optimized.
To create a production build, use yarn build.

assets by path static/ 3.47 MiB
  asset static/js/bundle.js 3.16 MiB [emitted] (name: main) 1 related asset
  asset static/media/Inter-Light.58a136ec3193fa8a63e5.ttf 303 KiB [emitted] [immutable] [from: appConfigs/base/fonts/Inter-Light.ttf] (auxiliary name: main)
  asset static/media/logo.63d54a55b067ffc3e842.png 12.1 KiB [emitted] [immutable] [from: platformAssets/runtime/logo.png] (auxiliary name: main)
asset index.html 1.88 KiB [emitted]
asset asset-manifest.json 356 bytes [emitted]
cached modules 2.65 MiB (javascript) 315 KiB (asset) 28.7 KiB (runtime) [cached] 676 modules
webpack 5.95.0 compiled successfully in 1129 ms
No issues found.
✔ Executing: "C:\Users\Ariel\AppData\Roaming\npm\ares-package.cmd" -o "D:\free-lancers\my_smart_app\platformBuilds\app_webos\output" "D:\free-lancers\my_smart_app\platformBuilds\app_webos" -n
✔ Executing: "C:\Users\Ariel\AppData\Roaming\npm\ares-device.cmd" -D
✔ Executing: "C:\Users\Ariel\AppData\Roaming\npm\ares-launch.cmd" -V
error: ⨯ ○ run: Error: ENOENT: no such file or directory, scandir 'C:\webOS_TV_SDK\Simulator'
```

Here's what I've done so far:

- Downloaded the webOS_TV_24_Simulator_1.4.1.exe from the official site [link](https://webostv.developer.lge.com/develop/tools/simulator-installation) and placed the file in a folder named Simulator inside C:\webOS_TV_SDK.

- Configured the CLI from the [link](https://webostv.developer.lge.com/develop/tools/cli-installation) oficial

- Set up my renative.json file with the SDK path like this:
```json
{
  "defaultTargets": {},
  "sdks": {
    "WEBOS_SDK": "C:\\webOS_TV_SDK"
  }
}
```

Despite these steps, the error persists. Does anyone know how I can fix this or if I'm missing something in the simulator configuration?

Note:

I also tried running it using the command rnv target launch -p webos -t emulator, as instructed in the [documentation](https://next.renative.org/docs/platforms/webos)

However, I didn't understand this configuration: `<USER_PATH>/Library/webOS_TV_SDK/Emulator/v4.0.0/LG_webOS_TV_Emulator_RCU.app`

That said, when configuring a normal project using LG's CLI, everything works as expected.

For example:

```bash
ares-generate -t hosted_webapp smarttv-app-webos
ares-setup-device --modify emulator --simulator-path "D:\dev\webOS_TV_24_Simulator_1.4.1"
ares-launch -s 24 .\smarttv-app-webos\
```

With this setup, the project runs normally.

Either way, it resulted in the following error:

```text
PS D:\free-lancers\my_smart_app> npx rnv target launch -p webos -t emulator

┌─────────────────────────────────────────────────────────────────┐
│ ██████╗ ███████╗███╗   ██╗ █████╗ ████████╗██╗██╗   ██╗███████╗ │
│ ██╔══██╗██╔════╝████╗  ██║██╔══██╗╚══██╔══╝██║██║   ██║██╔════╝ │
│ ██████╔╝█████╗  ██╔██╗ ██║███████║   ██║   ██║██║   ██║█████╗   │
│ ██╔══██╗██╔══╝  ██║╚██╗██║██╔══██║   ██║   ██║╚██╗ ██╔╝██╔══╝   │
│ ██║  ██║███████╗██║ ╚████║██║  ██║   ██║   ██║ ╚████╔╝ ███████╗ │
│ ╚═╝  ╚═╝╚══════╝╚═╝  ╚═══╝╚═╝  ╚═╝   ╚═╝   ╚═╝  ╚═══╝  ╚══════╝ │
│ $ rnv target launch -p webos -t emulator                        │
└─────────────────────────────────────────────────────────────────┘
info: Current engine: @rnv/engine-rn-web (D:\free-lancers\my_smart_app\node_modules\@rnv\engine-rn-web)
task: ○ target launch ↺1
task: ○ workspace configure ↺1
task: ✔ workspace configure
error: ⨯ ○ target launch: Error: ENOENT: no such file or directory, scandir 'C:\webOS_TV_SDK\Simulator'
    at Object.readdirSync (node:fs:1506:26)
    at getDirectories (D:\free-lancers\my_smart_app\node_modules\@rnv\core\src\system\fs.ts:811:10)
    at D:\free-lancers\my_smart_app\node_modules\@rnv\sdk-webos\src\deviceManager.ts:46:54
    at step (D:\free-lancers\my_smart_app\node_modules\tslib\tslib.js:195:27)
    at Object.next (D:\free-lancers\my_smart_app\node_modules\tslib\tslib.js:176:57)
    at D:\free-lancers\my_smart_app\node_modules\tslib\tslib.js:169:75
    at new Promise (<anonymous>)
    at Object.__awaiter (D:\free-lancers\my_smart_app\node_modules\tslib\tslib.js:165:16)
    at launchWebOSimulator (D:\free-lancers\my_smart_app\node_modules\@rnv\sdk-webos\src\deviceManager.ts:37:67)
    at D:\free-lancers\my_smart_app\node_modules\@rnv\sdk-webos\src\tasks\taskTargetLaunch.ts:14:35

┌─────────────────────────────────────────────────────────────────┐
│ ⨯ SUMMARY | 13/10/2024, 19:38:49 | rnv@                         │
│ $ rnv target launch -p webos -t emulator                        │
├─────────────────────────────────────────────────────────────────┤
│ Project: my_smart_app@0.1.0                                     │
│ Workspace: rnv                                                  │
│ Platform (-p): webos                                            │
│ Engine: @rnv/engine-rn-web                                      │
│ Template: @rnv/template-starter                                 │
│ App Config (-c): app                                            │
│ Build Scheme (-s): debug                                        │
│ Env Info: win32 | x64 | node v20.18.0                           │
│ Executed Time: 0h:0m:0s:488ms                                   │
│ error: ⨯ ○ target launch: Error: ENOENT: no such file or directory, scandir 'C:\webOS_TV_SDK\Simulator'
    at Object.readdirSync (node:fs:1506:26)
    at getDirectories (D:\free-lancers\my_smart_app\node_modules\@rnv\core\src\system\fs.ts:811:10)
    at D:\free-lancers\my_smart_app\node_modules\@rnv\sdk-webos\src\deviceManager.ts:46:54
    at step (D:\free-lancers\my_smart_app\node_modules\tslib\tslib.js:195:27)
    at Object.next (D:\free-lancers\my_smart_app\node_modules\tslib\tslib.js:176:57)
    at D:\free-lancers\my_smart_app\node_modules\tslib\tslib.js:169:75
    at new Promise (<anonymous>)
    at Object.__awaiter (D:\free-lancers\my_smart_app\node_modules\tslib\tslib.js:165:16)
    at launchWebOSimulator (D:\free-lancers\my_smart_app\node_modules\@rnv\sdk-webos\src\deviceManager.ts:37:67)
    at D:\free-lancers\my_smart_app\node_modules\@rnv\sdk-webos\src\tasks\taskTargetLaunch.ts:14:35

│ You are trying to run global rnv command in your current project.
│ This might lead to unexpected behaviour.
│ Run your rnv command with npx prefix:
│ npx rnv target launch -p webos -t emulator
└─────────────────────────────────────────────────────────────────┘
PS D:\free-lancers\my_smart_app>
``´

**Comment by arielsardinha** [comment]
![image](https://github.com/user-attachments/assets/5b66699f-8f4f-47c4-9d10-8d53878770c0)

**Comment by pauliusguzas** [comment]
@arielsardinha thanks for reporting, what rnv version are you using?

**Comment by pauliusguzas** [comment]
@arielsardinha The issue most likely is that you put your simulator into sdk folder, your simulator should be put like this `C:\webOS_TV_SDK\Simulator\webOS_TV_24_Simulator_1.4.1`

**Comment by arielsardinha** [comment]
I am using version 1.3.0.

I had already done that, placing the simulator in the indicated folder, which was intuitive due to the warning, but it still doesn't solve the issue, @pauliusguzas 

![image](https://github.com/user-attachments/assets/5ce5507c-0b79-40b6-bb47-4c12208e72d4)

**Comment by Marius456** [comment]
Hello @arielsardinha,
I see that that folder name is a bit confusing. It is actually simulators folder where you put separate simulators.
For example, this webos_tv_23 simulator has its own folder in "Simulator" folder.
![Screenshot 2024-10-14 102512](https://github.com/user-attachments/assets/f8389369-cd8e-41f1-9cf7-1600452e2fb0)

**Comment by arielsardinha** [comment]
That's exactly it, @Marius456.
It worked perfectly.
Thank you so much!!!
