### ISSUE TITLE
Failed to install Emulator (Tizen Studio) on MacOS

### ISSUE THREAD

**Issue by hellofrontendxxx** [flexn-io/renative#1803]
I tried to install Tizen Studio Emulator to test the app but couldn't find a solution. Looking forward to receiving help from everyone. Thanks a lot.

```
Cannot install the Tizen Studio package.
org.tizen.manager.exception.UMException: Cannot install the Tizen Studio package.
  	at org.tizen.manager.core.InstallController.wrapExceptionWithGeneralInstallException(InstallController.java:583)
  	at org.tizen.manager.core.InstallController.install(InstallController.java:658)
  	at org.tizen.manager.core.InstallController.install(InstallController.java:543)
  	at org.tizen.manager.core.Install.InstallProcess.run(InstallProcess.java:65)
  	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
  	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
  	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
  	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
  	at java.lang.Thread.run(Thread.java:750)
  Caused by: org.tizen.manager.exception.UMException: Cannot install the Tizen Studio package.
  	at org.tizen.manager.core.InstallController.waitForInstallingPackagesDone(InstallController.java:1024)
  	at org.tizen.manager.core.InstallController.install(InstallController.java:655)
  	... 7 more
  Caused by: java.lang.Exception: The installation was stopped by failure of dependent packages. ==> 5.0-emulator-sdbscript
  	at org.tizen.manager.core.Install.ManagerableInstallerCallable.call(ManagerableInstallerCallable.java:87)
  	at org.tizen.manager.core.Install.ManagerableInstallerCallable.call(ManagerableInstallerCallable.java:51)
  	... 4 more
```

**Comment by pauliusguzas** [comment]
@hellofrontendxxx hello, thanks for ticket. The issue you are having doesn't look like is related to renative, therefore sorry but not able to help you here

**Comment by pauliusguzas** [comment]
Closing this ticket. Feel free to reopen if rnv issues pop up
