### ISSUE TITLE
RNV Tizen TV unable to deploy into TVs

### ISSUE THREAD

**Issue by RicardasSimcikas** [flexn-io/renative#295]
**Describe the bug**
'rnv run -p tizen -d -t "TV ip" ' - unable to deploy into TVs.

**Screenshots or copy&paste**
**Linux/mac**
```
/home/testlab/tizen-studio/tools/ide/bin/tizen install -- /home/testlab/Desktop/testRnv/platformBuilds/helloWorld_tizen/output -n RNVanillaTV.wgt -t UE43NU7192 

FAILED with ERROR: 

Command failed with exit code 1 (EPERM): /home/testlab/tizen-studio/tools/ide/bin/tizen install -- /home/testlab/Desktop/testRnv/platformBuilds/helloWorld_tizen/output -n RNVanillaTV.wgt -t UE43NU7192
│ ⚠️  $ rnv run -p tizen -d -t 192.168.1.175 - WARNING: Looks like there is no emulator or device connected! Let's try to launch it. "rnv target launch -p tizen -t 192.168.1.175"
│ 🛑  $ rnv run -p tizen -d -t 192.168.1.175 - ERRROR! COMMAND: 

/home/testlab/tizen-studio/tools/emulator/bin/em-cli launch --name 192.168.1.175 

FAILED with ERROR: 

Error: 192.168.1.175 does not match any VM
```
**Windows**
```
C:\tizen-studio\tools\ide\bin\tizen.bat install -- C:\Users\ricsim\Desktop\test\platformBuilds\helloWorld_tizen\output -n RNVanillaTV.wgt -t UE43NU7192
FAILED with ERROR:
Command failed with exit code 2 (ENOENT): C:\tizen-studio\tools\ide\bin\tizen.bat install -- C:\Users\ricsim\Desktop\test\platformBuilds\helloWorld_tizen\output -n RNVanillaTV.wgt -t UE43NU7192
spawn C:\tizen-studio\tools\ide\bin\tizen.bat ENOENT
│ ⚠️  $ rnv run -p tizen -d -t 192.168.1.175 - WARNING: Looks like there is no emulator or device connected! Let's try to launch it. "rnv target launch -p tizen -t 192.168.1.175"
│ 🛑  $ rnv run -p tizen -d -t 192.168.1.175 - ERRROR! COMMAND:
C:\tizen-studio\tools\emulator\bin\em-cli.bat launch --name 192.168.1.175
FAILED with ERROR:
Command failed with exit code 2 (Unknown system error -2): C:\tizen-studio\tools\emulator\bin\em-cli.bat launch --name 192.168.1.175
```

**Desktop (please complete the following information):**
 - OS: Ubuntu 18.04.3 LTS, Windows 10, mac
 - RNV Version [0.27.5-alpha.3]

**Comment by mihaiblaga89** [comment]
@RicardasSimcikas For tizen you first need to enable `Dev mode` on TV then set your PC's IP in "Host PC IP", as specified here (https://developer.samsung.com/tv/develop/getting-started/using-sdk/tv-device), section 1. But we will change the errors on RNV to be a little more descriptive in this case, instead of "EPERM" and provide full guidelines on how to do it.

**Comment by RicardasSimcikas** [comment]
@mihaiblaga89 I did exactly the same and the error is still present.
![Image from iOS](https://user-images.githubusercontent.com/52383327/66183769-b1860c80-e682-11e9-88cc-c9e3a21258c7.jpg)

**Comment by mihaiblaga89** [comment]
If you run `rnv` with `-i` it will give you more info, as stated in the other issue. There you can find the exact commands that are running, for example something with `tizen-studio/.../sdb connect 192.168.1.175`. Try running that command manually and see if it connects to your tv. `sdb` is a copy of android's `adb`, so you can run the same commands to debug, like `sdb devices`

**Comment by RicardasSimcikas** [comment]
**rnv run -p tizen -d -i -t ip**

```
install wgt
package_path /home/owner/share/tmp/sdk_tools/tmp/RNVanillaTV.wgt
was_install_app return WAS_TRUE
app_id[wgt] install start
app_id[wgt] installing[7]
app_id[wgt] installing[9]
app_id[wgt] installing[11]
app_id[wgt] installing[14]
app_id[wgt] installing[16]
app_id[wgt] install failed[118012]
spend time for wascmd is [1190]ms
cmd_ret:0
Failed to install Tizen application.
Total time: 00:00:01.984
🛑  $ rnv run -p tizen -d -i -t 192.168.1.175 - ERRROR! COMMAND:

/Users/ricardassimcikas/tizen-studio/tools/ide/bin/tizen install -- /Users/ricardassimcikas/Desktop/HelloWorld/platformBuilds/helloWorld_tizen/output -n RNVanillaTV.wgt -t UE43NU7192

FAILED with ERROR:

Command failed with exit code 1 (EPERM): /Users/ricardassimcikas/tizen-studio/tools/ide/bin/tizen install -- /Users/ricardassimcikas/Desktop/HelloWorld/platformBuilds/helloWorld_tizen/output -n RNVanillaTV.wgt -t UE43NU7192
⚠️  $ rnv run -p tizen -d -i -t 192.168.1.175 - WARNING: Looks like there is no emulator or device connected! Let's try to launch it. "rnv target launch -p tizen -t 192.168.1.175"
$ rnv run -p tizen -d -i -t 192.168.1.175 - launchTizenSimulator:192.168.1.175 - Starting!
_execute: /Users/ricardassimcikas/tizen-studio/tools/emulator/bin/em-cli launch --name 192.168.1.175
⠸ Executing: /Users/ricardassimcikas/tizen-studio/tools/emulator/bin/em-cli launch --name 192.168.1.175Error: 192.168.1.175 does not match any VM
✖ FAILED: /Users/ricardassimcikas/tizen-studio/tools/emulator/bin/em-cli launch --name 192.168.1.175
Error: 192.168.1.175 does not match any VM
```

I have tried to run  '/Users/ricardassimcikas/tizen-studio/tools/ide/bin/tizen install -- /Users/ricardassimcikas/Desktop/HelloWorld/platformBuilds/helloWorld_tizen/output -n RNVanillaTV.wgt -t UE43NU7192' separately, but output is the same.

**Comment by MrAndrewMal** [comment]
There is news on a bug, how fix?

**Mac**
```
$ rnv run -p tizen -d -t 10.0.0.235 - ERRROR! COMMAND: 

/Users/andrei/tizen-studio/tools/ide/bin/tizen install -- /Users/andrei/work/web/TV/platformBuilds/helloWorld_tizen/output -n RNVanillaTV.wgt -t PH49F 

FAILED with ERROR: 

Error: Command failed with exit code 1 (EPERM): /Users/andrei/tizen-studio/tools/ide/bin/tizen install -- /Users/andrei/work/web/TV/platformBuilds/helloWorld_tizen/output -n RNVanillaTV.wgt -t PH49F
    at makeError (/usr/local/lib/node_modules/rnv/node_modules/execa/lib/error.js:58:11)
    at handlePromise (/usr/local/lib/node_modules/rnv/node_modules/execa/index.js:112:26)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
│ ⚠️  $ rnv run -p tizen -d -t 10.0.0.235 - WARNING: Looks like there is no emulator or device connected! Let's try to launch it. "rnv target launch -p tizen -t 10.0.0.235"
│ 🛑  $ rnv run -p tizen -d -t 10.0.0.235 - ERRROR! COMMAND: 

/Users/andrei/tizen-studio/tools/emulator/bin/em-cli launch --name 10.0.0.235 

FAILED with ERROR: 

Error: 10.0.0.235 does not match any VM
```

Enable Dev mode on TV, set PC ip in "HOST PC IP".

```
➜  tools ./sdb devices           
List of devices attached 
10.0.0.235:26101    	device    	PH49F
```

**Comment by EyMaddis** [comment]
I think I had the same problem... if I remember correctly my workaround was to edit the ~/.rnv/renative.json directly and avoid the `-t` argument

**Comment by Govindsa421** [comment]
ya i have also facing same this issues. while sdb connect its show already connected to tv but while running renative project on tv it is not launhed. 
can anyone help us how to resolve this issues

**Comment by pauliusguzas** [comment]
Hello, probably what is happening here is that Renative has wrong certificate name provided in `appConfigs -> <your_app_name> -> renative.json` under tizen object `"certificateProfile": "<my_cert_name>"`. Renative creates certificate `RNVanillaCert`, so you can try using this in `renative.json` or you can create your own in `TizenStudio -> Tools -> Certificate Manager`
