### ISSUE TITLE
Cannot read property 'renative' of undefined in  RNV PLUGIN UPDATE

### ISSUE THREAD

**Issue by rafagouveia** [flexn-io/renative#660]
**Describe the bug**
When updating the Renative plugins, an undefined error occurs, I tried to create a project from scratch, but the error is the same, I tried to use linux environment, but the error remains the same, I tried to install plugins manually, but I still get the same error .

**To Reproduce**
`rnv plugin update`

2. See error
```
 TypeError: Cannot read property 'renative' of undefined
    at C:\Users\rafae\AppData\Local\Yarn\Data\global\node_modules\rnv\src\engine-core\tasks\task.rnv.plugin.update.js:33:51
    at Array.forEach (<anonymous>)
**Expected behavior**
```

I'm trying to add Socket.io with a third plugin, and update the plugins but I get this error.

Also even adding the dependencies manually, I can't import the library directly on the front with React;

```shell
? Above installed plugins will be updated with RNV Yes
┌──────────────────────────────────────────────────────────────────────────────┐
│  🚀  SUMMARY | 2021-3-5 20:54:48                                             │
│  $ rnv plugin update                                                         │
├──────────────────────────────────────────────────────────────────────────────┤
│  ReNative Version: 0.31.3                                               │
│  Project Name ($package.name): painelsenhahserver                       │
│  Project Version ($package.version): 0.1.0                              │
│  Workspace ($.workspaceID): rnv                                         │
│  Engine: engine-core                                                    │
│  App Config (-c): blank                                                 │
│  Build Scheme (-s): debug                                               │
│  Supported Platforms: tizen, web, windows                          │
│  Env Info: win32 | x64 | node v10.13.0                                  │
│  Executed Time: 0h:0m:4s:938ms                                          │
│                                                                              │
│ [ warn ] [project configure] Extra platform android will be ignored because it's not configured in your ./renative.json: { defaults.supportedPlatforms } object.
│ [ warn ] [project configure] Extra platform androidwear will be ignored because it's not configured in your ./renative.json: { defaults.supportedPlatforms } object.
│ [ warn ] [project configure] Extra platform androidtv will be ignored because it's not configured in your ./renative.json: { defaults.supportedPlatforms } object.
│ [ error ] [plugin update] Cannot read property 'renative' of undefined
TypeError: Cannot read property 'renative' of undefined
    at C:\Users\rafae\AppData\Local\Yarn\Data\global\node_modules\rnv\src\engine-core\tasks\task.rnv.plugin.update.js:33:51
    at Array.forEach (<anonymous>)
    at forEach (C:\Users\rafae\AppData\Local\Yarn\Data\global\node_modules\rnv\src\engine-core\tasks\task.rnv.plugin.update.js:31:30)
    at tryCatch (C:\Users\rafae\AppData\Local\Yarn\Data\global\node_modules\regenerator-runtime\runtime.js:63:40)
    at Generator.invoke [as _invoke] (C:\Users\rafae\AppData\Local\Yarn\Data\global\node_modules\regenerator-runtime\runtime.js:293:22)
    at Generator.next (C:\Users\rafae\AppData\Local\Yarn\Data\global\node_modules\regenerator-runtime\runtime.js:118:21)
    at tryCatch (C:\Users\rafae\AppData\Local\Yarn\Data\global\node_modules\regenerator-runtime\runtime.js:63:40)
    at invoke (C:\Users\rafae\AppData\Local\Yarn\Data\global\node_modules\regenerator-runtime\runtime.js:154:20)
    at C:\Users\rafae\AppData\Local\Yarn\Data\global\node_modules\regenerator-runtime\runtime.js:164:13
```

**Desktop (please complete the following information):**

-   OS: `Windows 10`
-   Node Version: `v10.13.0`
-   RNV Version: `0.31.3

> Renative is still kind of complicated for beginners like me, I hope someone can explain to me how to use third-party plugins and fix this problem, because I have no idea how to fix it.

**Comment by pauliusguzas** [comment]
@rafagouveia Thanks for reporting this issue. Is this still reproduced on latest rnv version?

**Comment by mihaiblaga89** [comment]
closing this for now, feel free to reopen if this happens with the latest version
