### ISSUE TITLE
Could not initialize class org.codehaus.groovy.runtime.InvokerHelper when using "rnv -p androidwear"

### ISSUE THREAD

**Issue by LeonardMichiels** [flexn-io/renative#693]
**Describe the bug**
When I try to ust the "rnv -p androidwear" on a freshly created app. i get an error : Could not initialize class org.codehaus.groovy.runtime.InvokerHelper .

**To Reproduce**

1. Run command "rnv -p androidwear"

**Expected behavior**
This command should start my application on my android studio emulator. So far it boots the emulator properly but then crashes.

**Screenshots or copy&paste**
![image](https://user-images.githubusercontent.com/56160814/123452964-3f382700-d5df-11eb-9a5d-2b08dc966723.png)

**Desktop (please complete the following information):**

-   OS: windows 7
-   Node Version v12.18.2
-   RNV Version v0.31.3

**Additional context**
 I've checked that the JAVA_HOME environement variable is correct and tried with both JDK 15.0.1 and 16.0.1.

**Comment by uplusion23** [comment]
> @uplusion23 you need to update the gradle/ gradle plugin version:
> 
> ```
> "platforms": {
>         "android": {
>             "gradleWrapperVersion": "6.7.1",
>             "gradleBuildToolsVersion": "4.2.1",
> ```

I would enter this under `renative.json/#/platforms/androidwear`? I've tried doing such, but the build resets back to version 5.5 in `~/platformBuilds/blank_appname/gradle/wrapper/gradle-wrapper.properties`.

Thank you for the assistance!

**Comment by pauliusguzas** [comment]
@LeonardMichiels Thanks for reporting this, is this still reproduced on latest rnv?

**Comment by pauliusguzas** [comment]
Tested on 0.37.1 with same version template-starter
macOS and Windows same bug:
```
✖ FAILED: ./gradlew assembleDebug -x bundleReleaseJsAndAssets
┌──────────────────────────────────────────────────────────────────────────────┐
│  🚀  SUMMARY | 7/21/2023, 3:12:02 PM                                         │
│  $ rnv run -p androidwear                                                    │
├──────────────────────────────────────────────────────────────────────────────┤
│  ReNative Version: 0.37.1                                                    │
│  Project Name ($package.name): tizen                                         │
│  Project Version ($package.version): 0.1.0                                   │
│  Workspace ($.workspaceID): rnv                                              │
│  Platform (-p): androidwear                                                  │
│  Engine ($.platforms.androidwear.engine): engine-rn                          │
│  Template: @rnv/template-starter@0.37.1                                      │
│  App Config (-c): app                                                        │
│  Build Scheme (-s): debug                                                    │
│  Target (-t): Android_Wear_Round_API_28                                      │
│  Supported Platforms: androidwear                                            │
│  Env Info: darwin | x64 | node v16.14.2                                      │
│  Executed Time: 0h:1m:32s:209ms                                              │
│                                                                              │
│ [ success ] [run] Found active emulator! emulator-5554. Will use it
│ [ error ] [run] COMMAND:

./gradlew assembleDebug -x bundleReleaseJsAndAssets

FAILED with ERROR:

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:processDebugResources'.
> A failure occurred while executing com.android.build.gradle.internal.res.LinkApplicationAndroidResourcesTask$TaskAction
   > Android resource linking failed
     ERROR:/Users/pauliusguzas/Desktop/tizen/platformBuilds/app_androidwear/app/build/intermediates/packaged_manifests/debug/AndroidManifest.xml:21: AAPT: error: resource mipmap/ic_launcher_round (aka com.mycompany.tizen:mipmap/ic_launcher_round) not found.


* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 37s
38 actionable tasks: 38 executed

Command failed with exit code 1: ./gradlew assembleDebug -x bundleReleaseJsAndAssets

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:processDebugResources'.
> A failure occurred while executing com.android.build.gradle.internal.res.LinkApplicationAndroidResourcesTask$TaskAction
   > Android resource linking failed
     ERROR:/Users/pauliusguzas/Desktop/tizen/platformBuilds/app_androidwear/app/build/intermediates/packaged_manifests/debug/AndroidManifest.xml:21: AAPT: error: resource mipmap/ic_launcher_round (aka com.mycompany.tizen:mipmap/ic_launcher_round) not found.


* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 37s
Starting a Gradle Daemon (subsequent builds will be faster)
Configuration on demand is an incubating feature.

> Configure project :app
WARNING:: The option 'android.useDeprecatedNdk' is deprecated.
The current default is 'false'.
It has been removed from the current version of the Android Gradle plugin.
NdkCompile is no longer supported
Warning: The 'kotlin-android-extensions' Gradle plugin is deprecated. Please use this migration guide (https://goo.gle/kotlin-android-extensions-deprecation) to start working with View Binding (https://developer.android.com/topic/libraries/view-binding) and the 'kotlin-parcelize' plugin.
WARNING:: The specified Android SDK Build Tools version (30.0.0) is ignored, as it is below the minimum supported version (30.0.2) for Android Gradle Plugin 4.2.2.
Android SDK Build Tools 30.0.2 will be used.
To suppress this warning, remove "buildToolsVersion '30.0.0'" from your build.gradle file, as each version of the Android Gradle Plugin now has a default version of the build tools.

> Task :app:preBuild UP-TO-DATE
> Task :app:preDebugBuild UP-TO-DATE
> Task :react-native-gesture-handler:assertNoMultipleInstances
> Task :react-native-gesture-handler:preBuild
> Task :react-native-gesture-handler:preDebugBuild
> Task :react-native-gesture-handler:compileDebugAidl NO-SOURCE
> Task :react-native-gesture-handler:packageDebugRenderscript NO-SOURCE
> Task :app:generateDebugBuildConfig
> Task :app:compileDebugAidl NO-SOURCE
> Task :app:compileDebugRenderscript NO-SOURCE
> Task :app:bundleDebugJsAndAssets SKIPPED
> Task :react-native-gesture-handler:writeDebugAarMetadata
> Task :react-native-gesture-handler:mergeDebugShaders
> Task :app:mergeDebugShaders
> Task :react-native-gesture-handler:compileDebugShaders NO-SOURCE
> Task :react-native-gesture-handler:generateDebugAssets UP-TO-DATE
> Task :app:compileDebugShaders NO-SOURCE
> Task :react-native-gesture-handler:packageDebugAssets
> Task :react-native-gesture-handler:compileDebugRenderscript NO-SOURCE
> Task :react-native-gesture-handler:generateDebugResValues
> Task :react-native-gesture-handler:generateDebugResources
> Task :react-native-gesture-handler:packageDebugResources
> Task :react-native-gesture-handler:extractDeepLinksDebug
> Task :react-native-gesture-handler:compileDebugLibraryResources
> Task :react-native-gesture-handler:generateDebugBuildConfig
> Task :react-native-gesture-handler:processDebugJavaRes NO-SOURCE
> Task :react-native-gesture-handler:javaPreCompileDebug
> Task :react-native-gesture-handler:processDebugManifest
> Task :react-native-gesture-handler:mergeDebugJniLibFolders
> Task :react-native-gesture-handler:mergeDebugNativeLibs NO-SOURCE
> Task :react-native-gesture-handler:stripDebugDebugSymbols NO-SOURCE
> Task :react-native-gesture-handler:copyDebugJniLibsProjectOnly
> Task :react-native-gesture-handler:copyDebugJniLibsProjectAndLocalJars
> Task :react-native-gesture-handler:prepareLintJarForPublish
> Task :react-native-gesture-handler:parseDebugLocalResources
> Task :react-native-gesture-handler:generateDebugRFile
> Task :app:generateDebugAssets UP-TO-DATE
> Task :app:checkDebugAarMetadata
> Task :app:mergeDebugAssets
> Task :app:copyDebugBundledJs SKIPPED
> Task :app:generateDebugResValues
> Task :app:generateDebugResources
> Task :app:createDebugCompatibleScreenManifests
> Task :app:extractDeepLinksDebug
> Task :app:processDebugMainManifest
> Task :app:processDebugManifest
> Task :app:mergeDebugNativeDebugMetadata NO-SOURCE
> Task :app:javaPreCompileDebug
> Task :app:processDebugJavaRes NO-SOURCE
> Task :app:compressDebugAssets
> Task :app:mergeDebugResources
> Task :app:mergeDebugJniLibFolders
> Task :app:validateSigningDebug
> Task :app:checkDebugDuplicateClasses
> Task :app:writeDebugAppMetadata
> Task :app:writeDebugSigningConfigVersions
> Task :app:processDebugManifestForPackage
> Task :app:processDebugResources FAILED
> Task :app:desugarDebugFileDependencies

> Task :react-native-gesture-handler:compileDebugKotlin
w: /Users/pauliusguzas/Desktop/tizen/node_modules/react-native-gesture-handler/android/noreanimated/src/main/java/com/swmansion/gesturehandler/ReanimatedEventDispatcher.kt: (7, 31): Parameter 'event' is never used
w: /Users/pauliusguzas/Desktop/tizen/node_modules/react-native-gesture-handler/android/noreanimated/src/main/java/com/swmansion/gesturehandler/ReanimatedEventDispatcher.kt: (7, 41): Parameter 'reactApplicationContext' is never used
w: /Users/pauliusguzas/Desktop/tizen/node_modules/react-native-gesture-handler/android/src/main/java/com/swmansion/gesturehandler/core/GestureHandler.kt: (755, 11): Name shadowed: size
w: /Users/pauliusguzas/Desktop/tizen/node_modules/react-native-gesture-handler/android/src/main/java/com/swmansion/gesturehandler/react/RNGestureHandlerEnabledRootView.kt: (9, 51): Unreachable code
w: /Users/pauliusguzas/Desktop/tizen/node_modules/react-native-gesture-handler/android/src/main/java/com/swmansion/gesturehandler/react/RNGestureHandlerEnabledRootView.kt: (10, 80): Unreachable code
w: /Users/pauliusguzas/Desktop/tizen/node_modules/react-native-gesture-handler/android/src/main/java/com/swmansion/gesturehandler/react/RNGestureHandlerRootHelper.kt: (82, 42): Parameter 'disallowIntercept' is never used
w: /Users/pauliusguzas/Desktop/tizen/node_modules/react-native-gesture-handler/android/src/main/java/com/swmansion/gesturehandler/react/RNGestureHandlerRootHelper.kt: (114, 28): Parameter 'viewTag' is never used
w: /Users/pauliusguzas/Desktop/tizen/node_modules/react-native-gesture-handler/android/src/main/java/com/swmansion/gesturehandler/react/RNGestureHandlerTouchEvent.kt: (7, 44): 'RCTEventEmitter' is deprecated. Deprecated in Java
w: /Users/pauliusguzas/Desktop/tizen/node_modules/react-native-gesture-handler/android/src/main/java/com/swmansion/gesturehandler/react/RNGestureHandlerTouchEvent.kt: (14, 11): 'init(Int): Unit' is deprecated. Deprecated in Java
w: /Users/pauliusguzas/Desktop/tizen/node_modules/react-native-gesture-handler/android/src/main/java/com/swmansion/gesturehandler/react/RNGestureHandlerTouchEvent.kt: (30, 42): 'RCTEventEmitter' is deprecated. Deprecated in Java
w: /Users/pauliusguzas/Desktop/tizen/node_modules/react-native-gesture-handler/android/src/main/java/com/swmansion/gesturehandler/react/RNGestureHandlerTouchEvent.kt: (31, 21): 'receiveEvent(Int, String!, WritableMap?): Unit' is deprecated. Deprecated in Java
38 actionable tasks: 38 executed


FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:processDebugResources'.
> A failure occurred while executing com.android.build.gradle.internal.res.LinkApplicationAndroidResourcesTask$TaskAction
   > Android resource linking failed
     ERROR:/Users/pauliusguzas/Desktop/tizen/platformBuilds/app_androidwear/app/build/intermediates/packaged_manifests/debug/AndroidManifest.xml:21: AAPT: error: resource mipmap/ic_launcher_round (aka com.mycompany.tizen:mipmap/ic_launcher_round) not found.


* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 37s

Error: Command failed with exit code 1: ./gradlew assembleDebug -x bundleReleaseJsAndAssets

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:processDebugResources'.
> A failure occurred while executing com.android.build.gradle.internal.res.LinkApplicationAndroidResourcesTask$TaskAction
   > Android resource linking failed
     ERROR:/Users/pauliusguzas/Desktop/tizen/platformBuilds/app_androidwear/app/build/intermediates/packaged_manifests/debug/AndroidManifest.xml:21: AAPT: error: resource mipmap/ic_launcher_round (aka com.mycompany.tizen:mipmap/ic_launcher_round) not found.


* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 37s
Starting a Gradle Daemon (subsequent builds will be faster)
Configuration on demand is an incubating feature.

> Configure project :app
WARNING:: The option 'android.useDeprecatedNdk' is deprecated.
The current default is 'false'.
It has been removed from the current version of the Android Gradle plugin.
NdkCompile is no longer supported
Warning: The 'kotlin-android-extensions' Gradle plugin is deprecated. Please use this migration guide (https://goo.gle/kotlin-android-extensions-deprecation) to start working with View Binding (https://developer.android.com/topic/libraries/view-binding) and the 'kotlin-parcelize' plugin.
WARNING:: The specified Android SDK Build Tools version (30.0.0) is ignored, as it is below the minimum supported version (30.0.2) for Android Gradle Plugin 4.2.2.
Android SDK Build Tools 30.0.2 will be used.
To suppress this warning, remove "buildToolsVersion '30.0.0'" from your build.gradle file, as each version of the Android Gradle Plugin now has a default version of the build tools.

> Task :app:preBuild UP-TO-DATE
> Task :app:preDebugBuild UP-TO-DATE
> Task :react-native-gesture-handler:assertNoMultipleInstances
> Task :react-native-gesture-handler:preBuild
> Task :react-native-gesture-handler:preDebugBuild
> Task :react-native-gesture-handler:compileDebugAidl NO-SOURCE
> Task :react-native-gesture-handler:packageDebugRenderscript NO-SOURCE
> Task :app:generateDebugBuildConfig
> Task :app:compileDebugAidl NO-SOURCE
> Task :app:compileDebugRenderscript NO-SOURCE
> Task :app:bundleDebugJsAndAssets SKIPPED
> Task :react-native-gesture-handler:writeDebugAarMetadata
> Task :react-native-gesture-handler:mergeDebugShaders
> Task :app:mergeDebugShaders
> Task :react-native-gesture-handler:compileDebugShaders NO-SOURCE
> Task :react-native-gesture-handler:generateDebugAssets UP-TO-DATE
> Task :app:compileDebugShaders NO-SOURCE
> Task :react-native-gesture-handler:packageDebugAssets
> Task :react-native-gesture-handler:compileDebugRenderscript NO-SOURCE
> Task :react-native-gesture-handler:generateDebugResValues
> Task :react-native-gesture-handler:generateDebugResources
> Task :react-native-gesture-handler:packageDebugResources
> Task :react-native-gesture-handler:extractDeepLinksDebug
> Task :react-native-gesture-handler:compileDebugLibraryResources
> Task :react-native-gesture-handler:generateDebugBuildConfig
> Task :react-native-gesture-handler:processDebugJavaRes NO-SOURCE
> Task :react-native-gesture-handler:javaPreCompileDebug
> Task :react-native-gesture-handler:processDebugManifest
> Task :react-native-gesture-handler:mergeDebugJniLibFolders
> Task :react-native-gesture-handler:mergeDebugNativeLibs NO-SOURCE
> Task :react-native-gesture-handler:stripDebugDebugSymbols NO-SOURCE
> Task :react-native-gesture-handler:copyDebugJniLibsProjectOnly
> Task :react-native-gesture-handler:copyDebugJniLibsProjectAndLocalJars
> Task :react-native-gesture-handler:prepareLintJarForPublish
> Task :react-native-gesture-handler:parseDebugLocalResources
> Task :react-native-gesture-handler:generateDebugRFile
> Task :app:generateDebugAssets UP-TO-DATE
> Task :app:checkDebugAarMetadata
> Task :app:mergeDebugAssets
> Task :app:copyDebugBundledJs SKIPPED
> Task :app:generateDebugResValues
> Task :app:generateDebugResources
> Task :app:createDebugCompatibleScreenManifests
> Task :app:extractDeepLinksDebug
> Task :app:processDebugMainManifest
> Task :app:processDebugManifest
> Task :app:mergeDebugNativeDebugMetadata NO-SOURCE
> Task :app:javaPreCompileDebug
> Task :app:processDebugJavaRes NO-SOURCE
> Task :app:compressDebugAssets
> Task :app:mergeDebugResources
> Task :app:mergeDebugJniLibFolders
> Task :app:validateSigningDebug
> Task :app:checkDebugDuplicateClasses
> Task :app:writeDebugAppMetadata
> Task :app:writeDebugSigningConfigVersions
> Task :app:processDebugManifestForPackage
> Task :app:processDebugResources FAILED
> Task :app:desugarDebugFileDependencies

> Task :react-native-gesture-handler:compileDebugKotlin
w: /Users/pauliusguzas/Desktop/tizen/node_modules/react-native-gesture-handler/android/noreanimated/src/main/java/com/swmansion/gesturehandler/ReanimatedEventDispatcher.kt: (7, 31): Parameter 'event' is never used
w: /Users/pauliusguzas/Desktop/tizen/node_modules/react-native-gesture-handler/android/noreanimated/src/main/java/com/swmansion/gesturehandler/ReanimatedEventDispatcher.kt: (7, 41): Parameter 'reactApplicationContext' is never used
w: /Users/pauliusguzas/Desktop/tizen/node_modules/react-native-gesture-handler/android/src/main/java/com/swmansion/gesturehandler/core/GestureHandler.kt: (755, 11): Name shadowed: size
w: /Users/pauliusguzas/Desktop/tizen/node_modules/react-native-gesture-handler/android/src/main/java/com/swmansion/gesturehandler/react/RNGestureHandlerEnabledRootView.kt: (9, 51): Unreachable code
w: /Users/pauliusguzas/Desktop/tizen/node_modules/react-native-gesture-handler/android/src/main/java/com/swmansion/gesturehandler/react/RNGestureHandlerEnabledRootView.kt: (10, 80): Unreachable code
w: /Users/pauliusguzas/Desktop/tizen/node_modules/react-native-gesture-handler/android/src/main/java/com/swmansion/gesturehandler/react/RNGestureHandlerRootHelper.kt: (82, 42): Parameter 'disallowIntercept' is never used
w: /Users/pauliusguzas/Desktop/tizen/node_modules/react-native-gesture-handler/android/src/main/java/com/swmansion/gesturehandler/react/RNGestureHandlerRootHelper.kt: (114, 28): Parameter 'viewTag' is never used
w: /Users/pauliusguzas/Desktop/tizen/node_modules/react-native-gesture-handler/android/src/main/java/com/swmansion/gesturehandler/react/RNGestureHandlerTouchEvent.kt: (7, 44): 'RCTEventEmitter' is deprecated. Deprecated in Java
w: /Users/pauliusguzas/Desktop/tizen/node_modules/react-native-gesture-handler/android/src/main/java/com/swmansion/gesturehandler/react/RNGestureHandlerTouchEvent.kt: (14, 11): 'init(Int): Unit' is deprecated. Deprecated in Java
w: /Users/pauliusguzas/Desktop/tizen/node_modules/react-native-gesture-handler/android/src/main/java/com/swmansion/gesturehandler/react/RNGestureHandlerTouchEvent.kt: (30, 42): 'RCTEventEmitter' is deprecated. Deprecated in Java
w: /Users/pauliusguzas/Desktop/tizen/node_modules/react-native-gesture-handler/android/src/main/java/com/swmansion/gesturehandler/react/RNGestureHandlerTouchEvent.kt: (31, 21): 'receiveEvent(Int, String!, WritableMap?): Unit' is deprecated. Deprecated in Java
38 actionable tasks: 38 executed
    at makeError (/Users/pauliusguzas/Desktop/tizen/node_modules/execa/lib/error.js:60:11)
    at handlePromise (/Users/pauliusguzas/Desktop/tizen/node_modules/execa/index.js:118:26)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)


│                                                                              │
│  Project location:                                                           │
│  ./platformBuilds/app_androidwear                                            │
└──────────────────────────────────────────────────────────────────────────────┘
⠏  - Click "OK"%
pauliusguzas@Pauliuss-MacBook-Pro tizen %
```

**Comment by GabrieleKaceviciute** [comment]
I can't reproduce it on version 1.0.0-rc.18
