### ISSUE TITLE
When using NPM as package manager rnv run gets stuck in endless loop

### ISSUE THREAD

**Issue by dotted** [flexn-io/renative#806]
**Describe the bug**
When `rnv run` tries to install dependencies using NPM it gets stuck in an endless loop as it is unable to resolve peerDependencies

**To Reproduce**
1. Make sure yarn is not installed or enabled through corepack
2. Make sure `legacy-peer-deps=true` is not defined in a `.npmrc` file NPM will be [reading during installation](https://docs.npmjs.com/cli/v8/configuring-npm/npmrc)
3. Create a new project with default values using blank template
4. See many errors

**Expected behavior**
Ideally peerDependencies should have been set up correctly, but given that is a problem far outside the scope of renative itself, I'd consider adding a `.npmrc` with the content of `legacy-peer-deps=true` when NPM is used as the package manager as that will allow the `npm install` command to succeed.

**Screenshots or copy&paste**
[renative-error.txt](https://github.com/renative-org/renative/files/8060311/renative-error.txt)

**Desktop (please complete the following information):**

-   OS: Ubuntu 20.04 on WSL2
-   Node Version v14.19.0
-   RNV Version 0.35.2

**Comment by lKinderBueno** [comment]
Same issue here
`Command failed with exit code 1: npm install
npm ERR! code ERESOLVE
npm ERR! ERESOLVE could not resolve
npm ERR!
npm ERR! While resolving: renative@0.1.0
npm ERR! Found: react@17.0.2
npm ERR! node_modules/react
npm ERR!   peer react@"^17.0.2 || ^18.0.0-0" from next@12.1.0
npm ERR!   node_modules/next
npm ERR!     peer next@">=12.0.8" from @rnv/engine-rn-next@0.35.3
npm ERR!     node_modules/@rnv/engine-rn-next
npm ERR!       dev @rnv/engine-rn-next@"0.35.3" from the root project
npm ERR!   peer react@"17.0.2" from react-dom@17.0.2
npm ERR!   node_modules/react-dom
npm ERR!     peer react-dom@"^17.0.2 || ^18.0.0-0" from next@12.1.0
npm ERR!     node_modules/next
npm ERR!       peer next@">=12.0.8" from @rnv/engine-rn-next@0.35.3
npm ERR!       node_modules/@rnv/engine-rn-next
npm ERR!         dev @rnv/engine-rn-next@"0.35.3" from the root project
npm ERR!
npm ERR! Could not resolve dependency:
npm ERR! dev @rnv/engine-rn-windows@"0.35.3" from the root project
npm ERR!
npm ERR! Conflicting peer dependency: react@16.13.1
npm ERR! node_modules/react
npm ERR!   peer react@"16.13.1" from react-native@0.63.4
npm ERR!   node_modules/react-native
npm ERR!     peer react-native@"0.63.4" from @rnv/engine-rn-windows@0.35.3
npm ERR!     node_modules/@rnv/engine-rn-windows
npm ERR!       dev @rnv/engine-rn-windows@"0.35.3" from the root project
npm ERR!     peer react-native@">=0.62.0-rc.0 <0.64.0" from @react-native-community/cli@4.14.0
npm ERR!     node_modules/@react-native-community/cli
npm ERR!       peer @react-native-community/cli@"^4.10.0" from @rnv/engine-rn-windows@0.35.3
npm ERR!       node_modules/@rnv/engine-rn-windows
npm ERR!         dev @rnv/engine-rn-windows@"0.35.3" from the root project
npm ERR!       1 more (react-native)
npm ERR!
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
npm ERR!
npm ERR! See C:\Users\elio1\AppData\Local\npm-cache\eresolve-report.txt for a full report.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\elio1\AppData\Local\npm-cache\_logs\2022-02-22T14_04_57_375Z-debug.log

npm ERR! code ERESOLVE
npm ERR! ERESOLVE could not resolve
npm ERR!
npm ERR! While resolving: renative@0.1.0
npm ERR! Found: react@17.0.2
npm ERR! node_modules/react
npm ERR!   peer react@"^17.0.2 || ^18.0.0-0" from next@12.1.0
npm ERR!   node_modules/next
npm ERR!     peer next@">=12.0.8" from @rnv/engine-rn-next@0.35.3
npm ERR!     node_modules/@rnv/engine-rn-next
npm ERR!       dev @rnv/engine-rn-next@"0.35.3" from the root project
npm ERR!   peer react@"17.0.2" from react-dom@17.0.2
npm ERR!   node_modules/react-dom
npm ERR!     peer react-dom@"^17.0.2 || ^18.0.0-0" from next@12.1.0
npm ERR!     node_modules/next
npm ERR!       peer next@">=12.0.8" from @rnv/engine-rn-next@0.35.3
npm ERR!       node_modules/@rnv/engine-rn-next
npm ERR!         dev @rnv/engine-rn-next@"0.35.3" from the root project
npm ERR!
npm ERR! Could not resolve dependency:
npm ERR! dev @rnv/engine-rn-windows@"0.35.3" from the root project
npm ERR!
npm ERR! Conflicting peer dependency: react@16.13.1
npm ERR! node_modules/react
npm ERR!   peer react@"16.13.1" from react-native@0.63.4
npm ERR!   node_modules/react-native
npm ERR!     peer react-native@"0.63.4" from @rnv/engine-rn-windows@0.35.3
npm ERR!     node_modules/@rnv/engine-rn-windows
npm ERR!       dev @rnv/engine-rn-windows@"0.35.3" from the root project
npm ERR!     peer react-native@">=0.62.0-rc.0 <0.64.0" from @react-native-community/cli@4.14.0
npm ERR!     node_modules/@react-native-community/cli
npm ERR!       peer @react-native-community/cli@"^4.10.0" from @rnv/engine-rn-windows@0.35.3
npm ERR!       node_modules/@rnv/engine-rn-windows
npm ERR!         dev @rnv/engine-rn-windows@"0.35.3" from the root project
npm ERR!       1 more (react-native)
npm ERR!
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
npm ERR!
npm ERR! See C:\Users\elio1\AppData\Local\npm-cache\eresolve-report.txt for a full report.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\elio1\AppData\Local\npm-cache\_logs\2022-02-22T14_04_57_375Z-debug.log

Error: Command failed with exit code 1: npm install
npm ERR! code ERESOLVE
npm ERR! ERESOLVE could not resolve
npm ERR!
npm ERR! While resolving: renative@0.1.0
npm ERR! Found: react@17.0.2
npm ERR! node_modules/react
npm ERR!   peer react@"^17.0.2 || ^18.0.0-0" from next@12.1.0
npm ERR!   node_modules/next
npm ERR!     peer next@">=12.0.8" from @rnv/engine-rn-next@0.35.3
npm ERR!     node_modules/@rnv/engine-rn-next
npm ERR!       dev @rnv/engine-rn-next@"0.35.3" from the root project
npm ERR!   peer react@"17.0.2" from react-dom@17.0.2
npm ERR!   node_modules/react-dom
npm ERR!     peer react-dom@"^17.0.2 || ^18.0.0-0" from next@12.1.0
npm ERR!     node_modules/next
npm ERR!       peer next@">=12.0.8" from @rnv/engine-rn-next@0.35.3
npm ERR!       node_modules/@rnv/engine-rn-next
npm ERR!         dev @rnv/engine-rn-next@"0.35.3" from the root project
npm ERR!
npm ERR! Could not resolve dependency:
npm ERR! dev @rnv/engine-rn-windows@"0.35.3" from the root project
npm ERR!
npm ERR! Conflicting peer dependency: react@16.13.1
npm ERR! node_modules/react
npm ERR!   peer react@"16.13.1" from react-native@0.63.4
npm ERR!   node_modules/react-native
npm ERR!     peer react-native@"0.63.4" from @rnv/engine-rn-windows@0.35.3
npm ERR!     node_modules/@rnv/engine-rn-windows
npm ERR!       dev @rnv/engine-rn-windows@"0.35.3" from the root project
npm ERR!     peer react-native@">=0.62.0-rc.0 <0.64.0" from @react-native-community/cli@4.14.0
npm ERR!     node_modules/@react-native-community/cli
npm ERR!       peer @react-native-community/cli@"^4.10.0" from @rnv/engine-rn-windows@0.35.3
npm ERR!       node_modules/@rnv/engine-rn-windows
npm ERR!         dev @rnv/engine-rn-windows@"0.35.3" from the root project
npm ERR!       1 more (react-native)
npm ERR!
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
npm ERR!
npm ERR! See C:\Users\elio1\AppData\Local\npm-cache\eresolve-report.txt for a full report.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\elio1\AppData\Local\npm-cache\_logs\2022-02-22T14_04_57_375Z-debug.log
    at makeError (C:\Users\elio1\AppData\Roaming\npm\node_modules\rnv\node_modules\execa\lib\error.js:60:11)
    at handlePromise (C:\Users\elio1\AppData\Roaming\npm\node_modules\rnv\node_modules\execa\index.js:118:26)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)`

**Comment by mihaiblaga89** [comment]
@dotted can you please give the latest canary a go? The problem should be fixed there

**Comment by dotted** [comment]
Unable to test due to a `[ error ] Cannot find module '@rnv/engine-rn'`

```
➜  test npm i -g rnv@0.36.0-canary.12
npm WARN deprecated core-js@2.6.12: core-js@<3.4 is no longer maintained and not recommended for usage due to the number of issues. Because of the V8 engine whims, feature detection in old core-js versions could cause a slowdown up to 100x even if nothing is polyfilled. Please, upgrade your dependencies to the actual version of core-js.

added 433 packages, and audited 434 packages in 11s

59 packages are looking for funding
  run `npm fund` for details

found 0 vulnerabilities
➜  test rnv new

┌──────────────────────────────────────────────────────────────────────────────┐
│                                                                              │
│        ██████╗ ███████╗███╗   ██╗ █████╗ ████████╗██╗██╗   ██╗███████╗       │
│        ██╔══██╗██╔════╝████╗  ██║██╔══██╗╚══██╔══╝██║██║   ██║██╔════╝       │
│        ██████╔╝█████╗  ██╔██╗ ██║███████║   ██║   ██║██║   ██║█████╗         │
│        ██╔══██╗██╔══╝  ██║╚██╗██║██╔══██║   ██║   ██║╚██╗ ██╔╝██╔══╝         │
│        ██║  ██║███████╗██║ ╚████║██║  ██║   ██║   ██║ ╚████╔╝ ███████╗       │
│        ╚═╝  ╚═╝╚══════╝╚═╝  ╚═══╝╚═╝  ╚═╝   ╚═╝   ╚═╝  ╚═══╝  ╚══════╝       │
│                                                                              │
│        Version: 0.36.0-canary.12                                             │
│        https://renative.org                                                  │
│        🚀 Firing up!...                                                      │
│        $ rnv new                                                             │
│        Start Time: 3/23/2022, 9:00:38 AM                                     │
│                                                                              │
└──────────────────────────────────────────────────────────────────────────────┘

[ task ] registerEngine:engine-core[1]
[ task ] configureRuntimeDefaults[1] appId:null
[ task ] checkAndMigrateProject[1]
[ task ] loadPluginTemplates[1]
[ task ] _parsePluginTemplateDependencies[1] scope:root
[ task ] parseRenativeConfigs[1]
[ task ] getWorkspaceDirPath[1]
[ task ] checkAndBootstrapIfRequired[1]
[ task ] loadIntegrations[1]
[ task ] loadEngines[1]
[ task ] findSuitableTask[1]
[ info ] Current Engine: engine-core path: undefined
[ task ] registerMissingPlatformEngines[1]
[ task ] initializeTask[1] new
[ task ] => [new]
[ task ] [new] taskRnvNew[1]
? What's your project Name? (no spaces, folder based on ID will be created in this directory) issue806
? What's your project Title? Hello Renative
? What's your App ID? com.mycompany.issue806
? What's your Version? 0.1.0
? What workspace to use? rnv
[ task ] [new] loadPluginTemplates[2]
[ task ] [new] _parsePluginTemplateDependencies[2] scope:root
[ task ] [new] parseRenativeConfigs[2]
[ task ] [new] getWorkspaceDirPath[2]
? What template to use? @rnv/template-blank - Blank renative template with no UI
✔ Executing: npm view @rnv/template-blank versions
✔ Executing: npm dist-tag ls @rnv/template-blank
? What @rnv/template-blank version to use? 0.36.0-canary.12 (HEAD: canary)
✔ Executing: npm add @rnv/template-blank@0.36.0-canary.12
? What platforms would you like to use? ios, android, androidtv, firetv, androidwear, web, webtv, tizen, tvos, webos, macos, windows, tizenwatch, tizenmobile, kaios, firefoxos, firefoxtv, chromecast, xbox
? Do you want to set-up git in your new project? Yes
?
┌──────────────────────────────────────────────────────────────────────────────┐
│  🚀  ReNative Project Generator                                              │
│                                                                              │
├──────────────────────────────────────────────────────────────────────────────┤
│                                                                              │
│  Project Name (folder): issue806                                             │
│  Workspace: rnv                                                              │
│  Project Title: Hello Renative                                               │
│  Project Version: 0.1.0                                                      │
│  App ID: com.mycompany.issue806                                              │
│  Project Template: @rnv/template-blank@0.36.0-canary.12                      │
│  Git Enabled: true                                                           │
│                                                                              │
│  Project Platforms:                                                          │
│  ios, android, androidtv, firetv, androidwear, web, webtv, tizen,            │
│  tvos, webos, macos, windows, tizenwatch, tizenmobile, kaios,                │
│  firefoxos, firefoxtv, chromecast, xbox                                      │
│                                                                              │
│  Project Structure:                                                          │
│                                                                              │
│  issue806                                                                    │
│   ├── appConfigs            # Application flavour configuration files/assets │
│   │   └── [APP_ID]          # Example application flavour                    │
│   │       ├── assets        # Platform assets injected to ./platformAssets   │
│   │       ├── builds        # Platform files injected to ./platformBuilds    │
│   │       ├── fonts             # Folder for all custom fonts                │
│   │       ├── plugins           # Multi-platform plugins injections          │
│   │       └── renative.json # Application flavour config                     │
│   ├── platformAssets        # Generated cross-platform assets                │
│   ├── platformBuilds        # Generated platform app projects                │
│   ├── src                   # Source code files                              │
│   ├── index.*.js            # Entry files                                    │
│   └── renative.json         # ReNative project configuration                 │
│                                                                              │
└──────────────────────────────────────────────────────────────────────────────┘

Is all this correct? Yes
[ task ] [new] _generateProject:@rnv/template-blank:0.36.0-canary.12[1]
[ task ] [new] checkAndCreateGitignore[1]
[ info ] [new] Your .gitignore is missing. CREATING...DONE
[ task ] [new] configureGit:.[1]
[ info ] [new] Your project does not have a git repo. Creating one...DONE
✔ Executing: git init
✔ Executing: git add -A
✔ Executing: git commit -m "Initial"
[ success ] [new] Your project is ready! navigate to project cd issue806 and run rnv run to see magic happen!
[ task ] <= new

 $ rnv new - Done! 🚀
┌──────────────────────────────────────────────────────────────────────────────┐
│  🚀  SUMMARY | 3/23/2022, 9:01:00 AM                                         │
│  $ rnv new                                                                   │
├──────────────────────────────────────────────────────────────────────────────┤
│  ReNative Version: 0.36.0-canary.12                                          │
│  Engine: engine-core                                                         │
│  Build Scheme (-s): debug                                                    │
│  Env Info: linux | x64 | node v14.19.0                                       │
│  Executed Time: 0h:0m:22s:554ms                                              │
│                                                                              │
│ [ success ] [new] Your project is ready! navigate to project cd issue806 and run rnv run to see magic happen!
│                                                                              │
└──────────────────────────────────────────────────────────────────────────────┘
➜  test cd issue806
➜  issue806 git:(master) rnv run

┌──────────────────────────────────────────────────────────────────────────────┐
│                                                                              │
│        ██████╗ ███████╗███╗   ██╗ █████╗ ████████╗██╗██╗   ██╗███████╗       │
│        ██╔══██╗██╔════╝████╗  ██║██╔══██╗╚══██╔══╝██║██║   ██║██╔════╝       │
│        ██████╔╝█████╗  ██╔██╗ ██║███████║   ██║   ██║██║   ██║█████╗         │
│        ██╔══██╗██╔══╝  ██║╚██╗██║██╔══██║   ██║   ██║╚██╗ ██╔╝██╔══╝         │
│        ██║  ██║███████╗██║ ╚████║██║  ██║   ██║   ██║ ╚████╔╝ ███████╗       │
│        ╚═╝  ╚═╝╚══════╝╚═╝  ╚═══╝╚═╝  ╚═╝   ╚═╝   ╚═╝  ╚═══╝  ╚══════╝       │
│                                                                              │
│        Version: 0.36.0-canary.12                                             │
│        https://renative.org                                                  │
│        🚀 Firing up!...                                                      │
│        $ rnv run                                                             │
│        Start Time: 3/23/2022, 9:01:08 AM                                     │
│                                                                              │
└──────────────────────────────────────────────────────────────────────────────┘

[ task ] registerEngine:engine-core[1]
[ task ] configureRuntimeDefaults[1] appId:null
[ task ] checkAndMigrateProject[1]
[ task ] loadPluginTemplates[1]
[ task ] _parsePluginTemplateDependencies[1] scope:root
[ task ] parseRenativeConfigs[1]
[ warn ] You are trying to extend config file with ./node_modules/@rnv/template-blank/@rnv/template-starter/renative.json does not exists. SKIPPING.
[ task ] getWorkspaceDirPath[1]
[ task ] _generatePlatformTemplatePaths[1]
[ warn ] You're missing paths object in your ./renative.json
[ task ] checkAndBootstrapIfRequired[1]
[ task ] loadIntegrations[1]
[ task ] loadEngines[1]
[ warn ] Platform ios requires engine @rnv/engine-rn which is not available in engines list
[ warn ] Platform android requires engine @rnv/engine-rn which is not available in engines list
[ warn ] Platform androidtv requires engine @rnv/engine-rn which is not available in engines list
[ warn ] Platform firetv requires engine @rnv/engine-rn which is not available in engines list
[ warn ] Platform androidwear requires engine @rnv/engine-rn which is not available in engines list
[ warn ] Platform web requires engine @rnv/engine-rn-next which is not available in engines list
[ warn ] Platform webtv requires engine @rnv/engine-rn-web which is not available in engines list
[ warn ] Platform tizen requires engine @rnv/engine-rn-web which is not available in engines list
[ warn ] Platform tvos requires engine @rnv/engine-rn-tvos which is not available in engines list
[ warn ] Platform webos requires engine @rnv/engine-rn-web which is not available in engines list
[ warn ] Platform macos requires engine @rnv/engine-rn which is not available in engines list
[ warn ] Platform windows requires engine @rnv/engine-rn-electron which is not available in engines list
[ warn ] Platform tizenwatch requires engine @rnv/engine-rn-web which is not available in engines list
[ warn ] Platform tizenmobile requires engine @rnv/engine-rn-web which is not available in engines list
[ warn ] Platform kaios requires engine @rnv/engine-rn-web which is not available in engines list
[ warn ] Platform firefoxos requires engine @rnv/engine-rn-web which is not available in engines list
[ warn ] Platform firefoxtv requires engine @rnv/engine-rn-web which is not available in engines list
[ warn ] Platform chromecast requires engine @rnv/engine-rn-web which is not available in engines list
[ warn ] Platform xbox requires engine @rnv/engine-rn-windows which is not available in engines list
[ task ] loadEnginePluginDeps[1]
[ task ] loadEnginePackageDeps[1]
[ task ] findSuitableTask[1]
[ task ] registerAllPlatformEngines[1]
┌──────────────────────────────────────────────────────────────────────────────┐
│  🚀  SUMMARY | 3/23/2022, 9:01:08 AM                                         │
│  $ rnv run                                                                   │
├──────────────────────────────────────────────────────────────────────────────┤
│  ReNative Version: 0.36.0-canary.12                                          │
│  Project Name ($package.name): undefined                                     │
│  Project Version ($package.version): undefined                               │
│  Workspace ($.workspaceID): rnv                                              │
│  Build Scheme (-s): debug                                                    │
│  Env Info: linux | x64 | node v14.19.0                                       │
│  Executed Time: 0h:0m:0s:86ms                                                │
│                                                                              │
│ [ warn ] You are trying to extend config file with ./node_modules/@rnv/template-blank/@rnv/template-starter/renative.json does not exists. SKIPPING.
│ [ warn ] You're missing paths object in your ./renative.json
│ [ warn ] Platform ios requires engine @rnv/engine-rn which is not available in engines list
│ [ warn ] Platform android requires engine @rnv/engine-rn which is not available in engines list
│ [ warn ] Platform androidtv requires engine @rnv/engine-rn which is not available in engines list
│ [ warn ] Platform firetv requires engine @rnv/engine-rn which is not available in engines list
│ [ warn ] Platform androidwear requires engine @rnv/engine-rn which is not available in engines list
│ [ warn ] Platform web requires engine @rnv/engine-rn-next which is not available in engines list
│ [ warn ] Platform webtv requires engine @rnv/engine-rn-web which is not available in engines list
│ [ warn ] Platform tizen requires engine @rnv/engine-rn-web which is not available in engines list
│ [ warn ] Platform tvos requires engine @rnv/engine-rn-tvos which is not available in engines list
│ [ warn ] Platform webos requires engine @rnv/engine-rn-web which is not available in engines list
│ [ warn ] Platform macos requires engine @rnv/engine-rn which is not available in engines list
│ [ warn ] Platform windows requires engine @rnv/engine-rn-electron which is not available in engines list
│ [ warn ] Platform tizenwatch requires engine @rnv/engine-rn-web which is not available in engines list
│ [ warn ] Platform tizenmobile requires engine @rnv/engine-rn-web which is not available in engines list
│ [ warn ] Platform kaios requires engine @rnv/engine-rn-web which is not available in engines list
│ [ warn ] Platform firefoxos requires engine @rnv/engine-rn-web which is not available in engines list
│ [ warn ] Platform firefoxtv requires engine @rnv/engine-rn-web which is not available in engines list
│ [ warn ] Platform chromecast requires engine @rnv/engine-rn-web which is not available in engines list
│ [ warn ] Platform xbox requires engine @rnv/engine-rn-windows which is not available in engines list
│ [ error ] Cannot find module '@rnv/engine-rn'
Require stack:
- /home/bo/.nvm/versions/node/v14.19.0/lib/node_modules/rnv/dist/core/engineManager/index.js
- /home/bo/.nvm/versions/node/v14.19.0/lib/node_modules/rnv/dist/core/runtimeManager/index.js
- /home/bo/.nvm/versions/node/v14.19.0/lib/node_modules/rnv/dist/cli/index.js
- /home/bo/.nvm/versions/node/v14.19.0/lib/node_modules/rnv/dist/index.js
- /home/bo/.nvm/versions/node/v14.19.0/lib/node_modules/rnv/bin/index.js
Error: Cannot find module '@rnv/engine-rn'
Require stack:
- /home/bo/.nvm/versions/node/v14.19.0/lib/node_modules/rnv/dist/core/engineManager/index.js
- /home/bo/.nvm/versions/node/v14.19.0/lib/node_modules/rnv/dist/core/runtimeManager/index.js
- /home/bo/.nvm/versions/node/v14.19.0/lib/node_modules/rnv/dist/cli/index.js
- /home/bo/.nvm/versions/node/v14.19.0/lib/node_modules/rnv/dist/index.js
- /home/bo/.nvm/versions/node/v14.19.0/lib/node_modules/rnv/bin/index.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:902:15)
    at Function.resolve (internal/modules/cjs/helpers.js:107:19)
    at _resolvePkgPath (/home/bo/.nvm/versions/node/v14.19.0/lib/node_modules/rnv/src/core/engineManager/index.js:421:23)
    at _registerPlatformEngine (/home/bo/.nvm/versions/node/v14.19.0/lib/node_modules/rnv/src/core/engineManager/index.js:435:17)
    at /home/bo/.nvm/versions/node/v14.19.0/lib/node_modules/rnv/src/core/engineManager/index.js:136:13
    at Array.forEach (<anonymous>)
    at /home/bo/.nvm/versions/node/v14.19.0/lib/node_modules/rnv/src/core/engineManager/index.js:134:47
    at step (/home/bo/.nvm/versions/node/v14.19.0/lib/node_modules/rnv/node_modules/tslib/tslib.js:143:27)
    at Object.next (/home/bo/.nvm/versions/node/v14.19.0/lib/node_modules/rnv/node_modules/tslib/tslib.js:124:57)
    at /home/bo/.nvm/versions/node/v14.19.0/lib/node_modules/rnv/node_modules/tslib/tslib.js:117:75
│                                                                              │
└──────────────────────────────────────────────────────────────────────────────┘
➜  issue806 git:(master)
```
