### ISSUE TITLE
Spaces in the project name are changed to underscores and project cannot be runned

### ISSUE THREAD

**Issue by GabrieleKaceviciute** [flexn-io/renative#905]
**Describe the bug**
Spaces in the project name are changed to underscores and project cannot be runned

**To Reproduce**
1. When doing ‘rnv new’ enter project name with space
2. Do ‘rnv run’

**Expected behavior**
New project can be run

**Screenshots or copy&paste**

```
 🚀  SUMMARY | 8/23/2022, 4:56:28 PM                                         │
│  $ rnv run                                                                   │
├──────────────────────────────────────────────────────────────────────────────┤
│  ReNative Version: 0.36.2-canary.3                                           │
│  Project Name ($package.name): space space                                   │
│  Project Version ($package.version): 0.1.0                                   │
│  Workspace ($.workspaceID): rnv                                              │
│  Build Scheme (-s): debug                                                    │
│  Env Info: darwin | x64 | node v16.14.0                                      │
│  Executed Time: 0h:0m:0s:647ms                                               │
│                                                                              │
│ [ warn ] COMMAND:

yarn

FAILED with ERROR:

error package.json: Name contains illegal characters
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.

Command failed with exit code 1: yarn
error package.json: Name contains illegal characters
yarn install v1.22.19
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.

error package.json: Name contains illegal characters

Error: Command failed with exit code 1: yarn
error package.json: Name contains illegal characters
yarn install v1.22.19
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
    at makeError (/Users/gabriele/.config/yarn/global/node_modules/execa/lib/error.js:60:11)
    at handlePromise (/Users/gabriele/.config/yarn/global/node_modules/execa/index.js:118:26)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)


 Seems like your node_modules is corrupted by other libs. ReNative will try to fix it for you
│ [ error ] COMMAND:

yarn

FAILED with ERROR:

error package.json: Name contains illegal characters
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.

Command failed with exit code 1: yarn
error package.json: Name contains illegal characters
yarn install v1.22.19
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.

error package.json: Name contains illegal characters

Error: Command failed with exit code 1: yarn
error package.json: Name contains illegal characters
yarn install v1.22.19
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
    at makeError (/Users/gabriele/.config/yarn/global/node_modules/execa/lib/error.js:60:11)
    at handlePromise (/Users/gabriele/.config/yarn/global/node_modules/execa/index.js:118:26)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)


│                                                                              │
└──────────────────────────────────────────────────────────────────────────────┘
```

**Desktop (please complete the following information):**
- OS: macOS Monterey 12.5
- Node Version: 16.14.0
- RNV Version: 0.36.1-canary.3
- @rnv/template-starter: 0.36.1-canary.3

**Comment by pauliusguzas** [comment]
Also after successful project creating rnv shows that user should do 'cd space space' while the project was named 'space_space' automatically
