### ISSUE TITLE
Wdio config file fails to launch on template-starter package

### ISSUE THREAD

**Issue by pauliusguzas** [flexn-io/renative#978]
**Describe the bug**
wdio config file fails to launch

**To Reproduce**
1. do `yarn bootstrap`
2. navigate to `template-starter` package
3. do yarn `e2e:web` or any other platform

**Expected behavior**
wdio config lauches test runner

**Screenshots or copy&paste**
```
pauliusguzas@Pauliuss-MacBook-Pro template-starter % yarn e2e:web
yarn run v1.22.19
$ PLATFORM=web npx wdio wdio.conf.js
2023-05-03T09:14:35.529Z ERROR @wdio/config:ConfigParser: Failed loading configuration file: /Users/pauliusguzas/Desktop/renative/packages/template-starter/wdio.conf.js: Cannot read properties of undefined (reading 'process')
wdio [command]

The `wdio` command allows you run and manage your WebdriverIO test suite.
If no command is provided it calls the `run` command by default, so:

$ wdio wdio.conf.js

is the same as:
$ wdio run wdio.conf.js

For more information, visit: https://webdriver.io/docs/clioptions

Commands:
  wdio config                        Initialize WebdriverIO and setup
                                     configuration in your current project.
  wdio install <type> <name>         Add a `reporter`, `service`, or `framework`
                                     to your WebdriverIO project. The command
                                     installs the package from NPM, adds it to
                                     your package.json and modifies the
                                     wdio.conf.js accordingly.
  wdio repl <option> [capabilities]  Run WebDriver session in command line
  wdio run <configPath>              Run your WDIO configuration file to
                                     initialize your tests. (default)

Options:
      --help             Show help                                     [boolean]
      --version          Show version number                           [boolean]
      --watch            Run WebdriverIO in watch mode                 [boolean]
  -h, --hostname         automation driver host address                 [string]
  -p, --port             automation driver port                         [number]
      --path             path to WebDriver endpoints (default "/")      [string]
  -u, --user             username if using a cloud service as automation backend
                                                                        [string]
  -k, --key              corresponding access key to the user           [string]
  -l, --logLevel         level of logging verbosity
                  [choices: "trace", "debug", "info", "warn", "error", "silent"]
      --bail             stop test runner after specific amount of tests have
                         failed                                         [number]
      --baseUrl          shorten url command calls by setting a base url[string]
  -w, --waitforTimeout   timeout for all waitForXXX commands            [number]
  -f, --framework        defines the framework (Mocha, Jasmine or Cucumber) to
                         run the specs                                  [string]
  -r, --reporters        reporters to print out the results on stdout    [array]
      --suite            overwrites the specs attribute and runs the defined
                         suite                                           [array]
      --spec             run only a certain spec file - overrides specs piped
                         from stdin                                      [array]
      --exclude          exclude certain spec file from the test run - overrides
                         exclude piped from stdin                        [array]
      --mochaOpts        Mocha options
      --jasmineOpts      Jasmine options
      --cucumberOpts     Cucumber options
      --autoCompileOpts  Auto compilation options

Examples:
  wdio run wdio.conf.js --suite foobar      Run suite on testsuite "foobar"
  wdio run wdio.conf.js --spec              Run suite on specific specs
  ./tests/e2e/a.js --spec ./tests/e2e/b.js
  wdio run wdio.conf.js --spec              Run scenario by line number
  ./tests/e2e/a.feature:5
  wdio run wdio.conf.js --spec              Run scenarios by line number
  ./tests/e2e/a.feature:5:10
  wdio run wdio.conf.js --spec              Run scenarios by line number in
  ./tests/e2e/a.feature:5:10 --spec         single feature and another complete
  ./test/e2e/b.feature                      feature
  wdio install reporter spec                Install @wdio/spec-reporter
  wdio repl chrome -u <SAUCE_USERNAME> -k   Run repl in Sauce Labs cloud
  <SAUCE_ACCESS_KEY>

Documentation: https://webdriver.io
@wdio/cli (v7.19.5)

TypeError: Cannot read properties of undefined (reading 'process')
    at _configureLogger (/Users/pauliusguzas/Desktop/renative/packages/rnv/src/core/systemManager/logger.js:112:25)
    at cnf (/Users/pauliusguzas/Desktop/renative/packages/rnv/src/core/systemManager/logger.js:103:9)
    at _getCurrentTask (/Users/pauliusguzas/Desktop/renative/packages/rnv/src/core/systemManager/logger.js:327:32)
    at logInfo (/Users/pauliusguzas/Desktop/renative/packages/rnv/src/core/systemManager/logger.js:414:46)
    at /Users/pauliusguzas/Desktop/renative/packages/rnv/src/core/adapter/index.js:20:16
    at readConfigJS (/Users/pauliusguzas/Desktop/renative/node_modules/@babel/register/node_modules/@babel/core/lib/config/files/configuration.js:202:15)
    at readConfigJS.next (<anonymous>)
    at Function.<anonymous> (/Users/pauliusguzas/Desktop/renative/node_modules/@babel/register/node_modules/@babel/core/lib/gensync-utils/async.js:26:3)
    at Generator.next (<anonymous>)
    at evaluateSync (/Users/pauliusguzas/Desktop/renative/node_modules/gensync/index.js:251:28)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
pauliusguzas@Pauliuss-MacBook-Pro template-starter %
```

**Desktop (please complete the following information):**
-   OS: Ventura 13.2
-   Node Version 16.14.2

**Comment by mihaiblaga89** [comment]
should be fixed by https://github.com/flexn-io/renative/pull/1008
